hello-world = Hello, world! { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = Silicon
Iron = Iron
Xenon = Xenon
Helium = Helium
Carbon = Carbon
Rhodium = Rhodium

Sandbag = Sandbag

Ruins = Ruins
Transistor = Transistor
Eroded = Eroded
Scales = Scales
Crossing = Crossing
Longboat = Longboat
Boombox = Boombox
Fountain = Fountain
Great-White = Great White
Plane = Plane
Satellite = Satellite
Divided = Divided
Pillars = Pillars
Debug = Debug

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = Vanilla
Physics = Physics
color-preset-random = Random
color-preset-red = Red
color-preset-orange = Orange
color-preset-gold = Gold
color-preset-green = Green
color-preset-blue = Blue
color-preset-purple = Purple
color-preset-pink = Pink
color-preset-white = White
versus-color-preset-help = Choose a color family; each choice gets a small random variation. Disabled while teams are enabled.

# Navigation
Back = Back
Exit = Exit
Save = Save
Cancel = Cancel
Close-Symbol = X

Modify = Modify
Reset = Reset

# Main Menu
Versus = Versus
Training = Training
Courses = Courses
TRAINING = TRAINING
COURSES = COURSES
battle-results = Battle Results
Settings = Settings
Controls = Controls
Discord = Discord {"\u29C9"}
Guide = Guide {"\u29C9"}

# Settings Menu
SETTINGS = SETTINGS
Audio = Audio
Video = Video
Windowed = Windowed
Fullscreen = Fullscreen

main = Main Menu
versus = Versus
training = Training
start-mode = Start: { TRANSLATE($value) }

# Audio Menu
AUDIO = AUDIO

Play-Audio = Play Audio
Play-Music = Play Music

Audio-volume = Volume: {$value}
SFX-volume = SFX: {$value}
Music-volume = Music: {$value}
UI-volume = UI: {$value}
Voice-volume = Voice: {$value}

# Video Menu
VIDEO = VIDEO
Quick-Setup = Quick Setup
Display = Display
Quality = Quality
Effects = Effects
Apply-Changes = Apply Changes

graphics-preset-low = Graphics: Low
graphics-preset-medium = Graphics: Medium
graphics-preset-high = Graphics: High
graphics-preset-max = Graphics: Max
graphics-preset-custom = Graphics: Custom

vsync-off = Vsync: Off
vsync-on = Vsync: On
vsync-adaptive = Vsync: Adaptive

shadow-off = Shadows: Off
shadow-low = Shadows: Low
shadow-highest = Shadows: Highest

ssao-off = SSAO: Off
ssao-on = SSAO: On
ssao-full = SSAO: Full

aa-off = Antialias: Off
aa-fxaa = Antialias: FXAA
aa-fxaa-high = Antialias: FXAA High

bloom-off = Bloom: Off
bloom-on = Bloom: On
reflections-off = Reflections: Off
reflections-on = Reflections: On
reflections-low = Reflections: Low
reflections-high = Reflections: High
godrays-off = God Rays: Off
godrays-on = God Rays: On

perf-overlay-off = Perf Overlay: Off
perf-overlay-on = Perf Overlay: On

point-lights-off = Point Lights: Off
point-lights-on = Point Lights: On

particles-low = Particles: Low
particles-medium = Particles: Medium
particles-full = Particles: Full

max-fps-off = Max FPS: Off
max-fps-30 = Max FPS: 30
max-fps-60 = Max FPS: 60
max-fps-120 = Max FPS: 120
max-fps-144 = Max FPS: 144

# Controls Menu
CONTROLS = CONTROLS

standard = standard
keyboard = keyboard
gcn_native = GCN native

# Training Menu
Swap-Character = Swap Character
Overlays = Overlays
press-start = Press Start

drawHitbubbleInfo = Attack Info
drawECB = Collision
drawHeatmap = Heatmap
drawRawPosition = Raw Position
drawStage = Stage Collision
animations = Animations
controllers = Controllers

# Versus Menu
FFA = FFA
Teams = Teams

Host-Netplay = Host Netplay
Join-Netplay-Clipboard = Join Netplay from Clipboard
Disconnect = Disconnect
Copy-Lobby-Code = Copy Lobby Code

# Controls Menu
controls-title = CONTROLS
controls-section-controllers = Controllers
controls-section-mappings = Mappings
controls-set-tag = Set Tag
controls-edit-bindings = Edit Bindings
controls-tag-untagged = (no tag)
controls-tag-title = Player Tag
controls-tag-prompt = P{$port} ({$layout}). Tags are 1-24 alphanumerics, "-", or "_". Leave blank to clear.
controls-tag-confirm = Confirm
controls-tag-clear = Clear
controls-tag-cancel = Cancel
controls-tag-select-title = Choose Tag
controls-tag-filter-empty = Type to filter saved tags
controls-tag-filter-value = Filter: {$filter}
controls-tag-summary-empty = {$total} saved tags. Type to filter, or create a new tag.
controls-tag-summary-filter = {$visible} shown of {$total} saved tags. Exact matches use saved controls.
controls-tag-defaults-suffix = defaults for this controller
controls-tag-create-new = Create New Tag
controls-tag-use-existing = Use Existing Tag "{$tag}"
controls-tag-create = Create "{$tag}"
controls-tag-reserved = "{$tag}" is reserved
controls-tag-netplay-blocked = Tags cannot be changed during netplay
controls-tag-no-controller = No local controller selected
controls-tag-no-layout = Selected controller has no layout
controls-tag-filter-help = Type to filter tags; ESC clears or exits
controls-tag-no-saved = No saved tags yet
controls-tag-no-matches = No matching tags
controls-tag-invalid = Invalid tag (1-24 chars, alphanumerics/-/_; "default" reserved)
controls-profile-help-untagged = Controls save to the shared untagged profile; set a tag only to save tap-jump defaults.
controls-profile-help-tagged = Controls and tap-jump defaults save for this tag on this controller type.
controls-choose-existing-tag = Choose Existing Tag
controls-create-tag = Create Tag
controls-rename-create-tag = Rename/Create Tag
controls-edit-set-tag-first = Edit Controls (set a tag first)
controls-edit-controls = Edit Controls
controls-tap-jump-default = Tap Jump Default: {$state}
controls-state-on = ON
controls-state-off = OFF
controls-netplay-blocked = Controls cannot be changed during netplay
controls-no-local-controllers = No local controllers connected
controls-no-layout = Controller has no layout
controls-set-tag-before-editing = Set a tag before editing controls
controls-no-mapping = No mapping available for this controller
controls-set-tag-before-tap-jump = Set a tag to save a tap-jump default
controls-connected-controllers = Connected Controllers
controls-remap-add-key = + Add Binding (press a key)
controls-remap-find-input = Find Binding (press an input)
controls-remap-capture-key-title = Press a Key
controls-remap-capture-input-title = Press an Input
controls-remap-capture-key-help = The next key you press will be added as a new binding.
controls-remap-capture-input-help = The next button or stick you use will be focused for editing.
controls-remap-capture-cancel = ESC to cancel
controls-default-save-blocked = Default controls cannot be overwritten; set a tag first
controls-default-reset-blocked = Default controls cannot be reset from this menu
controls-tag-filter-entry-help = Type to filter saved controller tags; gamepads can use the D-pad.
controls-tag-filter-label = Filter
controls-tag-preconfigured = preconfigured
controls-tag-rename-title = Rename Tag
controls-tag-create-title = Create Tag
controls-tag-apply-existing-help = Apply the matching saved tag to this controller.
controls-tag-create-empty-help = Create a new tag for this controller.
controls-tag-create-filtered-help = Create this tag for the controller if the name is valid.
controls-tag-apply-saved-help = Apply this tag and its saved mapping to the controller.
controls-tag-apply-preconfigured-help = Apply this preconfigured tag using the default mapping for this controller layout.
controls-tag-apply-default-help = Apply this tag using the default mapping for this controller layout.
controls-tag-delete-button = Delete {$tag}
controls-tag-delete-help = Delete {$tag} and its saved controls after confirmation.
controls-tag-delete-title = Delete Tag?
controls-tag-delete-body = Delete "{$tag}" and its saved controls?
controls-tag-delete-warning = This cannot be undone.
controls-back-help = Return to Controls.
controls-tag-select-help = Choose or create a controller tag.
controls-edit-set-tag-first-help = Create a controller tag first, then edit gameplay and menu bindings.
controls-edit-controls-help = Edit gameplay and menu bindings for this controller profile.
controls-tap-jump-set-tag-first-help = Create a controller tag first, then set the default tap-jump preference.
controls-tap-jump-default-help = Toggle whether pressing up makes this controller jump by default.
controls-create-new-tag-help = Create a new tag and switch this controller to it.
controls-choose-existing-tag-help = Choose or delete a saved tag.
controls-rename-current-tag-help = Rename the current controller tag.
controls-switch-controller-help = Switch the controls menu to this connected controller.
menu-binding-hint = Move with Stick or D-pad · Confirm/Start selects · Back returns
menu-adjust-hint = Move with Stick or D-pad · Left/Right changes values · Confirm selects · Back returns
menu-bind-hint = Move with Stick or D-pad · Confirm chooses a binding · Back returns
arcade-select-leave = Select leaves
main-help-about-help = Guides, credits, and bluehexagons links.
main-replays-available-help = Browse, preview, and play saved replay files.
main-replays-unavailable-help = Replays are only available offline because they load from the local filesystem.
arcade-menu-battles-help = Start the current Arcade Battles run setup.
arcade-menu-infinite-help = Start the endless Arcade mode with scaling 1-stock CPUs.
arcade-menu-training-help = Open Training mode with its practice tools and savestates.
arcade-menu-back-help = Return to the main menu.
arcade-menu-help = Choose an arcade mode.
training-menu-courses-help = Choose a short course about game mechanics.
training-menu-help = Choose a training activity.
courses-menu-course-help = Visit this course area.
courses-menu-back-help = Return to Training.
courses-menu-help = Course areas run left to right. You can roam freely at any time.
course-instruction-movement-walk = Tilt the movement stick left or right to walk.
course-instruction-movement-dash = Flick the movement stick left or right to dash.
course-name-movement = Movement
course-name-jumping = Jumping
course-name-attacks = Attacks
course-name-defense = Defense
course-name-advanced = Advanced
course-summary-movement = Walk, dash, and reach the marker.
course-summary-jumping = Jump and steer in the air.
course-summary-attacks = Hit a target with normal and special attacks.
course-summary-defense = Block an attack, then grab the target.
course-summary-advanced = Use stick attacks, air dodges, and fast-falls.
course-instruction-movement-travel = Move to the arrow marker.
course-instruction-jumping-jump = Press jump to leave the ground.
course-instruction-jumping-steer = Hold left or right after jumping to steer in the air.
course-instruction-attacks-normal = Hit the practice target with a normal attack.
course-instruction-attacks-special = Hit the practice target with a special attack.
course-instruction-defense-shield = Block the practice target's attack with your shield.
course-instruction-defense-grab = Grab the practice target.
course-instruction-advanced-stick = Flick the right stick in any direction for a stick attack.
course-instruction-advanced-air-dodge = Jump, then press a shield button firmly to air dodge.
course-instruction-advanced-fast-fall = While airborne, press down to fast-fall.
course-instruction-complete = Area complete. Move to another area when you're ready.
help-bluehex-homepage-help = Visit the bluehexagons homepage.
help-bluehex-github-help = Browse bluehexagons projects on GitHub.
help-bluehex-steam-help = Open the bluehexagons Steam curator page.
help-bluehex-itch-help = Open the bluehexagons itch.io page.
help-bluehex-bluesky-help = Follow bluehexagons on Bluesky.
help-bluehex-patreon-help = Support bluehexagons on Patreon.
controls-source-keyboard = Keyboard
controls-source-keyboard-defaults = Keyboard defaults
controls-current-menu-controls-heading = Current menu controls
controls-current-menu-controls-summary = {$source} · Move: {$navigate} · Select: {$confirm} · Back: {$back}
controls-action-attack = Attack
controls-action-jump = Jump
controls-action-special = Special
controls-action-grab = Grab
controls-action-shield-1 = Shield 1
controls-action-shield-2 = Shield 2
controls-action-hard-shield-1 = Hard Shield 1
controls-action-hard-shield-2 = Hard Shield 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-Pad Up
controls-action-dpad-down = D-Pad Down
controls-action-dpad-left = D-Pad Left
controls-action-dpad-right = D-Pad Right
controls-action-move-horizontal = Move Horizontal
controls-action-move-vertical = Move Vertical
controls-action-right-stick-horizontal = Right Stick Horizontal
controls-action-right-stick-vertical = Right Stick Vertical
controls-action-ui-confirm = UI Confirm
controls-action-ui-back = UI Back
controls-action-ui-up = UI Up
controls-action-ui-down = UI Down
controls-action-ui-left = UI Left
controls-action-ui-right = UI Right
controls-action-ui-horizontal-nav = UI Horizontal Nav
controls-action-ui-vertical-nav = UI Vertical Nav
controls-action-move-left = Move Left
controls-action-move-right = Move Right
controls-action-move-up = Move Up
controls-action-move-down = Move Down
controls-action-tilt-left = Tilt Left
controls-action-tilt-right = Tilt Right
controls-action-tilt-up = Tilt Up
controls-action-tilt-down = Tilt Down
controls-action-right-stick-left = Right Stick Left
controls-action-right-stick-right = Right Stick Right
controls-action-right-stick-up = Right Stick Up
controls-action-right-stick-down = Right Stick Down
controls-action-light-shield-l = Light Shield L
controls-action-light-shield-r = Light Shield R
controls-action-ui-nav-left = UI Nav Left
controls-action-ui-nav-right = UI Nav Right
controls-action-ui-nav-up = UI Nav Up
controls-action-ui-nav-down = UI Nav Down
controls-remap-section-buttons = Buttons
controls-remap-section-dpad = D-Pad
controls-remap-section-movement = Movement
controls-remap-section-tilts = Tilts (Soft Movement)
controls-remap-section-right-stick = Right Stick
controls-remap-section-light-shields = Light Shields
controls-remap-section-ui-navigation = UI Navigation
controls-remap-section-sticks-triggers = Sticks & Triggers
controls-remap-unbound = Unbound
controls-remap-free-keys-none = Free keys: (none in common set)
controls-remap-more-suffix = , +{$count} more
controls-remap-free-keys = Free keys: {$keys}{$suffix}
controls-remap-free-buttons = Free buttons: {$buttons}
controls-remap-free-axes = Free axes: {$axes}
controls-remap-conflict-detail = {$input} is already bound to {$actions}.
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = Keep at least one UI Confirm and UI Back binding so menus remain usable.
controls-remap-capture-key-hint = Press a keyboard key for {$action}. ESC cancels.
controls-remap-capture-button-hint = Press a {$layout} button for {$action}. Back cancels.
controls-remap-capture-axis-hint = Move a {$layout} stick/trigger for {$action}. Back cancels.
controls-remap-capture-add-title = Add {$action}
controls-remap-capture-replace-title = Replace {$action}
controls-remap-capture-matching-input = Press a matching input for this action.
controls-remap-confirm-reassign = Confirm to reassign it to {$action}.
controls-remap-confirm-cancel-help = Confirm replaces it. Back cancels.
controls-remap-command-add = Add
controls-remap-command-replace = Replace
controls-remap-command-remove = Remove
controls-remap-add-help = Add another physical input for {$action}.
controls-remap-replace-help = Replace {$input} for {$action}.
controls-remap-remove-help = Remove {$input} from {$action}.
controls-remap-back-to-controls = Back to Controls
controls-remap-back-to-controls-help = Return to Controls without scrolling to the bottom of the remap list.
controls-remap-help = Choose Add, Replace, or Remove. Page keys jump through the list.
controls-remap-help-extended = Choose Add, Replace, or Remove. Page keys jump through the list; Back cancels.
controls-remap-jump-to-section = Jump to section
controls-remap-jump-to-binding = Jump to {$section}
controls-remap-focus-section-help = Move focus to the first {$section} binding.
controls-remap-reset-help = Reset this tagged profile to its default layout. Requires two confirms.
controls-remap-reset-confirm = Press again to confirm reset

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = Direct Connect
Connect = Connect

netplay-action-start-lobby = Start Lobby
netplay-action-join-clipboard = Join from Clipboard
netplay-action-quick-host-copy-code = Quick Host & Copy Code
netplay-action-copy-lan-invite = Copy LAN Invite
netplay-action-copy-localhost-invite = Copy Localhost Invite
netplay-action-copy-stun-invite = Copy STUN Invite
netplay-action-find-random-match = Find Random Match
netplay-action-cancel-lobby = Cancel Lobby
netplay-action-cancel-connection = Cancel Connection
netplay-action-please-wait = Please Wait
netplay-action-open-versus = Open Versus
netplay-action-cancel-matchmaking = Cancel Matchmaking

netplay-status-label = Netplay: {$status}
netplay-status-uninitialized = uninitialized
netplay-status-initialized = initialized
netplay-status-waiting = waiting
netplay-status-hosting = hosting
netplay-status-connecting = connecting
netplay-status-establishing = establishing
netplay-status-connected = connected
netplay-status-ready = Ready for netplay
netplay-status-waiting-player = Waiting for player to join
netplay-status-waiting-lobby = Waiting for lobby response
netplay-status-hosting-lobby = Hosting lobby
netplay-status-hosting-lobby-code = Hosting lobby {$code}
netplay-status-starting-lobby = Starting lobby
netplay-status-connecting-host = Connecting to host
netplay-status-connected-host = Connected as host
netplay-status-connected-client = Connected to host
netplay-status-disconnecting = Disconnecting
netplay-status-canceling = Canceling connection
netplay-status-matchmaking = Searching for random match
netplay-status-match-found = Random match found
netplay-status-matchmaking-canceling = Canceling matchmaking
netplay-status-error = Netplay error
netplay-status-error-message = Netplay error: {$error}
netplay-status-unavailable = Netplay status unavailable

matchmaking-title = MATCHMAKING
matchmaking-status-select-character = Select a character to queue
matchmaking-status-no-controller = No controller connected
matchmaking-status-searching = Searching for a match...
matchmaking-status-searching-details = Searching... waited {$wait}s. Players waiting: {$players}. Longest wait: {$longest}s.
matchmaking-status-searching-estimate = Searching... waited {$wait}s. Players waiting: {$players}. Completed matches averaged {$average}s.
matchmaking-status-canceling = Canceling...
matchmaking-status-found = Match found!
matchmaking-status-connecting = Connecting...
matchmaking-status-disconnecting = Disconnecting...
matchmaking-status-error = {$error} Select a character to retry.

# Match by Code
match-code-title = MATCH BY CODE
match-code-hint = Share your code. Enter theirs. Both press Search. Case does not matter.
match-code-own-label = Your code: {$code}
match-code-peer-label = Friend’s code: {$code}
match-code-peer-unset = Friend’s code: (not set)
match-code-search = Search
match-code-entry-limit = {$length} letters or numbers max
match-code-own-prompt = Your Code
match-code-peer-prompt = Friend’s Code
match-code-status-enter-peer = Enter your friend’s code to set up a private match
match-code-status-ready = Ready — both players should press Search
match-code-error-enter-peer = Enter your friend’s code first
match-code-error-own = Enter your friend’s code, not your own
match-code-error-invalid = That code is not valid
match-code-error-length = Code must be {$min}–{$max} letters or numbers
match-code-error-blocked = That code is not allowed; please choose another

netplay-detail-ready = Host a lobby, paste a copied invite, or type an address manually.
netplay-detail-lobby-code-ready = Lobby code {$code} is ready to share.
netplay-detail-creating-lobby-code = Creating your lobby code.
netplay-detail-waiting-for-host = Waiting for the host to answer your join request.
netplay-detail-share-lobby-code = Share lobby code {$code} with the other player.
netplay-detail-starting-lobby = Starting your lobby connection.
netplay-detail-joining-host = Trying to join the selected host.
netplay-detail-establishing = Players found. Finish the handshake, then open Versus.
netplay-detail-connected = Connection ready. Open Versus to pick rules, characters, and stage.
netplay-detail-disconnecting = Closing the current session and returning to offline play.
netplay-detail-canceling = Stopping the current join request.
netplay-detail-matchmaking = Use Versus to queue for a random opponent with your preferred rules.
netplay-detail-match-found = Opponent found. Finish setup in Versus when both players are ready.
netplay-detail-matchmaking-canceling = Stopping the current random match search.
netplay-detail-error-message = Last error: {$error}
netplay-detail-error-generic = Something went wrong. Try a different code or connection method.
netplay-detail-unavailable = Netplay details unavailable.

netplay-help-host-copy-code = Copy your lobby code so the other player can paste it.
netplay-help-host-cancel-join = Stop the current join attempt and return to the ready state.
netplay-help-host-disconnect = Leave the current netplay session.
netplay-help-host-start-lobby = Start a new lobby and wait for another player to join.
netplay-help-busy = Netplay is busy right now. Wait for it to finish.
netplay-help-join-cancel-lobby = Close the current lobby and stop waiting for another player.
netplay-help-join-in-progress = A join is already in progress. Wait or use Cancel Connection.
netplay-help-join-open-versus = Continue to Versus and finish setting up the match.
netplay-help-stop-random-search = Stop searching for a random opponent.
netplay-help-join-clipboard = Paste a lobby, direct, or STUN invite code from the clipboard.
netplay-help-copy-server = Start a lobby if needed, then copy its shareable lobby code.
netplay-help-copy-direct = Copy a direct-connect invite for another device on this LAN.
netplay-help-copy-localhost = Copy a direct-connect invite for another copy running on this computer.
netplay-help-copy-stun = Copy a STUN-assisted invite that is easier to use over the internet.
netplay-help-direct-connect = Type an address manually instead of using a copied invite code.
netplay-help-find-random-match = Open Versus and queue for a random opponent.
netplay-help-open-versus = Open the Versus menu without leaving this screen.
netplay-help-back = Return to the main menu.
netplay-help-unavailable = Netplay action help unavailable.
netplay-help-advanced = Adjust advanced netplay settings like rollback and buffer.

ADVANCED-CONNECTIONS = ADVANCED CONNECTIONS
netplay-settings-rollback-help = Toggle rollback simulation for online matches.
netplay-settings-buffer-help = Choose how many input frames to buffer, or let netplay choose automatically.
netplay-settings-force-ipv4-help = Prefer IPv4 when generating LAN invite codes on mixed networks.
netplay-settings-back-help = Return to the netplay menu.
netplay-advanced-info = Use these as fallback options when Quick Play or normal lobby codes cannot connect. STUN helps punch through routers for internet play. Direct Connect is best for LAN play or a host with a forwarded UDP port.
netplay-advanced-direct-help = Manual fallback. Enter a host:port for LAN play or when the host has forwarded a UDP port.
netplay-advanced-stun-help = Internet fallback. Share this when normal lobby joins fail and you still need router-assisted hole punching.
netplay-advanced-lan-help = LAN fallback. Share your reachable local address when both players are on the same network.
netplay-advanced-localhost-help = Testing fallback. Use this only when both clients are running on the same machine.
netplay-advanced-back-help = Return to Virtual Couch.
netplay-rollback-off = Rollback: Off
netplay-rollback-on = Rollback: On
netplay-buffer-auto = Net Buffer: Auto
netplay-buffer-2 = Net Buffer: 2
netplay-buffer-3 = Net Buffer: 3
netplay-buffer-4 = Net Buffer: 4
netplay-buffer-5 = Net Buffer: 5
netplay-buffer-6 = Net Buffer: 6
netplay-buffer-7 = Net Buffer: 7
netplay-buffer-8 = Net Buffer: 8
netplay-buffer-10 = Net Buffer: 10
netplay-buffer-12 = Net Buffer: 12
netplay-force-ipv4-dual = LAN Address: IPv6/IPv4
netplay-force-ipv4-v4 = LAN Address: Force IPv4

netplay-rollback = Rollback
netplay-buffer = Net Buffer
netplay-force-ipv4 = LAN Address

netplay-direct-connect-prompt = Enter IP address:port. Port defaults to {$port}.
netplay-stun-connect-title = Use STUN Service?
netplay-stun-connect-prompt = This code used {$service} to discover {$address}:{$port}.
netplay-waiting-host-battle = Waiting for the host battle to finish

Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = Characters
Stages = Stages
CPU = CPU

Starter = Starter
Legal = Legal
Miscellaneous = Miscellaneous

Start-Battle = Start Battle

# Start Menu
quit-info = Shield + Attack + Start to quit
paused = PAUSED
tag-info = D-pad up/down to tag in/out

# Pause Menu
pause-resume = Resume
pause-restart = Restart
pause-quit = Quit
pause-players = Players
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = Connect a controller and press any button to join.
arcade-return-prompt = Press confirm to return to the main menu.

# Replay
replay-paused = Replay paused
replay-controls = Confirm: join  ←/→: frame  Back: menu  Save Replay: [key]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = {en-english}
spanish = Spanish
french = French
italian = Italian
german = German
russian = Russian
japanese = Japanese
chinese-cn = Simplified Chinese
chinese-hk = Traditional Chinese
korean = Korean

en = {en-english}
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean} ({korean})

# Placeholder UI strings
Advanced = Advanced
Clear-Spawns = Clear Spawns
Create-new-tag = Create new tag
Credits = Credits
CREDITS = CREDITS
Cycle-Palette = Cycle Palette
Delete = Delete
Help = Help
HELP = HELP
Join = Join
Join-Lobby-Code = Join Lobby Code
Main-Menu = Main Menu
Mode = Mode
Native-Adapter = Native Adapter
NATIVE-ADAPTER = NATIVE ADAPTER
NETPLAY-SETTINGS = NETPLAY SETTINGS
Other-saved-tags = Other saved tags
Profiles-for-this-controller-type = Profiles for this controller type
Quick-Play = Quick Play
Random-Color = Random Color
Rename-current-tag = Rename current tag
Reset-to-Defaults = Reset to Defaults
Set-Character = Set Character
Spawn-CPU = Spawn CPU
Team = Team
Virtual-Couch = Virtual Couch
x = x
Find-Random-Match = Find Random Match
training-label-stage = Stage
training-label-character = Character
training-label-player-cursor = Player Cursor
training-label-cpu-spawn = CPU Spawn
training-label-savestate = Save State
Save-State = Save State
Load-State = Load State
State-Saved = State Saved
State-Restored = State Restored
No-State-Saved = No State Saved
DPad-Right-Save-Left-Load = D-pad Right saves · D-pad Left loads
shared-main-menu-help = Return to the main menu.
shared-mode-selector-label-help = Ruleset selector label.
training-mode-selector-help = Switch between Antistatic and 19XX training constants.
training-overlays-help = Toggle debug overlays and training visualization aids.
training-close-help = Close the training menu.
training-stage-help = Change the training stage and reset stage-bound entities.
training-character-help = Choose the character used by Set Character and Spawn CPU.
training-set-character-help = Change the hovering player cursor to the selected character.
training-random-color-help = Assign a new random base color to the cursor's character.
training-cycle-palette-help = Cycle the cursor character's palette style.
training-cpu-level-down-help = Lower the CPU level used for new training CPUs.
training-cpu-level-current-help = Current CPU level for newly spawned CPUs. Confirm to cycle.
training-cpu-level-up-help = Raise the CPU level used for new training CPUs.
training-spawn-cpu-help = Spawn a CPU using the selected character and CPU level.
training-clear-spawns-help = Remove all training-spawned CPUs and dummy characters.
training-save-state-help = Save the current Training position, damage, stocks, spawned CPUs, stage, and timing state. D-pad Right does the same shortcut.
training-load-state-help = Restore the saved Training state. D-pad Left does the same shortcut.
training-savestate-shortcuts-help = D-pad Right saves the current Training state; D-pad Left restores it.
versus-tag-selector-default = Tag: {$tag}
versus-tag-none = No Tag
versus-tag-manage = Create / Manage Tags
versus-tag-change-failed = Unable to change tag
versus-cpu-level-help = Cycle this CPU level.
versus-cpu-color-help = Shuffle this CPU color and palette.
versus-cpu-team-help = Cycle this CPU team.
versus-cpu-remove-help = Remove this CPU.
versus-character-select-help = Select this character for the hovering player cursor.
versus-add-cpu-help = Add a CPU using this character.
versus-tap-jump-help = Toggle tap jump for this player.
versus-random-color-help = Assign this player a new random color. Disabled while teams are enabled.
versus-cycle-palette-help = Cycle this player's palette style.
versus-team-help = Cycle this player team. Shown while team mode is enabled.
versus-tag-selector-help = Choose this player tag. Disabled during netplay.
versus-start-select-character-first = Select a character first
versus-start-not-enough-players = Not enough players to start a game, found {$count}
versus-start-not-enough-teams = Not enough teams to start a game, found {$count}
versus-start-waiting-for-host = Waiting for host to start
versus-ffa-help = Toggle free-for-all and team battle rules.
versus-start-help = Start the match once enough players, CPUs, teams, and a stage are ready.
versus-starter-help = Randomly choose a starter stage and start the match.
versus-legal-help = Randomly choose a legal starter or counterpick stage and start the match.
versus-misc-help = Miscellaneous stages.
versus-stage-preview-help = Hover to preview this stage; confirm to select it and start.
versus-stage-preview-counterpick-help = Hover to preview this counterpick stage; confirm to select it and start.
versus-stage-preview-misc-help = Hover to preview this miscellaneous stage; confirm to select it and start.
versus-mode-selector-help = Switch between Antistatic and 19XX versus constants.
versus-tab-stages-help = Browse and select a stage for the match.
versus-tab-settings-help = Configure match rules and settings. Pressing Start here switches to stage select.
versus-setting-stock = Stock
versus-setting-time = Time
versus-setting-on = On
versus-setting-off = Off
versus-setting-none = None
versus-setting-stock-mode-value = Mode: {$value}
versus-setting-stocks-value = Stocks: {$value}
versus-setting-time-limit-value = Time: {$value}
versus-setting-friendly-fire-value = FF: {$value}
versus-setting-stamina-value = Stamina: {$value}
versus-setting-knockback-value = KB: {$value}×
versus-setting-pause-value = Pause: {$value}
versus-setting-sd-value = SD: {$value}
versus-setting-stock-mode-help = Cycle between Stock mode (last player standing wins) and Time mode (most stocks when timer expires wins).
versus-setting-stocks-help = Number of stocks (lives) each player starts with.
versus-setting-time-limit-help = Match time limit. In Time mode this determines the winner.
versus-setting-friendly-fire-help = Toggle whether teammates can damage each other. Only shown in team mode.
versus-setting-stamina-help = Starting stamina (HP). Set to 0 for damage percentage mode.
versus-setting-knockback-help = Global knockback multiplier. Higher values increase launch distance.
versus-setting-pause-help = Allow or disallow pausing during the match.
versus-setting-sd-help = Penalty for self-destructs. -1 deducts a stock; 0 has no penalty.
netplay-copy-lobby-missing = No lobby code to copy
netplay-copy-lobby-copied = Copied lobby code to clipboard
netplay-direct-connect-empty = Enter an IP address
netplay-lobby-code-prompt = Type a lobby, LAN, or STUN invite code.
netplay-lobby-code-empty = Enter a lobby code
netplay-error-connecting = Error connecting: {$error}
matchmaking-no-controller-connected = No controller connected
battle-winner-log = Winner: {$player}
battle-winner-message = Winner: Player {$player}
battle-winner-team-log = Winner: Team {$team}
battle-winner-team-message = Winner: Team {$team}
battle-tie-log = Tie
battle-tie-message = TIE
battle-time-out = TIME OUT
battle-countdown-go = GO
battle-infinite-score-log = Infinite Score: {$score}
battle-infinite-score-message = Score {$score}
team-name-red = Red
team-name-green = Green
team-name-blue = Blue
team-name-grey = Grey
versus-start-sync-failed = Failed to sync battle start

main-menu-help = Hover over an option to see what it does.
netplay-main-help = Choose a netplay action.
netplay-settings-help = Adjust netplay behavior.
netplay-advanced-help = Choose a connection tool.
settings-help = Choose a settings category.
help-discord-help = Open the Antistatic Discord community in your browser.
help-guide-help = Open the online Antistatic guide in your browser.
help-adapter-guide-help = Open Dolphin setup notes for the official GameCube controller adapter.
Adapter-Guide = Adapter Guide
Open-Dolphin-Guide = Open Dolphin Guide
Native-Adapter-Help = Adapter Help
NATIVE-ADAPTER-HELP = ADAPTER HELP
native-adapter-help-summary = Antistatic uses libusb directly, so it shares the same driver setup as Dolphin native adapter support.
native-adapter-help-windows = Windows: install WinUSB for USB ID 057e:0337 with Zadig.
native-adapter-help-linux = Linux: add a udev rule that grants user access to 057e:0337.
native-adapter-help-sdl = If SDL/Dolphin grabs the adapter first, launch with SDL_JOYSTICK_HIDAPI_GAMECUBE=0.
native-adapter-help-dolphin = Dolphin/Slippi: close them before opening Antistatic native adapter diagnostics.
native-adapter-help-claim = If another app had the adapter claimed, close it and reopen this diagnostics screen.
native-adapter-help-back = Return to native adapter status.
help-credits-help = View credits, copyright, and third-party attribution.
help-back-help = Return to the main menu.
help-help = Choose a help destination.
controls-help = Choose a controller action.
netplay-quick-play-help = Search for a random opponent using the selected controller.
credits-help = Credits and attribution.

credits-heading = Antistatic - credits and attribution
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. All rights reserved.
credits-developer = Developer: bluehexagons (Loren Crain).
credits-original = Original sounds, models, animations, gameplay, UI, and engine code were created in-house.
credits-runtime = Open-source runtime/tools: Node.js, TypeScript, CMake, Fluent, gl-matrix, jsonc-parser, os-locale.
credits-libraries = Native libraries: SDL3, SDL3_image, GLEW, OpenAL Soft, FreeType, Vorbis/libvorbisfile, libusb.
credits-build = Build/check tooling: npm, oxlint, oxfmt, and platform compiler toolchains.
credits-fonts = Bundled fonts: Noto Sans, IBM Plex Mono, and GNU Unifont.
credits-tools = Production tools: Blender for 3D models; Audacity and LMMS for audio and music.
credits-packages = bluehexagons packages: capacitor, trace, and antistatic-translations.
credits-thanks = Thanks to the maintainers and contributors of these projects.
credits-license = Third-party projects remain under their respective licenses.

# Old UI hover/help text
main-versus-help = Choose characters, CPUs, teams, rules, and a stage before starting a local match.
main-arcade-help = Co-op CPU battles for everyone plugged in. Limited stocks, retry on defeat.
main-netplay-help = Host or join online games, quick play, and netplay connection settings.
main-training-help = Open training mode with stage, CPU, color, palette, and debug controls.
main-replays-help = Browse, preview, and play saved replay files.
main-settings-help = Adjust audio, video, language, controller adapter, and start mode settings.
main-controls-help = Create controller tags and edit per-tag control mappings.
main-help-help = Open community and external guide links.
main-exit-help = Quit Antistatic.

settings-audio-help = Adjust master, sound effect, UI, voice, and music volume.
settings-video-help = Change graphics preset, fullscreen, sync, effects, and frame limit options.
settings-native-adapter-help = Inspect GameCube adapter status and setup notes.
settings-language-help = Cycle the menu language.
settings-start-mode-help = Choose which mode opens first at startup.
shared-settings-help = Return to Settings.

native-adapter-copy-udev-install-help = Copy the standard udev rule install and reload commands for 057e:0337.
native-adapter-copy-udev-line-help = Copy only the standard 057e:0337 udev rule line.
native-adapter-help-button-help = Open Windows and Linux setup notes for Dolphin/Slippi-compatible adapter installs.

audio-master-help = Set the master output volume.
audio-sfx-toggle-help = Toggle sound effects and UI sounds.
audio-sfx-help = Set gameplay sound effect volume.
audio-ui-help = Set menu and interface sound volume.
audio-voice-help = Set character voice volume.
audio-music-toggle-help = Toggle music playback.
audio-music-help = Set music volume.

video-preset-help = Apply a grouped graphics preset, or show Custom when individual settings differ.
video-fullscreen-toggle-help = Switch between windowed and fullscreen display.
video-display-help = Choose which display the game window or fullscreen mode should use.
video-fullscreen-resolution-help = Choose the exclusive fullscreen mode resolution. Auto uses desktop fullscreen.
video-windowed-resolution-help = Choose the window size used for windowed mode and fullscreen restore.
video-render-scale-help = Render 3D graphics below or above window resolution while keeping UI native.
video-vsync-help = Choose swap timing. Adaptive uses low-latency tear-if-late sync when the driver supports it.
video-shadow-quality-help = Choose shadow quality or disable shadows.
video-ssao-help = Choose ambient occlusion quality.
video-antialias-help = Toggle FXAA anti-aliasing.
video-bloom-help = Add a soft glow around the brightest highlights. Best on higher-end GPUs.
video-reflections-help = Mirror the scene in shiny surfaces with screen-space reflections. Demanding; best on high-end GPUs.
video-godrays-help = Cast volumetric shafts of light from the sun through the scene. Demanding; best on high-end GPUs.
video-perf-overlay-help = Show or hide the performance overlay.
video-point-lights-help = Choose extra point-light quality.
video-particle-quality-help = Choose particle effect density.
video-max-fps-help = Set an optional frame-rate cap.
video-apply-help = Apply changed video settings.

replays-enabled-help = Record eligible Versus and Quick Play battles in memory. Disable this on memory-constrained systems.
replays-auto-save-help = Save replays automatically at the results screen instead of waiting for a manual save press.
replays-compression-help = Compress replay files when saving. Disable only if compression causes slow saves.

netplay-copy-lobby-help = Copy the current lobby code when one is available.
netplay-virtual-couch-help = Open lobby hosting, lobby-code joining, and advanced invite options.
netplay-settings-menu-help = Configure rollback, input buffer, and LAN address behavior.
netplay-back-help = Return to the main menu without disconnecting an established session.

arcade-cpu-level-help = CPU difficulty level for opponents (0 easiest, 6 hardest).
arcade-stocks-help = Stocks per battle.
arcade-retries-help = Retries before a defeat ends the run.
arcade-battles-help = Total number of battles in the run.
arcade-start-help = Begin the run once every joined player has readied up.

controls-remap-page-help = Rebind menu navigation, console, fullscreen, and training-mode keys.
controls-remap-reset-binding-help = Reset {$action} to its default binding.
controls-remap-reset-all-help = Restore every keyboard shortcut to its built-in default.

replay-browser-help = Replay browser.
replay-offline-only-help = Replays are only available offline because they load from the local filesystem.
replay-refresh-help = Rescan saved replay files from {$dir}.
replay-entry-help = {$players} on {$stage}; {$duration} ({$truncated}); {$result}; {$version}; {$compression}.
replay-unreadable-help = Could not read replay: {$error}
replay-actions-watch-help = Play the saved replay from the start. Jump In is available during replay playback.
replay-actions-back-help = Return to the replay list.
replay-load-help = Load saved replay files from the replay directory.
replay-prev-help = Show newer replays.
replay-next-help = Show older replays.
replay-settings-help = Replay recording, auto-save, and compression options.
audio-help = Adjust audio settings.
video-help = Adjust video settings.
replays-help = Replays are enabled by default and capped at 16 minutes per battle.
native-adapter-help-text = Native Adapter gives direct 4-port polling. PC mode is simpler but uses SDL controller mappings.

shortcut-menu-up-help = Move selection up in menus.
shortcut-menu-down-help = Move selection down in menus.
shortcut-menu-left-help = Move selection left or decrement a value.
shortcut-menu-right-help = Move selection right or increment a value.
shortcut-menu-confirm-help = Activate the focused item.
shortcut-menu-next-help = Move to the next focusable item. Hold Shift to go back.
shortcut-menu-page-up-help = Jump up several items.
shortcut-menu-page-down-help = Jump down several items.
shortcut-menu-home-help = Focus the first item in the list.
shortcut-menu-end-help = Focus the last item in the list.
shortcut-console-help = Open the in-game debug console.
shortcut-chat-help = Open the chat prompt (say command).
shortcut-fullscreen-help = Toggle fullscreen. Alt+Enter also works.
shortcut-frame-step-help = Advance one frame while frozen. Requires debug mode.
shortcut-freeze-help = Pause or unpause TAS. Requires debug mode.
shortcut-save-state-help = Snapshot the current state in training mode.
shortcut-restore-state-help = Restore the last training-mode snapshot.

# Translation audit additions
# These old-UI labels and help strings are rendered directly by the Arcade select scene.
# `arcade-setting-value` formats numeric selectors after the label itself has already been translated.
Start = Start
Color = Color
Leave = Leave
Not-Joined = Not Joined
Hold-Start = Hold Start
arcade-join-help = Join this arcade run.
arcade-color-help = Randomize this player color.
arcade-palette-help = Select this player palette.
arcade-leave-help = Leave this arcade run.
arcade-setting-cpu-level = CPU Lv
arcade-setting-stocks = Stocks
arcade-setting-starting-stocks = Starting Stocks
arcade-setting-retries = Retries
arcade-setting-battles = Battles
arcade-setting-value = {$label}: {$value}
arcade-palette = Palette {$number}
arcade-select-title = ARCADE
arcade-select-infinite-title = INFINITE BATTLES
arcade-select-instructions = Confirm join · choose character and palette per player · Back leave

# These strings are shared by Arcade interstitials plus the post-battle / arcade results panels.
# `results-title-*` receive already-localized character names from gameplay data.
arcade-between-cleared-battle = Cleared Battle {$current} / {$total}
arcade-between-next = Confirm: next
arcade-between-retries-remaining =
    Defeat — { $count ->
        [one] {$count} retry remaining
       *[other] {$count} retries remaining
    }
arcade-between-retry-actions = Confirm: retry · Back: abandon
arcade-between-results = Confirm: results
arcade-between-complete = Arcade complete!
arcade-results-infinite-title = Infinite Battles
arcade-results-infinite-subtitle = Score {$score} in {$time}
arcade-results-cleared-title = Arcade Cleared
arcade-results-cleared-subtitle = Cleared all {$battles} battles.
arcade-results-abandoned-title = Run Abandoned
arcade-results-abandoned-subtitle = Abandoned after battle {$current} of {$total}.
arcade-results-gameover-title = Game Over
arcade-results-gameover-subtitle = Reached battle {$current} of {$total}.
replay-battle-controls = Replay: Save Replay jump in · Start pause · hold Confirm/Attack fast-forward · Back exit
results-controller-port = Controller P{$port}
results-controller-id = Controller {$id}
results-disconnected-slot = Disconnected slot
results-remote-player = Remote player
results-replay-capture = Replay capture
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = Slot {$index}: {$name}
results-row-kos = KOs
results-row-falls = Falls
results-row-sds = SDs
results-row-damage-given = Damage given
results-row-damage-taken = Damage taken
results-row-blocked = Blocked
results-row-parries = Parries
results-row-power-shields = Power shields
results-row-lag-cancels = Lag cancels
results-row-kb-given = KB given
results-row-kb-taken = KB taken
results-row-kb-absorbed = KB absorbed
results-row-ledge-grabs = Ledge grabs
results-row-ledge-time = Ledge time
results-row-crouch-cancels = Crouch cancels
results-row-velocity-cancels = Velocity cancels

# These labels are shown in the keyboard-shortcuts page and interpolated into prompts and overlap warnings.
controls-action-ui-save-replay = Save Replay
controls-device-unknown = Unknown
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = Keyboard Shortcuts
shortcut-unbound = (unbound)
shortcut-category-menu = Menu Navigation
shortcut-category-general = General
shortcut-category-debug = Debug (TAS)
shortcut-category-training = Training Mode
shortcut-label-menu-up = Move Up
shortcut-label-menu-down = Move Down
shortcut-label-menu-left = Move Left
shortcut-label-menu-right = Move Right
shortcut-label-menu-confirm = Confirm
shortcut-label-menu-next = Next Field
shortcut-label-menu-page-up = Page Up
shortcut-label-menu-page-down = Page Down
shortcut-label-menu-home = First Item
shortcut-label-menu-end = Last Item
shortcut-label-console = Open Console
shortcut-label-chat = Chat
shortcut-label-fullscreen = Toggle Fullscreen
shortcut-label-frame-step = Frame Step (TAS)
shortcut-label-freeze = Freeze (TAS)
shortcut-label-save-state = Save State
shortcut-label-restore-state = Restore State
shortcut-bind = Bind
shortcut-add = Add
shortcut-replace = Replace
shortcut-remove-key = Remove {$key}
shortcut-capture-bind-title = Bind key: {$action}
shortcut-capture-replace-title = Replace key: {$action}
shortcut-capture-hint = Press the key to bind, or Esc to cancel.
shortcut-conflict-detail = {$key} is already bound to {$action}. Reassign?
shortcut-conflict-hint = Press Enter to reassign, Esc to cancel.
shortcut-min-binding = {$action} must keep at least one binding.
shortcut-overlap-menu = Menu-nav overlap: {$keys} also navigates menus. Controller binding wins in menus.
shortcut-overlap-actions = Shortcut overlap: {$overlaps}. Controller binding wins during gameplay.
shortcut-reset-all = Reset all shortcuts to defaults
character-select-help = Select a character.

# Follow-up translation coverage for replay browser/status text and Quick Play setup phases.
# Replay browser rows are assembled in code and then localized via these message IDs.
matchmaking-service-fallback-stun = fallback STUN
matchmaking-status-preparing-binding = Preparing Quick Play... Opening the netplay socket.
matchmaking-status-preparing-primary-stun = Preparing Quick Play... Checking your public UDP route via {$service}.
matchmaking-status-preparing-fallback-stun = Preparing Quick Play... Primary STUN failed, retrying via {$service}.
matchmaking-status-preparing-queueing = Preparing Quick Play... Joining the queue.
matchmaking-status-connecting-tunneling = Match found. Opening the peer-to-peer route...
matchmaking-status-connecting-peer = Peer route open. Finishing the connection handshake...
matchmaking-status-waiting-peer = Route open. Waiting for the other player...
matchmaking-status-starting-battle = Connection ready. Starting the match...
netplay-experimental-note = Experimental — may be unstable
netplay-detail-connecting-peer = Peer route open. Finishing the connection handshake...
netplay-detail-waiting-for-peer = Route open. Waiting for the other player to finish connecting...
netplay-detail-starting-battle = Connection ready. Starting the match...
netplay-detail-matchmaking-binding = Preparing Quick Play. Opening the netplay socket...
netplay-detail-matchmaking-primary-stun = Checking your public UDP route via {$service}...
netplay-detail-matchmaking-fallback-stun = Primary STUN did not answer. Trying {$service}...
netplay-detail-matchmaking-queueing = Joining the matchmaking queue...
netplay-detail-matchmaking-wait = In queue for {$wait}s. Players waiting: {$players}.
replay-stage-fallback = Stage {$number}
replay-unknown-error = unknown error
replay-title = REPLAY
replays-title = REPLAYS
replay-watch-button = Watch Replay
replay-settings-button = Replay Settings
replay-refresh-button = Refresh List
replay-refreshing = Refreshing...
replay-prev-button = Previous Page
replay-prev-disabled = Previous Page -
replay-next-button = Next Page
replay-next-disabled = Next Page -
replay-browser-scanning = Scanning replay directory...
replay-browser-scan-failed = Replay scan failed.
replay-browser-empty = 0 replays found.
replay-browser-page =
    {$first}-{$last} of {$count} { $count ->
        [one] replay
       *[other] replays
    } · Page {$page}/{$pages}
replay-browser-loading = Loading replays...
replay-browser-scanning-files = Scanning saved replay files.
replay-browser-scan-failed-detail = Replay scan failed: {$error}
replay-browser-empty-slot = No replay in this slot.
replay-browser-empty-list = No saved replays found.
replay-browser-root-help = Replay files are loaded recursively from the local replay directory.
replay-title-unreadable = Unreadable: {$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = No result
replay-result-none-winner = Winner: none
replay-result-quit = Quit early
replay-result-tie = Tie
replay-result-winner = Winner: {$winner}
replay-action-participants = Participants: {$players}
replay-action-duration = Duration: {$duration}
replay-action-duration-truncated = Duration: {$duration} (truncated)
replay-action-result = Result: {$result}
replay-action-stage = Stage: {$stage}
replay-action-mode = Mode: {$mode}
replay-action-version = Version: {$version}
replay-action-file = File: {$compression}; Truncated: {$truncated}
replay-compression-compressed = Compressed
replay-compression-uncompressed = Uncompressed
replay-truncated-yes = Yes
replay-truncated-no = No

# Social and versus CPU roster
press-any-button-or-key = Press Any Button or Key
social-title = FRIENDS & INVITES
social-steam = Steam
social-steam-help = Show your lobby on Steam and let friends join from their friends list.
social-discord = Discord
social-discord-help = Show your lobby on Discord and let friends ask to join.
social-info = Off by default. When enabled, the integration loads its platform SDK and shares your lobby join code so friends can join you. Connections still use Antistatic’s own netplay.
social-summary = Steam and Discord rich presence and invites.
social-settings-help = Steam and Discord rich presence and invites. Disabled by default.
versus-add-cpu = Add CPU
versus-cpu-page-prev = Prev
versus-cpu-page-next = Next
versus-cpu-page-help = Change visible CPU page.
versus-no-cpus-added = No CPUs added
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# Controller calibration
controller-calibration-title = CONTROLLER CALIBRATION
controller-calibration-open = Calibrate Controller
controller-calibration-open-help = Inspect and calibrate the selected local controller.
controller-calibration-online-blocked = Controller calibration is unavailable during online play.
controller-calibration-no-local-controller = Connect and select a local controller to calibrate.
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = untagged
controller-calibration-capability-no-axes = This controller reports no calibratable axes.
controller-calibration-capability-native-origin = Native origin data supports automatic calibration.
controller-calibration-capability-absolute-no-automatic = Absolute data available; automatic calibration is unavailable.
controller-calibration-capability-sdl-normalized = SDL normalized input; manual calibration only.
controller-calibration-suspicious-origin-warning = Connection origin looks unreliable and was ignored. Reconnect with all controls released or calibrate manually.
controller-calibration-invalid-saved-warning = Saved calibration ignored: {$reason}
controller-calibration-invalid-shaping-warning = Saved stick settings ignored: {$reason}
controller-calibration-status-policy-preview = policy preview
controller-calibration-status-manual-preview = manual preview
controller-calibration-status-modified = modified
controller-calibration-status-current = current
controller-calibration-status-policy = policy
controller-calibration-status-manual = manual
controller-calibration-status-not-saved = not saved
controller-calibration-status-saved = saved
controller-calibration-status-active-differs = Active differs from saved
controller-calibration-draft-status = {$intent} · draft {$draft} · active {$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = Automatic calibration: {$state}
controller-calibration-automatic-unavailable = unavailable
controller-calibration-automatic-on = on
controller-calibration-automatic-off = off
controller-calibration-automatic-policy-native-help = Toggle automatic GameCube origin calibration.
controller-calibration-automatic-policy-unavailable-help = Automatic calibration is unavailable for this input source.
controller-calibration-axis-left-x = Left stick X
controller-calibration-axis-left-y = Left stick Y
controller-calibration-axis-right-x = Right stick X
controller-calibration-axis-right-y = Right stick Y
controller-calibration-axis-left-trigger = Left trigger
controller-calibration-axis-right-trigger = Right trigger
controller-calibration-field-minimum = minimum
controller-calibration-field-center = center
controller-calibration-field-maximum = maximum
controller-calibration-field-released = released
controller-calibration-field-pressed = pressed
controller-calibration-value-na = N/A
controller-calibration-unit-gamecube-directed = GameCube directed byte
controller-calibration-unit-sdl-normalized = SDL normalized
controller-calibration-unit-canonical-normalized = normalized
controller-calibration-unit-gamecube-protocol-byte = GameCube protocol byte
controller-calibration-axis-values-normalized = {$axis} · {$unit} · source {$source} · corrected {$corrected} · preview {$preview} · gameplay {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} absolute {$absolute}, origin {$origin} · {$sourceUnit} source {$source} · {$normalizedUnit} corrected {$corrected}, preview {$preview}, gameplay {$gameplay}
controller-calibration-axis-statistics = {$samples} samples · min {$minimum} · max {$maximum} · peak {$peak} · jitter {$jitter} · {$unit}
controller-calibration-reported-buttons = Pressed: {$buttons}
controller-calibration-reported-buttons-none = none
controller-calibration-capture-status-ready = ready
controller-calibration-capture-status-waiting-release = release all controls
controller-calibration-capture-status-capturing = capturing
controller-calibration-capture-status-captured = captured
controller-calibration-capture-status-invalid = invalid capture
controller-calibration-capture-neutral = Capture Neutral
controller-calibration-capture-range = Capture Full Range
controller-calibration-capture-help = Release all controls when prompted, then follow the capture action.
controller-calibration-stick-movement = Movement stick
controller-calibration-stick-right = Right / C-stick
controller-calibration-shaping-deadzone = dead zone
controller-calibration-shaping-cardinal-snap = cardinal snap
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting}: {$value}{$unit} · {$step}
controller-calibration-shaping-help = Left/Right adjust · Confirm toggles fine/coarse. Dead zone 0–50%; cardinal snap 0–45°.
controller-calibration-adjust-value = {$axis} {$field}: {$value} {$unit} · {$step}
controller-calibration-step-fine = fine
controller-calibration-step-coarse = coarse
controller-calibration-adjust-help = Left/Right adjust · Confirm toggles fine/coarse.
controller-calibration-apply-current-connection = Apply to Current Connection
controller-calibration-save-to-tag = Save to Controller Tag
controller-calibration-save-to-tag-target = Save to {$tag} ({$layout})
controller-calibration-save-to-tag-no-tag = Save to Tag (tag required)
controller-calibration-reset-draft-active = Reset Draft to Active
controller-calibration-reset-draft-saved = Reset Draft to Saved
controller-calibration-reset-draft-layout-defaults = Reset Draft to Layout Defaults
controller-calibration-reset-session = Reset Connection Session
controller-calibration-delete-saved = Delete Saved Calibration
controller-calibration-delete-saved-confirm = Confirm: Delete Saved Calibration
controller-calibration-copy-diagnostic = Copy Diagnostic
controller-calibration-action-help = Confirm to perform this action.
controller-calibration-applied = Calibration applied to current connection.
controller-calibration-save-tag-required = A valid controller tag is required to save calibration.
controller-calibration-saved = Calibration saved to {$tag} ({$layout}).
controller-calibration-no-saved-calibration = No saved calibration exists for this controller.
controller-calibration-delete-saved-complete = Saved calibration deleted.
controller-calibration-copy-diagnostic-complete = Calibration diagnostic copied.
controller-calibration-local-controllers = Other local controllers
controller-calibration-switch-controller = Switch Controller
controller-calibration-switch-controller-name = Switch to {$controller}
controller-calibration-switch-decision = {$controller} · Left apply · Right {$save} · Confirm discard
controller-calibration-switch-save-available = save
controller-calibration-switch-save-unavailable = save unavailable
controller-calibration-switch-decision-help = Unsaved draft: Left applies, Right saves, Confirm discards and switches.
controller-calibration-back = Back
controller-calibration-back-help = Return to Controls. An active capture is canceled first.
controller-calibration-back-discard-confirm = Confirm: Discard Draft and Go Back
controller-calibration-disconnected-draft-discarded = Controller disconnected; calibration draft discarded.

# PhobGCC guide
controller-calibration-phob-board-unconfirmed = board unconfirmed
controller-calibration-phob-board-v1 = Select PhobGCC v1
controller-calibration-phob-board-v1-value = PhobGCC v1
controller-calibration-phob-board-v2 = Select PhobGCC v2
controller-calibration-phob-board-v2-value = PhobGCC v2
controller-calibration-phob-calibrate-c-stick = Calibrate C-stick: A+X+Y+R
controller-calibration-phob-calibrate-left = Calibrate main stick: A+X+Y+L
controller-calibration-phob-calibration-complete = Complete (keyboard/mouse only)
controller-calibration-phob-calibration-confirm = Confirm: start firmware calibration
controller-calibration-phob-calibration-help = Starts a firmware workflow that must be finished on the controller.
controller-calibration-phob-calibration-no-cancel = Controller input cannot cancel or complete this workflow. Finish it, then select Complete with keyboard/mouse. If stuck, unplug and replug the controller.
controller-calibration-phob-calibration-phases = Follow the other stick's cue through every center, rim, and notch step. Complete both firmware phases before selecting Complete.
controller-calibration-phob-enter-configure = Enter Configure Mode
controller-calibration-phob-enter-configure-instruction = On the physical controller, hold A+X+Y+Start until both sticks report top-right, then release.
controller-calibration-phob-exit-safe-instruction = On the physical controller, press A+X+Y+Start. Release after the longer top-right response.
controller-calibration-phob-host-correction-stale = Antistatic correction after firmware calibration: active {$active}; saved {$saved}. Review defaults or recapture before use.
controller-calibration-phob-instruction-none = no command pending
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = mode unknown
controller-calibration-phob-open = Open PhobGCC Guide
controller-calibration-phob-open-guide-031 = Open official firmware 0.31 guide
controller-calibration-phob-open-help = Guided read-only checks for a user-confirmed PhobGCC v1 or v2.
controller-calibration-phob-open-phobvision-029-v2 = Open PhobVision 0.29 guide (equipped v2 only)
controller-calibration-phob-open-release-031 = Open firmware 0.31 release notes
controller-calibration-phob-open-version-guide = Open guide for reported firmware
controller-calibration-phob-origin-checks = Before changing firmware calibration, activate the sticks with physical B if required and verify the adapter's reported origins.
controller-calibration-phob-query-c-settings = Read C-stick settings: R+Start
controller-calibration-phob-query-main-settings = Read main-stick settings: L+Start
controller-calibration-phob-query-trigger-settings = Read trigger settings: L+R+Z
controller-calibration-phob-query-version = Read firmware version: A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = Raw diagnostics are active. Values are unprocessed sensor reports in the 0..100 range, not gameplay output.
controller-calibration-phob-raw-disable = Disable raw output: L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = On the physical controller, press L+R+D-pad Down, wait for the top-right response, then release everything.
controller-calibration-phob-raw-enable = Enable raw output: L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = On the physical controller, press L+R+D-pad Up, wait for the top-right response, then release everything.
controller-calibration-phob-raw-values = raw main X {$leftX}, Y {$leftY}; C-stick X {$cX}, Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = raw values unavailable
controller-calibration-phob-remap-warning = Commands use physical shell-labeled buttons despite firmware remaps. Antistatic observes reported buttons, which may differ.
controller-calibration-phob-result-matched = Phob-style response matched
controller-calibration-phob-result-none = no response yet
controller-calibration-phob-result-unknown-custom = unknown or custom response
controller-calibration-phob-result-version-known = firmware {$version}
controller-calibration-phob-result-version-no-response = no firmware response; version unknown
controller-calibration-phob-return-safe = Return to Safe Mode
controller-calibration-phob-safe-recovery = To guarantee Safe Mode, unplug and replug the controller. Reopen this guide afterward; its detected state resets on disconnect.
controller-calibration-phob-setting-c-response-x-raw = C-stick X response byte
controller-calibration-phob-setting-c-response-y-raw = C-stick Y response byte
controller-calibration-phob-setting-c-snapback-x = C-stick snapback X
controller-calibration-phob-setting-c-snapback-y = C-stick snapback Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick waveshaping X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick waveshaping X raw
controller-calibration-phob-setting-c-waveshaping-y = C-stick waveshaping Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick waveshaping Y raw
controller-calibration-phob-setting-main-smoothing-x = main-stick smoothing X
controller-calibration-phob-setting-main-smoothing-y = main-stick smoothing Y
controller-calibration-phob-setting-main-snapback-x = main-stick snapback X
controller-calibration-phob-setting-main-snapback-y = main-stick snapback Y
controller-calibration-phob-setting-main-waveshaping-x = main-stick waveshaping X
controller-calibration-phob-setting-main-waveshaping-x-raw = main-stick waveshaping X raw
controller-calibration-phob-setting-main-waveshaping-y = main-stick waveshaping Y
controller-calibration-phob-setting-main-waveshaping-y-raw = main-stick waveshaping Y raw
controller-calibration-phob-setting-row = {$setting}: {$value} {$unit}
controller-calibration-phob-setting-rows-none = no decoded settings
controller-calibration-phob-settings-c-stick-instruction = On the physical controller, hold R+Start for the two-second readout, then release.
controller-calibration-phob-settings-main-instruction = On the physical controller, hold L+Start for the two-second readout, then release.
controller-calibration-phob-settings-read-only = These readouts do not change firmware settings. Use official instructions for changes and resets.
controller-calibration-phob-settings-triggers-instruction = On the physical controller, hold L+R+Z for the two-second readout, then release.
controller-calibration-phob-setting-trigger-left-mode = left trigger mode
controller-calibration-phob-setting-trigger-left-value = left trigger value
controller-calibration-phob-setting-trigger-right-mode = right trigger mode
controller-calibration-phob-setting-trigger-right-value = right trigger value
controller-calibration-phob-setup-active = Phob Setup Mode active: reported D-pad navigates and reported A confirms.
controller-calibration-phob-setup-enter = Enter Phob Setup Mode
controller-calibration-phob-setup-exit = Exit Phob Setup Mode
controller-calibration-phob-setup-exit-chord = To exit, hold exactly reported D-pad Down+Left + main stick top-right + C-stick bottom-right for one second, then release. Disabled during firmware calibration.
controller-calibration-phob-stale-state-current = current
controller-calibration-phob-stale-state-stale = stale
controller-calibration-phob-status = Board: {$board} · Mode: {$mode} · Result: {$result} · Step: {$instruction} · {$raw} · Settings: {$rows}
controller-calibration-phob-unit-protocol-byte = protocol byte
controller-calibration-phob-unit-setting-value = setting value
controller-calibration-phob-unit-trigger-byte = trigger byte
controller-calibration-phob-unofficial-warning = Unofficial, unaffiliated PhobGCC helper. Confirm your board and firmware; Antistatic cannot identify hardware or write settings.
controller-calibration-phob-version-instruction = In Configure Mode, press physical A+Z+D-pad Up, hold the readout for two seconds, then release.
controller-calibration-mode-basic = View: BASIC
controller-calibration-mode-advanced = View: ADVANCED
controller-calibration-mode-toggle-help = Switch between common controls and detailed calibration diagnostics.
controller-calibration-origin-diagnostic-unavailable = Automatic origin diagnostics are unavailable for this source.
controller-calibration-origin-diagnostic = Stable-window origin: {$phase} · {$reports} reports · {$stable}/6 applied · {$fallback}/6 fallback · {$dropped} overruns
controller-calibration-origin-phase-collecting = collecting
controller-calibration-origin-phase-complete = complete
controller-calibration-use-suggested-deadzones = Use Suggested Dead Zones
controller-calibration-use-suggested-deadzones-help = Apply measured inner and outer dead-zone suggestions to this draft.
controller-calibration-section-stick-shaping = STICK SHAPING
controller-calibration-section-trigger-shaping = TRIGGER SHAPING
controller-calibration-section-action-diagnostics = ACTION DIAGNOSTICS
controller-calibration-section-physical-diagnostics = PHYSICAL AXIS DIAGNOSTICS
controller-calibration-section-hardware-correction = HARDWARE CORRECTION
controller-calibration-shaping-inner-deadzone = inner dead zone
controller-calibration-shaping-outer-deadzone = outer dead zone
controller-calibration-snap-override-help = Toggle the player override. The current ruleset floor still applies.
controller-calibration-snap-override-state = {$stick} snap override: {$state} · ruleset floor {$floor}° · effective {$effective}°
controller-calibration-override-enabled = enabled
controller-calibration-override-disabled = disabled
controller-calibration-trigger-shaping-help = Left/Right adjust · Confirm toggles fine/coarse.
controller-calibration-trigger-inner-deadzone = inner dead zone
controller-calibration-trigger-outer-deadzone = outer dead zone
controller-calibration-trigger-response-curve = response curve
controller-calibration-trigger-hard-press-threshold = hard press threshold
controller-calibration-trigger-shaping-value = {$trigger} {$setting}: {$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = Measured: move noise {$movementNoise}, suggested inner {$movementInner}, outer {$movementOuter}, coverage {$movementCoverage}/16 · right noise {$rightNoise}, suggested inner {$rightInner}, outer {$rightOuter}, coverage {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = Triggers: L noise {$leftNoise}, suggested inner {$leftInner}, outer {$leftOuter} · R noise {$rightNoise}, suggested inner {$rightInner}, outer {$rightOuter}
controller-calibration-stick-diagnostic = {$stick}: mapped {$mapped} · gameplay {$gameplay} · {$zone} · snapped {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger}: mapped {$mapped} · gameplay {$gameplay} · {$zone} · hard {$hard}
controller-calibration-zone-inner-dead = inner dead zone
controller-calibration-zone-linear = active range
controller-calibration-zone-outer-saturated = outer saturation
controller-calibration-state-yes = yes
controller-calibration-state-no = no
controller-calibration-hard-source-none = none
controller-calibration-hard-source-digital-button = digital click
controller-calibration-hard-source-analog-threshold = analog threshold
