hello-world = Bonjour le monde! { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = Silicium
Iron = Fer
Xenon = Xénon
Helium = Hélium
Carbon = Carbone
Rhodium = Rhodium

Sandbag = Sac de sable

Ruins = Ruines
Transistor = Transistor
Eroded = Érodé
Scales = Balance
Crossing = Le Passage
Longboat = Longboat
Boombox = Boombox
Fountain = Fontaine
Great-White = Grand Blanc
Plane = Plan
Satellite = Satellite
Divided = Divisé
Pillars = Piliers
Debug = Déboguer

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = Vanilla
Physics = Physique
color-preset-random = Aléatoire
color-preset-red = Rouge
color-preset-orange = Orange
color-preset-gold = Or
color-preset-green = Vert
color-preset-blue = Bleu
color-preset-purple = Violet
color-preset-pink = Rose
color-preset-white = Blanc
versus-color-preset-help = Choisissez une famille de couleurs ; chaque choix reçoit une légère variation aléatoire. Désactivé en mode équipes.

# Navigation
Back = Retour
Exit = Sortir
Save = Sauvegarder
Cancel = Annuler
Close-Symbol = X

Modify = Modifier
Reset = Réinitialiser

# Training Menu
Swap-Character = Echange de personnage
Overlays = Superpositions
press-start = Appuyez sur Start

drawHitbubbleInfo = Informations d'Attaque
drawECB = Collision
drawHeatmap = Carte de Chaleur
drawRawPosition = Position Brute
drawStage = Collision d'Étape
animations = Animations
controllers = Contrôleurs

# Main Menu
Versus = Versus
Training = Entrainement
Courses = Parcours
TRAINING = ENTRAINEMENT
COURSES = PARCOURS
battle-results = Résultats du combat
Settings = Paramètres
Controls = Contrôles
Discord = Discord {"\u29C9"}
Guide = Guide {"\u29C9"}

# Settings Menu
SETTINGS = PARAMÈTRES
Audio = Son
Video = Video
accessibility-title = Accessibilité
settings-accessibility-help = Réglez les mouvements, les effets d'impact, les sons du menu et la visibilité du focus.
accessibility-reduced-motion = Mouvements réduits
accessibility-reduced-motion-help = Arrête l'animation du décor des menus et les secousses visuelles d'impact.
accessibility-hit-flash = Flash d'impact : {$value}
accessibility-hit-flash-help = Réglez la luminosité des flashs d'impact des personnages.
accessibility-screen-shake = Secousse d'impact : {$value}
accessibility-screen-shake-help = Réglez les secousses visuelles des personnages et de l'ATH lors des impacts.
accessibility-menu-sound = Accentuer les sons du menu
accessibility-menu-sound-help = Augmente le volume des sons de navigation et de confirmation.
accessibility-high-contrast-focus = Focus à contraste élevé
accessibility-high-contrast-focus-help = Ajoute un double contour lumineux à la commande de menu sélectionnée.
accessibility-help = Réglez les préférences d'accessibilité et de présentation.
first-run-title = Bienvenue dans Antistatic
first-run-intro = Choisissez un point de départ. Les commandes et l'accessibilité restent disponibles dans le menu principal.
first-run-versus = Versus local
first-run-versus-help = Configurez un match pour les joueurs qui partagent cet appareil.
first-run-controls = Commandes
first-run-controls-help = Consultez, réassignez et calibrez vos commandes.
first-run-training = Entraînement
first-run-training-help = Entraînez-vous librement avec les outils et les cibles.
first-run-courses = Cours
first-run-courses-help = Apprenez les déplacements, les attaques, la défense et la récupération avec des leçons guidées.
first-run-skip = Aller au menu principal (Passer)
first-run-skip-help = Terminez cette présentation unique sans ouvrir de mode.
first-run-help = Choisissez où commencer. Chaque choix termine cette présentation unique.
Windowed = Fenêtré
Fullscreen = Plein Écran

main = Menu principal
versus = Versus
training = Entrainement
start-mode = Commencer: { TRANSLATE($value) }

# Audio Menu
AUDIO = SON

Play-Audio = Jouer Son
Play-Music = Jouer de la Musique

Audio-volume = Volume: {$value}
SFX-volume = SFX: {$value}
Music-volume = Musique: {$value}
UI-volume = UI: {$value}
Voice-volume = Voix: {$value}

# Video Menu
VIDEO = VIDÉO
Quick-Setup = Configuration rapide
Display = Affichage
Quality = Qualité
Effects = Effets
Apply-Changes = Appliquer les modifications

graphics-preset-low = Graphismes : Faible
graphics-preset-medium = Graphismes : Moyen
graphics-preset-high = Graphismes : Élevé
graphics-preset-max = Graphismes : Maximum
graphics-preset-custom = Graphismes : Personnalisé

vsync-off = Vsync: Désactivé
vsync-on = Vsync: Activé
vsync-adaptive = Vsync: Adaptatif

shadow-off = Ombres: Désactivé
shadow-low = Ombres: Faible
shadow-highest = Ombres: Maximum

ssao-off = SSAO: Désactivé
ssao-on = SSAO: Activé
ssao-full = SSAO: Complet

aa-off = Anticrénelage: Désactivé
aa-fxaa = Anticrénelage: FXAA
aa-fxaa-high = Anticrénelage: FXAA élevé

bloom-off = Bloom : Désactivé
bloom-on = Bloom : Activé
reflections-off = Reflets : Désactivé
reflections-on = Reflets : Activé
reflections-low = Reflets : Faible
reflections-high = Reflets : Élevé
godrays-off = Rayons de soleil : Désactivé
godrays-on = Rayons de soleil : Activé

perf-overlay-off = Indicateur de perf : Désactivé
perf-overlay-on = Indicateur de perf : Activé


point-lights-off = Lumières ponctuelles : Désactivées
point-lights-on = Lumières ponctuelles : Activées

particles-low = Particules : Faible
particles-medium = Particules : Moyen
particles-full = Particules : Maximum


max-fps-off = FPS max : Désactivé
max-fps-30 = FPS max : 30
max-fps-60 = FPS max : 60
max-fps-120 = FPS max : 120
max-fps-144 = FPS max : 144

# Controls Menu
CONTROLS = CONTRÔLES

controls-title = CONTRÔLES
controls-section-controllers = Manettes
controls-section-mappings = Assignations
controls-set-tag = Définir le tag
controls-edit-bindings = Modifier la configuration
controls-tag-untagged = (aucun tag)
controls-tag-title = Tag du joueur
controls-tag-prompt = P{$port} ({$layout}). Les tags peuvent contenir 1-24 caractères alphanumériques, «-» ou «_». Laisser vide pour effacer.
controls-tag-confirm = Confirmer
controls-tag-clear = Effacer
controls-tag-cancel = Annuler
controls-tag-select-title = Choisir un tag
controls-tag-filter-empty = Tapez pour filtrer les tags enregistrés
controls-tag-filter-value = Filtre : {$filter}
controls-tag-summary-empty = {$total} tags enregistrés. Tapez pour filtrer ou créer un nouveau tag.
controls-tag-summary-filter = {$visible} sur {$total} tags enregistrés affichés. Les correspondances exactes utilisent les contrôles enregistrés.
controls-tag-defaults-suffix = valeurs par défaut pour cette manette
controls-tag-create-new = Créer un nouveau tag
controls-tag-use-existing = Utiliser le tag existant « {$tag} »
controls-tag-create = Créer « {$tag} »
controls-tag-reserved = « {$tag} » est réservé
controls-tag-netplay-blocked = Les tags ne peuvent pas être modifiés pendant le netplay
controls-tag-no-controller = Aucune manette locale sélectionnée
controls-tag-no-layout = La manette sélectionnée n'a pas de configuration
controls-tag-filter-help = Tapez pour filtrer les tags ; Échap efface ou quitte
controls-tag-no-saved = Aucun tag enregistré pour le moment
controls-tag-no-matches = Aucun tag correspondant
controls-tag-invalid = Tag invalide (1-24 caractères, alphanumériques/-/_ ; « default » réservé)
controls-profile-help-untagged = Les commandes sont enregistrées dans le profil partagé sans tag ; seul le saut avec le stick exige un tag.
controls-profile-help-tagged = Les contrôles et le saut avec le stick par défaut sont enregistrés pour ce tag et ce type de manette.
controls-choose-existing-tag = Choisir un tag existant
controls-create-tag = Créer un tag
controls-rename-create-tag = Renommer/créer un tag
controls-edit-set-tag-first = Modifier les contrôles (définir un tag d'abord)
controls-edit-controls = Modifier les contrôles
controls-tap-jump-default = Saut avec le stick par défaut : {$state}
controls-state-on = OUI
controls-state-off = NON
controls-netplay-blocked = Les contrôles ne peuvent pas être modifiés pendant le netplay
controls-no-local-controllers = Aucune manette active. Appuyez sur une touche de jeu ou un bouton de manette pour en connecter une.
controls-no-layout = La manette n'a pas de configuration
controls-set-tag-before-editing = Définissez un tag avant de modifier les contrôles
controls-no-mapping = Aucune assignation disponible pour cette manette
controls-set-tag-before-tap-jump = Définissez un tag pour enregistrer le saut avec le stick par défaut
controls-connected-controllers = Manettes connectées
controls-remap-add-key = + Ajouter une assignation (appuyez sur une touche)
controls-remap-find-input = Trouver une assignation (appuyez sur une entrée)
controls-remap-capture-key-title = Appuyez sur une touche
controls-remap-capture-input-title = Appuyez sur une entrée
controls-remap-capture-key-help = La prochaine touche appuyée sera ajoutée comme nouvelle assignation.
controls-remap-capture-input-help = Le prochain bouton ou stick utilisé sera sélectionné pour modification.
controls-remap-capture-cancel = Échap pour annuler
controls-default-save-blocked = Les contrôles par défaut ne peuvent pas être remplacés ; définissez d'abord un tag
controls-default-reset-blocked = Les contrôles par défaut ne peuvent pas être réinitialisés depuis ce menu
controls-tag-filter-entry-help = Tapez pour filtrer les tags de manette enregistrés ; les manettes peuvent utiliser la croix directionnelle.
controls-tag-filter-label = Filtre
controls-tag-preconfigured = préconfiguré
controls-tag-rename-title = Renommer le tag
controls-tag-create-title = Créer un tag
controls-tag-apply-existing-help = Appliquer à cette manette le tag enregistré correspondant.
controls-tag-create-empty-help = Créer un nouveau tag pour cette manette.
controls-tag-create-filtered-help = Créer ce tag pour la manette si le nom est valide.
controls-tag-apply-saved-help = Appliquer ce tag et sa configuration enregistrée à la manette.
controls-tag-apply-preconfigured-help = Appliquer ce tag préconfiguré avec le mapping par défaut pour ce type de manette.
controls-tag-apply-default-help = Appliquer ce tag avec le mapping par défaut pour ce type de manette.
controls-tag-delete-button = Supprimer {$tag}
controls-tag-delete-help = Supprime {$tag}, ses contrôles et son calibrage enregistrés pour chaque type de manette après confirmation.
controls-tag-delete-title = Supprimer le tag ?
controls-tag-delete-body = Supprimer « {$tag} », ses contrôles et son calibrage pour chaque type de manette, et le retirer des manettes connectées ?
controls-tag-delete-warning = Cette action est irréversible.
controls-back-help = Retour à Contrôles.
controls-tag-select-help = Choisissez ou créez un tag de manette.
controls-edit-set-tag-first-help = Créez d'abord un tag de manette, puis modifiez les affectations de jeu et de menu.
controls-edit-controls-help = Modifier les affectations de jeu et de menu pour ce profil de manette.
controls-tap-jump-set-tag-first-help = Créez d'abord un tag de manette, puis définissez la préférence de saut sur appui par défaut.
controls-tap-jump-default-help = Active ou désactive le saut par défaut de cette manette quand on appuie vers le haut.
controls-create-new-tag-help = Créez un nouveau tag et affectez-y cette manette.
controls-choose-existing-tag-help = Choisissez ou supprimez un tag enregistré.
controls-rename-current-tag-help = Renommez le tag actuel de la manette.
controls-switch-controller-help = Bascule le menu Contrôles vers cette manette connectée.
menu-binding-hint = Déplacez-vous avec le stick ou la croix · Confirmer/Start sélectionne · Retour revient en arrière
menu-adjust-hint = Déplacez-vous avec le stick ou la croix · Gauche/Droite modifie les valeurs · Confirmer sélectionne · Retour revient en arrière
menu-bind-hint = Déplacez-vous avec le stick ou la croix · Confirmer choisit une assignation · Retour revient en arrière
arcade-select-leave = Select quitte
main-help-about-help = Guides, crédits et liens bluehexagons.
main-replays-available-help = Parcourez, prévisualisez et lancez les fichiers de replay enregistrés.
main-replays-unavailable-help = Les replays ne sont disponibles qu'hors ligne, car ils sont chargés depuis le système de fichiers local.
arcade-menu-battles-help = Lance la configuration actuelle d'Arcade Battles.
arcade-menu-infinite-help = Lance le mode Arcade sans fin avec des CPU à 1 stock qui montent en puissance.
arcade-menu-training-help = Ouvre l'entraînement avec ses outils de pratique et ses sauvegardes d'état.
arcade-menu-back-help = Retourne au menu principal.
arcade-menu-help = Choisissez un mode arcade.
training-menu-courses-help = Choisissez un court parcours sur les mécaniques du jeu.
training-menu-help = Choisissez une activité d'entrainement.
courses-menu-course-help = Visitez cette zone du parcours.
courses-menu-back-help = Retourner à l'entrainement.
courses-menu-help = Les zones des parcours vont de gauche à droite. Vous pouvez vous déplacer librement à tout moment.
course-instruction-movement-walk = Inclinez le stick de déplacement à gauche ou à droite pour marcher.
course-instruction-movement-dash = Donnez un coup sec au stick de déplacement à gauche ou à droite pour sprinter.
course-instruction-movement-crouch = Appuyez vers le bas pour vous accroupir.
course-name-movement = Déplacement
course-name-jumping = Sauts
course-name-attacks = Attaques
course-name-defense = Défense
course-name-advanced = Avancé
course-name-directional-influence = Influence directionnelle
course-name-teching = Tech
course-summary-movement = Marchez, sprintez, accroupissez-vous et atteignez le repère.
course-summary-jumping = Sautez, ressautez en l'air, saisissez les rebords et exercez les sauts muraux disponibles.
course-summary-attacks = Attaquez au sol et dans les airs, puis dépensez de l'énergie avec une attaque spéciale.
course-summary-defense = Bloquez, faites un bouclier parfait, esquivez, roulez, parez et saisissez.
course-summary-advanced = Utilisez les attaques au stick, l'esquive aérienne, la chute rapide et la récupération spéciale haute.
course-summary-directional-influence = Utilisez le stick de déplacement pour modifier la trajectoire d'un propulseur dangereux.
course-summary-teching = Faites un tech à l'atterrissage après une propulsion dangereuse.
course-instruction-movement-travel = Allez jusqu'au repère en forme de flèche.
course-instruction-jumping-jump = Appuyez sur saut pour quitter le sol.
course-instruction-jumping-air-jump = Appuyez à nouveau sur saut dans les airs pour effectuer un saut aérien.
course-instruction-jumping-steer = Maintenez gauche ou droite après le saut pour vous diriger dans les airs.
course-instruction-jumping-ledge-grab = Approchez un bord de plateforme par dessous pour vous y accrocher.
course-instruction-jumping-wall-jump = Touchez le mur supérieur, puis donnez un coup sec dans la direction opposée pour rebondir dessus.
course-instruction-attacks-normal = Touchez la cible d'entraînement avec une attaque normale.
course-instruction-attacks-aerial = Sautez et touchez la cible d'entraînement avec une attaque aérienne.
course-instruction-attacks-energy = Utilisez une attaque spéciale et observez la jauge d'énergie partagée diminuer, puis se remplir après un délai.
course-instruction-attacks-special = Touchez la cible d'entraînement avec une attaque spéciale.
course-instruction-defense-shield = Bloquez l'attaque de la cible d'entraînement avec votre bouclier.
course-instruction-defense-power-shield = Appuyez fermement sur le bouclier juste avant l'impact pour réussir un bouclier parfait sans perdre d'énergie.
course-instruction-defense-roll = En maintenant le bouclier, appuyez à gauche ou à droite pour rouler.
course-instruction-defense-spot-dodge = En maintenant le bouclier, appuyez vers le bas pour esquiver sur place.
course-instruction-defense-parry = Relâchez le bouclier juste avant l'impact pour parer.
course-instruction-defense-grab = Saisissez la cible d'entraînement.
course-instruction-advanced-stick = Donnez un coup sec au stick droit dans une direction pour effectuer une attaque au stick.
course-instruction-advanced-air-dodge = Sautez, puis appuyez fermement sur un bouton de bouclier pour esquiver dans les airs.
course-instruction-advanced-fast-fall = Dans les airs, appuyez vers le bas pour chuter rapidement.
course-instruction-advanced-recovery = Dans les airs, appuyez vers le haut et sur Spécial pour remonter avec un spécial haut.
course-instruction-directional-influence = Maintenez gauche ou droite quand le propulseur vous touche pour modifier votre angle de projection.
course-instruction-teching-neutral = Appuyez fermement sur un bouton de bouclier juste avant d'atterrir après la propulsion pour faire un tech.
course-instruction-complete = Zone terminée. Passez à une autre zone quand vous êtes prêt.
course-action-restart = Recommencer la zone
course-action-next = Zone suivante
course-session-progress = Zones terminées : {$completed}/{$total}
course-target-label = Cible d'entraînement
course-target-reset = Réinitialiser la cible
course-target-disable = Désactiver la cible
course-target-enable = Activer la cible
course-target-unavailable = Aucune cible dans cette zone
course-target-reset-help = Replace la cible d'entraînement de cette zone à sa position initiale et l'active.
course-target-toggle-help = Masque ou restaure la cible d'entraînement de cette zone pour la session en cours.
course-defense-feedback-early = Protégez-vous plus près de l'attaque.
course-defense-feedback-late = Trop tard. Protégez-vous avant que l'attaque ne touche.
course-defense-feedback-success = Bon timing. L'attaque a été bloquée.
course-demonstration-label = Démonstration
course-demonstration-show = Afficher la démo statique
course-demonstration-hide = Masquer la démo statique
course-demonstration-help = Affiche ou masque un exemple sans animation pour l'étape actuelle de la leçon.
course-demonstration-still = Pose fixe · sans animation
help-bluehex-homepage-help = Visitez la page d'accueil de bluehexagons.
help-bluehex-github-help = Parcourez les projets bluehexagons sur GitHub.
help-bluehex-steam-help = Ouvrez la page curateur Steam de bluehexagons.
help-bluehex-itch-help = Ouvrez la page itch.io de bluehexagons.
help-bluehex-bluesky-help = Suivez bluehexagons sur Bluesky.
help-bluehex-patreon-help = Soutenez bluehexagons sur Patreon.
controls-source-keyboard = Clavier
controls-source-keyboard-defaults = Paramètres clavier par défaut
controls-current-menu-controls-heading = Contrôles actuels du menu
controls-current-menu-controls-summary = {$source} · Déplacer : {$navigate} · Confirmer : {$confirm} · Retour : {$back}
controls-action-attack = Attaque
controls-action-jump = Saut
controls-action-special = Spécial
controls-action-grab = Saisie
controls-action-shield-1 = Bouclier 1
controls-action-shield-2 = Bouclier 2
controls-action-hard-shield-1 = Bouclier fort 1
controls-action-hard-shield-2 = Bouclier fort 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = Croix haut
controls-action-dpad-down = Croix bas
controls-action-dpad-left = Croix gauche
controls-action-dpad-right = Croix droite
controls-action-move-horizontal = Mouvement horizontal
controls-action-move-vertical = Mouvement vertical
controls-action-right-stick-horizontal = Stick droit horizontal
controls-action-right-stick-vertical = Stick droit vertical
controls-action-ui-confirm = Confirmer UI
controls-action-ui-back = Retour UI
controls-action-ui-up = UI haut
controls-action-ui-down = UI bas
controls-action-ui-left = UI gauche
controls-action-ui-right = UI droite
controls-action-ui-horizontal-nav = Navigation UI horizontale
controls-action-ui-vertical-nav = Navigation UI verticale
controls-action-move-left = Aller à gauche
controls-action-move-right = Aller à droite
controls-action-move-up = Aller en haut
controls-action-move-down = Aller en bas
controls-action-tilt-left = Inclinaison gauche
controls-action-tilt-right = Inclinaison droite
controls-action-tilt-up = Inclinaison haut
controls-action-tilt-down = Inclinaison bas
controls-action-right-stick-left = Stick droit gauche
controls-action-right-stick-right = Stick droit droite
controls-action-right-stick-up = Stick droit haut
controls-action-right-stick-down = Stick droit bas
controls-action-light-shield-l = Bouclier léger L
controls-action-light-shield-r = Bouclier léger R
controls-action-ui-nav-left = Navigation UI gauche
controls-action-ui-nav-right = Navigation UI droite
controls-action-ui-nav-up = Navigation UI haut
controls-action-ui-nav-down = Navigation UI bas
controls-remap-section-buttons = Boutons
controls-remap-section-dpad = Croix
controls-remap-section-movement = Mouvement
controls-remap-section-tilts = Inclinaisons (mouvement léger)
controls-remap-section-right-stick = Stick droit
controls-remap-section-light-shields = Boucliers légers
controls-remap-section-ui-navigation = Navigation UI
controls-remap-section-sticks-triggers = Sticks et gâchettes
controls-remap-unbound = Non assigné
controls-remap-free-keys-none = Touches libres : (aucune dans l'ensemble courant)
controls-remap-more-suffix = , +{$count} de plus
controls-remap-free-keys = Touches libres : {$keys}{$suffix}
controls-remap-free-buttons = Boutons libres : {$buttons}
controls-remap-free-axes = Axes libres : {$axes}
controls-remap-conflict-detail = {$input} est déjà assigné à {$actions}.
controls-remap-row-label = {$label} : {$input}
controls-remap-protected-ui-bindings = Gardez Confirmer UI, Retour UI et la navigation horizontale et verticale pour que les menus restent utilisables.
controls-remap-capture-key-hint = Appuyez sur une touche du clavier pour {$action}. ESC annule.
controls-remap-capture-button-hint = Appuyez sur un bouton {$layout} pour {$action}. Retour annule.
controls-remap-capture-axis-hint = Bougez un stick/gâchette {$layout} pour {$action}. Retour annule.
controls-remap-capture-add-title = Ajouter {$action}
controls-remap-capture-replace-title = Remplacer {$action}
controls-remap-capture-matching-input = Utilisez une entrée compatible pour cette action.
controls-remap-confirm-reassign = Confirmez pour le réaffecter à {$action}.
controls-remap-confirm-cancel-help = Confirmer le remplace. Retour annule.
controls-remap-command-add = Ajouter
controls-remap-command-replace = Remplacer
controls-remap-command-remove = Retirer
controls-remap-add-help = Ajouter une autre entrée physique pour {$action}.
controls-remap-replace-help = Remplacer {$input} pour {$action}.
controls-remap-remove-help = Retirer {$input} de {$action}.
controls-remap-back-to-controls = Retour à Contrôles
controls-remap-back-to-controls-help = Retourner à Contrôles sans faire défiler jusqu'en bas de la liste de remappage.
controls-remap-help = Choisissez Ajouter, Remplacer ou Retirer. Les touches Page sautent dans la liste.
controls-remap-help-extended = Choisissez Ajouter, Remplacer ou Retirer. Les touches Page sautent dans la liste ; Retour annule.
controls-remap-jump-to-section = Aller à la section
controls-remap-jump-to-binding = Aller à {$section}
controls-remap-focus-section-help = Déplacer le focus vers la première affectation {$section}.
controls-remap-reset-help = Réinitialise ce profil de contrôles à sa disposition par défaut. Deux confirmations sont nécessaires.
controls-remap-reset-confirm = Appuyez encore pour confirmer la réinitialisation
controls-quick-map-action-unbound = Non assigné
controls-quick-map-action-hard-shield-1-short = Bouclier 1
controls-quick-map-action-hard-shield-2-short = Bouclier 2
controls-quick-map-action-dpad-up-short = D-Haut
controls-quick-map-action-dpad-down-short = D-Bas
controls-quick-map-action-dpad-left-short = D-Gauche
controls-quick-map-action-dpad-right-short = D-Droite
controls-quick-map-title = Configuration rapide {$layout}
controls-quick-map-mode-editing = Confirmer ou cliquer sur une action pour appliquer · Retour ou cliquer sur le titre pour quitter
controls-quick-map-mode-ready = Confirmer ouvre l'édition rapide
controls-quick-map-mode-unavailable = Contrôles indisponibles
controls-quick-map-assign = Assigner
controls-quick-map-assign-input = Assigner {$input}
controls-quick-map-unavailable-status = La configuration rapide est indisponible pour cette manette. Aucun changement enregistré.
controls-remap-autosave-status = Les changements sont enregistrés automatiquement.
controls-remap-saved-status = Enregistré automatiquement.
controls-remap-blocked-menu-controls-status = Bloqué : gardez Confirmer UI, Retour UI et la navigation horizontale et verticale du menu. Aucun changement enregistré.
controls-remap-default-reset-blocked-status = Les contrôles intégrés par défaut ne peuvent pas être réinitialisés. Aucun changement enregistré.
controls-layout-standard = Xbox / standard
controls-layout-arcade-stick = Stick arcade
controls-layout-retro-dpad = Croix rétro
controls-layout-switch-pro = Switch Pro
controls-layout-playstation = PlayStation
controls-layout-8bitdo-nintendo = 8BitDo (disposition Nintendo)
controls-layout-steam-deck = Steam Deck
controls-layout-gamecube = GameCube
controls-layout-n64 = Nintendo 64
controls-layout-keyboard = Clavier

standard = Standard
keyboard = clavier
gcn_native = GCN native

# Versus Menu
FFA = FFA
Teams = Les équipes

Host-Netplay = Netplay hôte
Join-Netplay-Clipboard = Rejoindre Netplay depuis le presse papier
Disconnect = Déconnecter
Copy-Lobby-Code = Copier le code du lobby

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = Connexion directe
Connect = Se connecter

netplay-action-start-lobby = Démarrer le lobby
netplay-action-join-clipboard = Rejoindre depuis le presse-papiers
netplay-action-quick-host-copy-code = Hôte rapide et copier le code
netplay-action-copy-lan-invite = Copier l'invitation LAN
netplay-action-copy-localhost-invite = Copier l'invitation localhost
netplay-action-copy-stun-invite = Copier l'invitation STUN
netplay-action-find-random-match = Trouver une partie aléatoire
netplay-action-cancel-lobby = Annuler le lobby
netplay-action-cancel-connection = Annuler la connexion
netplay-action-please-wait = Veuillez patienter
netplay-action-open-versus = Ouvrir Versus
netplay-action-cancel-matchmaking = Annuler le matchmaking

netplay-status-label = Jeu en ligne : {$status}
netplay-status-uninitialized = non initialisé
netplay-status-initialized = initialisé
netplay-status-waiting = en attente
netplay-status-hosting = hébergeant
netplay-status-connecting = connexion en cours
netplay-status-establishing = établissement en cours
netplay-status-connected = connecté
netplay-status-ready = Prêt pour le netplay
netplay-status-waiting-player = En attente d'un joueur
netplay-status-waiting-lobby = En attente de réponse du lobby
netplay-status-hosting-lobby = Hébergement du lobby
netplay-status-hosting-lobby-code = Hébergement du lobby {$code}
netplay-status-starting-lobby = Démarrage du lobby
netplay-status-connecting-host = Connexion à l'hôte
netplay-status-connected-host = Connecté en tant qu'hôte
netplay-status-connected-client = Connecté à l'hôte
netplay-status-disconnecting = Déconnexion en cours
netplay-status-canceling = Annulation de la connexion
netplay-status-matchmaking = Recherche d'une partie aléatoire
netplay-status-match-found = Partie aléatoire trouvée
netplay-status-matchmaking-canceling = Annulation du matchmaking
netplay-status-error = Erreur netplay
netplay-status-error-message = Erreur netplay : {$error}
netplay-status-unavailable = État du netplay indisponible

matchmaking-title = RECHERCHE DE MATCH
matchmaking-status-select-character = Choisissez un personnage pour entrer dans la file
matchmaking-status-no-controller = Aucune manette connectée
matchmaking-status-searching = Recherche d'un match...
matchmaking-status-searching-details = Recherche... {$wait}s écoulées. Joueurs en attente : {$players}. Attente la plus longue : {$longest}s.
matchmaking-status-searching-estimate = Recherche... {$wait}s écoulées. Joueurs en attente : {$players}. Les matchs terminés ont duré {$average}s en moyenne.
matchmaking-status-canceling = Annulation...
matchmaking-status-found = Match trouvé !
matchmaking-status-connecting = Connexion...
matchmaking-status-disconnecting = Déconnexion...
matchmaking-status-error = {$error} Choisissez un personnage pour réessayer.

# Match by Code
match-code-title = MATCH PAR CODE
match-code-hint = Partagez votre code. Saisissez le sien. Appuyez tous les deux sur Rechercher. La casse n’a pas d’importance.
match-code-own-label = Votre code : {$code}
match-code-peer-label = Code de votre ami : {$code}
match-code-peer-unset = Code de votre ami : (non défini)
match-code-search = Rechercher
match-code-entry-limit = {$length} lettres ou chiffres maximum
match-code-own-prompt = Votre code
match-code-peer-prompt = Code de votre ami
match-code-status-enter-peer = Saisissez le code de votre ami pour créer un match privé
match-code-status-ready = Prêt — les deux joueurs doivent appuyer sur Rechercher
match-code-error-enter-peer = Saisissez d’abord le code de votre ami
match-code-error-own = Saisissez le code de votre ami, pas le vôtre
match-code-error-invalid = Ce code n’est pas valide
match-code-error-length = Le code doit contenir entre {$min} et {$max} lettres ou chiffres
match-code-error-blocked = Ce code n’est pas autorisé ; choisissez-en un autre

netplay-detail-ready = Hébergez un lobby, collez une invitation copiée ou saisissez manuellement une adresse.
netplay-detail-lobby-code-ready = Le code de lobby {$code} est prêt à être partagé.
netplay-detail-creating-lobby-code = Création de votre code de lobby.
netplay-detail-waiting-for-host = En attente que l'hôte réponde à votre demande de jointure.
netplay-detail-share-lobby-code = Partagez le code de lobby {$code} avec l'autre joueur.
netplay-detail-starting-lobby = Démarrage de votre connexion de lobby.
netplay-detail-joining-host = Tentative de rejoindre l'hôte sélectionné.
netplay-detail-establishing = Joueurs trouvés. Terminez la poignée de main, puis ouvrez Versus.
netplay-detail-connected = Connexion prête. Ouvrez Versus pour choisir les règles, les personnages et le stage.
netplay-detail-disconnecting = Fermeture de la session actuelle et retour au jeu hors ligne.
netplay-detail-canceling = Arrêt de la demande de jointure actuelle.
netplay-detail-matchmaking = Utilisez Versus pour faire la queue pour un adversaire aléatoire avec vos règles préférées.
netplay-detail-match-found = Adversaire trouvé. Terminez la configuration dans Versus quand les deux joueurs sont prêts.
netplay-detail-matchmaking-canceling = Arrêt de la recherche actuelle de partie aléatoire.
netplay-detail-error-message = Dernière erreur : {$error}
netplay-detail-error-generic = Quelque chose s'est mal passé. Essayez un code ou une méthode de connexion différente.
netplay-detail-unavailable = Détails du netplay indisponibles.

netplay-help-host-copy-code = Copiez votre code de lobby pour que l'autre joueur puisse le coller.
netplay-help-host-cancel-join = Arrêtez la tentative de jointure actuelle et revenez à l'état de prêt.
netplay-help-host-disconnect = Quittez la session netplay actuelle.
netplay-help-host-start-lobby = Démarrez un nouveau lobby et attendez qu'un autre joueur se joigne.
netplay-help-busy = Netplay est occupé en ce moment. Attendez qu'il finisse.
netplay-help-join-cancel-lobby = Fermez le lobby actuel et arrêtez d'attendre un autre joueur.
netplay-help-join-in-progress = Une jointure est déjà en cours. Attendez ou utilisez Annuler la connexion.
netplay-help-join-open-versus = Continuez vers Versus et terminez la configuration du match.
netplay-help-stop-random-search = Arrêter la recherche d'un adversaire aléatoire.
netplay-help-join-clipboard = Collez un code d'invitation de lobby, direct ou STUN depuis le presse-papiers.
netplay-help-copy-server = Démarrez un lobby si nécessaire, puis copiez son code de lobby partageable.
netplay-help-copy-direct = Copiez une invitation de connexion directe pour un autre appareil sur ce LAN.
netplay-help-copy-localhost = Copiez une invitation de connexion directe pour une autre copie exécutée sur cet ordinateur.
netplay-help-copy-stun = Copiez une invitation assistée par STUN qui est plus facile à utiliser sur Internet.
netplay-help-direct-connect = Saisissez manuellement une adresse au lieu d'utiliser un code d'invitation copié.
netplay-help-find-random-match = Ouvrez Versus et faites la queue pour un adversaire aléatoire.
netplay-help-open-versus = Ouvrez le menu Versus sans quitter cet écran.
netplay-help-back = Retour au menu principal.
netplay-help-unavailable = Aide sur l'action netplay indisponible.
netplay-help-advanced = Ajuster les paramètres avancés du netplay comme le rollback et le tampon.

ADVANCED-CONNECTIONS = CONNEXIONS AVANCÉES
netplay-settings-rollback-help = Activez ou désactivez la simulation rollback pour les matchs en ligne.
netplay-settings-buffer-help = Choisissez combien d'images d'entrée mettre en tampon, ou laissez le netplay choisir automatiquement.
netplay-settings-force-ipv4-help = Préférez IPv4 lors de la génération de codes d'invitation LAN sur des réseaux mixtes.
netplay-settings-back-help = Retour au menu netplay.
netplay-advanced-info = Utilisez ces options de secours quand Quick Play ou les codes de lobby normaux ne parviennent pas à se connecter. STUN aide à traverser les routeurs pour le jeu sur internet. La connexion directe est préférable pour le jeu en LAN ou pour un hôte avec un port UDP redirigé.
netplay-advanced-direct-help = Secours manuel. Entrez hôte:port pour le jeu en LAN ou quand l'hôte a redirigé un port UDP.
netplay-advanced-stun-help = Secours internet. Partagez ceci quand les jointures de lobby normales échouent et que vous avez encore besoin du hole punching assisté par routeur.
netplay-advanced-lan-help = Secours LAN. Partagez votre adresse locale joignable quand les deux joueurs sont sur le même réseau.
netplay-advanced-localhost-help = Secours de test. À utiliser seulement quand les deux clients tournent sur la même machine.
netplay-advanced-back-help = Retour au Canapé virtuel.
netplay-rollback-off = Rollback : Désactivé
netplay-rollback-on = Rollback : Activé
netplay-buffer-auto = Tampon réseau : Auto
netplay-buffer-2 = Tampon réseau : 2
netplay-buffer-3 = Tampon réseau : 3
netplay-buffer-4 = Tampon réseau : 4
netplay-buffer-5 = Tampon réseau : 5
netplay-buffer-6 = Tampon réseau : 6
netplay-buffer-7 = Tampon réseau : 7
netplay-buffer-8 = Tampon réseau : 8
netplay-buffer-10 = Tampon réseau : 10
netplay-buffer-12 = Tampon réseau : 12
netplay-force-ipv4-dual = Adresse LAN : IPv6/IPv4
netplay-force-ipv4-v4 = Adresse LAN : Forcer IPv4

netplay-rollback = Rollback
netplay-buffer = Tampon réseau
netplay-force-ipv4 = Adresse LAN

netplay-direct-connect-prompt = Entrez l'adresse IP:port. Le port par défaut est {$port}.
netplay-stun-connect-title = Utiliser le service STUN ?
netplay-stun-connect-prompt = Ce code a utilisé {$service} pour découvrir {$address}:{$port}.
netplay-waiting-host-battle = En attente de la fin de la bataille de l'hôte
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = Personnages
Stages = Arènes
CPU = CPU

Starter = Starter
Legal = Légal
Miscellaneous = Divers

Start-Battle = Commencer le combat

# Start Menu
quit-info = Bouclier + Attaque + Start pour quitter
paused = EN PAUSE
tag-info = Croix directionnelle haut/bas pour entrer/sortir

# Pause Menu
pause-resume = Reprendre
pause-restart = Recommencer
pause-quit = Quitter
pause-players = Joueurs
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = Connectez une manette et appuyez sur n'importe quel bouton pour rejoindre.
arcade-return-prompt = Appuyez sur confirmer pour retourner au menu principal.

# Replay
replay-paused = Lecture en pause
replay-controls = Confirmer : rejoindre  ←/→ : image  Retour : menu  Enregistrer : [touche]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = Anglais
spanish = Espagnol
french = {fr-french}
italian = Italien
german = Allemand
russian = Russe
japanese = Japonais
chinese-cn = Chinois simplifié
chinese-hk = Chinois traditionnel
korean = Coréen

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french}
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean} ({korean})

# Shared UI labels
Advanced = Avancé
Clear-Spawns = Effacer les apparitions
Create-new-tag = Créer un nouveau tag
Credits = Crédits
CREDITS = CRÉDITS
Cycle-Palette = Changer de palette
Delete = Supprimer
Help = Aide
HELP = AIDE
Join = Rejoindre
Join-Lobby-Code = Rejoindre avec code de salon
Main-Menu = Menu principal
Mode = Mode
Native-Adapter = Adaptateur natif
NATIVE-ADAPTER = ADAPTATEUR NATIF
NETPLAY-SETTINGS = PARAMÈTRES NETPLAY
Other-saved-tags = Autres tags enregistrés
Profiles-for-this-controller-type = Profils pour ce type de manette
Quick-Play = Partie rapide
Random-Color = Couleur aléatoire
Rename-current-tag = Renommer le tag actuel
Reset-to-Defaults = Réinitialiser par défaut
Set-Character = Définir le personnage
Spawn-CPU = Ajouter un CPU
Team = Équipe
Virtual-Couch = Canapé virtuel
x = x
Find-Random-Match = Chercher un match aléatoire
training-label-stage = Stage
training-label-character = Personnage
training-label-player-cursor = Curseur du joueur
training-label-cpu-spawn = Apparition CPU
training-label-savestate = Sauvegarde d'état
Save-State = Sauver l'état
Load-State = Charger l'état
State-Saved = État sauvegardé
State-Restored = État restauré
No-State-Saved = Aucun état sauvegardé
DPad-Right-Save-Left-Load = Croix droite sauvegarde · gauche charge
shared-main-menu-help = Retourner au menu principal.
shared-mode-selector-label-help = Libellé du sélecteur de règles.
training-mode-selector-help = Basculer entre les constantes d’entraînement Antistatic et 19XX.
training-overlays-help = Activer ou désactiver les superpositions de débogage et les aides d’entraînement.
training-close-help = Fermer le menu d’entraînement.
training-stage-help = Changer de stage d’entraînement et réinitialiser les éléments liés au stage.
training-character-help = Choisir le personnage utilisé par Définir le personnage et Ajouter un CPU.
training-set-character-help = Faire passer le curseur flottant du joueur au personnage sélectionné.
training-random-color-help = Attribuer une nouvelle couleur de base aléatoire au personnage du curseur.
training-cycle-palette-help = Parcourir la palette du personnage du curseur.
training-cpu-level-down-help = Réduire le niveau CPU utilisé pour les nouveaux CPU d’entraînement.
training-cpu-level-current-help = Niveau CPU actuel pour les nouveaux CPU d’entraînement. Confirmez pour le faire défiler.
training-cpu-level-up-help = Augmenter le niveau CPU utilisé pour les nouveaux CPU d’entraînement.
training-spawn-cpu-help = Ajouter un CPU avec le personnage et le niveau CPU sélectionnés.
training-clear-spawns-help = Retirer tous les CPU et mannequins apparus en entraînement.
training-save-state-help = Sauvegarde la position, les dégâts, les stocks, les CPU apparus, l'arène et le timing actuels de l'entraînement. Croix droite utilise le même raccourci.
training-load-state-help = Restaure l'état d'entraînement sauvegardé. Croix gauche utilise le même raccourci.
training-savestate-shortcuts-help = Croix droite sauvegarde l'état d'entraînement actuel ; croix gauche le restaure.
versus-tag-selector-default = Tag : {$tag}
versus-tag-none = Aucun tag
versus-tag-manage = Créer / gérer les tags
versus-tag-change-failed = Impossible de changer le tag
versus-cpu-level-help = Faire défiler ce niveau CPU.
versus-cpu-color-help = Mélanger de nouveau la couleur et la palette de ce CPU.
versus-cpu-team-help = Changer l’équipe de ce CPU.
versus-cpu-remove-help = Retirer ce CPU.
versus-character-select-help = Sélectionner ce personnage pour le curseur flottant du joueur.
versus-add-cpu-help = Ajouter un CPU avec ce personnage.
versus-tap-jump-help = Activer ou désactiver le tap jump pour ce joueur.
versus-random-color-help = Attribuer une nouvelle couleur aléatoire à ce joueur. Désactivé lorsque les équipes sont activées.
versus-cycle-palette-help = Parcourir la palette de ce joueur.
versus-team-help = Changer l’équipe de ce joueur. Visible quand le mode équipes est activé.
versus-tag-selector-help = Choisir le tag de ce joueur. Désactivé en netplay.
versus-start-select-character-first = Sélectionnez d’abord un personnage
versus-start-not-enough-players = Pas assez de joueurs pour lancer une partie : {$count}
versus-start-not-enough-teams = Pas assez d’équipes pour lancer une partie : {$count}
versus-start-waiting-for-host = En attente de l’hôte
versus-ffa-help = Basculer entre chacun pour soi et règles par équipes.
versus-start-help = Lancer le match une fois que suffisamment de joueurs, CPU, équipes et un stage sont prêts.
versus-starter-help = Choisir aléatoirement un stage starter et lancer le match.
versus-legal-help = Choisir aléatoirement un starter légal ou un contre-pick et lancer le match.
versus-misc-help = Stages divers.
versus-stage-preview-help = Survolez pour prévisualiser ce stage ; confirmez pour le choisir et lancer le match.
versus-stage-preview-counterpick-help = Survolez pour prévisualiser ce contre-pick ; confirmez pour le choisir et lancer le match.
versus-stage-preview-misc-help = Survolez pour prévisualiser ce stage divers ; confirmez pour le choisir et lancer le match.
versus-mode-selector-help = Basculer entre les constantes versus Antistatic et 19XX.
versus-tab-stages-help = Parcourez et choisissez une arène pour le match.
versus-tab-settings-help = Configurez les règles et paramètres du match. Appuyer sur Start ici passe au choix de l'arène.
versus-setting-stock = Stock
versus-setting-time = Temps
versus-setting-on = Oui
versus-setting-off = Non
versus-setting-none = Aucun
versus-setting-stock-mode-value = Mode : {$value}
versus-setting-stocks-value = Stocks : {$value}
versus-setting-time-limit-value = Temps : {$value}
versus-setting-friendly-fire-value = FF : {$value}
versus-setting-stamina-value = Stamina : {$value}
versus-setting-knockback-value = KB : {$value}×
versus-setting-pause-value = Pause : {$value}
versus-setting-sd-value = SD : {$value}
versus-setting-stock-mode-help = Alterne entre le mode Stock (le dernier joueur en vie gagne) et le mode Temps (le plus de stocks à la fin du chrono gagne).
versus-setting-stocks-help = Nombre de stocks (vies) de départ pour chaque joueur.
versus-setting-time-limit-help = Limite de temps du match. En mode Temps, elle détermine le vainqueur.
versus-setting-friendly-fire-help = Active ou désactive les dégâts entre coéquipiers. Visible seulement en équipe.
versus-setting-stamina-help = Stamina de départ (PV). Réglez sur 0 pour le mode pourcentage de dégâts.
versus-setting-knockback-help = Multiplicateur global de projection. Les valeurs élevées augmentent la distance d'éjection.
versus-setting-pause-help = Autorise ou interdit la pause pendant le match.
versus-setting-sd-help = Pénalité d'autodestruction. -1 retire un stock ; 0 n'applique aucune pénalité.
netplay-copy-lobby-missing = Aucun code de salon à copier
netplay-copy-lobby-copied = Code du salon copié dans le presse-papiers
netplay-direct-connect-empty = Entrez une adresse IP
netplay-lobby-code-prompt = Saisissez un code d’invitation de salon, LAN ou STUN.
netplay-lobby-code-empty = Entrez un code de salon
netplay-error-connecting = Erreur de connexion : {$error}
matchmaking-no-controller-connected = Aucun contrôleur connecté
battle-winner-log = Vainqueur : {$player}
battle-winner-message = Vainqueur : Joueur {$player}
battle-winner-team-log = Vainqueur : Équipe {$team}
battle-winner-team-message = Vainqueur : Équipe {$team}
battle-tie-log = Match nul
battle-tie-message = MATCH NUL
battle-time-out = TEMPS ÉCOULÉ
battle-countdown-go = GO
battle-infinite-score-log = Score infini : {$score}
battle-infinite-score-message = Score {$score}
team-name-red = Rouge
team-name-green = Vert
team-name-blue = Bleu
team-name-grey = Gris
versus-start-sync-failed = Impossible de synchroniser le début du combat

main-menu-help = Passez sur une option pour voir ce qu'elle fait.
netplay-main-help = Choisissez une action de jeu en ligne.
netplay-settings-help = Ajustez le comportement du jeu en ligne.
netplay-advanced-help = Choisissez un outil de connexion.
settings-help = Choisissez une catégorie de paramètres.
help-discord-help = Ouvrez la communauté Antistatic sur Discord dans votre navigateur.
help-guide-help = Ouvrez le guide en ligne d'Antistatic dans votre navigateur.
help-adapter-guide-help = Ouvrez les notes de configuration de Dolphin pour l'adaptateur officiel de manette GameCube.
Adapter-Guide = Guide de l'adaptateur
Open-Dolphin-Guide = Ouvrir le guide Dolphin
Native-Adapter-Help = Aide de l'adaptateur
NATIVE-ADAPTER-HELP = AIDE DE L'ADAPTATEUR
native-adapter-help-summary = Antistatic utilise libusb directement, donc il partage la même configuration de pilotes que la prise en charge de l'adaptateur natif de Dolphin.
native-adapter-help-windows = Windows : installez WinUSB pour l'ID USB 057e:0337 avec Zadig.
native-adapter-help-linux = Linux : ajoutez une règle udev accordant l'accès utilisateur à 057e:0337.
native-adapter-help-sdl = Si SDL/Dolphin prend l'adaptateur en premier, lancez avec SDL_JOYSTICK_HIDAPI_GAMECUBE=0.
native-adapter-help-dolphin = Dolphin/Slippi : fermez-les avant d'ouvrir le diagnostic de l'adaptateur natif d'Antistatic.
native-adapter-help-claim = Si une autre application utilisait l'adaptateur, fermez-la et rouvrez cet écran de diagnostic.
native-adapter-help-back = Retour à l'état de l'adaptateur natif.
help-credits-help = Voir les crédits, le copyright et l'attribution des tiers.
help-back-help = Retour au menu principal.
help-help = Choisissez une destination d'aide.
controls-help = Choisissez une action de la manette.
netplay-quick-play-help = Cherchez un adversaire aléatoire avec la manette sélectionnée.
credits-help = Crédits et attribution.

credits-heading = Antistatic - crédits et attribution
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. Tous droits réservés.
credits-developer = Développeur : bluehexagons (Loren Crain).
credits-original = Les sons, modèles, animations, gameplay, interface et code moteur originaux ont été créés en interne.
credits-runtime = Runtime/outils open source : Node.js, TypeScript, CMake, Fluent, gl-matrix, jsonc-parser, os-locale.
credits-libraries = Bibliothèques natives : SDL3, SDL3_image, GLEW, OpenAL Soft, FreeType, Vorbis/libvorbisfile, libusb.
credits-build = Outils de build/vérification : npm, oxlint, oxfmt et chaînes d'outils de compilation des plateformes.
credits-fonts = Polices incluses : Noto Sans, IBM Plex Mono et GNU Unifont.
credits-tools = Outils de production : Blender pour les modèles 3D ; Audacity et LMMS pour l'audio et la musique.
credits-packages = Packages bluehexagons : capacitor, trace et antistatic-translations.
credits-thanks = Merci aux mainteneurs et contributeurs de ces projets.
credits-license = Les projets tiers restent soumis à leurs licences respectives.

# Old UI hover/help text
main-versus-help = Choisissez les personnages, les CPU, les équipes, les règles et un stage avant de lancer un match local.
main-arcade-help = Combats coopératifs contre l'IA pour toute personne connectée. Stocks limités, réessai en cas de défaite.
main-netplay-help = Hébergez ou rejoignez des parties en ligne, Quick Play et les réglages de connexion Netplay.
main-training-help = Ouvrez le mode entraînement avec stage, CPU, couleur, palette et commandes de débogage.
main-replays-help = Parcourez, prévisualisez et lancez les fichiers Replay enregistrés.
main-settings-help = Ajustez les paramètres audio, vidéo, langue, adaptateur de manette et mode de démarrage.
main-controls-help = Créez des tags de manette et modifiez les commandes avec tag ou le profil partagé sans tag.
main-help-help = Ouvrez les liens de la communauté et des guides externes.
main-exit-help = Quitter Antistatic.
settings-audio-help = Ajustez le volume principal, des effets sonores, de l'interface, des voix et de la musique.
settings-video-help = Modifiez le préréglage graphique, le plein écran, la synchronisation, les effets et les options de limite de FPS.
settings-native-adapter-help = Inspectez l'état de l'adaptateur GameCube et les notes de configuration.
settings-language-help = Changez la langue du menu.
settings-start-mode-help = Choisissez quel mode s'ouvre en premier au démarrage.
settings-live-reload = Rechargement en direct
settings-live-reload-help = Recharge les fichiers de personnages depuis l'Animator pendant l'édition locale. Désactivé par défaut.
shared-settings-help = Retour aux Paramètres.
native-adapter-copy-udev-install-help = Copiez les commandes standard d'installation et de rechargement de la règle udev pour 057e:0337.
native-adapter-copy-udev-line-help = Copiez uniquement la ligne standard de règle udev pour 057e:0337.
native-adapter-help-button-help = Ouvrez les notes de configuration Windows et Linux pour les installations d'adaptateur compatibles avec Dolphin/Slippi.
audio-master-help = Définissez le volume de sortie principal.
audio-sfx-toggle-help = Activez ou désactivez les effets sonores et les sons de l'interface.
audio-sfx-help = Définissez le volume des effets sonores du jeu.
audio-ui-help = Définissez le volume du menu et de l'interface.
audio-voice-help = Définissez le volume des voix des personnages.
audio-music-toggle-help = Activez ou désactivez la lecture de musique.
audio-music-help = Définissez le volume de la musique.
video-preset-help = Appliquez un préréglage graphique groupé, ou affichez Personnalisé lorsque les réglages individuels diffèrent.
video-fullscreen-toggle-help = Basculez entre affichage fenêtré et plein écran.
video-display-help = Choisissez l'écran que la fenêtre du jeu ou le mode plein écran doit utiliser.
video-fullscreen-resolution-help = Choisissez la résolution du mode plein écran exclusif. Auto utilise le plein écran du bureau.
video-windowed-resolution-help = Choisissez la taille de la fenêtre utilisée en mode fenêtré et lors du retour depuis le plein écran.
video-render-scale-help = Rendez les graphismes 3D en dessous ou au-dessus de la résolution de la fenêtre tout en gardant l'interface native.
video-vsync-help = Choisissez le timing d'échange. Adaptatif utilise une synchronisation à faible latence tear-if-late lorsque le pilote le prend en charge.
video-shadow-quality-help = Choisissez la qualité des ombres ou désactivez les ombres.
video-ssao-help = Choisissez la qualité de l'occlusion ambiante.
video-antialias-help = Activez ou désactivez l'anticrénelage FXAA.
video-bloom-help = Ajoute une lueur douce autour des reflets les plus lumineux. Idéal sur GPU haut de gamme.
video-reflections-help = Reflète la scène sur les surfaces brillantes grâce aux reflets en espace écran. Exigeant ; idéal sur GPU haut de gamme.
video-godrays-help = Projette des rayons de lumière volumétriques du soleil à travers la scène. Exigeant ; idéal sur GPU haut de gamme.
video-perf-overlay-help = Affichez ou masquez la superposition de performances.
video-point-lights-help = Choisissez la qualité des lumières ponctuelles supplémentaires.
video-particle-quality-help = Choisissez la densité des effets de particules.
video-max-fps-help = Définissez une limite de fréquence d'images optionnelle.
video-apply-help = Appliquez les changements de vidéo.
replays-enabled-help = Enregistrez en mémoire les combats Versus et Quick Play éligibles. Désactivez cela sur les systèmes à mémoire limitée.
replays-auto-save-help = Enregistrez automatiquement les Replay sur l'écran des résultats au lieu d'attendre une pression manuelle sur Enregistrer.
replays-compression-help = Compressez les fichiers Replay lors de l'enregistrement. Désactivez-le uniquement si la compression ralentit les sauvegardes.
netplay-copy-lobby-help = Copiez le code de salon actuel lorsqu'il est disponible.
netplay-virtual-couch-help = Ouvrez l'hébergement de salon, la connexion par code de salon et les options d'invitation avancées.
netplay-settings-menu-help = Configurez le rollback, le tampon d'entrée et le comportement de l'adresse LAN.
netplay-back-help = Retournez au menu principal sans déconnecter une session établie.
arcade-cpu-level-help = Niveau de difficulté du CPU pour les adversaires (0 le plus facile, 6 le plus difficile).
arcade-stocks-help = Stocks par combat.
arcade-retries-help = Nombre de réessais avant qu'une défaite ne mette fin à la partie.
arcade-battles-help = Nombre total de combats dans la partie.
arcade-start-help = Commencez la partie une fois que chaque joueur rejoint est prêt.
controls-remap-page-help = Réattribuez la navigation du menu, la console, le plein écran et les touches du mode entraînement.
controls-remap-reset-binding-help = Réinitialisez {$action} à son affectation par défaut.
controls-remap-reset-all-help = Restaurez tous les raccourcis clavier à leur valeur par défaut intégrée.
replay-browser-help = Navigateur de Replay.
replay-offline-only-help = Les Replay ne sont disponibles qu'hors ligne, car ils sont chargés depuis le système de fichiers local.
replay-refresh-help = Réanalysez les fichiers Replay enregistrés depuis {$dir}.
replay-entry-help = {$players} sur {$stage} ; {$duration} ({$truncated}) ; {$result} ; {$version} ; {$compression}.
replay-unreadable-help = Impossible de lire le Replay : {$error}
replay-actions-watch-help = Lancez le Replay enregistré depuis le début. Jump In est disponible pendant la lecture du Replay.
replay-actions-back-help = Revenir à la liste des Replay.
replay-load-help = Chargez les fichiers Replay enregistrés depuis le dossier Replay.
replay-prev-help = Afficher les Replay plus récents.
replay-next-help = Afficher les Replay plus anciens.
replay-settings-help = Options d'enregistrement, d'auto-sauvegarde et de compression des Replay.
audio-help = Ajustez les paramètres audio.
video-help = Ajustez les paramètres vidéo.
replays-help = Les Replay sont activés par défaut et limités à 16 minutes par combat.
native-adapter-help-text = Native Adapter offre un sondage direct des 4 ports. Le mode PC est plus simple mais utilise les affectations de manette SDL.
shortcut-menu-up-help = Déplace la sélection vers le haut dans les menus.
shortcut-menu-down-help = Déplace la sélection vers le bas dans les menus.
shortcut-menu-left-help = Déplace la sélection vers la gauche ou diminue une valeur.
shortcut-menu-right-help = Déplace la sélection vers la droite ou augmente une valeur.
shortcut-menu-confirm-help = Active l'élément ciblé.
shortcut-menu-next-help = Passe à l'élément focalisable suivant. Maintenez Shift pour revenir en arrière.
shortcut-menu-page-up-help = Saute vers le haut de plusieurs éléments.
shortcut-menu-page-down-help = Saute vers le bas de plusieurs éléments.
shortcut-menu-home-help = Met l'accent sur le premier élément de la liste.
shortcut-menu-end-help = Met l'accent sur le dernier élément de la liste.
shortcut-console-help = Ouvrez la console de débogage du jeu.
shortcut-chat-help = Ouvrez l'invite de chat (commande say).
shortcut-fullscreen-help = Basculez le plein écran. Alt+Entrée fonctionne aussi.
shortcut-frame-step-help = Avancez d'une image pendant que c'est figé. Nécessite le mode débogage.
shortcut-freeze-help = Mettez en pause ou reprenez TAS. Nécessite le mode débogage.
shortcut-save-state-help = Créez un instantané de l'état actuel en mode entraînement.
shortcut-restore-state-help = Restaurez le dernier instantané du mode entraînement.

Start = Start
Color = Couleur
Leave = Quitter
Not-Joined = Pas rejoint
Hold-Start = Maintenir Start
arcade-join-help = Rejoindre cette partie arcade.
arcade-color-help = Choisir aléatoirement la couleur de ce joueur.
arcade-palette-help = Sélectionner la palette de ce joueur.
arcade-leave-help = Quitter cette partie arcade.
arcade-setting-cpu-level = Niv. CPU
arcade-setting-stocks = Stocks
arcade-setting-starting-stocks = Stocks de départ
arcade-setting-retries = Réessais
arcade-setting-battles = Combats
arcade-setting-value = {$label}: {$value}
arcade-palette = Palette {$number}
arcade-select-title = ARCADE
arcade-select-infinite-title = COMBATS INFINIS
arcade-select-instructions = Confirmer rejoint · choisissez personnage et palette par joueur · Retour quitte
arcade-between-cleared-battle = Combat {$current} / {$total} terminé
arcade-between-next = Confirmer : suivant
arcade-between-retries-remaining =
    Défaite — { $count ->
        [one] {$count} réessai restant
       *[other] {$count} réessais restants
    }
arcade-between-retry-actions = Confirmer : réessayer · Retour : abandonner
arcade-between-results = Confirmer : résultats
arcade-between-complete = Arcade terminé !
arcade-results-infinite-title = Combats infinis
arcade-results-infinite-subtitle = Score {$score} en {$time}
arcade-results-cleared-title = Arcade terminé
arcade-results-cleared-subtitle = Tous les {$battles} combats ont été terminés.
arcade-results-abandoned-title = Parcours abandonné
arcade-results-abandoned-subtitle = Abandonné après le combat {$current} sur {$total}.
arcade-results-gameover-title = Fin de partie
arcade-results-gameover-subtitle = Combat {$current} sur {$total} atteint.
replay-battle-controls = Replay : Enregistrer ajoute un repère · Start pause · croix navigue · Saisie change la vitesse · maintenir Confirmer/Attaque avance · Retour quitte
replay-battle-status = {$current} / {$total} · {$speed}x
replay-marker-default = Repère {$number}
replay-marker-added = {$label} ajouté à {$time}
replay-marker-selected = {$label} · {$time}
replay-marker-none = Aucun repère de replay
replay-marker-save-unavailable = Enregistrement des repères indisponible
replay-speed-changed = Vitesse de lecture : {$speed}x
replay-export-button = Exporter le paquet de replay
replay-export-help = Crée un paquet local avec ce replay et ses repères. Aucun envoi en ligne.
replay-exporting = Exportation du paquet de replay...
replay-exported = {$name} exporté
replay-export-failed = Échec de l’exportation : {$error}
results-controller-port = Manette P{$port}
results-controller-id = Manette {$id}
results-disconnected-slot = Emplacement déconnecté
results-remote-player = Joueur distant
results-replay-capture = Capture de replay
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = Emplacement {$index}: {$name}
results-row-kos = KOs
results-row-falls = Chutes
results-row-sds = Auto-KOs
results-row-damage-given = Dégâts infligés
results-row-damage-taken = Dégâts subis
results-row-blocked = Bloqués
results-row-parries = Parades
results-row-power-shields = Boucliers parfaits
results-row-lag-cancels = Annulations de lag
results-row-kb-given = Recul infligé
results-row-kb-taken = Recul subi
results-row-kb-absorbed = Recul absorbé
results-row-ledge-grabs = Accroches au rebord
results-row-ledge-time = Temps au rebord
results-row-crouch-cancels = Annulations accroupies
results-row-velocity-cancels = Annulations de vitesse
controls-action-ui-save-replay = Enregistrer le replay
controls-device-unknown = Inconnu
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = Raccourcis clavier
shortcut-unbound = (non attribué)
shortcut-category-menu = Navigation des menus
shortcut-category-general = Général
shortcut-category-debug = Débogage (TAS)
shortcut-category-training = Mode entraînement
shortcut-label-menu-up = Monter
shortcut-label-menu-down = Descendre
shortcut-label-menu-left = Aller à gauche
shortcut-label-menu-right = Aller à droite
shortcut-label-menu-confirm = Confirmer
shortcut-label-menu-next = Champ suivant
shortcut-label-menu-page-up = Page précédente
shortcut-label-menu-page-down = Page suivante
shortcut-label-menu-home = Premier élément
shortcut-label-menu-end = Dernier élément
shortcut-label-console = Ouvrir la console
shortcut-label-chat = Chat
shortcut-label-fullscreen = Basculer plein écran
shortcut-label-frame-step = Avancer d'une image (TAS)
shortcut-label-freeze = Geler (TAS)
shortcut-label-save-state = Sauvegarder l'état
shortcut-label-restore-state = Restaurer l'état
shortcut-bind = Assigner
shortcut-add = Ajouter
shortcut-replace = Remplacer
shortcut-remove-key = Retirer {$key}
shortcut-capture-bind-title = Assigner une touche : {$action}
shortcut-capture-replace-title = Remplacer la touche : {$action}
shortcut-capture-hint = Appuyez sur la touche à assigner, ou sur Échap pour annuler.
shortcut-conflict-detail = {$key} est déjà assignée à {$action}. Réassigner ?
shortcut-conflict-hint = Appuyez sur Entrée pour réassigner, sur Échap pour annuler.
shortcut-min-binding = {$action} doit garder au moins une assignation.
shortcut-overlap-menu = Chevauchement menu : {$keys} navigue aussi dans les menus. L'affectation manette prime dans les menus.
shortcut-overlap-actions = Chevauchement de raccourcis : {$overlaps}. L'affectation manette prime en jeu.
shortcut-reset-all = Réinitialiser tous les raccourcis
character-select-help = Sélectionnez un personnage.

matchmaking-service-fallback-stun = STUN de secours
matchmaking-status-preparing-binding = Préparation du Quick Play... Ouverture du socket netplay.
matchmaking-status-preparing-primary-stun = Préparation du Quick Play... Vérification de votre route UDP publique via {$service}.
matchmaking-status-preparing-fallback-stun = Préparation du Quick Play... Le STUN principal a échoué, nouvelle tentative via {$service}.
matchmaking-status-preparing-queueing = Préparation du Quick Play... Entrée dans la file.
matchmaking-status-connecting-tunneling = Match trouvé. Ouverture de la route pair à pair...
matchmaking-status-connecting-peer = Route pair à pair ouverte. Finalisation du handshake de connexion...
matchmaking-status-waiting-peer = Route ouverte. Attente de l'autre joueur...
matchmaking-status-starting-battle = Connexion prête. Lancement du match...
netplay-experimental-note = Expérimental — peut être instable
netplay-detail-connecting-peer = Route pair à pair ouverte. Finalisation du handshake de connexion...
netplay-detail-waiting-for-peer = Route ouverte. Attente que l'autre joueur finisse de se connecter...
netplay-detail-starting-battle = Connexion prête. Lancement du match...
netplay-detail-matchmaking-binding = Préparation du Quick Play. Ouverture du socket netplay...
netplay-detail-matchmaking-primary-stun = Vérification de votre route UDP publique via {$service}...
netplay-detail-matchmaking-fallback-stun = Le STUN principal n'a pas répondu. Tentative avec {$service}...
netplay-detail-matchmaking-queueing = Entrée dans la file de matchmaking...
netplay-detail-matchmaking-wait = {$wait}s dans la file. Joueurs en attente : {$players}.
replay-stage-fallback = Stage {$number}
replay-unknown-error = erreur inconnue
replay-title = REPLAY
replays-title = REPLAYS
replay-watch-button = Voir le replay
replay-settings-button = Paramètres des replays
replay-refresh-button = Actualiser la liste
replay-refreshing = Actualisation...
replay-prev-button = Page précédente
replay-prev-disabled = Page précédente -
replay-next-button = Page suivante
replay-next-disabled = Page suivante -
replay-browser-scanning = Analyse du dossier des replays...
replay-browser-scan-failed = L'analyse des replays a échoué.
replay-browser-empty = 0 replays trouvés.
replay-browser-page =
    {$first}-{$last} sur {$count} { $count ->
        [one] replay
       *[other] replays
    } · Page {$page}/{$pages}
replay-browser-loading = Chargement des replays...
replay-browser-scanning-files = Analyse des fichiers de replay enregistrés.
replay-browser-scan-failed-detail = L'analyse des replays a échoué : {$error}
replay-browser-empty-slot = Aucun replay dans cet emplacement.
replay-browser-empty-list = Aucun replay enregistré trouvé.
replay-browser-root-help = Les fichiers de replay sont chargés récursivement depuis le dossier local des replays.
replay-title-unreadable = Illisible : {$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = Aucun résultat
replay-result-none-winner = Gagnant : aucun
replay-result-quit = Abandon prématuré
replay-result-tie = Égalité
replay-result-winner = Gagnant : {$winner}
replay-action-participants = Participants : {$players}
replay-action-duration = Durée : {$duration}
replay-action-duration-truncated = Durée : {$duration} (tronquée)
replay-action-result = Résultat : {$result}
replay-action-stage = Stage : {$stage}
replay-action-mode = Mode : {$mode}
replay-action-version = Version : {$version}
replay-action-file = Fichier : {$compression} ; Tronquée : {$truncated}
replay-compression-compressed = Compressé
replay-compression-uncompressed = Non compressé
replay-truncated-yes = Oui
replay-truncated-no = Non

# Social et liste des CPU en versus
press-any-button-or-key = Appuyez sur n’importe quelle touche ou bouton
social-title = AMIS ET INVITATIONS
social-steam = Steam
social-steam-help = Affichez votre salon sur Steam et laissez vos amis le rejoindre depuis leur liste d’amis.
social-discord = Discord
social-discord-help = Affichez votre salon sur Discord et laissez vos amis demander à le rejoindre.
social-info = Désactivé par défaut. Une fois activée, l’intégration charge le SDK de la plateforme et partage le code de votre salon afin que vos amis puissent vous rejoindre. Les connexions utilisent toujours le netplay d’Antistatic.
social-summary = Présence enrichie et invitations Steam et Discord.
social-settings-help = Présence enrichie et invitations Steam et Discord. Désactivé par défaut.
versus-add-cpu = Ajouter une CPU
versus-cpu-page-prev = Préc.
versus-cpu-page-next = Suiv.
versus-cpu-page-help = Changer la page de CPU affichée.
versus-no-cpus-added = Aucune CPU ajoutée
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# Calibrage des manettes
controller-calibration-title = CALIBRAGE DE LA MANETTE
controller-calibration-open = Calibrer la manette
controller-calibration-open-help = Contrôle et calibre la manette locale sélectionnée.
controller-calibration-online-blocked = Le calibrage est indisponible pendant le jeu en ligne.
controller-calibration-no-local-controller = Connectez et sélectionnez une manette locale à calibrer.
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = sans tag
controller-calibration-capability-no-axes = Cette manette ne signale aucun axe calibrable.
controller-calibration-capability-native-origin = L'origine native permet le calibrage automatique.
controller-calibration-capability-absolute-no-automatic = Données absolues disponibles ; calibrage automatique indisponible.
controller-calibration-capability-sdl-normalized = Entrée SDL normalisée ; calibrage manuel uniquement.
controller-calibration-suspicious-origin-warning = Un ou plusieurs axes à origine automatique ont été ignorés. Consultez les détails de secours ci-dessous.
controller-calibration-invalid-saved-warning = Calibrage enregistré ignoré : {$reason}
controller-calibration-invalid-shaping-warning = Réglages de sticks enregistrés ignorés : {$reason}
controller-calibration-status-policy-preview = aperçu auto
controller-calibration-status-manual-preview = aperçu manuel
controller-calibration-status-modified = modifié
controller-calibration-status-current = actuel
controller-calibration-status-policy = auto
controller-calibration-status-manual = manuel
controller-calibration-status-not-saved = non enregistré
controller-calibration-status-saved = enregistré
controller-calibration-status-active-differs = Le calibrage actif diffère de celui enregistré
controller-calibration-draft-status = {$intent} · brouillon {$draft} · actif {$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = Calibrage automatique : {$state}
controller-calibration-automatic-unavailable = indisponible
controller-calibration-automatic-on = activé
controller-calibration-automatic-off = désactivé
controller-calibration-automatic-policy-native-help = Active ou désactive le calibrage automatique de l'origine GameCube.
controller-calibration-automatic-policy-unavailable-help = Cette source d'entrée ne permet pas le calibrage automatique.
controller-calibration-axis-left-x = Stick gauche X
controller-calibration-axis-left-y = Stick gauche Y
controller-calibration-axis-right-x = Stick droit X
controller-calibration-axis-right-y = Stick droit Y
controller-calibration-axis-left-trigger = Gâchette gauche
controller-calibration-axis-right-trigger = Gâchette droite
controller-calibration-field-minimum = minimum
controller-calibration-field-center = centre
controller-calibration-field-maximum = maximum
controller-calibration-field-released = relâchée
controller-calibration-field-pressed = enfoncée
controller-calibration-value-na = N/D
controller-calibration-unit-gamecube-directed = octet dirigé GameCube
controller-calibration-unit-sdl-normalized = normalisé SDL
controller-calibration-unit-canonical-normalized = normalisé
controller-calibration-unit-gamecube-protocol-byte = octet de protocole GameCube
controller-calibration-axis-values-normalized = {$axis} · {$unit} · source {$source} · corrigé {$corrected} · aperçu {$preview} · jeu {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} absolu {$absolute}, origine {$origin} · {$sourceUnit} source {$source} · {$normalizedUnit} corrigé {$corrected}, aperçu {$preview}, jeu {$gameplay}
controller-calibration-axis-statistics = {$samples} mesures · min. {$minimum} · max. {$maximum} · pic {$peak} · gigue {$jitter} · {$unit}
controller-calibration-reported-buttons = Enfoncés : {$buttons}
controller-calibration-reported-buttons-none = aucun
controller-calibration-capture-status-ready = prêt
controller-calibration-capture-status-waiting-release = relâchez toutes les commandes
controller-calibration-capture-status-capturing = capture
controller-calibration-capture-status-captured = capturé
controller-calibration-capture-status-invalid = capture invalide
controller-calibration-capture-neutral = Capturer le neutre
controller-calibration-capture-range = Capturer toute l'amplitude
controller-calibration-capture-help = Relâchez toutes les commandes à l'invite, puis effectuez l'action.
controller-calibration-stick-movement = Stick de déplacement
controller-calibration-stick-right = Stick droit / C
controller-calibration-shaping-deadzone = zone morte
controller-calibration-shaping-cardinal-snap = aimantation cardinale
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting} : {$value}{$unit} · {$step}
controller-calibration-shaping-help = Gauche/Droite ou les côtés de la ligne pour ajuster · Confirmer ou le centre pour alterner fin/large.
controller-calibration-adjust-value = {$axis} {$field} : {$value} {$unit} · {$step}
controller-calibration-step-fine = fin
controller-calibration-step-coarse = large
controller-calibration-adjust-help = Gauche/Droite ou les côtés de la ligne pour ajuster · Confirmer ou le centre pour alterner fin/large. Les unités physiques restent propres à la source.
controller-calibration-apply-current-connection = Appliquer à la connexion actuelle
controller-calibration-save-to-tag = Enregistrer sous le tag de manette
controller-calibration-save-to-tag-target = Enregistrer sous {$tag} ({$layout})
controller-calibration-save-to-tag-no-tag = Enregistrer sous un tag (requis)
controller-calibration-reset-draft-active = Réinitialiser le brouillon à l'actif
controller-calibration-reset-draft-saved = Réinitialiser le brouillon à l'enregistré
controller-calibration-reset-draft-layout-defaults = Réinitialiser aux valeurs du layout
controller-calibration-reset-session = Réinitialiser la session de connexion
controller-calibration-delete-saved = Supprimer le calibrage enregistré
controller-calibration-delete-saved-confirm = Confirmer : supprimer le calibrage
controller-calibration-copy-diagnostic = Copier le diagnostic
controller-calibration-action-help = Confirmez pour effectuer cette action.
controller-calibration-applied = Calibrage appliqué à la connexion actuelle.
controller-calibration-save-tag-required = Un tag de manette valide est requis pour enregistrer.
controller-calibration-saved = Calibrage enregistré sous {$tag} ({$layout}).
controller-calibration-no-saved-calibration = Aucun calibrage enregistré pour cette manette.
controller-calibration-delete-saved-complete = Calibrage enregistré supprimé.
controller-calibration-copy-diagnostic-complete = Diagnostic de calibrage copié.
controller-calibration-local-controllers = Autres manettes locales
controller-calibration-switch-controller = Changer de manette
controller-calibration-switch-controller-name = Passer à {$controller}
controller-calibration-switch-decision = {$controller} · Gauche appliquer · Droite {$save} · Confirmer ignorer
controller-calibration-switch-save-available = enregistrer
controller-calibration-switch-save-unavailable = enregistrement indisponible
controller-calibration-switch-decision-help = Non enregistré : Gauche applique, Droite enregistre, Confirmer ignore et change.
controller-calibration-back = Retour
controller-calibration-back-help = Retourne aux contrôles. Une capture active est d'abord annulée.
controller-calibration-back-discard-confirm = Confirmer : ignorer le brouillon et revenir
controller-calibration-disconnected-draft-discarded = Manette déconnectée ; brouillon de calibrage ignoré.

# PhobGCC
controller-calibration-phob-board-unconfirmed = tableau non confirmé
controller-calibration-phob-board-v1 = Sélectionnez PhobGCC v1
controller-calibration-phob-board-v1-value = PhobGCCv1
controller-calibration-phob-board-v2 = Sélectionnez PhobGCC v2
controller-calibration-phob-board-v2-value = PhobGCCv2
controller-calibration-phob-calibrate-c-stick = Calibrer C-stick : A+X+Y+R
controller-calibration-phob-calibrate-left = Calibrer le manche principal : A+X+Y+L
controller-calibration-phob-calibration-complete = Terminer (clavier/souris uniquement)
controller-calibration-phob-calibration-confirm = Confirmer : démarrer l'étalonnage du firmware
controller-calibration-phob-calibration-help = Démarre un workflow de micrologiciel qui doit être terminé sur le contrôleur.
controller-calibration-phob-calibration-no-cancel = La manette ne peut ni annuler ni terminer cette procédure. Finissez-la, puis choisissez Terminer au clavier/à la souris. En cas de blocage, débranchez et rebranchez la manette.
controller-calibration-phob-calibration-phases = Suivez l'indication de l'autre stick pour chaque étape de centre, bord et encoche. Terminez les deux phases du firmware avant Terminer.
controller-calibration-phob-enter-configure = Entrez Configure Mode
controller-calibration-phob-enter-configure-instruction = Sur le contrôleur physique, maintenez A+X+Y+Start jusqu'à ce que les deux sticks se trouvent en haut à droite, puis relâchez.
controller-calibration-phob-exit-safe-instruction = Sur le contrôleur physique, appuyez sur A+X+Y+Start. Relâchez après la réponse plus longue en haut à droite.
controller-calibration-phob-host-correction-stale = Correction Antistatic après calibrage du firmware : active {$active} ; sauvegardée {$saved}. Vérifiez les valeurs par défaut ou refaites une capture.
controller-calibration-phob-instruction-none = aucune commande en attente
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = mode inconnu
controller-calibration-phob-open = Ouvrir le guide PhobGCC
controller-calibration-phob-open-guide-031 = Ouvrir le guide officiel du firmware 0.31
controller-calibration-phob-open-help = Vérifications guidées en lecture seule pour un PhobGCC v1 ou v2 confirmé par l'utilisateur.
controller-calibration-phob-open-phobvision-029-v2 = Ouvrir le guide PhobVision 0.29 (équipé v2 uniquement)
controller-calibration-phob-open-release-031 = Notes de version du micrologiciel ouvert 0.31
controller-calibration-phob-open-version-guide = Guide d'ouverture du firmware signalé
controller-calibration-phob-origin-checks = Avant le calibrage du firmware, activez si nécessaire les sticks avec le B physique et vérifiez les origines signalées par l'adaptateur.
controller-calibration-phob-query-c-settings = Lire les paramètres C-stick : R+Start
controller-calibration-phob-query-main-settings = Lire les paramètres du stick principal : L+Start
controller-calibration-phob-query-trigger-settings = Lire les paramètres de déclenchement : L+R+Z
controller-calibration-phob-query-version = Lire la version du micrologiciel : A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = Les diagnostics bruts sont actifs. Les valeurs sont des coordonnées d'affichage après firmware issues de rapports normaux de manette, et non des données directes des capteurs ni la sortie de jeu.
controller-calibration-phob-raw-disable = Désactiver la sortie brute : L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = Sur le contrôleur physique, appuyez sur L+R+D-pad Down, attendez la réponse en haut à droite, puis relâchez le tout.
controller-calibration-phob-raw-enable = Activer la sortie brute : L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = Sur le contrôleur physique, appuyez sur L+R+D-pad Up, attendez la réponse en haut à droite, puis relâchez le tout.
controller-calibration-phob-raw-values = après firmware, principal X {$leftX}, Y {$leftY} ; C-stick X {$cX}, Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = valeurs brutes indisponibles
controller-calibration-phob-remap-warning = Les commandes utilisent les boutons physiques inscrits malgré les remappages. Antistatic observe les boutons signalés, qui peuvent différer.
controller-calibration-phob-result-matched = Réponse de style phob correspondante
controller-calibration-phob-result-none = pas encore de réponse
controller-calibration-phob-result-unknown-custom = réponse inconnue ou personnalisée
controller-calibration-phob-result-version-known = micrologiciel {$version}
controller-calibration-phob-result-version-no-response = aucune réponse du micrologiciel ; version inconnue
controller-calibration-phob-return-safe = Retour à Safe Mode
controller-calibration-phob-safe-recovery = Pour garantir le Safe Mode, débranchez puis rebranchez la manette. Rouvrez ce guide ; l'état détecté est réinitialisé à la déconnexion.
controller-calibration-phob-setting-c-response-x-raw = C-stick Octet de réponse X
controller-calibration-phob-setting-c-response-y-raw = C-stick Octet de réponse Y
controller-calibration-phob-setting-c-snapback-x = snapback du C-stick X
controller-calibration-phob-setting-c-snapback-y = snapback du C-stick Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick mise en forme d'onde X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick façonnage d'ondes X brut
controller-calibration-phob-setting-c-waveshaping-y = C-stick mise en forme d'onde Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick mise en forme d'onde Y brute
controller-calibration-phob-setting-main-smoothing-x = lissage du manche principal X
controller-calibration-phob-setting-main-smoothing-y = lissage du manche principal Y
controller-calibration-phob-setting-main-snapback-x = snapback du bâton principal X
controller-calibration-phob-setting-main-snapback-y = snapback du bâton principal Y
controller-calibration-phob-setting-main-waveshaping-x = mise en forme des ondes du manche principal X
controller-calibration-phob-setting-main-waveshaping-x-raw = Waveshaping du bâton principal X brut
controller-calibration-phob-setting-main-waveshaping-y = mise en forme des ondes du manche principal Y
controller-calibration-phob-setting-main-waveshaping-y-raw = mise en forme d'onde du bâton principal Y brut
controller-calibration-phob-setting-row = {$setting} : {$value} {$unit}
controller-calibration-phob-setting-rows-none = aucun paramètre décodé
controller-calibration-phob-settings-c-stick-instruction = Sur le contrôleur physique, maintenez R+Start pendant la lecture de deux secondes, puis relâchez.
controller-calibration-phob-settings-main-instruction = Sur le contrôleur physique, maintenez L+Start pendant la lecture de deux secondes, puis relâchez.
controller-calibration-phob-settings-read-only = Ces lectures ne modifient pas les paramètres du micrologiciel. Utilisez les instructions officielles pour les modifications et les réinitialisations.
controller-calibration-phob-settings-triggers-instruction = Sur le contrôleur physique, maintenez L+R+Z pendant la lecture de deux secondes, puis relâchez.
controller-calibration-phob-setting-trigger-left-mode = mode de déclenchement gauche
controller-calibration-phob-setting-trigger-left-value = valeur de déclenchement gauche
controller-calibration-phob-setting-trigger-right-mode = mode de déclenchement droit
controller-calibration-phob-setting-trigger-right-value = valeur de déclenchement droite
controller-calibration-phob-setup-active = Phob Setup Mode actif : le D-pad signalé navigue et le A confirme.
controller-calibration-phob-setup-enter = Entrez Phob Setup Mode
controller-calibration-phob-setup-exit = Quitter Phob Setup Mode
controller-calibration-phob-setup-exit-chord = Pour quitter, maintenez exactement la croix Bas+Gauche signalée + stick principal en haut à droite + C-stick en bas à droite pendant une seconde, puis relâchez. Désactivé pendant le calibrage du firmware.
controller-calibration-phob-stale-state-current = actuel
controller-calibration-phob-stale-state-stale = vicié
controller-calibration-phob-status = Carte : {$board} · Mode : {$mode} · Résultat : {$result} · Étape : {$instruction} · {$raw} · Paramètres : {$rows}
controller-calibration-phob-unit-protocol-byte = octet de protocole
controller-calibration-phob-unit-setting-value = valeur de réglage
controller-calibration-phob-unit-trigger-byte = octet de déclenchement
controller-calibration-phob-unofficial-warning = Assistant PhobGCC non officiel et sans affiliation. Confirmez carte et firmware ; Antistatic ne peut ni identifier le matériel ni écrire de réglages.
controller-calibration-phob-version-instruction = Dans Configure Mode, appuyez physiquement sur A+Z+D-pad Up, maintenez l'affichage pendant deux secondes, puis relâchez.
controller-calibration-mode-basic = Vue : SIMPLE
controller-calibration-mode-advanced = Vue : AVANCÉE
controller-calibration-mode-toggle-help = Alterne entre les réglages courants et les diagnostics détaillés.
controller-calibration-origin-diagnostic-unavailable = Le diagnostic automatique de l'origine est indisponible pour cette source.
controller-calibration-origin-diagnostic = Origine stable : {$phase} · {$reports} rapports · {$stable}/6 appliqués · {$fallback}/6 secours · {$dropped} débordements
controller-calibration-origin-phase-collecting = collecte
controller-calibration-origin-phase-complete = terminé
controller-calibration-use-suggested-deadzones = Utiliser les zones mortes suggérées
controller-calibration-use-suggested-deadzones-help = Applique les suggestions mesurées à ce brouillon.
controller-calibration-section-stick-shaping = RÉGLAGE DES STICKS
controller-calibration-section-trigger-shaping = RÉGLAGE DES GÂCHETTES
controller-calibration-section-action-diagnostics = DIAGNOSTIC DES ACTIONS
controller-calibration-section-physical-diagnostics = DIAGNOSTIC DES AXES
controller-calibration-section-hardware-correction = CORRECTION MATÉRIELLE
controller-calibration-shaping-inner-deadzone = zone morte intérieure
controller-calibration-shaping-outer-deadzone = zone morte extérieure
controller-calibration-snap-override-help = Active le réglage joueur. Le minimum du mode reste appliqué.
controller-calibration-snap-override-state = Aimantation {$stick} : {$state} · minimum {$floor}° · effectif {$effective}°
controller-calibration-override-enabled = activée
controller-calibration-override-disabled = désactivée
controller-calibration-trigger-shaping-help = Gauche/Droite ou les côtés de la ligne pour ajuster · Confirmer ou le centre pour alterner fin/large.
controller-calibration-trigger-inner-deadzone = zone morte intérieure
controller-calibration-trigger-outer-deadzone = zone morte extérieure
controller-calibration-trigger-response-curve = courbe de réponse
controller-calibration-trigger-hard-press-threshold = seuil de pression forte
controller-calibration-trigger-shaping-value = {$trigger} {$setting} : {$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = Mesure : bruit mouvement {$movementNoise}, intérieur {$movementInner}, extérieur {$movementOuter}, couverture {$movementCoverage}/16 · droit bruit {$rightNoise}, intérieur {$rightInner}, extérieur {$rightOuter}, couverture {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = Gâchettes : L bruit {$leftNoise}, intérieur {$leftInner}, extérieur {$leftOuter} · R bruit {$rightNoise}, intérieur {$rightInner}, extérieur {$rightOuter}
controller-calibration-stick-diagnostic = {$stick} : assigné {$mapped} · jeu {$gameplay} · {$zone} · aimanté {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger} : assigné {$mapped} · jeu {$gameplay} · {$zone} · forte {$hard}
controller-calibration-zone-inner-dead = zone morte intérieure
controller-calibration-zone-linear = plage active
controller-calibration-zone-outer-saturated = saturation extérieure
controller-calibration-state-yes = oui
controller-calibration-state-no = non
controller-calibration-hard-source-none = aucune
controller-calibration-hard-source-digital-button = clic numérique
controller-calibration-hard-source-analog-threshold = seuil analogique
controller-calibration-help = Haut/Bas pour se déplacer · Gauche/Droite ou les côtés de la ligne pour ajuster · Confirmer ou le centre pour changer la précision · Retour pour revenir.
controller-calibration-tag-required-prerequisite = Ajoutez un tag de joueur dans Contrôles avant le calibrage pour activer Enregistrer. Appliquer reste disponible pour cette connexion.
controller-calibration-status-draft-or-active-differs = Le brouillon ou le réglage actif diffère de l'enregistré
controller-calibration-capture-mode-neutral = Neutre
controller-calibration-capture-mode-range = Amplitude complète
controller-calibration-capture-accept-pending = Accepter la capture {$mode}
controller-calibration-capture-accept-and-start = Accepter {$pending}, puis capturer {$next}
controller-calibration-capture-status-pending = capture {$mode} en attente de vérification
controller-calibration-legend-source = Valeur par défaut du layout
controller-calibration-legend-corrected = Corrigé
controller-calibration-legend-preview = Aperçu
controller-calibration-legend-gameplay = Jeu
controller-calibration-origin-fallback-detail = Secours : {$axes}
controller-calibration-origin-fallback-axis = {$axis} : {$reason}
controller-calibration-origin-reason-insufficient-reports = pas assez de rapports fiables ; relâchez les commandes et reconnectez
controller-calibration-origin-reason-unstable = l'entrée a bougé ; relâchez les commandes et reconnectez
controller-calibration-origin-reason-implausible = origine hors de la plage attendue ; relâchez les commandes et reconnectez
controller-calibration-origin-reason-unsafe-bounds = l'origine rendrait la correction dangereuse ; capturez Neutre et Amplitude complète
controller-calibration-phob-setup-suspended-raw = Phob Setup Mode est suspendu pendant les diagnostics bruts. Désactivez la sortie brute pour reprendre.
controller-calibration-phob-result-version-custom = réponse de firmware personnalisée : X {$x}, Y {$y}
controller-calibration-phob-result-unknown = réponse non reconnue
controller-calibration-phob-raw-mode-off = mode brut désactivé

# Confidentialité, rapports et avis
privacy-title = Confidentialité
privacy-settings-help = Gérez le réseau, les rapports de plantage, les mesures anonymes et les avis.
privacy-networking = Accès réseau
privacy-networking-help = Interrupteur général du jeu en ligne et des services Antistatic. Le désactiver coupe les sessions en ligne.
privacy-crash-reporting = Rapports de plantage : {$value}
privacy-crash-reporting-help = Choisissez si Antistatic doit demander avant d'envoyer un diagnostic anonyme de plantage.
privacy-crash-ask = Toujours demander
privacy-crash-never = Ne jamais envoyer
privacy-crash-always = Toujours envoyer
privacy-gameplay-metrics = Mesures de jeu anonymes
privacy-gameplay-metrics-help = Acceptez l'envoi de données générales : mode, personnages, durée et résultat.
privacy-performance-metrics = Mesures de performances anonymes
privacy-performance-metrics-help = Acceptez l'envoi de données générales sur le matériel et le temps d'image pour améliorer les performances.
privacy-feedback-open = Envoyer un avis
privacy-feedback-open-help = Envoyez un rapport de bug ou un autre avis à l'équipe Antistatic.
privacy-policy-open = Consulter la politique de confidentialité
privacy-policy-open-help = Lire la politique officielle de confidentialité d'Antistatic.
privacy-policy-title = Politique de confidentialité
privacy-policy-help = Cette politique explique comment Antistatic traite l'accès réseau, les rapports de plantage, les mesures facultatives et les avis.
privacy-crash-send-pending = Envoyer le rapport en attente
privacy-crash-send-pending-help = Envoyez le rapport de plantage qui attend votre accord.
privacy-crash-discard-pending = Supprimer le rapport en attente
privacy-crash-discard-pending-help = Supprimez définitivement le rapport sans l'envoyer.
privacy-summary = Le réseau est actif par défaut. Les rapports de plantage exigent votre choix ; les mesures anonymes restent désactivées sans accord.
privacy-netplay-disabled = Jeu en réseau désactivé
privacy-netplay-disabled-help = Activez Accès réseau dans Confidentialité pour jouer en réseau.
privacy-crash-prompt-title = Rapport de plantage
privacy-crash-prompt-body = Antistatic a trouvé un rapport de plantage en attente. Envoyer des diagnostics anonymes pour améliorer la stabilité ?
privacy-crash-prompt-send = Envoyer le rapport
privacy-crash-prompt-later = Demander plus tard
privacy-crash-prompt-never = Ne jamais envoyer de rapports
privacy-crash-prompt-summary = Envoyez ce rapport, décidez plus tard ou désactivez les rapports de plantage.
privacy-report-sending = Envoi en cours...
privacy-report-failed = Échec de l'envoi. Vérifiez le réseau et réessayez.
privacy-crash-sent = Rapport de plantage envoyé
privacy-crash-discarded = Rapport de plantage supprimé
privacy-feedback-title = Avis
privacy-feedback-category = Catégorie : {$value}
privacy-feedback-category-help = Choisissez le type de message à envoyer.
privacy-feedback-category-bug = Bug
privacy-feedback-category-feedback = Avis
privacy-feedback-category-other = Autre
privacy-feedback-subject = Objet
privacy-feedback-subject-help = Saisissez un bref résumé.
privacy-feedback-subject-placeholder = Bref résumé
privacy-feedback-body = Message
privacy-feedback-body-help = Décrivez le problème ou la suggestion. N'indiquez aucune information personnelle.
privacy-feedback-body-placeholder = Que souhaitez-vous nous dire ?
privacy-feedback-submit = Envoyer l'avis
privacy-feedback-submit-help = Envoyez ce message à l'équipe Antistatic.
privacy-feedback-warning = N'indiquez aucune information personnelle, aucun mot de passe ni aucune donnée privée de compte.
privacy-feedback-help = Remplissez l'objet et le message, puis envoyez votre avis.
privacy-feedback-required = Saisissez un objet et un message.
privacy-feedback-sent = Avis envoyé. ID du rapport : {$id}
