hello-world = Ciao mondo! { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = Silicio
Iron = Ferro
Xenon = Xenon
Helium = Elio
Carbon = Carbonio
Rhodium = Rodio

Sandbag = Sacchetto di sabbia

Ruins = Rovine
Transistor = Transistor
Eroded = Eroso
Scales = Bilancia
Crossing = Incrocio
Longboat = Barcaccia
Boombox = Boombox
Fountain = Fontana
Great-White = Grande Bianco
Plane = Il Piano
Satellite = Satellite
Divided = Diviso
Pillars = Pilastri
Debug = Mettere a Punto

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = Vanilla
Physics = Fisica
color-preset-random = Casuale
color-preset-red = Rosso
color-preset-orange = Arancione
color-preset-gold = Oro
color-preset-green = Verde
color-preset-blue = Blu
color-preset-purple = Viola
color-preset-pink = Rosa
color-preset-white = Bianco
versus-color-preset-help = Scegli una famiglia di colori; ogni scelta riceve una piccola variazione casuale. Disattivato in modalità squadre.

# Navigation
Back = Indietro
Exit = Esci
Save = Salva
Cancel = Cancella
Close-Symbol = X

Modify = Modificare
Reset = Ripristina

# Main Menu
Versus = Sfida
Training = Addestramento
Courses = Corsi
TRAINING = ADDESTRAMENTO
COURSES = CORSI
battle-results = Risultati del combattimento
Settings = Opzioni
Controls = Comandi
Discord = Discord {"\u29C9"}
Guide = Guida {"\u29C9"}

# Settings Menu
SETTINGS = OPZIONI
Audio = Audio
Video = Video
accessibility-title = Accessibilità
settings-accessibility-help = Regola movimento, effetti d'impatto, suoni del menu e visibilità del focus.
accessibility-reduced-motion = Movimento ridotto
accessibility-reduced-motion-help = Ferma l'animazione dello sfondo dei menu e le vibrazioni visive degli impatti.
accessibility-hit-flash = Lampo d'impatto: {$value}
accessibility-hit-flash-help = Regola la luminosità dei lampi d'impatto dei personaggi.
accessibility-screen-shake = Vibrazione d'impatto: {$value}
accessibility-screen-shake-help = Regola le vibrazioni visive di personaggi e HUD durante gli impatti.
accessibility-menu-sound = Enfatizza suoni del menu
accessibility-menu-sound-help = Aumenta il volume dei suoni di navigazione e conferma.
accessibility-high-contrast-focus = Focus ad alto contrasto
accessibility-high-contrast-focus-help = Aggiunge un doppio contorno luminoso al controllo del menu selezionato.
accessibility-help = Regola le preferenze di accessibilità e presentazione.
first-run-title = Benvenuto in Antistatic
first-run-intro = Scegli da dove iniziare. Controlli e accessibilità restano disponibili nel menu principale.
first-run-versus = Versus locale
first-run-versus-help = Configura un incontro per i giocatori che condividono questo dispositivo.
first-run-controls = Controlli
first-run-controls-help = Controlla, rimappa e calibra i tuoi comandi.
first-run-training = Allenamento
first-run-training-help = Esercitati liberamente con strumenti e bersagli di allenamento.
first-run-courses = Corsi
first-run-courses-help = Impara movimento, attacchi, difesa e recupero con lezioni guidate.
first-run-skip = Vai al menu principale (Salta)
first-run-skip-help = Completa questa introduzione unica senza aprire una modalità.
first-run-help = Scegli da dove iniziare. Ogni scelta completa questa introduzione unica.
Windowed = A Finestra
Fullscreen = Schermo Intero

main = Menu Principale
versus = Sfida
training = Addestramento
start-mode = Inizio: { TRANSLATE($value) }

# Audio Menu
AUDIO = AUDIO

Play-Audio = Riprodurre Audio
Play-Music = Riprodurre Musica

Audio-volume = Volume: {$value}
SFX-volume = SFX: {$value}
Music-volume = Musica: {$value}
UI-volume = UI: {$value}
Voice-volume = Voce: {$value}

# Video Menu
VIDEO = VIDEO
Quick-Setup = Configurazione rapida
Display = Schermo
Quality = Qualità
Effects = Effetti
Apply-Changes = Applica modifiche

graphics-preset-low = Grafica: Basso
graphics-preset-medium = Grafica: Medio
graphics-preset-high = Grafica: Alto
graphics-preset-max = Grafica: Massimo
graphics-preset-custom = Grafica: Personalizzato

vsync-off = Vsync: Disattivato
vsync-on = Vsync: Attivato
vsync-adaptive = Vsync: Adattivo

shadow-off = Ombre: Disattivato
shadow-low = Ombre: Basso
shadow-highest = Ombre: Massimo

ssao-off = SSAO: Disattivato
ssao-on = SSAO: Attivato
ssao-full = SSAO: Completo

aa-off = Antialias: Disattivato
aa-fxaa = Antialias: FXAA
aa-fxaa-high = Antialias: FXAA alto

bloom-off = Bloom: Disattivato
bloom-on = Bloom: Attivato
reflections-off = Riflessi: Disattivato
reflections-on = Riflessi: Attivato
reflections-low = Riflessi: Basso
reflections-high = Riflessi: Alto
godrays-off = Raggi di luce: Disattivati
godrays-on = Raggi di luce: Attivati

perf-overlay-off = Indicatore prestazioni: Disattivato
perf-overlay-on = Indicatore prestazioni: Attivato


point-lights-off = Luci puntiformi: Disattivate
point-lights-on = Luci puntiformi: Attivate

particles-low = Particelle: Basso
particles-medium = Particelle: Medio
particles-full = Particelle: Massimo


max-fps-off = FPS max: Disattivato
max-fps-30 = FPS max: 30
max-fps-60 = FPS max: 60
max-fps-120 = FPS max: 120
max-fps-144 = FPS max: 144

# Controls Menu
CONTROLS = COMANDI

controls-title = COMANDI
controls-section-controllers = Controller
controls-section-mappings = Mappature
controls-set-tag = Imposta tag
controls-edit-bindings = Modifica configurazione
controls-tag-untagged = (nessun tag)
controls-tag-title = Tag giocatore
controls-tag-prompt = P{$port} ({$layout}). I tag possono contenere 1-24 caratteri alfanumerici, "-" o "_". Lascia vuoto per cancellare.
controls-tag-confirm = Conferma
controls-tag-clear = Cancella
controls-tag-cancel = Annulla
controls-tag-select-title = Scegli tag
controls-tag-filter-empty = Digita per filtrare i tag salvati
controls-tag-filter-value = Filtro: {$filter}
controls-tag-summary-empty = {$total} tag salvati. Digita per filtrare o crea un nuovo tag.
controls-tag-summary-filter = {$visible} di {$total} tag salvati mostrati. Le corrispondenze esatte usano i comandi salvati.
controls-tag-defaults-suffix = predefiniti per questo controller
controls-tag-create-new = Crea nuovo tag
controls-tag-use-existing = Usa tag esistente "{$tag}"
controls-tag-create = Crea "{$tag}"
controls-tag-reserved = "{$tag}" è riservato
controls-tag-netplay-blocked = I tag non possono essere cambiati durante il netplay
controls-tag-no-controller = Nessun controller locale selezionato
controls-tag-no-layout = Il controller selezionato non ha layout
controls-tag-filter-help = Digita per filtrare i tag; ESC cancella o esce
controls-tag-no-saved = Nessun tag salvato
controls-tag-no-matches = Nessun tag corrispondente
controls-tag-invalid = Tag non valido (1-24 caratteri, alfanumerici/-/_; "default" riservato)
controls-profile-help-untagged = I comandi vengono salvati nel profilo condiviso senza tag; solo il tap jump richiede un tag.
controls-profile-help-tagged = Comandi e tap jump predefinito vengono salvati per questo tag e questo tipo di controller.
controls-choose-existing-tag = Scegli tag esistente
controls-create-tag = Crea tag
controls-rename-create-tag = Rinomina/crea tag
controls-edit-set-tag-first = Modifica comandi (imposta prima un tag)
controls-edit-controls = Modifica comandi
controls-tap-jump-default = Tap Jump predefinito: {$state}
controls-state-on = SÌ
controls-state-off = NO
controls-netplay-blocked = I comandi non possono essere modificati durante il netplay
controls-no-local-controllers = Nessun controller attivo. Premi un tasto di gioco o un pulsante del controller per collegarne uno.
controls-no-layout = Il controller non ha layout
controls-set-tag-before-editing = Imposta un tag prima di modificare i comandi
controls-no-mapping = Nessuna mappatura disponibile per questo controller
controls-set-tag-before-tap-jump = Imposta un tag per salvare un tap jump predefinito
controls-connected-controllers = Controller collegati
controls-remap-add-key = + Aggiungi binding (premi un tasto)
controls-remap-find-input = Trova binding (premi un input)
controls-remap-capture-key-title = Premi un tasto
controls-remap-capture-input-title = Premi un input
controls-remap-capture-key-help = Il prossimo tasto premuto sarà aggiunto come nuovo binding.
controls-remap-capture-input-help = Il prossimo pulsante o stick usato sarà selezionato per la modifica.
controls-remap-capture-cancel = ESC per annullare
controls-default-save-blocked = I comandi predefiniti non possono essere sovrascritti; imposta prima un tag
controls-default-reset-blocked = I comandi predefiniti non possono essere ripristinati da questo menu
controls-tag-filter-entry-help = Scrivi per filtrare i tag controller salvati; i gamepad possono usare il D-pad.
controls-tag-filter-label = Filtro
controls-tag-preconfigured = preconfigurato
controls-tag-rename-title = Rinomina tag
controls-tag-create-title = Crea tag
controls-tag-apply-existing-help = Applica a questo controller il tag salvato corrispondente.
controls-tag-create-empty-help = Crea un nuovo tag per questo controller.
controls-tag-create-filtered-help = Crea questo tag per il controller se il nome è valido.
controls-tag-apply-saved-help = Applica questo tag e la sua configurazione salvata al controller.
controls-tag-apply-preconfigured-help = Applica questo tag preconfigurato usando la mappatura predefinita per questo tipo di controller.
controls-tag-apply-default-help = Applica questo tag usando la mappatura predefinita per questo tipo di controller.
controls-tag-delete-button = Elimina {$tag}
controls-tag-delete-help = Elimina {$tag} e i comandi e la calibrazione salvati per ogni tipo di controller dopo la conferma.
controls-tag-delete-title = Eliminare tag?
controls-tag-delete-body = Eliminare "{$tag}", i suoi comandi e la calibrazione per ogni tipo di controller e rimuoverlo dai controller collegati?
controls-tag-delete-warning = Questa azione non può essere annullata.
controls-back-help = Torna a Controlli.
controls-tag-select-help = Scegli o crea un tag controller.
controls-edit-set-tag-first-help = Crea prima un tag controller, poi modifica le assegnazioni di gioco e menu.
controls-edit-controls-help = Modifica le assegnazioni di gioco e menu per questo profilo controller.
controls-tap-jump-set-tag-first-help = Crea prima un tag controller, poi imposta la preferenza predefinita del tap jump.
controls-tap-jump-default-help = Attiva o disattiva se premere su fa saltare questo controller per impostazione predefinita.
controls-create-new-tag-help = Crea un nuovo tag e passa questo controller a esso.
controls-choose-existing-tag-help = Scegli o elimina un tag salvato.
controls-rename-current-tag-help = Rinomina il tag controller attuale.
controls-switch-controller-help = Passa il menu controlli a questo controller collegato.
menu-binding-hint = Muovi con stick o D-pad · Conferma/Start seleziona · Indietro torna
menu-adjust-hint = Muovi con stick o D-pad · Sinistra/Destra cambia i valori · Conferma seleziona · Indietro torna
menu-bind-hint = Muovi con stick o D-pad · Conferma sceglie un'associazione · Indietro torna
arcade-select-leave = Select esce
main-help-about-help = Guide, crediti e link di bluehexagons.
main-replays-available-help = Sfoglia, visualizza in anteprima e riproduci i file replay salvati.
main-replays-unavailable-help = I replay sono disponibili solo offline perché vengono caricati dal filesystem locale.
arcade-menu-battles-help = Avvia la configurazione attuale di Arcade Battles.
arcade-menu-infinite-help = Avvia la modalità Arcade infinita con CPU a 1 stock che scalano.
arcade-menu-training-help = Apri Allenamento con strumenti di pratica e stati salvati.
arcade-menu-back-help = Torna al menu principale.
arcade-menu-help = Scegli una modalità arcade.
training-menu-courses-help = Scegli un breve corso sulle meccaniche di gioco.
training-menu-help = Scegli un'attività di addestramento.
courses-menu-course-help = Visita questa area del corso.
courses-menu-back-help = Torna ad Addestramento.
courses-menu-help = Le aree dei corsi vanno da sinistra a destra. Puoi muoverti liberamente in qualsiasi momento.
course-instruction-movement-walk = Inclina lo stick di movimento a sinistra o a destra per camminare.
course-instruction-movement-dash = Muovi rapidamente lo stick di movimento a sinistra o a destra per scattare.
course-instruction-movement-crouch = Premi verso il basso per accovacciarti.
course-name-movement = Movimento
course-name-jumping = Salti
course-name-attacks = Attacchi
course-name-defense = Difesa
course-name-advanced = Avanzato
course-name-directional-influence = Influenza direzionale
course-name-teching = Tech
course-summary-movement = Cammina, scatta, accovacciati e raggiungi l'indicatore.
course-summary-jumping = Salta, salta di nuovo in aria, afferra i bordi e prova i salti a parete disponibili.
course-summary-attacks = Attacca a terra e in aria, poi consuma energia con un attacco speciale.
course-summary-defense = Blocca, usa lo scudo perfetto, schiva, rotola, para e afferra.
course-summary-advanced = Usa attacchi con lo stick, schivate aeree, cadute rapide e recupero con speciale in alto.
course-summary-directional-influence = Usa lo stick di movimento per cambiare il lancio di un pericolo.
course-summary-teching = Esegui un tech all'atterraggio dopo il lancio di un pericolo.
course-instruction-movement-travel = Raggiungi l'indicatore a forma di freccia.
course-instruction-jumping-jump = Premi salto per staccarti da terra.
course-instruction-jumping-air-jump = Premi di nuovo salto mentre sei in aria per eseguire un salto aereo.
course-instruction-jumping-steer = Tieni premuto sinistra o destra dopo il salto per muoverti in aria.
course-instruction-jumping-ledge-grab = Avvicinati dal basso al bordo di una piattaforma per afferrarlo.
course-instruction-jumping-ledge-option = Dal bordo, scegli un'opzione: risali, rotola, attacca, salta o lasciati cadere.
course-instruction-jumping-wall-jump = Tocca la parete superiore, poi muovi rapidamente lo stick in direzione opposta per saltare dalla parete.
course-instruction-attacks-normal = Colpisci il bersaglio di pratica con un attacco normale.
course-instruction-attacks-aerial = Salta e colpisci il bersaglio di pratica con un attacco aereo.
course-instruction-attacks-energy = Usa un attacco speciale e osserva la barra di energia condivisa diminuire e poi ricaricarsi dopo una pausa.
course-instruction-attacks-special = Colpisci il bersaglio di pratica con un attacco speciale.
course-instruction-defense-shield = Blocca l'attacco del bersaglio di pratica con lo scudo.
course-instruction-defense-power-shield = Premi a fondo lo scudo appena prima dell'impatto per usare uno scudo perfetto senza perdere energia.
course-instruction-defense-roll = Mentre usi lo scudo, premi sinistra o destra per rotolare.
course-instruction-defense-spot-dodge = Mentre usi lo scudo, premi verso il basso per schivare sul posto.
course-instruction-defense-parry = Rilascia lo scudo appena prima dell'impatto per parare.
course-instruction-defense-grab = Afferra il bersaglio di pratica.
course-instruction-advanced-stick = Muovi rapidamente lo stick destro in una direzione per eseguire un attacco con lo stick.
course-instruction-advanced-air-dodge = Salta, poi premi a fondo un pulsante scudo per schivare in aria.
course-instruction-advanced-fast-fall = In aria, premi verso il basso per cadere rapidamente.
course-instruction-advanced-recovery = In aria, premi verso l'alto e Speciale per recuperare con uno speciale in alto.
course-instruction-directional-influence = Tieni premuto sinistra o destra quando il lanciatore ti colpisce per cambiare l'angolo di lancio.
course-instruction-teching-neutral = Premi a fondo un pulsante scudo subito prima di atterrare dal lanciatore per eseguire un tech.
course-instruction-complete = Area completata. Vai in un'altra area quando sei pronto.
course-action-restart = Riavvia area
course-action-next = Area successiva
course-session-progress = Aree completate: {$completed}/{$total}
course-target-label = Bersaglio di pratica
course-target-reset = Ripristina bersaglio
course-target-disable = Disattiva bersaglio
course-target-enable = Attiva bersaglio
course-target-unavailable = Nessun bersaglio in quest'area
course-target-reset-help = Riporta il bersaglio di pratica di quest'area alla posizione iniziale e lo attiva.
course-target-toggle-help = Nasconde o ripristina il bersaglio di pratica di quest'area per la sessione attuale.
course-defense-feedback-early = Attiva lo scudo più vicino all'attacco in arrivo.
course-defense-feedback-late = Troppo tardi. Attiva lo scudo prima che l'attacco colpisca.
course-defense-feedback-success = Tempismo perfetto. L'attacco è stato bloccato.
course-demonstration-label = Dimostrazione
course-demonstration-show = Mostra demo statica
course-demonstration-hide = Nascondi demo statica
course-demonstration-help = Mostra o nasconde un esempio non animato per il passaggio attuale della lezione.
course-demonstration-still = Posa statica · nessuna animazione
help-bluehex-homepage-help = Visita la homepage di bluehexagons.
help-bluehex-github-help = Sfoglia i progetti bluehexagons su GitHub.
help-bluehex-steam-help = Apri la pagina curatore Steam di bluehexagons.
help-bluehex-itch-help = Apri la pagina itch.io di bluehexagons.
help-bluehex-bluesky-help = Segui bluehexagons su Bluesky.
help-bluehex-patreon-help = Sostieni bluehexagons su Patreon.
controls-source-keyboard = Tastiera
controls-source-keyboard-defaults = Impostazioni tastiera predefinite
controls-current-menu-controls-heading = Controlli attuali del menu
controls-current-menu-controls-summary = {$source} · Muovi: {$navigate} · Conferma: {$confirm} · Indietro: {$back}
controls-action-attack = Attacco
controls-action-jump = Salto
controls-action-special = Speciale
controls-action-grab = Presa
controls-action-shield-1 = Scudo 1
controls-action-shield-2 = Scudo 2
controls-action-hard-shield-1 = Scudo forte 1
controls-action-hard-shield-2 = Scudo forte 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-pad su
controls-action-dpad-down = D-pad giù
controls-action-dpad-left = D-pad sinistra
controls-action-dpad-right = D-pad destra
controls-action-move-horizontal = Movimento orizzontale
controls-action-move-vertical = Movimento verticale
controls-action-right-stick-horizontal = Stick destro orizzontale
controls-action-right-stick-vertical = Stick destro verticale
controls-action-ui-confirm = Conferma UI
controls-action-ui-back = Indietro UI
controls-action-ui-up = UI su
controls-action-ui-down = UI giù
controls-action-ui-left = UI sinistra
controls-action-ui-right = UI destra
controls-action-ui-horizontal-nav = Navigazione UI orizzontale
controls-action-ui-vertical-nav = Navigazione UI verticale
controls-action-move-left = Muovi a sinistra
controls-action-move-right = Muovi a destra
controls-action-move-up = Muovi su
controls-action-move-down = Muovi giù
controls-action-tilt-left = Tilt a sinistra
controls-action-tilt-right = Tilt a destra
controls-action-tilt-up = Tilt in alto
controls-action-tilt-down = Tilt in basso
controls-action-right-stick-left = Stick destro sinistra
controls-action-right-stick-right = Stick destro destra
controls-action-right-stick-up = Stick destro su
controls-action-right-stick-down = Stick destro giù
controls-action-light-shield-l = Scudo leggero L
controls-action-light-shield-r = Scudo leggero R
controls-action-ui-nav-left = Navigazione UI sinistra
controls-action-ui-nav-right = Navigazione UI destra
controls-action-ui-nav-up = Navigazione UI su
controls-action-ui-nav-down = Navigazione UI giù
controls-remap-section-buttons = Pulsanti
controls-remap-section-dpad = D-pad
controls-remap-section-movement = Movimento
controls-remap-section-tilts = Tilt (movimento morbido)
controls-remap-section-right-stick = Stick destro
controls-remap-section-light-shields = Scudi leggeri
controls-remap-section-ui-navigation = Navigazione UI
controls-remap-section-sticks-triggers = Stick e grilletti
controls-remap-unbound = Non assegnato
controls-remap-free-keys-none = Tasti liberi: (nessuno nel set comune)
controls-remap-more-suffix = , +{$count} altri
controls-remap-free-keys = Tasti liberi: {$keys}{$suffix}
controls-remap-free-buttons = Pulsanti liberi: {$buttons}
controls-remap-free-axes = Assi liberi: {$axes}
controls-remap-conflict-detail = {$input} è già assegnato a {$actions}.
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = Mantieni Conferma UI, Indietro UI e la navigazione orizzontale e verticale affinché i menu restino utilizzabili.
controls-remap-capture-key-hint = Premi un tasto della tastiera per {$action}. ESC annulla.
controls-remap-capture-button-hint = Premi un pulsante {$layout} per {$action}. Indietro annulla.
controls-remap-capture-axis-hint = Muovi uno stick/grilletto {$layout} per {$action}. Indietro annulla.
controls-remap-capture-add-title = Aggiungi {$action}
controls-remap-capture-replace-title = Sostituisci {$action}
controls-remap-capture-matching-input = Usa un input compatibile per questa azione.
controls-remap-confirm-reassign = Conferma per riassegnarlo a {$action}.
controls-remap-confirm-cancel-help = Conferma lo sostituisce. Indietro annulla.
controls-remap-command-add = Aggiungi
controls-remap-command-replace = Sostituisci
controls-remap-command-remove = Rimuovi
controls-remap-add-help = Aggiungi un altro input fisico per {$action}.
controls-remap-replace-help = Sostituisci {$input} per {$action}.
controls-remap-remove-help = Rimuovi {$input} da {$action}.
controls-remap-back-to-controls = Torna a Controlli
controls-remap-back-to-controls-help = Torna a Controlli senza scorrere fino in fondo alla lista di rimappatura.
controls-remap-help = Scegli Aggiungi, Sostituisci o Rimuovi. I tasti Pagina saltano nella lista.
controls-remap-help-extended = Scegli Aggiungi, Sostituisci o Rimuovi. I tasti Pagina saltano nella lista; Indietro annulla.
controls-remap-jump-to-section = Vai alla sezione
controls-remap-jump-to-binding = Vai a {$section}
controls-remap-focus-section-help = Sposta il focus al primo assegnamento {$section}.
controls-remap-reset-help = Reimposta questo profilo comandi al layout predefinito. Richiede due conferme.
controls-remap-reset-confirm = Premi di nuovo per confermare il ripristino
controls-quick-map-action-unbound = Non assegnato
controls-quick-map-action-hard-shield-1-short = Scudo 1
controls-quick-map-action-hard-shield-2-short = Scudo 2
controls-quick-map-action-dpad-up-short = D-Su
controls-quick-map-action-dpad-down-short = D-Giù
controls-quick-map-action-dpad-left-short = D-Sinistra
controls-quick-map-action-dpad-right-short = D-Destra
controls-quick-map-title = Layout rapido {$layout}
controls-quick-map-mode-editing = Conferma o fai clic su un'azione per applicare · Indietro o fai clic sul titolo per uscire
controls-quick-map-mode-ready = Conferma apre la modifica rapida
controls-quick-map-mode-unavailable = Comandi non disponibili
controls-quick-map-assign = Assegna
controls-quick-map-assign-input = Assegna {$input}
controls-quick-map-unavailable-status = La mappatura rapida non è disponibile per questo controller. Nessuna modifica salvata.
controls-remap-autosave-status = Le modifiche vengono salvate automaticamente.
controls-remap-saved-status = Salvato automaticamente.
controls-remap-blocked-menu-controls-status = Bloccato: mantieni Conferma UI, Indietro UI e la navigazione orizzontale e verticale del menu. Nessuna modifica salvata.
controls-remap-default-reset-blocked-status = I comandi predefiniti integrati non possono essere ripristinati. Nessuna modifica salvata.
controls-layout-standard = Xbox / Standard
controls-layout-arcade-stick = Stick arcade
controls-layout-retro-dpad = D-pad retrò
controls-layout-switch-pro = Switch Pro
controls-layout-playstation = PlayStation
controls-layout-8bitdo-nintendo = 8BitDo (layout Nintendo)
controls-layout-steam-deck = Steam Deck
controls-layout-gamecube = GameCube
controls-layout-n64 = Nintendo 64
controls-layout-keyboard = Tastiera

standard = Standard
keyboard = tastiera
gcn_native = GCN native

# Training Menu
Swap-Character = Scambia personaggio
Overlays = Sovrapposizioni
press-start = Premi Start

drawHitbubbleInfo = Informazioni sull'attacco
drawECB = Collisione
drawHeatmap = Mappa di Calore
drawRawPosition = Posizione Grezza
drawStage = Collisione sul Palco
animations = Animazioni
controllers = Controllori

# Versus Menu
FFA = FFA
Teams = Squadre

Host-Netplay = Netplay dell'host
Join-Netplay-Clipboard = Unisciti a netplay dagli appunti
Disconnect = Disconnetti
Copy-Lobby-Code = Copia il codice della lobby

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = Connessione diretta
Connect = Connetti

netplay-action-start-lobby = Avvia lobby
netplay-action-join-clipboard = Unisci dagli appunti
netplay-action-quick-host-copy-code = Host rapido e copia codice
netplay-action-copy-lan-invite = Copia invito LAN
netplay-action-copy-localhost-invite = Copia invito localhost
netplay-action-copy-stun-invite = Copia invito STUN
netplay-action-find-random-match = Trova partita casuale
netplay-action-cancel-lobby = Annulla lobby
netplay-action-cancel-connection = Annulla connessione
netplay-action-please-wait = Attendere prego
netplay-action-open-versus = Apri Versus
netplay-action-cancel-matchmaking = Annulla matchmaking

netplay-status-label = Netplay: {$status}
netplay-status-uninitialized = non inizializzato
netplay-status-initialized = inizializzato
netplay-status-waiting = in attesa
netplay-status-hosting = hostando
netplay-status-connecting = connessione in corso
netplay-status-establishing = stabilimento in corso
netplay-status-connected = connesso
netplay-status-ready = Pronto per netplay
netplay-status-waiting-player = In attesa di un giocatore
netplay-status-waiting-lobby = In attesa di risposta dal lobby
netplay-status-hosting-lobby = Hostando lobby
netplay-status-hosting-lobby-code = Hostando lobby {$code}
netplay-status-starting-lobby = Avvio lobby
netplay-status-connecting-host = Connessione all'host
netplay-status-connected-host = Connesso come host
netplay-status-connected-client = Connesso all'host
netplay-status-disconnecting = Disconnessione in corso
netplay-status-canceling = Annullamento connessione
netplay-status-matchmaking = Ricerca partita casuale
netplay-status-match-found = Partita casuale trovata
netplay-status-matchmaking-canceling = Annullamento matchmaking
netplay-status-error = Errore netplay
netplay-status-error-message = Errore netplay: {$error}
netplay-status-unavailable = Stato netplay non disponibile

matchmaking-title = RICERCA PARTITA
matchmaking-status-select-character = Seleziona un personaggio per metterti in coda
matchmaking-status-no-controller = Nessun controller collegato
matchmaking-status-searching = Ricerca di una partita...
matchmaking-status-searching-details = Ricerca... attesa di {$wait}s. Giocatori in coda: {$players}. Attesa più lunga: {$longest}s.
matchmaking-status-searching-estimate = Ricerca... attesa di {$wait}s. Giocatori in coda: {$players}. Le partite concluse hanno avuto una media di {$average}s.
matchmaking-status-canceling = Annullamento...
matchmaking-status-found = Partita trovata!
matchmaking-status-connecting = Connessione...
matchmaking-status-disconnecting = Disconnessione...
matchmaking-status-error = {$error} Seleziona un personaggio per riprovare.

# Match by Code
match-code-title = PARTITA TRAMITE CODICE
match-code-hint = Condividi il tuo codice. Inserisci il suo. Premete entrambi Cerca. Maiuscole e minuscole non contano.
match-code-own-label = Il tuo codice: {$code}
match-code-peer-label = Codice del tuo amico: {$code}
match-code-peer-unset = Codice del tuo amico: (non impostato)
match-code-search = Cerca
match-code-entry-limit = Massimo {$length} lettere o numeri
match-code-own-prompt = Il tuo codice
match-code-peer-prompt = Codice del tuo amico
match-code-status-enter-peer = Inserisci il codice del tuo amico per creare una partita privata
match-code-status-ready = Pronto — entrambi i giocatori devono premere Cerca
match-code-error-enter-peer = Inserisci prima il codice del tuo amico
match-code-error-own = Inserisci il codice del tuo amico, non il tuo
match-code-error-invalid = Questo codice non è valido
match-code-error-length = Il codice deve contenere da {$min} a {$max} lettere o numeri
match-code-error-blocked = Questo codice non è consentito; scegline un altro

netplay-detail-ready = Hosta un lobby, incolla un invito copiato o inserisci manualmente un indirizzo.
netplay-detail-lobby-code-ready = Il codice lobby {$code} è pronto per essere condiviso.
netplay-detail-creating-lobby-code = Creazione del tuo codice lobby.
netplay-detail-waiting-for-host = In attesa che l'host risponda alla tua richiesta di accesso.
netplay-detail-share-lobby-code = Condividi il codice lobby {$code} con l'altro giocatore.
netplay-detail-starting-lobby = Avvio della tua connessione lobby.
netplay-detail-joining-host = Tentativo di unirsi all'host selezionato.
netplay-detail-establishing = Giocatori trovati. Termina la stretta di mano e poi apri Versus.
netplay-detail-connected = Connessione pronta. Apri Versus per scegliere regole, personaggi e stage.
netplay-detail-disconnecting = Chiusura della sessione corrente e ritorno al gioco offline.
netplay-detail-canceling = Arresto della richiesta di accesso corrente.
netplay-detail-matchmaking = Usa Versus per metterti in coda per un avversario casuale con le tue regole preferite.
netplay-detail-match-found = Avversario trovato. Termina la configurazione in Versus quando entrambi i giocatori sono pronti.
netplay-detail-matchmaking-canceling = Arresto della ricerca attuale di partite casuali.
netplay-detail-error-message = Ultimo errore: {$error}
netplay-detail-error-generic = Qualcosa è andato storto. Prova un codice o metodo di connessione diverso.
netplay-detail-unavailable = Dettagli netplay non disponibili.

netplay-help-host-copy-code = Copia il tuo codice lobby così l'altro giocatore può incollarlo.
netplay-help-host-cancel-join = Ferma il tentativo di accesso corrente e torna allo stato di pronto.
netplay-help-host-disconnect = Lascia la sessione netplay corrente.
netplay-help-host-start-lobby = Avvia un nuovo lobby e attendi che un altro giocatore si unisca.
netplay-help-busy = Netplay è occupato in questo momento. Attendi che finisca.
netplay-help-join-cancel-lobby = Chiudi il lobby corrente e smetti di attendere un altro giocatore.
netplay-help-join-in-progress = Un accesso è già in corso. Attendi o usa Annulla Connessione.
netplay-help-join-open-versus = Continua verso Versus e termina la configurazione della partita.
netplay-help-stop-random-search = Ferma la ricerca di un avversario casuale.
netplay-help-join-clipboard = Incolla un codice di invito lobby, diretto o STUN dagli appunti.
netplay-help-copy-server = Avvia un lobby se necessario, poi copia il suo codice lobby condivisibile.
netplay-help-copy-direct = Copia un invito di connessione diretta per un altro dispositivo su questo LAN.
netplay-help-copy-localhost = Copia un invito di connessione diretta per un'altra copia in esecuzione su questo computer.
netplay-help-copy-stun = Copia un invito assistito da STUN che è più facile da usare su Internet.
netplay-help-direct-connect = Inserisci manualmente un indirizzo invece di usare un codice di invito copiato.
netplay-help-find-random-match = Apri Versus e mettiti in coda per un avversario casuale.
netplay-help-open-versus = Apri il menu Versus senza lasciare questa schermata.
netplay-help-back = Torna al menu principale.
netplay-help-unavailable = Aiuto azione netplay non disponibile.
netplay-help-advanced = Regola le impostazioni avanzate di netplay come rollback e buffer.

ADVANCED-CONNECTIONS = CONNESSIONI AVANZATE
netplay-settings-rollback-help = Attiva o disattiva la simulazione rollback per le partite online.
netplay-settings-buffer-help = Scegli quanti frame di input mettere in buffer, oppure lascia che il netplay scelga automaticamente.
netplay-settings-force-ipv4-help = Preferisci IPv4 quando generi codici di invito LAN su reti miste.
netplay-settings-back-help = Torna al menu netplay.
netplay-advanced-info = Usa queste opzioni come ripiego quando Quick Play o i normali codici lobby non riescono a connettersi. STUN aiuta a oltrepassare i router per il gioco su internet. La connessione diretta è ideale per il gioco LAN o per un host con una porta UDP inoltrata.
netplay-advanced-direct-help = Ripiego manuale. Inserisci host:porta per il gioco LAN o quando l'host ha inoltrato una porta UDP.
netplay-advanced-stun-help = Ripiego internet. Condividilo quando l'accesso normale ai lobby fallisce e hai ancora bisogno del hole punching assistito dal router.
netplay-advanced-lan-help = Ripiego LAN. Condividi il tuo indirizzo locale raggiungibile quando entrambi i giocatori sono sulla stessa rete.
netplay-advanced-localhost-help = Ripiego di test. Usalo solo quando entrambi i client sono in esecuzione sulla stessa macchina.
netplay-advanced-back-help = Torna al Divano virtuale.
netplay-rollback-off = Rollback: Disattivato
netplay-rollback-on = Rollback: Attivato
netplay-buffer-auto = Buffer di rete: Auto
netplay-buffer-2 = Buffer di rete: 2
netplay-buffer-3 = Buffer di rete: 3
netplay-buffer-4 = Buffer di rete: 4
netplay-buffer-5 = Buffer di rete: 5
netplay-buffer-6 = Buffer di rete: 6
netplay-buffer-7 = Buffer di rete: 7
netplay-buffer-8 = Buffer di rete: 8
netplay-buffer-10 = Buffer di rete: 10
netplay-buffer-12 = Buffer di rete: 12
netplay-force-ipv4-dual = Indirizzo LAN: IPv6/IPv4
netplay-force-ipv4-v4 = Indirizzo LAN: Forza IPv4

netplay-rollback = Rollback
netplay-buffer = Buffer di rete
netplay-force-ipv4 = Indirizzo LAN

netplay-direct-connect-prompt = Inserisci indirizzo IP:porta. La porta predefinita è {$port}.
netplay-stun-connect-title = Usa servizio STUN?
netplay-stun-connect-prompt = Questo codice ha usato {$service} per scoprire {$address}:{$port}.
netplay-waiting-host-battle = In attesa della fine della battaglia dell'host
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = Personaggi
Stages = Arene
CPU = CPU

Starter = Starter
Legal = Legale
Miscellaneous = Miscellaneo

Start-Battle = Inizia la battaglia

# Start Menu
quit-info = Scudo + Attacco + Start per uscire
paused = PAUSA
tag-info = D-pad su/giù per entrare/uscire

# Pause Menu
pause-resume = Riprendi
pause-restart = Riavvia
pause-quit = Esci
pause-players = Giocatori
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = Collegati a un controller e premi un pulsante qualsiasi per unirti.
arcade-return-prompt = Premi conferma per tornare al menu principale.

# Replay
replay-paused = Riproduzione in pausa
replay-controls = Conferma: unisciti  ←/→: fotogramma  Indietro: menu  Salva Replay: [tasto]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = Inglese
spanish = Spagnolo
french = Francese
italian = {it-italian}
german = Tedesco
russian = Russo
japanese = Giapponese
chinese-cn = Cinese semplificato
chinese-hk = Cinese tradizionale
korean = Coreano

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian}
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean} ({korean})

# Shared UI labels
Advanced = Avanzate
Clear-Spawns = Cancella spawn
Create-new-tag = Crea nuovo tag
Credits = Crediti
CREDITS = CREDITI
Cycle-Palette = Cambia palette
Delete = Elimina
Help = Aiuto
HELP = AIUTO
Join = Partecipa
Join-Lobby-Code = Entra con codice lobby
Main-Menu = Menu principale
Mode = Modalità
Native-Adapter = Adattatore nativo
NATIVE-ADAPTER = ADATTATORE NATIVO
NETPLAY-SETTINGS = IMPOSTAZIONI NETPLAY
Other-saved-tags = Altri tag salvati
Profiles-for-this-controller-type = Profili per questo tipo di controller
Quick-Play = Partita rapida
Random-Color = Colore casuale
Rename-current-tag = Rinomina tag corrente
Reset-to-Defaults = Ripristina predefiniti
Set-Character = Imposta personaggio
Spawn-CPU = Genera CPU
Team = Squadra
Virtual-Couch = Divano virtuale
x = x
Find-Random-Match = Cerca partita casuale
training-label-stage = Stage
training-label-character = Personaggio
training-label-player-cursor = Cursore del giocatore
training-label-cpu-spawn = Generazione CPU
training-label-savestate = Stato salvato
Save-State = Salva stato
Load-State = Carica stato
State-Saved = Stato salvato
State-Restored = Stato ripristinato
No-State-Saved = Nessuno stato salvato
DPad-Right-Save-Left-Load = D-pad destra salva · sinistra carica
shared-main-menu-help = Torna al menu principale.
shared-mode-selector-label-help = Etichetta del selettore regole.
training-mode-selector-help = Passa tra le costanti allenamento di Antistatic e 19XX.
training-overlays-help = Attiva o disattiva overlay di debug e aiuti allenamento.
training-close-help = Chiudi il menu allenamento.
training-stage-help = Cambia stage di allenamento e reimposta le entità legate allo stage.
training-character-help = Scegli il personaggio usato da Imposta personaggio e Genera CPU.
training-set-character-help = Cambia il cursore del giocatore sospeso sul personaggio selezionato.
training-random-color-help = Assegna un nuovo colore base casuale al personaggio del cursore.
training-cycle-palette-help = Scorri la palette del personaggio del cursore.
training-cpu-level-down-help = Abbassa il livello CPU usato per le nuove CPU di allenamento.
training-cpu-level-current-help = Livello CPU attuale per le nuove CPU di allenamento. Conferma per farlo scorrere.
training-cpu-level-up-help = Alza il livello CPU usato per le nuove CPU di allenamento.
training-spawn-cpu-help = Genera una CPU usando il personaggio e il livello CPU selezionati.
training-clear-spawns-help = Rimuovi tutte le CPU e i manichini generati in allenamento.
training-save-state-help = Salva posizione, danni, stock, CPU generate, stage e timing attuali dell'allenamento. D-pad destra usa la stessa scorciatoia.
training-load-state-help = Ripristina lo stato di allenamento salvato. D-pad sinistra usa la stessa scorciatoia.
training-savestate-shortcuts-help = D-pad destra salva lo stato di allenamento attuale; D-pad sinistra lo ripristina.
versus-tag-selector-default = Tag: {$tag}
versus-tag-none = Nessun tag
versus-tag-manage = Crea / gestisci tag
versus-tag-change-failed = Impossibile cambiare tag
versus-cpu-level-help = Cambia questo livello CPU.
versus-cpu-color-help = Rimescola colore e palette di questa CPU.
versus-cpu-team-help = Cambia squadra di questa CPU.
versus-cpu-remove-help = Rimuovi questa CPU.
versus-character-select-help = Seleziona questo personaggio per il cursore sospeso del giocatore.
versus-add-cpu-help = Aggiungi una CPU con questo personaggio.
versus-tap-jump-help = Attiva o disattiva il tap jump per questo giocatore.
versus-random-color-help = Assegna a questo giocatore un nuovo colore casuale. Disattivato quando le squadre sono attive.
versus-cycle-palette-help = Scorri la palette di questo giocatore.
versus-team-help = Cambia squadra di questo giocatore. Mostrato quando la modalità squadre è attiva.
versus-tag-selector-help = Scegli il tag di questo giocatore. Disattivato durante il netplay.
versus-start-select-character-first = Seleziona prima un personaggio
versus-start-not-enough-players = Giocatori insufficienti per iniziare una partita: {$count}
versus-start-not-enough-teams = Squadre insufficienti per iniziare una partita: {$count}
versus-start-waiting-for-host = In attesa dell’host
versus-ffa-help = Passa tra tutti contro tutti e regole a squadre.
versus-start-help = Avvia la partita quando abbastanza giocatori, CPU, squadre e uno stage sono pronti.
versus-starter-help = Scegli casualmente uno stage starter e avvia la partita.
versus-legal-help = Scegli casualmente uno starter legale o un counterpick e avvia la partita.
versus-misc-help = Stage vari.
versus-stage-preview-help = Passa sopra per vedere in anteprima questo stage; conferma per selezionarlo e iniziare.
versus-stage-preview-counterpick-help = Passa sopra per vedere in anteprima questo counterpick; conferma per selezionarlo e iniziare.
versus-stage-preview-misc-help = Passa sopra per vedere in anteprima questo stage vario; conferma per selezionarlo e iniziare.
versus-mode-selector-help = Passa tra le costanti versus di Antistatic e 19XX.
versus-tab-stages-help = Sfoglia e scegli uno stage per il match.
versus-tab-settings-help = Configura regole e impostazioni del match. Premendo Start qui passi alla selezione stage.
versus-setting-stock = Stock
versus-setting-time = Tempo
versus-setting-on = Sì
versus-setting-off = No
versus-setting-none = Nessuna
versus-setting-stock-mode-value = Modalità: {$value}
versus-setting-stocks-value = Vite: {$value}
versus-setting-time-limit-value = Tempo: {$value}
versus-setting-friendly-fire-value = Fuoco amico: {$value}
versus-setting-stamina-value = Resistenza: {$value}
versus-setting-knockback-value = Lancio: {$value}×
versus-setting-pause-value = Metti in pausa: {$value}
versus-setting-sd-value = Autodistruzione: {$value}
versus-setting-stock-mode-help = Alterna tra modalità Stock (vince l'ultimo giocatore rimasto) e Tempo (vince chi ha più stock allo scadere).
versus-setting-stocks-help = Numero di stock (vite) con cui inizia ogni giocatore.
versus-setting-time-limit-help = Limite di tempo del match. In modalità Tempo determina il vincitore.
versus-setting-friendly-fire-help = Attiva se i compagni di squadra possono danneggiarsi tra loro. Visibile solo in modalità squadre.
versus-setting-stamina-help = Stamina iniziale (HP). Imposta 0 per la modalità percentuale danno.
versus-setting-knockback-help = Moltiplicatore globale del knockback. Valori più alti aumentano la distanza di lancio.
versus-setting-pause-help = Consenti o vieta la pausa durante il match.
versus-setting-sd-help = Penalità per autodistruzione. -1 sottrae uno stock; 0 non applica penalità.
netplay-copy-lobby-missing = Nessun codice lobby da copiare
netplay-copy-lobby-copied = Codice lobby copiato negli appunti
netplay-direct-connect-empty = Inserisci un indirizzo IP
netplay-lobby-code-prompt = Inserisci un codice invito lobby, LAN o STUN.
netplay-lobby-code-empty = Inserisci un codice lobby
netplay-error-connecting = Errore di connessione: {$error}
matchmaking-no-controller-connected = Nessun controller collegato
battle-winner-log = Vincitore: {$player}
battle-winner-message = Vincitore: Giocatore {$player}
battle-winner-team-log = Vincitore: Squadra {$team}
battle-winner-team-message = Vincitore: Squadra {$team}
battle-tie-log = Pareggio
battle-tie-message = PAREGGIO
battle-time-out = TEMPO SCADUTO
battle-countdown-go = VIA
battle-infinite-score-log = Punteggio infinito: {$score}
battle-infinite-score-message = Punteggio {$score}
team-name-red = Rosso
team-name-green = Verde
team-name-blue = Blu
team-name-grey = Grigio
versus-start-sync-failed = Impossibile sincronizzare l’inizio del match

main-menu-help = Passa su un'opzione per vedere cosa fa.
netplay-main-help = Scegli un'azione netplay.
netplay-settings-help = Regola il comportamento del netplay.
netplay-advanced-help = Scegli uno strumento di connessione.
settings-help = Scegli una categoria di impostazioni.
help-discord-help = Apri la community Discord di Antistatic nel browser.
help-guide-help = Apri la guida online di Antistatic nel browser.
help-adapter-guide-help = Apri le note di configurazione di Dolphin per l'adattatore ufficiale del controller GameCube.
Adapter-Guide = Guida adattatore
Open-Dolphin-Guide = Apri guida Dolphin
Native-Adapter-Help = Aiuto adattatore
NATIVE-ADAPTER-HELP = AIUTO ADATTATORE
native-adapter-help-summary = Antistatic usa libusb direttamente, quindi condivide la stessa configurazione dei driver del supporto adattatore nativo di Dolphin.
native-adapter-help-windows = Windows: installa WinUSB per USB ID 057e:0337 con Zadig.
native-adapter-help-linux = Linux: aggiungi una regola udev che conceda l'accesso utente a 057e:0337.
native-adapter-help-sdl = Se SDL/Dolphin prende l'adattatore per primo, avvia con SDL_JOYSTICK_HIDAPI_GAMECUBE=0.
native-adapter-help-dolphin = Dolphin/Slippi: chiudili prima di aprire la diagnostica dell'adattatore nativo di Antistatic.
native-adapter-help-claim = Se un'altra app aveva l'adattatore occupato, chiudila e riapri questa schermata di diagnostica.
native-adapter-help-back = Torna allo stato dell'adattatore nativo.
help-credits-help = Visualizza crediti, copyright e attribuzioni di terze parti.
help-back-help = Torna al menu principale.
help-help = Scegli una destinazione della guida.
controls-help = Scegli un'azione del controller.
netplay-quick-play-help = Cerca un avversario casuale usando il controller selezionato.
credits-help = Crediti e attribuzioni.

credits-heading = Antistatic - crediti e attribuzioni
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. Tutti i diritti riservati.
credits-developer = Sviluppatore: bluehexagons (Loren Crain).
credits-original = Suoni, modelli, animazioni, gameplay, UI e codice del motore originali sono stati creati internamente.
credits-runtime = Runtime/strumenti open source: Node.js, TypeScript, CMake, Fluent, gl-matrix, jsonc-parser, os-locale.
credits-libraries = Librerie native: SDL3, SDL3_image, GLEW, OpenAL Soft, FreeType, Vorbis/libvorbisfile, libusb.
credits-build = Strumenti di build/controllo: npm, oxlint, oxfmt e toolchain dei compilatori di piattaforma.
credits-fonts = Font inclusi: Noto Sans, IBM Plex Mono e GNU Unifont.
credits-tools = Strumenti di produzione: Blender per i modelli 3D; Audacity e LMMS per audio e musica.
credits-packages = Pacchetti bluehexagons: capacitor, trace e antistatic-translations.
credits-thanks = Grazie ai manutentori e ai contributori di questi progetti.
credits-license = I progetti di terze parti restano sotto le rispettive licenze.

# Old UI hover/help text
main-versus-help = Scegli personaggi, CPU, squadre, regole e uno stage prima di iniziare un match locale.
main-arcade-help = Battaglie CPU in cooperativa per chiunque sia collegato. Stock limitati, ritenta alla sconfitta.
main-netplay-help = Ospita o unisciti a partite online, Quick Play e impostazioni di connessione Netplay.
main-training-help = Apri la modalità allenamento con stage, CPU, colore, tavolozza e controlli di debug.
main-replays-help = Sfoglia, anteprima e riproduci i file Replay salvati.
main-settings-help = Regola audio, video, lingua, adattatore controller e modalità di avvio.
main-controls-help = Crea tag controller e modifica le mappature con tag o il profilo condiviso senza tag.
main-help-help = Apri i link della community e delle guide esterne.
main-exit-help = Esci da Antistatic.
settings-audio-help = Regola il volume master, degli effetti sonori, dell'interfaccia, delle voci e della musica.
settings-video-help = Cambia il preset grafico, lo schermo intero, la sincronizzazione, gli effetti e le opzioni del limite FPS.
settings-native-adapter-help = Controlla lo stato dell'adattatore GameCube e le note di configurazione.
settings-language-help = Cambia la lingua del menu.
settings-start-mode-help = Scegli quale modalità si apre per prima all'avvio.
settings-live-reload = Ricaricamento in tempo reale
settings-live-reload-help = Ricarica i file dei personaggi dall'Animator durante la modifica locale. Disattivato per impostazione predefinita.
shared-settings-help = Torna a Impostazioni.
native-adapter-copy-udev-install-help = Copia i comandi standard di installazione e ricarica della regola udev per 057e:0337.
native-adapter-copy-udev-line-help = Copia solo la riga standard della regola udev per 057e:0337.
native-adapter-help-button-help = Apri le note di configurazione Windows e Linux per installazioni di adattatori compatibili con Dolphin/Slippi.
audio-master-help = Imposta il volume di uscita master.
audio-sfx-toggle-help = Attiva o disattiva gli effetti sonori e i suoni dell'interfaccia.
audio-sfx-help = Imposta il volume degli effetti sonori di gioco.
audio-ui-help = Imposta il volume di menu e interfaccia.
audio-voice-help = Imposta il volume delle voci dei personaggi.
audio-music-toggle-help = Attiva o disattiva la riproduzione musicale.
audio-music-help = Imposta il volume della musica.
video-preset-help = Applica un preset grafico raggruppato, o mostra Personalizzato quando le impostazioni individuali differiscono.
video-fullscreen-toggle-help = Passa da finestra a schermo intero e viceversa.
video-display-help = Scegli quale schermo deve usare la finestra del gioco o la modalità schermo intero.
video-fullscreen-resolution-help = Scegli la risoluzione della modalità schermo intero esclusiva. Auto usa lo schermo intero del desktop.
video-windowed-resolution-help = Scegli la dimensione della finestra usata in modalità finestra e per il ripristino dallo schermo intero.
video-render-scale-help = Renderizza la grafica 3D sotto o sopra la risoluzione della finestra mantenendo nativa l'interfaccia.
video-vsync-help = Scegli il timing di scambio. Adattivo usa una sincronizzazione a bassa latenza tear-if-late quando il driver lo supporta.
video-shadow-quality-help = Scegli la qualità delle ombre o disattiva le ombre.
video-ssao-help = Scegli la qualità dell'occlusione ambientale.
video-antialias-help = Attiva o disattiva l'anti-aliasing FXAA.
video-bloom-help = Aggiunge un bagliore morbido attorno alle luci più intense. Ideale su GPU di fascia alta.
video-reflections-help = Riflette la scena sulle superfici lucide tramite riflessi in spazio schermo. Impegnativo; ideale su GPU di fascia alta.
video-godrays-help = Proietta fasci di luce volumetrici dal sole attraverso la scena. Impegnativo; ideale su GPU di fascia alta.
video-perf-overlay-help = Mostra o nascondi l'overlay delle prestazioni.
video-point-lights-help = Scegli la qualità delle luci puntiformi extra.
video-particle-quality-help = Scegli la densità degli effetti particellari.
video-max-fps-help = Imposta un limite opzionale di FPS.
video-apply-help = Applica le modifiche video.
replays-enabled-help = Registra in memoria i combattimenti Versus e Quick Play idonei. Disattivalo sui sistemi con poca memoria.
replays-auto-save-help = Salva automaticamente i Replay nella schermata dei risultati invece di aspettare una pressione manuale di salvataggio.
replays-compression-help = Comprimi i file Replay durante il salvataggio. Disattivalo solo se la compressione rallenta i salvataggi.
netplay-copy-lobby-help = Copia il codice lobby corrente quando è disponibile.
netplay-virtual-couch-help = Apri l'hosting della lobby, la partecipazione tramite codice lobby e le opzioni di invito avanzate.
netplay-settings-menu-help = Configura rollback, buffer di input e comportamento dell'indirizzo LAN.
netplay-back-help = Torna al menu principale senza scollegare una sessione stabilita.
arcade-cpu-level-help = Livello di difficoltà CPU per gli avversari (0 il più facile, 6 il più difficile).
arcade-stocks-help = Stock per combattimento.
arcade-retries-help = Ritentativi prima che una sconfitta termini la run.
arcade-battles-help = Numero totale di combattimenti nella run.
arcade-start-help = Inizia la run una volta che ogni giocatore unito è pronto.
controls-remap-page-help = Riassegna la navigazione del menu, la console, lo schermo intero e i tasti della modalità allenamento.
controls-remap-reset-binding-help = Ripristina {$action} alla sua assegnazione predefinita.
controls-remap-reset-all-help = Ripristina ogni scorciatoia da tastiera al valore predefinito integrato.
replay-browser-help = Browser Replay.
replay-offline-only-help = I Replay sono disponibili solo offline perché si caricano dal file system locale.
replay-refresh-help = Riesamina i file Replay salvati da {$dir}.
replay-entry-help = {$players} su {$stage}; {$duration} ({$truncated}); {$result}; {$version}; {$compression}.
replay-unreadable-help = Impossibile leggere il Replay: {$error}
replay-actions-watch-help = Riproduci il Replay salvato dall'inizio. Jump In è disponibile durante la riproduzione del Replay.
replay-actions-back-help = Torna all'elenco dei Replay.
replay-load-help = Carica i file Replay salvati dalla cartella Replay.
replay-prev-help = Mostra i Replay più recenti.
replay-next-help = Mostra i Replay più vecchi.
replay-settings-help = Opzioni di registrazione, salvataggio automatico e compressione dei Replay.
audio-help = Regola le impostazioni audio.
video-help = Regola le impostazioni video.
replays-help = I Replay sono abilitati per impostazione predefinita e limitati a 16 minuti per combattimento.
native-adapter-help-text = Native Adapter offre il polling diretto a 4 porte. La modalità PC è più semplice ma usa le mappature dei controller SDL.
shortcut-menu-up-help = Sposta la selezione in su nei menu.
shortcut-menu-down-help = Sposta la selezione in giù nei menu.
shortcut-menu-left-help = Sposta la selezione a sinistra o diminuisci un valore.
shortcut-menu-right-help = Sposta la selezione a destra o aumenta un valore.
shortcut-menu-confirm-help = Attiva l'elemento evidenziato.
shortcut-menu-next-help = Passa al successivo elemento focalizzabile. Tieni premuto Shift per tornare indietro.
shortcut-menu-page-up-help = Salta in alto di diversi elementi.
shortcut-menu-page-down-help = Salta in basso di diversi elementi.
shortcut-menu-home-help = Metti a fuoco il primo elemento dell'elenco.
shortcut-menu-end-help = Metti a fuoco l'ultimo elemento dell'elenco.
shortcut-console-help = Apri la console di debug nel gioco.
shortcut-chat-help = Apri il prompt della chat (comando say).
shortcut-fullscreen-help = Attiva/disattiva schermo intero. Funziona anche Alt+Invio.
shortcut-frame-step-help = Avanza di un frame mentre è congelato. Richiede la modalità debug.
shortcut-freeze-help = Metti in pausa o riprendi TAS. Richiede la modalità debug.
shortcut-save-state-help = Crea uno snapshot dello stato corrente in modalità allenamento.
shortcut-restore-state-help = Ripristina l'ultimo snapshot della modalità allenamento.

Start = Start
Color = Colore
Leave = Esci
Not-Joined = Non entrato
Hold-Start = Tieni premuto Start
arcade-join-help = Entra in questa run arcade.
arcade-color-help = Randomizza il colore di questo giocatore.
arcade-palette-help = Seleziona la palette di questo giocatore.
arcade-leave-help = Lascia questa run arcade.
arcade-setting-cpu-level = Lv CPU
arcade-setting-stocks = Stocks
arcade-setting-starting-stocks = Stock iniziali
arcade-setting-retries = Riprove
arcade-setting-battles = Battaglie
arcade-setting-value = {$label}: {$value}
arcade-palette = Palette {$number}
arcade-select-title = ARCADE
arcade-select-infinite-title = BATTAGLIE INFINITE
arcade-select-instructions = Conferma entra · scegli personaggio e palette per ogni giocatore · Indietro esci
arcade-between-cleared-battle = Battaglia {$current} / {$total} completata
arcade-between-next = Conferma: avanti
arcade-between-retries-remaining =
    Sconfitta — { $count ->
        [one] resta {$count} riprova
       *[other] restano {$count} riprove
    }
arcade-between-retry-actions = Conferma: riprova · Indietro: abbandona
arcade-between-results = Conferma: risultati
arcade-between-complete = Arcade completata!
arcade-results-infinite-title = Battaglie infinite
arcade-results-infinite-subtitle = Punteggio {$score} in {$time}
arcade-results-cleared-title = Arcade completata
arcade-results-cleared-subtitle = Completate tutte le {$battles} battaglie.
arcade-results-abandoned-title = Run abbandonata
arcade-results-abandoned-subtitle = Abbandonata dopo la battaglia {$current} di {$total}.
arcade-results-gameover-title = Fine partita
arcade-results-gameover-subtitle = Raggiunta la battaglia {$current} di {$total}.
replay-battle-controls = Replay: Salva aggiunge un marcatore · Start pausa · croce direzionale naviga · Presa cambia velocità · tieni Conferma/Attacco per avanzare · Indietro esce
replay-battle-status = {$current} / {$total} · {$speed}x
replay-marker-default = Marcatore {$number}
replay-marker-added = {$label} aggiunto a {$time}
replay-marker-selected = {$label} · {$time}
replay-marker-none = Nessun marcatore replay
replay-marker-save-unavailable = Salvataggio marcatori replay non disponibile
replay-speed-changed = Velocità di riproduzione: {$speed}x
replay-export-button = Esporta pacchetto replay
replay-export-help = Crea un pacchetto locale con questo replay e i marcatori. Non viene caricato nulla.
replay-exporting = Esportazione pacchetto replay...
replay-exported = {$name} esportato
replay-export-failed = Esportazione non riuscita: {$error}
results-controller-port = Controller P{$port}
results-controller-id = Controller {$id}
results-disconnected-slot = Slot disconnesso
results-remote-player = Giocatore remoto
results-replay-capture = Cattura replay
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = Slot {$index}: {$name}
results-row-kos = KOs
results-row-falls = Cadute
results-row-sds = Auto-KO
results-row-damage-given = Danno inflitto
results-row-damage-taken = Danno subito
results-row-blocked = Parato
results-row-parries = Parate
results-row-power-shields = Scudi perfetti
results-row-lag-cancels = Lag cancel
results-row-kb-given = KB inflitto
results-row-kb-taken = KB subito
results-row-kb-absorbed = KB assorbito
results-row-ledge-grabs = Prese al bordo
results-row-ledge-time = Tempo al bordo
results-row-crouch-cancels = Crouch cancel
results-row-velocity-cancels = Velocity cancel
controls-action-ui-save-replay = Salva replay
controls-device-unknown = Sconosciuto
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = Scorciatoie da tastiera
shortcut-unbound = (non assegnato)
shortcut-category-menu = Navigazione menu
shortcut-category-general = Generale
shortcut-category-debug = Debug (TAS)
shortcut-category-training = Modalità allenamento
shortcut-label-menu-up = Sposta su
shortcut-label-menu-down = Sposta giù
shortcut-label-menu-left = Sposta a sinistra
shortcut-label-menu-right = Sposta a destra
shortcut-label-menu-confirm = Conferma
shortcut-label-menu-next = Campo successivo
shortcut-label-menu-page-up = Pagina su
shortcut-label-menu-page-down = Pagina giù
shortcut-label-menu-home = Primo elemento
shortcut-label-menu-end = Ultimo elemento
shortcut-label-console = Apri console
shortcut-label-chat = Chat
shortcut-label-fullscreen = Attiva/disattiva schermo intero
shortcut-label-frame-step = Avanza di un frame (TAS)
shortcut-label-freeze = Congela (TAS)
shortcut-label-save-state = Salva stato
shortcut-label-restore-state = Ripristina stato
shortcut-bind = Assegna
shortcut-add = Aggiungi
shortcut-replace = Sostituisci
shortcut-remove-key = Rimuovi {$key}
shortcut-capture-bind-title = Assegna tasto: {$action}
shortcut-capture-replace-title = Sostituisci tasto: {$action}
shortcut-capture-hint = Premi il tasto da assegnare o Esc per annullare.
shortcut-conflict-detail = {$key} è già assegnato a {$action}. Riassegnare?
shortcut-conflict-hint = Premi Invio per riassegnare, Esc per annullare.
shortcut-min-binding = {$action} deve mantenere almeno un'assegnazione.
shortcut-overlap-menu = Sovrapposizione menu: {$keys} naviga anche i menu. L'assegnazione del controller ha priorità nei menu.
shortcut-overlap-actions = Sovrapposizione scorciatoie: {$overlaps}. L'assegnazione del controller ha priorità durante il gioco.
shortcut-reset-all = Reimposta tutte le scorciatoie ai valori predefiniti
character-select-help = Seleziona un personaggio.

matchmaking-service-fallback-stun = STUN di fallback
matchmaking-status-preparing-binding = Preparazione di Quick Play... Apertura del socket netplay.
matchmaking-status-preparing-primary-stun = Preparazione di Quick Play... Controllo del percorso UDP pubblico tramite {$service}.
matchmaking-status-preparing-fallback-stun = Preparazione di Quick Play... Lo STUN principale non ha risposto, nuovo tentativo tramite {$service}.
matchmaking-status-preparing-queueing = Preparazione di Quick Play... Ingresso in coda.
matchmaking-status-connecting-tunneling = Partita trovata. Apertura della route peer-to-peer...
matchmaking-status-connecting-peer = Route peer-to-peer aperta. Completamento dell'handshake di connessione...
matchmaking-status-waiting-peer = Route aperta. In attesa dell'altro giocatore...
matchmaking-status-starting-battle = Connessione pronta. Avvio della partita...
netplay-experimental-note = Sperimentale — potrebbe essere instabile
netplay-detail-connecting-peer = Route peer-to-peer aperta. Completamento dell'handshake di connessione...
netplay-detail-waiting-for-peer = Route aperta. In attesa che l'altro giocatore completi la connessione...
netplay-detail-starting-battle = Connessione pronta. Avvio della partita...
netplay-detail-matchmaking-binding = Preparazione di Quick Play. Apertura del socket netplay...
netplay-detail-matchmaking-primary-stun = Controllo del percorso UDP pubblico tramite {$service}...
netplay-detail-matchmaking-fallback-stun = Lo STUN principale non ha risposto. Provo {$service}...
netplay-detail-matchmaking-queueing = Ingresso nella coda di matchmaking...
netplay-detail-matchmaking-wait = In coda da {$wait}s. Giocatori in attesa: {$players}.
replay-stage-fallback = Scenario {$number}
replay-unknown-error = errore sconosciuto
replay-title = REPLAY
replays-title = REPLAY
replay-watch-button = Guarda replay
replay-settings-button = Impostazioni replay
replay-refresh-button = Aggiorna elenco
replay-refreshing = Aggiornamento...
replay-prev-button = Pagina precedente
replay-prev-disabled = Pagina precedente -
replay-next-button = Pagina successiva
replay-next-disabled = Pagina successiva -
replay-browser-scanning = Scansione della cartella replay...
replay-browser-scan-failed = Scansione dei replay non riuscita.
replay-browser-empty = 0 replay trovati.
replay-browser-page =
    {$first}-{$last} di {$count} { $count ->
        [one] replay
       *[other] replay
    } · Pagina {$page}/{$pages}
replay-browser-loading = Caricamento replay...
replay-browser-scanning-files = Scansione dei file replay salvati.
replay-browser-scan-failed-detail = Scansione dei replay non riuscita: {$error}
replay-browser-empty-slot = Nessun replay in questo slot.
replay-browser-empty-list = Nessun replay salvato trovato.
replay-browser-root-help = I file replay vengono caricati ricorsivamente dalla cartella locale dei replay.
replay-title-unreadable = Illeggibile: {$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = Nessun risultato
replay-result-none-winner = Vincitore: nessuno
replay-result-quit = Uscita anticipata
replay-result-tie = Pareggio
replay-result-winner = Vincitore: {$winner}
replay-action-participants = Partecipanti: {$players}
replay-action-duration = Durata: {$duration}
replay-action-duration-truncated = Durata: {$duration} (troncata)
replay-action-result = Risultato: {$result}
replay-action-stage = Scenario: {$stage}
replay-action-mode = Modalità: {$mode}
replay-action-version = Versione: {$version}
replay-action-file = File: {$compression}; Troncato: {$truncated}
replay-compression-compressed = Compresso
replay-compression-uncompressed = Non compresso
replay-truncated-yes = Sì
replay-truncated-no = No

# Social e lista CPU in versus
press-any-button-or-key = Premi un pulsante o tasto qualsiasi
social-title = AMICI E INVITI
social-steam = Steam
social-steam-help = Mostra la tua lobby su Steam e lascia che gli amici si uniscano dalla loro lista amici.
social-discord = Discord
social-discord-help = Mostra la tua lobby su Discord e lascia che gli amici chiedano di unirsi.
social-info = Disattivato per impostazione predefinita. Quando attivata, l’integrazione carica l’SDK della piattaforma e condivide il codice della lobby affinché gli amici possano unirsi. Le connessioni usano comunque il netplay di Antistatic.
social-summary = Presenza avanzata e inviti di Steam e Discord.
social-settings-help = Presenza avanzata e inviti di Steam e Discord. Disattivato per impostazione predefinita.
versus-add-cpu = Aggiungi CPU
versus-cpu-page-prev = Prec.
versus-cpu-page-next = Succ.
versus-cpu-page-help = Cambia la pagina CPU visibile.
versus-no-cpus-added = Nessuna CPU aggiunta
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# Calibrazione controller
controller-calibration-title = CALIBRAZIONE CONTROLLER
controller-calibration-open = Calibra controller
controller-calibration-open-help = Controlla e calibra il controller locale selezionato.
controller-calibration-online-blocked = La calibrazione non è disponibile durante il gioco online.
controller-calibration-no-local-controller = Collega e seleziona un controller locale da calibrare.
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = senza tag
controller-calibration-capability-no-axes = Questo controller non segnala assi calibrabili.
controller-calibration-capability-native-origin = L'origine nativa consente la calibrazione automatica.
controller-calibration-capability-absolute-no-automatic = Dati assoluti disponibili; calibrazione automatica non disponibile.
controller-calibration-capability-sdl-normalized = Input SDL normalizzato; solo calibrazione manuale.
controller-calibration-suspicious-origin-warning = Uno o più assi con origine automatica sono stati ignorati. Controlla i dettagli di riserva qui sotto.
controller-calibration-invalid-saved-warning = Calibrazione salvata ignorata: {$reason}
controller-calibration-invalid-shaping-warning = Impostazioni stick salvate ignorate: {$reason}
controller-calibration-status-policy-preview = anteprima automatica
controller-calibration-status-manual-preview = anteprima manuale
controller-calibration-status-modified = modificata
controller-calibration-status-current = attuale
controller-calibration-status-policy = automatica
controller-calibration-status-manual = manuale
controller-calibration-status-not-saved = non salvata
controller-calibration-status-saved = salvata
controller-calibration-status-active-differs = La calibrazione attiva differisce da quella salvata
controller-calibration-draft-status = {$intent} · bozza {$draft} · attiva {$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = Calibrazione automatica: {$state}
controller-calibration-automatic-unavailable = non disponibile
controller-calibration-automatic-on = attiva
controller-calibration-automatic-off = disattiva
controller-calibration-automatic-policy-native-help = Attiva/disattiva la calibrazione automatica dell'origine GameCube.
controller-calibration-automatic-policy-unavailable-help = La calibrazione automatica non è disponibile per questa sorgente.
controller-calibration-axis-left-x = Stick sinistro X
controller-calibration-axis-left-y = Stick sinistro Y
controller-calibration-axis-right-x = Stick destro X
controller-calibration-axis-right-y = Stick destro Y
controller-calibration-axis-left-trigger = Grilletto sinistro
controller-calibration-axis-right-trigger = Grilletto destro
controller-calibration-field-minimum = minimo
controller-calibration-field-center = centro
controller-calibration-field-maximum = massimo
controller-calibration-field-released = rilasciato
controller-calibration-field-pressed = premuto
controller-calibration-value-na = N/D
controller-calibration-unit-gamecube-directed = byte diretto GameCube
controller-calibration-unit-sdl-normalized = normalizzato SDL
controller-calibration-unit-canonical-normalized = normalizzato
controller-calibration-unit-gamecube-protocol-byte = byte protocollo GameCube
controller-calibration-axis-values-normalized = {$axis} · {$unit} · sorgente {$source} · corretto {$corrected} · anteprima {$preview} · gioco {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} assoluto {$absolute}, origine {$origin} · {$sourceUnit} sorgente {$source} · {$normalizedUnit} corretto {$corrected}, anteprima {$preview}, gioco {$gameplay}
controller-calibration-axis-statistics = {$samples} campioni · min {$minimum} · max {$maximum} · picco {$peak} · jitter {$jitter} · {$unit}
controller-calibration-reported-buttons = Premuti: {$buttons}
controller-calibration-reported-buttons-none = nessuno
controller-calibration-capture-status-ready = pronta
controller-calibration-capture-status-waiting-release = rilascia tutti i comandi
controller-calibration-capture-status-capturing = acquisizione
controller-calibration-capture-status-captured = acquisita
controller-calibration-capture-status-invalid = acquisizione non valida
controller-calibration-capture-neutral = Acquisisci neutro
controller-calibration-capture-range = Acquisisci corsa completa
controller-calibration-capture-help = Rilascia tutti i comandi quando richiesto, poi esegui l'azione.
controller-calibration-stick-movement = Stick di movimento
controller-calibration-stick-right = Stick destro / C
controller-calibration-shaping-deadzone = zona morta
controller-calibration-shaping-cardinal-snap = aggancio cardinale
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting}: {$value}{$unit} · {$step}
controller-calibration-shaping-help = Sinistra/Destra o i lati della riga per regolare · Conferma o il centro per alternare fine/ampio.
controller-calibration-adjust-value = {$axis} {$field}: {$value} {$unit} · {$step}
controller-calibration-step-fine = fine
controller-calibration-step-coarse = ampio
controller-calibration-adjust-help = Sinistra/Destra o i lati della riga per regolare · Conferma o il centro per alternare fine/ampio. Le unità fisiche dipendono dalla sorgente.
controller-calibration-apply-current-connection = Applica alla connessione attuale
controller-calibration-save-to-tag = Salva nel tag controller
controller-calibration-save-to-tag-target = Salva in {$tag} ({$layout})
controller-calibration-save-to-tag-no-tag = Salva nel tag (tag richiesto)
controller-calibration-reset-draft-active = Ripristina bozza all'attiva
controller-calibration-reset-draft-saved = Ripristina bozza alla salvata
controller-calibration-reset-draft-layout-defaults = Ripristina bozza ai predefiniti layout
controller-calibration-reset-session = Ripristina sessione connessione
controller-calibration-delete-saved = Elimina calibrazione salvata
controller-calibration-delete-saved-confirm = Conferma: elimina calibrazione
controller-calibration-copy-diagnostic = Copia diagnostica
controller-calibration-action-help = Conferma per eseguire l'azione.
controller-calibration-applied = Calibrazione applicata alla connessione attuale.
controller-calibration-save-tag-required = Per salvare serve un tag controller valido.
controller-calibration-saved = Calibrazione salvata in {$tag} ({$layout}).
controller-calibration-no-saved-calibration = Nessuna calibrazione salvata per questo controller.
controller-calibration-delete-saved-complete = Calibrazione salvata eliminata.
controller-calibration-copy-diagnostic-complete = Diagnostica calibrazione copiata.
controller-calibration-local-controllers = Altri controller locali
controller-calibration-switch-controller = Cambia controller
controller-calibration-switch-controller-name = Passa a {$controller}
controller-calibration-switch-decision = {$controller} · Sinistra applica · Destra {$save} · Conferma scarta
controller-calibration-switch-save-available = salva
controller-calibration-switch-save-unavailable = salvataggio non disponibile
controller-calibration-switch-decision-help = Non salvata: Sinistra applica, Destra salva, Conferma scarta e cambia.
controller-calibration-back = Indietro
controller-calibration-back-help = Torna a Comandi. Prima annulla un'acquisizione attiva.
controller-calibration-back-discard-confirm = Conferma: scarta bozza e torna
controller-calibration-disconnected-draft-discarded = Controller disconnesso; bozza calibrazione scartata.

# PhobGCC
controller-calibration-phob-board-unconfirmed = consiglio non confermato
controller-calibration-phob-board-v1 = Seleziona PhobGCC v1
controller-calibration-phob-board-v1-value = PhobGCC v1
controller-calibration-phob-board-v2 = Seleziona PhobGCC v2
controller-calibration-phob-board-v2-value = PhobGCC v2
controller-calibration-phob-calibrate-c-stick = Calibrare C-stick: A+X+Y+R
controller-calibration-phob-calibrate-left = Calibrare lo stick principale: A+X+Y+L
controller-calibration-phob-calibration-complete = Completa (solo tastiera/mouse)
controller-calibration-phob-calibration-confirm = Conferma: avvia la calibrazione del firmware
controller-calibration-phob-calibration-help = Avvia un flusso di lavoro del firmware che deve essere completato sul controller.
controller-calibration-phob-calibration-no-cancel = Il controller non può annullare o completare questa procedura. Terminala, poi seleziona Completa con tastiera/mouse. Se si blocca, scollega e ricollega il controller.
controller-calibration-phob-calibration-phases = Segui l'indicazione dell'altro stick in ogni passo di centro, bordo e tacca. Completa entrambe le fasi firmware prima di Completa.
controller-calibration-phob-enter-configure = Inserisci Configure Mode
controller-calibration-phob-enter-configure-instruction = Sul controller fisico, tieni premuto A+X+Y+Start finché entrambi gli stick non si trovano in alto a destra, quindi rilascia.
controller-calibration-phob-exit-safe-instruction = Sul controller fisico, premere A+X+Y+Start. Rilascia dopo la risposta più lunga in alto a destra.
controller-calibration-phob-host-correction-stale = Correzione Antistatic dopo la calibrazione firmware: attiva {$active}; salvata {$saved}. Controlla i valori predefiniti o ripeti l'acquisizione.
controller-calibration-phob-instruction-none = nessun comando in sospeso
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = modalità sconosciuta
controller-calibration-phob-open = Apri la Guida PhobGCC
controller-calibration-phob-open-guide-031 = Apri la guida ufficiale del firmware 0.31
controller-calibration-phob-open-help = Controlli guidati di sola lettura per un PhobGCC v1 o v2 confermato dall'utente.
controller-calibration-phob-open-phobvision-029-v2 = Apri la guida PhobVision 0.29 (equipaggiata solo con v2)
controller-calibration-phob-open-release-031 = Apri le note sulla versione del firmware 0.31
controller-calibration-phob-open-version-guide = Apri la guida per il firmware segnalato
controller-calibration-phob-origin-checks = Prima della calibrazione firmware, attiva gli stick con B fisico se necessario e controlla le origini indicate dall'adattatore.
controller-calibration-phob-query-c-settings = Leggi le impostazioni C-stick: R+Start
controller-calibration-phob-query-main-settings = Leggi le impostazioni dello stick principale: L+Start
controller-calibration-phob-query-trigger-settings = Leggi le impostazioni del trigger: L+R+Z
controller-calibration-phob-query-version = Leggi la versione del firmware: A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = La diagnostica grezza è attiva. I valori sono coordinate di visualizzazione post-firmware ricavate dai normali rapporti del controller, non dati diretti dei sensori né output di gioco.
controller-calibration-phob-raw-disable = Disabilita output non elaborato: L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = Sul controller fisico, premi L+R+D-pad Down, attendi la risposta in alto a destra, quindi rilascia il tutto.
controller-calibration-phob-raw-enable = Abilita output grezzo: L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = Sul controller fisico, premi L+R+D-pad Up, attendi la risposta in alto a destra, quindi rilascia il tutto.
controller-calibration-phob-raw-values = post-firmware principale X {$leftX}, Y {$leftY}; C-stick X {$cX}, Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = valori grezzi non disponibili
controller-calibration-phob-remap-warning = I comandi usano i pulsanti fisici indicati sulla scocca nonostante le rimappature. Antistatic vede i pulsanti segnalati, che possono differire.
controller-calibration-phob-result-matched = La risposta in stile Phob corrispondeva
controller-calibration-phob-result-none = nessuna risposta ancora
controller-calibration-phob-result-unknown-custom = risposta sconosciuta o personalizzata
controller-calibration-phob-result-version-known = firmware {$version}
controller-calibration-phob-result-version-no-response = nessuna risposta del firmware; versione sconosciuta
controller-calibration-phob-return-safe = Ritorno a Safe Mode
controller-calibration-phob-safe-recovery = Per garantire Safe Mode, scollega e ricollega il controller. Poi riapri questa guida; lo stato rilevato si azzera alla disconnessione.
controller-calibration-phob-setting-c-response-x-raw = C-stick X byte di risposta
controller-calibration-phob-setting-c-response-y-raw = C-stick Byte di risposta Y
controller-calibration-phob-setting-c-snapback-x = snapback del C-stick X
controller-calibration-phob-setting-c-snapback-y = snapback del C-stick Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick forma d'onda X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick waveshaping X grezzo
controller-calibration-phob-setting-c-waveshaping-y = C-stick forma d'onda Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick forma d'onda Y grezza
controller-calibration-phob-setting-main-smoothing-x = livellamento dello stick principale X
controller-calibration-phob-setting-main-smoothing-y = livellamento della bacchetta principale Y
controller-calibration-phob-setting-main-snapback-x = snapback della levetta principale X
controller-calibration-phob-setting-main-snapback-y = snapback della levetta principale Y
controller-calibration-phob-setting-main-waveshaping-x = forma d'onda del bastone principale X
controller-calibration-phob-setting-main-waveshaping-x-raw = waveshaping del bastone principale X grezzo
controller-calibration-phob-setting-main-waveshaping-y = forma d'onda del bastone principale Y
controller-calibration-phob-setting-main-waveshaping-y-raw = forma d'onda del bastone principale Y grezzo
controller-calibration-phob-setting-row = {$setting}: {$value} {$unit}
controller-calibration-phob-setting-rows-none = nessuna impostazione decodificata
controller-calibration-phob-settings-c-stick-instruction = Sul controller fisico, tieni premuto R+Start per la lettura di due secondi, quindi rilascia.
controller-calibration-phob-settings-main-instruction = Sul controller fisico, tieni premuto L+Start per la lettura di due secondi, quindi rilascia.
controller-calibration-phob-settings-read-only = Queste letture non modificano le impostazioni del firmware. Utilizzare le istruzioni ufficiali per modifiche e ripristini.
controller-calibration-phob-settings-triggers-instruction = Sul controller fisico, tieni premuto L+R+Z per la lettura di due secondi, quindi rilascia.
controller-calibration-phob-setting-trigger-left-mode = modalità grilletto sinistro
controller-calibration-phob-setting-trigger-left-value = valore di trigger sinistro
controller-calibration-phob-setting-trigger-right-mode = modalità grilletto destro
controller-calibration-phob-setting-trigger-right-value = valore di trigger destro
controller-calibration-phob-setup-active = Phob Setup Mode attivo: il D-pad segnalato naviga e la A segnalata conferma.
controller-calibration-phob-setup-enter = Inserisci Phob Setup Mode
controller-calibration-phob-setup-exit = Esci da Phob Setup Mode
controller-calibration-phob-setup-exit-chord = Per uscire, tieni esattamente D-pad Giù+Sinistra segnalati + stick principale in alto a destra + C-stick in basso a destra per un secondo, poi rilascia. Disattivato durante la calibrazione firmware.
controller-calibration-phob-stale-state-current = attuale
controller-calibration-phob-stale-state-stale = stantio
controller-calibration-phob-status = Scheda: {$board} · Modalità: {$mode} · Risultato: {$result} · Passo: {$instruction} · {$raw} · Impostazioni: {$rows}
controller-calibration-phob-unit-protocol-byte = byte di protocollo
controller-calibration-phob-unit-setting-value = valore di impostazione
controller-calibration-phob-unit-trigger-byte = byte di attivazione
controller-calibration-phob-unofficial-warning = Guida PhobGCC non ufficiale e non affiliata. Conferma scheda e firmware; Antistatic non identifica l'hardware né scrive impostazioni.
controller-calibration-phob-version-instruction = In Configure Mode, premi il A+Z+D-pad Up fisico, mantieni la lettura per due secondi, quindi rilascia.
controller-calibration-mode-basic = Vista: BASE
controller-calibration-mode-advanced = Vista: AVANZATA
controller-calibration-mode-toggle-help = Passa tra controlli comuni e diagnostica dettagliata.
controller-calibration-origin-diagnostic-unavailable = La diagnostica automatica dell'origine non è disponibile per questa sorgente.
controller-calibration-origin-diagnostic = Origine stabile: {$phase} · {$reports} rapporti · {$stable}/6 applicati · {$fallback}/6 riserva · {$dropped} overflow
controller-calibration-origin-phase-collecting = raccolta
controller-calibration-origin-phase-complete = completa
controller-calibration-use-suggested-deadzones = Usa zone morte suggerite
controller-calibration-use-suggested-deadzones-help = Applica al profilo le zone morte misurate.
controller-calibration-section-stick-shaping = REGOLAZIONE STICK
controller-calibration-section-trigger-shaping = REGOLAZIONE GRILLETTI
controller-calibration-section-action-diagnostics = DIAGNOSTICA AZIONI
controller-calibration-section-physical-diagnostics = DIAGNOSTICA ASSI
controller-calibration-section-hardware-correction = CORREZIONE HARDWARE
controller-calibration-shaping-inner-deadzone = zona morta interna
controller-calibration-shaping-outer-deadzone = zona morta esterna
controller-calibration-snap-override-help = Attiva la regolazione del giocatore. Il minimo della modalità resta attivo.
controller-calibration-snap-override-state = Aggancio {$stick}: {$state} · minimo {$floor}° · effettivo {$effective}°
controller-calibration-override-enabled = attivo
controller-calibration-override-disabled = disattivo
controller-calibration-trigger-shaping-help = Sinistra/Destra o i lati della riga per regolare · Conferma o il centro per alternare fine/ampio.
controller-calibration-trigger-inner-deadzone = zona morta interna
controller-calibration-trigger-outer-deadzone = zona morta esterna
controller-calibration-trigger-response-curve = curva di risposta
controller-calibration-trigger-hard-press-threshold = soglia pressione forte
controller-calibration-trigger-shaping-value = {$trigger} {$setting}: {$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = Misura: rumore movimento {$movementNoise}, interna {$movementInner}, esterna {$movementOuter}, copertura {$movementCoverage}/16 · destro rumore {$rightNoise}, interna {$rightInner}, esterna {$rightOuter}, copertura {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = Grilletti: L rumore {$leftNoise}, interna {$leftInner}, esterna {$leftOuter} · R rumore {$rightNoise}, interna {$rightInner}, esterna {$rightOuter}
controller-calibration-stick-diagnostic = {$stick}: mappato {$mapped} · gioco {$gameplay} · {$zone} · agganciato {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger}: mappato {$mapped} · gioco {$gameplay} · {$zone} · forte {$hard}
controller-calibration-zone-inner-dead = zona morta interna
controller-calibration-zone-linear = intervallo attivo
controller-calibration-zone-outer-saturated = saturazione esterna
controller-calibration-state-yes = sì
controller-calibration-state-no = no
controller-calibration-hard-source-none = nessuna
controller-calibration-hard-source-digital-button = clic digitale
controller-calibration-hard-source-analog-threshold = soglia analogica
controller-calibration-help = Su/Giù per spostarsi · Sinistra/Destra o i lati della riga per regolare · Conferma o il centro per cambiare precisione · Indietro per tornare.
controller-calibration-tag-required-prerequisite = Aggiungi un tag giocatore in Comandi prima della calibrazione per abilitare Salva. Applica resta disponibile per questa connessione.
controller-calibration-status-draft-or-active-differs = La bozza o la calibrazione attiva differiscono da quella salvata
controller-calibration-capture-mode-neutral = Neutro
controller-calibration-capture-mode-range = Corsa completa
controller-calibration-capture-accept-pending = Accetta acquisizione {$mode}
controller-calibration-capture-accept-and-start = Accetta {$pending}, poi acquisisci {$next}
controller-calibration-capture-status-pending = acquisizione {$mode} in attesa di verifica
controller-calibration-legend-source = Predefinito del layout
controller-calibration-legend-corrected = Corretto
controller-calibration-legend-preview = Anteprima
controller-calibration-legend-gameplay = Gioco
controller-calibration-origin-fallback-detail = Riserva: {$axes}
controller-calibration-origin-fallback-axis = {$axis}: {$reason}
controller-calibration-origin-reason-insufficient-reports = rapporti validi insufficienti; rilascia i comandi e ricollega
controller-calibration-origin-reason-unstable = l'input si è mosso; rilascia i comandi e ricollega
controller-calibration-origin-reason-implausible = origine fuori dall'intervallo previsto; rilascia i comandi e ricollega
controller-calibration-origin-reason-unsafe-bounds = l'origine renderebbe la correzione rischiosa; acquisisci Neutro e Corsa completa
controller-calibration-phob-setup-suspended-raw = Phob Setup Mode è sospeso durante la diagnostica grezza. Disabilita l'output grezzo per riprendere.
controller-calibration-phob-result-version-custom = risposta firmware personalizzata: X {$x}, Y {$y}
controller-calibration-phob-result-unknown = risposta non riconosciuta
controller-calibration-phob-raw-mode-off = modalità grezza disattivata

# Privacy, segnalazioni e commenti
privacy-title = Privacy
privacy-settings-help = Gestisci rete, segnalazioni di arresto, metriche anonime e commenti.
privacy-networking = Accesso alla rete
privacy-networking-help = Interruttore generale per gioco online e servizi Antistatic. Disattivandolo, le sessioni online vengono interrotte.
privacy-crash-reporting = Segnalazioni di arresto: {$value}
privacy-crash-reporting-help = Scegli se Antistatic deve chiedere prima di inviare diagnostica anonima sugli arresti.
privacy-crash-ask = Chiedi ogni volta
privacy-crash-never = Non inviare mai
privacy-crash-always = Invia sempre
privacy-gameplay-metrics = Metriche di gioco anonime
privacy-gameplay-metrics-help = Acconsenti all'invio di dati generici come modalità, personaggi, durata ed esito.
privacy-performance-metrics = Metriche anonime sulle prestazioni
privacy-performance-metrics-help = Acconsenti all'invio di dati generici su hardware e tempi dei fotogrammi per migliorare le prestazioni.
privacy-feedback-open = Invia commenti
privacy-feedback-open-help = Invia una segnalazione di errore o altri commenti al team di Antistatic.
privacy-policy-open = Visualizza l'informativa sulla privacy
privacy-policy-open-help = Leggi l'informativa ufficiale sulla privacy di Antistatic.
privacy-policy-title = Informativa sulla privacy
privacy-policy-help = Questa informativa spiega come Antistatic gestisce l'accesso alla rete, le segnalazioni di arresto, le metriche facoltative e i commenti.
privacy-crash-send-pending = Invia segnalazione in sospeso
privacy-crash-send-pending-help = Invia la segnalazione di arresto in attesa del tuo consenso.
privacy-crash-discard-pending = Elimina segnalazione in sospeso
privacy-crash-discard-pending-help = Elimina definitivamente la segnalazione senza inviarla.
privacy-summary = La rete è attiva per impostazione predefinita. Le segnalazioni di arresto richiedono una scelta; le metriche anonime restano disattivate senza consenso.
privacy-netplay-disabled = Gioco in rete disattivato
privacy-netplay-disabled-help = Attiva Accesso alla rete in Privacy per giocare in rete.
privacy-crash-prompt-title = Segnalazione di arresto
privacy-crash-prompt-body = Antistatic ha trovato una segnalazione di arresto in sospeso. Vuoi inviare dati diagnostici anonimi per migliorare la stabilità?
privacy-crash-prompt-send = Invia segnalazione
privacy-crash-prompt-later = Chiedi più tardi
privacy-crash-prompt-never = Non inviare segnalazioni di arresto
privacy-crash-prompt-summary = Invia questa segnalazione, decidi più tardi o disattiva le segnalazioni di arresto.
privacy-report-sending = Invio in corso...
privacy-report-failed = Invio non riuscito. Controlla la rete e riprova.
privacy-crash-sent = Segnalazione di arresto inviata
privacy-crash-discarded = Segnalazione di arresto eliminata
privacy-feedback-title = Commenti
privacy-feedback-category = Categoria: {$value}
privacy-feedback-category-help = Scegli il tipo di messaggio da inviare.
privacy-feedback-category-bug = Errore
privacy-feedback-category-feedback = Commento
privacy-feedback-category-other = Altro
privacy-feedback-subject = Oggetto
privacy-feedback-subject-help = Inserisci un breve riepilogo.
privacy-feedback-subject-placeholder = Breve riepilogo
privacy-feedback-body = Messaggio
privacy-feedback-body-help = Descrivi il problema o il suggerimento. Non inserire informazioni personali.
privacy-feedback-body-placeholder = Cosa vuoi comunicarci?
privacy-feedback-submit = Invia commenti
privacy-feedback-submit-help = Invia questo messaggio al team di Antistatic.
privacy-feedback-warning = Non inserire informazioni personali, password o dati privati degli account.
privacy-feedback-help = Compila oggetto e messaggio, quindi invia i commenti.
privacy-feedback-required = Inserisci sia l'oggetto sia il messaggio.
privacy-feedback-sent = Commenti inviati. ID segnalazione: {$id}
