hello-world = こんにちは世界！ { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = ケイ素
Iron = 鉄
Xenon = キセノン
Helium = ヘリウム
Carbon = 炭素
Rhodium = ロジウム

Sandbag = 土嚢

Ruins = 廃
Transistor = トランジスタ
Eroded = 侵食
Scales = 秤
Crossing = 交差点
Longboat = ロングボート
Boombox = ラジカセ
Fountain = 噴水
Great-White = グレートホワイト
Plane = 平面
Satellite = 衛星
Divided = 分割された
Pillars = 柱
Debug = デバッグ

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = バニラ
Physics = 物理
color-preset-random = ランダム
color-preset-red = 赤
color-preset-orange = オレンジ
color-preset-gold = 金
color-preset-green = 緑
color-preset-blue = 青
color-preset-purple = 紫
color-preset-pink = ピンク
color-preset-white = 白
versus-color-preset-help = 色の系統を選びます。選ぶたびに小さなランダム変化が加わります。チームモードでは無効です。

# Navigation
Back = 戻る
Exit = 終了する
Save = セーブ
Cancel = キャンセル
Close-Symbol = X

Modify = 変更する
Reset = リセットする

# Main Menu
Versus = 対戦
Training = トレーニング
Courses = コース
TRAINING = トレーニング
COURSES = コース
battle-results = バトル結果
Settings = 設定
Controls = 操作方法
Discord = Discord {"\u29C9"}
Guide = ガイド {"\u29C9"}

# Settings Menu
SETTINGS = 設定
Audio = オーディオ
Video = ビデオクオリティ
accessibility-title = アクセシビリティ
settings-accessibility-help = 動き、ヒット演出、メニュー音、フォーカス表示を調整します。
accessibility-reduced-motion = 動きを減らす
accessibility-reduced-motion-help = メニュー背景のアニメーションとヒット時の視覚的な揺れを止めます。
accessibility-hit-flash = ヒットフラッシュ：{$value}
accessibility-hit-flash-help = キャラクターのヒットフラッシュの明るさを調整します。
accessibility-screen-shake = ヒット時の揺れ：{$value}
accessibility-screen-shake-help = ヒット時のキャラクターとHUDの視覚的な揺れを調整します。
accessibility-menu-sound = メニュー音を強調
accessibility-menu-sound-help = 移動音と決定音を大きくします。
accessibility-high-contrast-focus = 高コントラストフォーカス
accessibility-high-contrast-focus-help = 選択中のメニュー項目に明るい二重枠を追加します。
accessibility-help = アクセシビリティと表示の設定を調整します。
first-run-title = Antistaticへようこそ
first-run-intro = 最初に遊ぶ項目を選んでください。操作とアクセシビリティはメインメニューからいつでも変更できます。
first-run-versus = ローカル対戦
first-run-versus-help = このデバイスを共有するプレイヤーの対戦を設定します。
first-run-controls = 操作設定
first-run-controls-help = 入力の確認、割り当て変更、調整を行います。
first-run-training = トレーニング
first-run-training-help = トレーニング機能とターゲットを使って自由に練習します。
first-run-courses = コース
first-run-courses-help = ガイド付きレッスンで移動、攻撃、防御、復帰を学びます。
first-run-skip = メインメニューへ（スキップ）
first-run-skip-help = モードを開かずに、この初回案内を完了します。
first-run-help = 最初に遊ぶ項目を選んでください。どの項目でも初回案内は完了します。
Windowed = ウィンドウモード
Fullscreen = フルスクリーン

main = メインメニュー
versus = 対戦
training = トレーニング
start-mode = 開始：{ TRANSLATE($value) }

# Audio Menu
AUDIO = オーディオ

Play-Audio = オーディオを再生する
Play-Music = 音楽を再生

Audio-volume = ボリューム：{$value}
SFX-volume = エフェクト：{$value}
Music-volume = 音楽：{$value}
UI-volume = UI：{$value}
Voice-volume = 音声：{$value}

# Video Menu
VIDEO = ビデオ品質
Quick-Setup = クイック設定
Display = ディスプレイ
Quality = 品質
Effects = エフェクト
Apply-Changes = 変更を適用

graphics-preset-low = グラフィック：低
graphics-preset-medium = グラフィック：中
graphics-preset-high = グラフィック：高
graphics-preset-max = グラフィック：最大
graphics-preset-custom = グラフィック：カスタム

vsync-off = 垂直同期：オフ
vsync-on = 垂直同期：オン
vsync-adaptive = 垂直同期：適応

shadow-off = 影：オフ
shadow-low = 影：低
shadow-highest = 影：最高

ssao-off = SSAO：オフ
ssao-on = SSAO：オン
ssao-full = SSAO：フル

aa-off = アンチエイリアス：オフ
aa-fxaa = アンチエイリアス：FXAA
aa-fxaa-high = アンチエイリアス：高品質 FXAA

bloom-off = Bloom：オフ
bloom-on = Bloom：オン
reflections-off = 反射：オフ
reflections-on = 反射：オン
reflections-low = 反射：低
reflections-high = 反射：高
godrays-off = 光芒：オフ
godrays-on = 光芒：オン

perf-overlay-off = パフォーマンス表示：オフ
perf-overlay-on = パフォーマンス表示：オン


point-lights-off = ポイントライト：オフ
point-lights-on = ポイントライト：オン

particles-low = パーティクル：低
particles-medium = パーティクル：中
particles-full = パーティクル：高


max-fps-off = 最大FPS：オフ
max-fps-30 = 最大FPS：30
max-fps-60 = 最大FPS：60
max-fps-120 = 最大FPS：120
max-fps-144 = 最大FPS：144

# Controls Menu
CONTROLS = 操作方法

controls-title = 操作方法
controls-section-controllers = コントローラー
controls-section-mappings = マッピング
controls-set-tag = タグを設定
controls-edit-bindings = ボタン設定を編集
controls-tag-untagged = (タグなし)
controls-tag-title = プレイヤータグ
controls-tag-prompt = P{$port} ({$layout})。タグは1-24文字の英数字、「-」、「_」が使用できます。空白にするとクリアされます。
controls-tag-confirm = 確定
controls-tag-clear = クリア
controls-tag-cancel = キャンセル
controls-tag-select-title = タグを選択
controls-tag-filter-empty = 入力して保存済みタグを絞り込み
controls-tag-filter-value = フィルター: {$filter}
controls-tag-summary-empty = 保存済みタグ: {$total}件。入力して絞り込むか、新しいタグを作成します。
controls-tag-summary-filter = 保存済みタグ{$total}件中{$visible}件を表示。完全一致は保存済み設定を使用します。
controls-tag-defaults-suffix = このコントローラーの初期設定
controls-tag-create-new = 新しいタグを作成
controls-tag-use-existing = 既存のタグ「{$tag}」を使用
controls-tag-create = 「{$tag}」を作成
controls-tag-reserved = 「{$tag}」は予約されています
controls-tag-netplay-blocked = ネットプレイ中はタグを変更できません
controls-tag-no-controller = ローカルコントローラーが選択されていません
controls-tag-no-layout = 選択したコントローラーにレイアウトがありません
controls-tag-filter-help = 入力してタグを絞り込み。ESCでクリアまたは終了
controls-tag-no-saved = 保存済みタグはまだありません
controls-tag-no-matches = 一致するタグがありません
controls-tag-invalid = 無効なタグです (1-24文字、英数字/-/_。「default」は予約済み)
controls-profile-help-untagged = ボタン設定は共有のタグなしプロファイルに保存されます。タップジャンプ初期値の保存にのみタグが必要です。
controls-profile-help-tagged = ボタン設定とタップジャンプ初期値は、このタグとコントローラー種類に保存されます。
controls-choose-existing-tag = 既存のタグを選択
controls-create-tag = タグを作成
controls-rename-create-tag = タグを変更/作成
controls-edit-set-tag-first = ボタン設定を編集 (先にタグを設定)
controls-edit-controls = ボタン設定を編集
controls-tap-jump-default = タップジャンプ初期値: {$state}
controls-state-on = ON
controls-state-off = OFF
controls-netplay-blocked = ネットプレイ中はボタン設定を変更できません
controls-no-local-controllers = 有効なコントローラーがありません。ゲーム操作キーまたはコントローラーのボタンを押して接続してください。
controls-no-layout = コントローラーにレイアウトがありません
controls-set-tag-before-editing = ボタン設定を編集する前にタグを設定してください
controls-no-mapping = このコントローラーで利用できるマッピングがありません
controls-set-tag-before-tap-jump = タップジャンプ初期値を保存するにはタグを設定してください
controls-connected-controllers = 接続中のコントローラー
controls-remap-add-key = + 割り当てを追加 (キーを押す)
controls-remap-find-input = 割り当てを検索 (入力を押す)
controls-remap-capture-key-title = キーを押してください
controls-remap-capture-input-title = 入力してください
controls-remap-capture-key-help = 次に押したキーが新しい割り当てとして追加されます。
controls-remap-capture-input-help = 次に押したボタンまたはスティックが編集対象になります。
controls-remap-capture-cancel = ESCでキャンセル
controls-default-save-blocked = 初期設定は上書きできません。先にタグを設定してください
controls-default-reset-blocked = このメニューから初期設定をリセットすることはできません
controls-tag-filter-entry-help = 保存されたコントローラータグを絞り込むには入力してください。ゲームパッドでは十字キーを使えます。
controls-tag-filter-label = フィルター
controls-tag-preconfigured = 事前設定済み
controls-tag-rename-title = タグ名を変更
controls-tag-create-title = タグを作成
controls-tag-apply-existing-help = 一致する保存済みタグをこのコントローラーに適用します。
controls-tag-create-empty-help = このコントローラー用に新しいタグを作成します。
controls-tag-create-filtered-help = 名前が有効ならこのタグをコントローラー用に作成します。
controls-tag-apply-saved-help = このタグと保存済み設定をコントローラーに適用します。
controls-tag-apply-preconfigured-help = このコントローラー種別の既定マッピングで、この事前設定済みタグを適用します。
controls-tag-apply-default-help = このコントローラー種別の既定マッピングでこのタグを適用します。
controls-tag-delete-button = {$tag} を削除
controls-tag-delete-help = 確認後に {$tag} と全コントローラー種類の保存済み設定・調整を削除します。
controls-tag-delete-title = タグを削除しますか？
controls-tag-delete-body = 「{$tag}」と全コントローラー種類の設定・調整を削除し、接続中のコントローラーから割り当てを解除しますか？
controls-tag-delete-warning = この操作は取り消せません。
controls-back-help = コントロールに戻ります。
controls-tag-select-help = コントローラータグを選ぶか作成してください。
controls-edit-set-tag-first-help = 先にコントローラータグを作成してから、ゲームプレイとメニューの割り当てを編集します。
controls-edit-controls-help = このコントローラープロファイルのゲームプレイとメニューの割り当てを編集します。
controls-tap-jump-set-tag-first-help = 先にコントローラータグを作成してから、タップジャンプの既定値を設定します。
controls-tap-jump-default-help = 上入力でこのコントローラーが既定でジャンプするかを切り替えます。
controls-create-new-tag-help = 新しいタグを作成してこのコントローラーに切り替えます。
controls-choose-existing-tag-help = 保存済みタグを選ぶか削除します。
controls-rename-current-tag-help = 現在のコントローラータグ名を変更します。
controls-switch-controller-help = コントロールメニューをこの接続済みコントローラーに切り替えます。
menu-binding-hint = スティックまたは十字キーで移動 · 決定/Startで選択 · 戻るで戻る
menu-adjust-hint = スティックまたは十字キーで移動 · 左/右で値を変更 · 決定で選択 · 戻るで戻る
menu-bind-hint = スティックまたは十字キーで移動 · 決定で割り当てを選択 · 戻るで戻る
arcade-select-leave = Selectで退出
main-help-about-help = ガイド、クレジット、bluehexagonsリンク。
main-replays-available-help = 保存済みリプレイを閲覧、プレビュー、再生します。
main-replays-unavailable-help = リプレイはローカルファイルシステムから読み込むため、オフラインでのみ利用できます。
arcade-menu-battles-help = 現在のArcade Battles設定で開始します。
arcade-menu-infinite-help = スケールする1ストックCPUとの無限Arcadeモードを開始します。
arcade-menu-training-help = 練習ツールとセーブステート付きのトレーニングを開きます。
arcade-menu-back-help = メインメニューに戻ります。
arcade-menu-help = アーケードモードを選んでください。
training-menu-courses-help = ゲームの操作を試せる短いコースを選びます。
training-menu-help = トレーニング内容を選びます。
courses-menu-course-help = このコースエリアへ移動します。
courses-menu-back-help = トレーニングに戻ります。
courses-menu-help = コースエリアは左から右へ並んでいます。いつでも自由に移動できます。
course-instruction-movement-walk = 移動スティックを左右に傾けて歩きます。
course-instruction-movement-dash = 移動スティックを左右に素早く倒してダッシュします。
course-instruction-movement-dash-dance = ダッシュ中に移動スティックを反対方向へ素早く倒し、逆向きにダッシュします。
course-instruction-movement-moonwalk = ダッシュ中に移動スティックを下へ回し、前を向いたまま後ろへ滑ります。
course-instruction-movement-crouch = 下を入力してしゃがみます。
course-name-movement = 移動
course-name-jumping = ジャンプ
course-name-attacks = 攻撃
course-name-defense = 防御
course-name-advanced = 上級
course-name-directional-influence = ベクトル変更
course-name-teching = 受け身
course-summary-movement = 歩き、ダッシュ、ダッシュダンス、ムーンウォーク、しゃがみを練習し、マーカーを目指します。
course-summary-jumping = ジャンプ、空中ジャンプ、小ジャンプ、通常とシールドからの床すり抜け、崖つかまり、使用可能な壁ジャンプを練習します。
course-summary-attacks = 地上攻撃、チャージ攻撃、空中攻撃、追撃を練習し、必殺技でエネルギーを消費します。
course-summary-defense = 防御、パワーシールド、回避、前後回避、パリィ、しゃがみキャンセル、つかみ、投げを練習します。
course-summary-advanced = スティック攻撃、空中回避、Vキャンセル、ウェーブダッシュ、急降下、着地キャンセル、復帰。
course-summary-directional-influence = 移動スティックでギミックの吹き飛び方向を変えます。
course-summary-teching = ギミックで吹き飛ばされた後に、その場受け身、移動受け身、壁受け身を練習します。
course-instruction-movement-travel = 矢印のマーカーまで移動します。
course-instruction-jumping-jump = ジャンプを押して地面から離れます。
course-instruction-jumping-air-jump = 空中でもう一度ジャンプを押して空中ジャンプします。
course-instruction-jumping-steer = ジャンプ後に左右を入力し続けて空中で移動します。
course-instruction-jumping-short-hop = ジャンプを短く押し、踏み切る前に離して小ジャンプします。
course-instruction-jumping-platform-drop = 頭上の足場に着地し、下を入力してすり抜けます。
course-instruction-jumping-shield-drop = 足場でシールドと下を押し続け、必殺ワザを押してシールドドロップします。
course-instruction-jumping-ledge-grab = 足場の崖に下から近づいてつかまります。
course-instruction-jumping-ledge-option = 崖につかまった状態で、登る、回避、攻撃、ジャンプ、手放すのいずれかを選びます。
course-instruction-jumping-wall-jump = 上の壁に触れてから、壁と反対方向へ素早く入力して壁ジャンプします。
course-instruction-attacks-normal = 通常攻撃で練習ターゲットに攻撃を当てます。
course-instruction-attacks-charged = 左右どちらかを素早く入力し、攻撃を長押ししてスマッシュ攻撃をため、攻撃を離して練習ターゲットに当てます。
course-instruction-attacks-aerial = ジャンプして空中攻撃を練習ターゲットに当てます。
course-instruction-attacks-combo = 練習ターゲットが復帰する前に、続けてもう一度攻撃を当てます。
course-instruction-attacks-energy = 必殺技を使い、共通のエネルギーゲージが減ってから時間を置いて回復する様子を確認します。
course-instruction-attacks-special = 必殺技で練習ターゲットに攻撃を当てます。
course-instruction-defense-shield = シールドで練習ターゲットの攻撃を防ぎます。
course-instruction-defense-power-shield = 攻撃が当たる直前にシールドを強く押し、エネルギーを失わずにパワーシールドします。
course-instruction-defense-roll = シールド中に左右を入力して前後回避します。
course-instruction-defense-spot-dodge = シールド中に下を入力してその場回避します。
course-instruction-defense-parry = 攻撃が当たる直前にシールドを離してパリィします。
course-instruction-defense-crouch-cancel = 下を入力し続け、しゃがんだ状態でターゲットの攻撃を受けてしゃがみキャンセルします。
course-instruction-defense-grab = 練習ターゲットをつかみます。
course-instruction-defense-throw = 練習ターゲットをつかんだ後、方向を選んで投げます。
course-instruction-advanced-stick = 右スティックをいずれかの方向に素早く倒してスティック攻撃を出します。
course-instruction-advanced-air-dodge = ジャンプ後にシールドボタンを強く押して空中回避します。
course-instruction-advanced-v-cancel = ターゲットの近くでジャンプし、ジャンプ開始時にシールドを強く押して空中で受ける攻撃をVキャンセルします。
course-instruction-advanced-wave-dash = ジャンプ後、地面へ斜めに空中回避してウェーブダッシュします。
course-instruction-advanced-fast-fall = 空中で下を入力して急降下します。
course-instruction-advanced-lag-cancel = 空中攻撃の後、着地直前にシールドを押して着地隙をキャンセルします。
course-instruction-advanced-recovery = 空中で上と必殺技を入力し、上必殺技で復帰します。
course-instruction-directional-influence = 発射台に当たる瞬間に左右を入力し続けて、吹き飛び角度を変えます。
course-instruction-teching-neutral = 発射台から着地する直前にシールドボタンを強く押して受け身を取ります。
course-instruction-teching-directional = 着地直前に左右を入力しながらシールドボタンを強く押し、その方向へ移動受け身を取ります。
course-instruction-teching-wall = 壁にぶつかる直前にシールドボタンを強く押して壁受け身を取ります。
course-instruction-complete = エリアクリア。準備ができたら別のエリアへ移動しましょう。
course-action-restart = エリアをやり直す
course-action-next = 次のエリア
course-session-progress = クリアしたエリア: {$completed}/{$total}
course-target-label = 練習ターゲット
course-target-reset = ターゲットをリセット
course-target-disable = ターゲットを無効化
course-target-enable = ターゲットを有効化
course-target-unavailable = このエリアにはターゲットがありません
course-target-reset-help = このエリアの練習ターゲットを開始位置に戻して有効にします。
course-target-toggle-help = 現在のコースセッション中、このエリアの練習ターゲットを非表示または復元します。
course-defense-feedback-early = 攻撃が近づいてからシールドしましょう。
course-defense-feedback-late = 遅すぎます。攻撃が当たる前にシールドしましょう。
course-defense-feedback-success = タイミング成功。攻撃を防ぎました。
course-demonstration-label = デモ
course-demonstration-show = 静止デモを表示
course-demonstration-hide = 静止デモを非表示
course-demonstration-help = 現在のレッスン手順のアニメーションなしの例を表示または非表示にします。
course-demonstration-still = 静止ポーズ・アニメーションなし
help-bluehex-homepage-help = bluehexagonsのホームページを開きます。
help-bluehex-github-help = GitHubでbluehexagonsのプロジェクトを閲覧します。
help-bluehex-steam-help = bluehexagonsのSteamキュレーターページを開きます。
help-bluehex-itch-help = bluehexagonsのitch.ioページを開きます。
help-bluehex-bluesky-help = Blueskyでbluehexagonsをフォローします。
help-bluehex-patreon-help = Patreonでbluehexagonsを支援します。
controls-source-keyboard = キーボード
controls-source-keyboard-defaults = キーボード既定値
controls-current-menu-controls-heading = 現在のメニュー操作
controls-current-menu-controls-summary = {$source} · 移動: {$navigate} · 決定: {$confirm} · 戻る: {$back}
controls-action-attack = 攻撃
controls-action-jump = ジャンプ
controls-action-special = 必殺技
controls-action-grab = つかみ
controls-action-shield-1 = シールド 1
controls-action-shield-2 = シールド 2
controls-action-hard-shield-1 = 強シールド 1
controls-action-hard-shield-2 = 強シールド 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-pad 上
controls-action-dpad-down = D-pad 下
controls-action-dpad-left = D-pad 左
controls-action-dpad-right = D-pad 右
controls-action-move-horizontal = 横移動
controls-action-move-vertical = 縦移動
controls-action-right-stick-horizontal = 右スティック横
controls-action-right-stick-vertical = 右スティック縦
controls-action-ui-confirm = UI 決定
controls-action-ui-back = UI 戻る
controls-action-ui-up = UI 上
controls-action-ui-down = UI 下
controls-action-ui-left = UI 左
controls-action-ui-right = UI 右
controls-action-ui-horizontal-nav = UI 横移動
controls-action-ui-vertical-nav = UI 縦移動
controls-action-move-left = 左へ移動
controls-action-move-right = 右へ移動
controls-action-move-up = 上へ移動
controls-action-move-down = 下へ移動
controls-action-tilt-left = 軽く左
controls-action-tilt-right = 軽く右
controls-action-tilt-up = 軽く上
controls-action-tilt-down = 軽く下
controls-action-right-stick-left = 右スティック左
controls-action-right-stick-right = 右スティック右
controls-action-right-stick-up = 右スティック上
controls-action-right-stick-down = 右スティック下
controls-action-light-shield-l = 軽シールド L
controls-action-light-shield-r = 軽シールド R
controls-action-ui-nav-left = UI ナビ左
controls-action-ui-nav-right = UI ナビ右
controls-action-ui-nav-up = UI ナビ上
controls-action-ui-nav-down = UI ナビ下
controls-remap-section-buttons = ボタン
controls-remap-section-dpad = D-pad
controls-remap-section-movement = 移動
controls-remap-section-tilts = 傾き（弱入力）
controls-remap-section-right-stick = 右スティック
controls-remap-section-light-shields = 軽シールド
controls-remap-section-ui-navigation = UI ナビゲーション
controls-remap-section-sticks-triggers = スティックとトリガー
controls-remap-unbound = 未割り当て
controls-remap-free-keys-none = 空きキー: （共通セットになし）
controls-remap-more-suffix = 、さらに +{$count}
controls-remap-free-keys = 空きキー: {$keys}{$suffix}
controls-remap-free-buttons = 空きボタン: {$buttons}
controls-remap-free-axes = 空き軸: {$axes}
controls-remap-conflict-detail = {$input} はすでに {$actions} に割り当てられています。
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = メニュー操作を保つため、UI 決定、UI 戻る、横・縦ナビゲーションを残してください。
controls-remap-capture-key-hint = {$action} に割り当てるキーボードキーを押してください。ESC でキャンセル。
controls-remap-capture-button-hint = {$action} に割り当てる {$layout} のボタンを押してください。戻るでキャンセル。
controls-remap-capture-axis-hint = {$action} に割り当てる {$layout} のスティック/トリガーを動かしてください。戻るでキャンセル。
controls-remap-capture-add-title = {$action} を追加
controls-remap-capture-replace-title = {$action} を置き換え
controls-remap-capture-matching-input = この操作に対応する入力を使ってください。
controls-remap-confirm-reassign = {$action} に再割り当てするには確認してください。
controls-remap-confirm-cancel-help = 決定で置き換え、戻るでキャンセル。
controls-remap-command-add = 追加
controls-remap-command-replace = 置き換え
controls-remap-command-remove = 削除
controls-remap-add-help = {$action} に別の物理入力を追加します。
controls-remap-replace-help = {$action} の {$input} を置き換えます。
controls-remap-remove-help = {$action} から {$input} を削除します。
controls-remap-back-to-controls = コントロールに戻る
controls-remap-back-to-controls-help = 割り当て一覧の一番下までスクロールせずにコントロールへ戻ります。
controls-remap-help = 追加、置き換え、削除を選んでください。Page キーで一覧をジャンプできます。
controls-remap-help-extended = 追加、置き換え、削除を選んでください。Page キーで一覧をジャンプできます。戻るでキャンセル。
controls-remap-jump-to-section = セクションへ移動
controls-remap-jump-to-binding = {$section} へ移動
controls-remap-focus-section-help = {$section} の最初の割り当てへフォーカスを移動します。
controls-remap-reset-help = この操作プロファイルを既定のレイアウトに戻します。2 回の確認が必要です。
controls-remap-reset-confirm = もう一度押してリセットを確認
controls-quick-map-action-unbound = 未割り当て
controls-quick-map-action-hard-shield-1-short = シールド 1
controls-quick-map-action-hard-shield-2-short = シールド 2
controls-quick-map-action-dpad-up-short = D-上
controls-quick-map-action-dpad-down-short = D-下
controls-quick-map-action-dpad-left-short = D-左
controls-quick-map-action-dpad-right-short = D-右
controls-quick-map-title = {$layout} クイックレイアウト
controls-quick-map-mode-editing = 決定またはアクションをクリックして適用 · 戻るまたはタイトルをクリックして終了
controls-quick-map-mode-ready = 決定でクイック編集
controls-quick-map-mode-unavailable = 操作を利用できません
controls-quick-map-assign = 割り当て
controls-quick-map-assign-input = {$input} を割り当て
controls-quick-map-unavailable-status = このコントローラーではクイックマップを利用できません。変更は保存されませんでした。
controls-remap-autosave-status = 変更は自動保存されます。
controls-remap-saved-status = 自動保存しました。
controls-remap-blocked-menu-controls-status = ブロック: UI 決定、UI 戻る、メニューの横・縦ナビゲーションを残してください。変更は保存されませんでした。
controls-remap-default-reset-blocked-status = 組み込みの初期設定はリセットできません。変更は保存されませんでした。
controls-layout-standard = Xbox / 標準
controls-layout-arcade-stick = アーケードスティック
controls-layout-retro-dpad = レトロ十字キー
controls-layout-switch-pro = Switch Pro
controls-layout-playstation = PlayStation
controls-layout-8bitdo-nintendo = 8BitDo（Nintendo 配列）
controls-layout-steam-deck = Steam Deck
controls-layout-gamecube = GameCube
controls-layout-n64 = Nintendo 64
controls-layout-keyboard = キーボード

standard = 標準
keyboard = キーボード
gcn_native = GCNネイティブ

# Training Menu
Swap-Character = スワップキャラクター
Overlays = オーバーレイ
press-start = STARTボタンを押す

drawHitbubbleInfo = 攻撃情報
drawECB = 衝突
drawHeatmap = ヒートマップ
drawRawPosition = 生の位置
drawStage = ステージ衝突
animations = アニメーション
controllers = コントローラー

# Versus Menu
FFA = FFA
Teams = チーム

Host-Netplay = ホストネットプレイ
Join-Netplay-Clipboard = クリップボードからネットプレイに参加する
Disconnect = 切断する
Copy-Lobby-Code = ロビーコードのコピー

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = 直接接続
Connect = 接続

netplay-action-start-lobby = ロビーを開始
netplay-action-join-clipboard = クリップボードから参加
netplay-action-quick-host-copy-code = クイックホスト＆コードコピー
netplay-action-copy-lan-invite = LAN招待をコピー
netplay-action-copy-localhost-invite = Localhost招待をコピー
netplay-action-copy-stun-invite = STUN招待をコピー
netplay-action-find-random-match = ランダムマッチを検索
netplay-action-cancel-lobby = ロビーをキャンセル
netplay-action-cancel-connection = 接続をキャンセル
netplay-action-please-wait = しばらくお待ちください
netplay-action-open-versus = Versusを開く
netplay-action-cancel-matchmaking = マッチメイキングをキャンセル

netplay-status-label = ネットプレイ: {$status}
netplay-status-uninitialized = 未初期化
netplay-status-initialized = 初期化済み
netplay-status-waiting = 待機中
netplay-status-hosting = ホスト中
netplay-status-connecting = 接続中
netplay-status-establishing = 確立中
netplay-status-connected = 接続済み
netplay-status-ready = Netplayの準備完了
netplay-status-waiting-player = プレイヤーの参加を待っています
netplay-status-waiting-lobby = ロビーの応答を待っています
netplay-status-hosting-lobby = ロビーをホスト中
netplay-status-hosting-lobby-code = ロビーをホスト中 {$code}
netplay-status-starting-lobby = ロビーを開始中
netplay-status-connecting-host = ホストに接続中
netplay-status-connected-host = ホストとして接続済み
netplay-status-connected-client = ホストに接続済み
netplay-status-disconnecting = 切断中
netplay-status-canceling = 接続をキャンセル中
netplay-status-matchmaking = ランダムマッチを検索中
netplay-status-match-found = ランダムマッチが見つかりました
netplay-status-matchmaking-canceling = マッチメイキングをキャンセル中
netplay-status-error = Netplayエラー
netplay-status-error-message = Netplayエラー: {$error}
netplay-status-unavailable = Netplayステータスは利用できません

matchmaking-title = マッチメイキング
matchmaking-status-select-character = キューに入るキャラクターを選んでください
matchmaking-status-no-controller = コントローラーが接続されていません
matchmaking-status-searching = 対戦相手を探しています...
matchmaking-status-searching-details = 検索中... 経過 {$wait} 秒。待機中のプレイヤー: {$players}。最長待機時間: {$longest} 秒。
matchmaking-status-searching-estimate = 検索中... 経過 {$wait} 秒。待機中のプレイヤー: {$players}。終了した対戦の平均時間: {$average} 秒。
matchmaking-status-canceling = キャンセル中...
matchmaking-status-found = 対戦相手が見つかりました!
matchmaking-status-connecting = 接続中...
matchmaking-status-disconnecting = 切断中...
matchmaking-status-error = {$error} もう一度試すにはキャラクターを選んでください。

# Match by Code
match-code-title = コードで対戦
match-code-hint = 自分のコードを共有し、相手のコードを入力してください。2人とも「検索」を押します。大文字と小文字は区別されません。
match-code-own-label = 自分のコード：{$code}
match-code-peer-label = フレンドのコード：{$code}
match-code-peer-unset = フレンドのコード：（未設定）
match-code-search = 検索
match-code-entry-limit = 英数字は最大{$length}文字
match-code-own-prompt = 自分のコード
match-code-peer-prompt = フレンドのコード
match-code-status-enter-peer = フレンドのコードを入力してプライベート対戦を設定してください
match-code-status-ready = 準備完了 — 2人とも「検索」を押してください
match-code-error-enter-peer = 先にフレンドのコードを入力してください
match-code-error-own = 自分のコードではなく、フレンドのコードを入力してください
match-code-error-invalid = そのコードは無効です
match-code-error-length = コードは{$min}～{$max}文字の英数字で入力してください
match-code-error-blocked = そのコードは使用できません。別のコードを選んでください

netplay-detail-ready = ロビーをホストするか、コピーした招待を貼り付けるか、アドレスを手動で入力します。
netplay-detail-lobby-code-ready = ロビーコード {$code} は共有する準備ができました。
netplay-detail-creating-lobby-code = ロビーコードを作成中。
netplay-detail-waiting-for-host = ホストがあなたの参加リクエストに応答するのを待っています。
netplay-detail-share-lobby-code = ロビーコード {$code} を他のプレイヤーと共有してください。
netplay-detail-starting-lobby = ロビー接続を開始中。
netplay-detail-joining-host = 選択したホストに参加を試みています。
netplay-detail-establishing = プレイヤーが見つかりました。ハンドシェイクを完了し、Versusを開いてください。
netplay-detail-connected = 接続準備完了。Versusを開いてルール、キャラクター、ステージを選んでください。
netplay-detail-disconnecting = 現在のセッションを閉じてオフラインプレイに戻ります。
netplay-detail-canceling = 現在の参加リクエストを停止中。
netplay-detail-matchmaking = Versusを使用して、好みのルールでランダムな対戦相手の列に入ります。
netplay-detail-match-found = 対戦相手が見つかりました。両プレイヤーが準備できたら、Versusでセットアップを完了してください。
netplay-detail-matchmaking-canceling = 現在のランダムマッチ検索を停止中。
netplay-detail-error-message = 最後のエラー: {$error}
netplay-detail-error-generic = 問題が発生しました。別のコードまたは接続方法を試してください。
netplay-detail-unavailable = Netplayの詳細は利用できません。

netplay-help-host-copy-code = 他のプレイヤーが貼り付けできるように、ロビーコードをコピーします。
netplay-help-host-cancel-join = 現在の参加試行を停止し、準備状態に戻ります。
netplay-help-host-disconnect = 現在のネットプレイセッションを退出します。
netplay-help-host-start-lobby = 新しいロビーを開始し、他のプレイヤーの参加を待ちます。
netplay-help-busy = Netplayは現在ビジー状態です。完了するまでお待ちください。
netplay-help-join-cancel-lobby = 現在のロビーを閉じて、他のプレイヤーを待つことを停止します。
netplay-help-join-in-progress = 参加はすでに進行中です。待つか「接続をキャンセル」を使用してください。
netplay-help-join-open-versus = Versusに続いて、マッチの設定を完了します。
netplay-help-stop-random-search = ランダムな対戦相手の検索を停止します。
netplay-help-join-clipboard = クリップボードからロビー、ダイレクト、またはSTUN招待コードを貼り付けます。
netplay-help-copy-server = 必要に応じてロビーを開始し、その共有可能なロビーコードをコピーします。
netplay-help-copy-direct = このLAN上の別のデバイス用にダイレクト接続招待をコピーします。
netplay-help-copy-localhost = このコンピュータで実行されている別のコピー用にダイレクト接続招待をコピーします。
netplay-help-copy-stun = インターネットで使いやすいSTUN支援招待をコピーします。
netplay-help-direct-connect = コピーした招待コードを使用する代わりに、手動でアドレスを入力します。
netplay-help-find-random-match = Versusを開いてランダムな対戦相手の列に入ります。
netplay-help-open-versus = この画面を離れずにVersusメニューを開きます。
netplay-help-back = メインメニューに戻ります。
netplay-help-unavailable = Netplayアクションヘルプは利用できません。
netplay-help-advanced = ロールバックやバッファーなどの高度なネットプレイ設定を調整します。

ADVANCED-CONNECTIONS = 高度な接続
netplay-settings-rollback-help = オンライン対戦でロールバックシミュレーションを切り替えます。
netplay-settings-buffer-help = 入力フレームをいくつバッファするか選ぶか、ネットプレイに自動選択させます。
netplay-settings-force-ipv4-help = 混在ネットワークで LAN 招待コードを生成するときは IPv4 を優先します。
netplay-settings-back-help = ネットプレイメニューに戻ります。
netplay-advanced-info = Quick Play や通常のロビーコードで接続できない場合の予備手段です。STUN はインターネット対戦のためにルーター越えを支援します。Direct Connect は LAN 対戦や、UDP ポートを転送済みのホストに最適です。
netplay-advanced-direct-help = 手動の予備手段です。LAN 対戦や、ホストが UDP ポートを転送している場合は host:port を入力してください。
netplay-advanced-stun-help = インターネット用の予備手段です。通常のロビー参加が失敗し、ルーター支援のホールパンチングがまだ必要な場合に共有してください。
netplay-advanced-lan-help = LAN 用の予備手段です。両方のプレイヤーが同じネットワークにいる場合は、到達可能なローカルアドレスを共有してください。
netplay-advanced-localhost-help = テスト用の予備手段です。両方のクライアントが同じマシンで動作している場合にのみ使用してください。
netplay-advanced-back-help = バーチャルカウチに戻ります。
netplay-rollback-off = ロールバック: オフ
netplay-rollback-on = ロールバック: オン
netplay-buffer-auto = ネットバッファ: 自動
netplay-buffer-2 = ネットバッファ: 2
netplay-buffer-3 = ネットバッファ: 3
netplay-buffer-4 = ネットバッファ: 4
netplay-buffer-5 = ネットバッファ: 5
netplay-buffer-6 = ネットバッファ: 6
netplay-buffer-7 = ネットバッファ: 7
netplay-buffer-8 = ネットバッファ: 8
netplay-buffer-10 = ネットバッファ: 10
netplay-buffer-12 = ネットバッファ: 12
netplay-force-ipv4-dual = LAN アドレス: IPv6/IPv4
netplay-force-ipv4-v4 = LAN アドレス: IPv4 を強制

netplay-rollback = ロールバック
netplay-buffer = ネットワークバッファ
netplay-force-ipv4 = LANアドレス

netplay-direct-connect-prompt = IPアドレス:ポートを入力してください。ポートはデフォルトで {$port} です。
netplay-stun-connect-title = STUNサービスを使用しますか？
netplay-stun-connect-prompt = このコードは {$service} を使用して {$address}:{$port} を検出しました。
netplay-waiting-host-battle = ホストのバトルが終了するのを待っています
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = キャラクター
Stages = ステージ
CPU = CPU

Starter = スターター
Legal = 公式
Miscellaneous = その他

Start-Battle = バトルを開始

# Start Menu
quit-info = シールド+攻撃+スタートで終了
paused = 一時停止
tag-info = Dパッド上下でタグイン/アウト

# Pause Menu
pause-resume = 続ける
pause-restart = リスタート
pause-quit = 終了
pause-players = プレイヤー
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = コントローラーを接続して、任意のボタンを押して参加します。
arcade-return-prompt = 確認を押してメインメニューに戻ります。

# Replay
replay-paused = リプレイ一時停止中
replay-controls = 確認: 参加する  ←/→: フレーム  戻る: メニュー  リプレイを保存: [キー]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = 英語
spanish = スペイン語
french = フランス語
italian = イタリア語
german = ドイツ語
russian = ロシア語
japanese = {ja-japanese}
chinese-cn = 簡体字中国語
chinese-hk = 繁体字中国語
korean = 韓国語

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese}
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean} ({korean})

# Shared UI labels
Advanced = 詳細
Clear-Spawns = スポーンをクリア
Create-new-tag = 新しいタグを作成
Credits = クレジット
CREDITS = クレジット
Cycle-Palette = パレット切替
Delete = 削除
Help = ヘルプ
HELP = ヘルプ
Join = 参加
Join-Lobby-Code = ロビーコードで参加
Main-Menu = メインメニュー
Mode = モード
Native-Adapter = ネイティブアダプター
NATIVE-ADAPTER = ネイティブアダプター
NETPLAY-SETTINGS = ネットプレイ設定
Other-saved-tags = 他の保存済みタグ
Profiles-for-this-controller-type = このコントローラー種別のプロファイル
Quick-Play = クイックプレイ
Random-Color = ランダムカラー
Rename-current-tag = 現在のタグ名を変更
Reset-to-Defaults = 初期設定に戻す
Set-Character = キャラクター設定
Spawn-CPU = CPU生成
Team = チーム
Virtual-Couch = バーチャルカウチ
x = x
Find-Random-Match = ランダム対戦を探す
training-label-stage = ステージ
training-label-character = キャラクター
training-label-player-cursor = プレイヤーカーソル
training-label-cpu-spawn = CPU生成
training-label-savestate = 状態保存
Save-State = 状態を保存
Load-State = 状態を読み込み
State-Saved = 状態を保存しました
State-Restored = 状態を復元しました
No-State-Saved = 保存された状態がありません
DPad-Right-Save-Left-Load = 十字キー右で保存 · 左で読み込み
shared-main-menu-help = メインメニューに戻ります。
shared-mode-selector-label-help = ルールセット選択ラベルです。
training-mode-selector-help = Antistatic と 19XX のトレーニング定数を切り替えます。
training-overlays-help = デバッグオーバーレイとトレーニング補助表示を切り替えます。
training-close-help = トレーニングメニューを閉じます。
training-stage-help = トレーニングステージを変更し、ステージ依存の要素をリセットします。
training-character-help = キャラクター設定と CPU生成 に使うキャラクターを選びます。
training-set-character-help = 浮いているプレイヤーカーソルを選択中のキャラクターに変更します。
training-random-color-help = カーソルのキャラクターに新しいランダムな基本色を割り当てます。
training-cycle-palette-help = カーソルキャラクターのパレットを切り替えます。
training-cpu-level-down-help = 新しいトレーニング CPU の CPU レベルを下げます。
training-cpu-level-current-help = 新しく生成するトレーニング CPU の現在の CPU レベルです。確認で切り替えます。
training-cpu-level-up-help = 新しいトレーニング CPU の CPU レベルを上げます。
training-spawn-cpu-help = 選択したキャラクターと CPU レベルで CPU を生成します。
training-clear-spawns-help = トレーニングで生成した CPU とダミーをすべて削除します。
training-save-state-help = 現在のトレーニングの位置、ダメージ、ストック、生成CPU、ステージ、タイミング状態を保存します。十字キー右でも同じ操作ができます。
training-load-state-help = 保存したトレーニング状態を復元します。十字キー左でも同じ操作ができます。
training-savestate-shortcuts-help = 十字キー右で現在のトレーニング状態を保存し、十字キー左で復元します。
versus-tag-selector-default = タグ: {$tag}
versus-tag-none = タグなし
versus-tag-manage = タグを作成 / 管理
versus-tag-change-failed = タグを変更できませんでした
versus-cpu-level-help = この CPU レベルを切り替えます。
versus-cpu-color-help = この CPU の色とパレットをシャッフルします。
versus-cpu-team-help = この CPU のチームを切り替えます。
versus-cpu-remove-help = この CPU を削除します。
versus-character-select-help = 浮いているプレイヤーカーソル用にこのキャラクターを選びます。
versus-add-cpu-help = このキャラクターで CPU を追加します。
versus-tap-jump-help = このプレイヤーのタップジャンプを切り替えます。
versus-random-color-help = このプレイヤーに新しいランダム色を割り当てます。チーム有効時は無効です。
versus-cycle-palette-help = このプレイヤーのパレットを切り替えます。
versus-team-help = このプレイヤーのチームを切り替えます。チームモード時に表示されます。
versus-tag-selector-help = このプレイヤーのタグを選びます。ネットプレイ中は無効です。
versus-start-select-character-first = 先にキャラクターを選んでください
versus-start-not-enough-players = 対戦開始に必要なプレイヤー数が足りません: {$count}
versus-start-not-enough-teams = 対戦開始に必要なチーム数が足りません: {$count}
versus-start-waiting-for-host = ホストの開始を待っています
versus-ffa-help = FFA とチーム戦ルールを切り替えます。
versus-start-help = 十分なプレイヤー、CPU、チーム、ステージが揃ったら対戦を開始します。
versus-starter-help = スターターステージをランダムに選んで対戦を開始します。
versus-legal-help = 合法なスターターまたはカウンターピックステージをランダムに選んで対戦を開始します。
versus-misc-help = その他のステージ。
versus-stage-preview-help = ホバーでこのステージをプレビューし、確認で選択して開始します。
versus-stage-preview-counterpick-help = ホバーでこのカウンターピックステージをプレビューし、確認で選択して開始します。
versus-stage-preview-misc-help = ホバーでこのその他ステージをプレビューし、確認で選択して開始します。
versus-mode-selector-help = Antistatic と 19XX の versus 定数を切り替えます。
versus-tab-stages-help = 対戦で使うステージを探して選びます。
versus-tab-settings-help = 対戦ルールと設定を変更します。ここでStartを押すとステージ選択に切り替わります。
versus-setting-stock = ストック
versus-setting-time = タイム
versus-setting-on = オン
versus-setting-off = オフ
versus-setting-none = なし
versus-setting-stock-mode-value = モード: {$value}
versus-setting-stocks-value = ストック: {$value}
versus-setting-time-limit-value = 時間: {$value}
versus-setting-friendly-fire-value = 味方攻撃: {$value}
versus-setting-stamina-value = スタミナ: {$value}
versus-setting-knockback-value = ふっとばし: {$value}×
versus-setting-pause-value = ポーズ: {$value}
versus-setting-sd-value = 自滅: {$value}
versus-setting-stock-mode-help = ストック制（最後まで残ったプレイヤーが勝利）とタイム制（時間切れ時にストックが最も多いプレイヤーが勝利）を切り替えます。
versus-setting-stocks-help = 各プレイヤーの開始ストック（残機）数です。
versus-setting-time-limit-help = 対戦の制限時間です。タイム制では勝者判定に使われます。
versus-setting-friendly-fire-help = チームメイト同士のダメージを有効/無効にします。チーム戦でのみ表示されます。
versus-setting-stamina-help = 開始スタミナ（HP）です。0にするとダメージ％制になります。
versus-setting-knockback-help = 全体のふっとばし倍率です。値が高いほどふっとび距離が伸びます。
versus-setting-pause-help = 対戦中のポーズを許可または禁止します。
versus-setting-sd-help = 自滅ペナルティです。-1はストックを1つ減らし、0はペナルティなしです。
netplay-copy-lobby-missing = コピーするロビーコードがありません
netplay-copy-lobby-copied = ロビーコードをクリップボードにコピーしました
netplay-direct-connect-empty = IP アドレスを入力してください
netplay-lobby-code-prompt = ロビー、LAN、または STUN の招待コードを入力してください。
netplay-lobby-code-empty = ロビーコードを入力してください
netplay-error-connecting = 接続エラー: {$error}
matchmaking-no-controller-connected = コントローラーが接続されていません
battle-winner-log = 勝者: {$player}
battle-winner-message = 勝者: プレイヤー {$player}
battle-winner-team-log = 勝者: チーム {$team}
battle-winner-team-message = 勝者: チーム {$team}
battle-tie-log = 引き分け
battle-tie-message = 引き分け
battle-time-out = タイムアップ
battle-countdown-go = スタート
battle-infinite-score-log = エンドレススコア: {$score}
battle-infinite-score-message = スコア {$score}
team-name-red = レッド
team-name-green = グリーン
team-name-blue = ブルー
team-name-grey = グレー
versus-start-sync-failed = バトル開始の同期に失敗しました

main-menu-help = 項目にカーソルを合わせると内容を確認できます。
netplay-main-help = ネットプレイの操作を選んでください。
netplay-settings-help = ネットプレイの動作を調整します。
netplay-advanced-help = 接続方法を選んでください。
settings-help = 設定カテゴリを選んでください。
help-discord-help = ブラウザーで Antistatic の Discord コミュニティを開きます。
help-guide-help = ブラウザーで Antistatic のオンラインガイドを開きます。
help-adapter-guide-help = 公式 GameCube コントローラーアダプター用の Dolphin 設定メモを開きます。
Adapter-Guide = アダプターガイド
Open-Dolphin-Guide = Dolphin ガイドを開く
Native-Adapter-Help = アダプターヘルプ
NATIVE-ADAPTER-HELP = アダプターヘルプ
native-adapter-help-summary = Antistatic は libusb を直接使用するため、Dolphin のネイティブアダプター対応と同じドライバー設定を使います。
native-adapter-help-windows = Windows: Zadig で USB ID 057e:0337 に WinUSB をインストールしてください。
native-adapter-help-linux = Linux: 057e:0337 へのユーザーアクセスを許可する udev ルールを追加してください。
native-adapter-help-sdl = SDL/Dolphin が先にアダプターを確保した場合は、SDL_JOYSTICK_HIDAPI_GAMECUBE=0 を付けて起動してください。
native-adapter-help-dolphin = Dolphin/Slippi: Antistatic のネイティブアダプター診断を開く前に終了してください。
native-adapter-help-claim = 別のアプリがアダプターを使用中だった場合は、そのアプリを閉じてからこの診断画面を開き直してください。
native-adapter-help-back = ネイティブアダプターの状態に戻ります。
help-credits-help = クレジット、著作権、サードパーティ表記を表示します。
help-back-help = メインメニューに戻ります。
help-help = ヘルプの項目を選んでください。
controls-help = コントローラー操作を選んでください。
netplay-quick-play-help = 選択したコントローラーでランダムな相手を探します。
credits-help = クレジットと表記。

credits-heading = Antistatic - クレジットと表記
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. 無断転載を禁じます。
credits-developer = 開発: bluehexagons (Loren Crain).
credits-original = オリジナルのサウンド、モデル、アニメーション、ゲームプレイ、UI、エンジンコードはすべて社内制作です。
credits-runtime = オープンソースのランタイム/ツール: Node.js, TypeScript, CMake, Fluent, gl-matrix, jsonc-parser, os-locale.
credits-libraries = ネイティブライブラリ: SDL3, SDL3_image, GLEW, OpenAL Soft, FreeType, Vorbis/libvorbisfile, libusb.
credits-build = ビルド/チェック用ツール: npm, oxlint, oxfmt, 各プラットフォームのコンパイラツールチェーン。
credits-fonts = 同梱フォント: Noto Sans, IBM Plex Mono, GNU Unifont.
credits-tools = 制作ツール: 3D モデルには Blender、音声と音楽には Audacity と LMMS。
credits-packages = bluehexagons のパッケージ: capacitor, trace, antistatic-translations.
credits-thanks = これらのプロジェクトのメンテナーと貢献者のみなさんに感謝します。
credits-license = サードパーティのプロジェクトはそれぞれのライセンスに従います。

# Old UI hover/help text
main-versus-help = ローカル対戦を始める前に、キャラクター、CPU、チーム、ルール、ステージを選びます。
main-arcade-help = 参加している全員向けの協力 CPU バトルです。ストックは少なめで、負けたらリトライします。
main-netplay-help = オンライン対戦のホスト/参加、Quick Play、Netplay 接続設定を開きます。
main-training-help = ステージ、CPU、カラー、パレット、デバッグ操作付きのトレーニングモードを開きます。
main-replays-help = 保存した Replay ファイルを閲覧、プレビュー、再生します。
main-settings-help = 音声、映像、言語、コントローラーアダプター、起動モードの設定を調整します。
main-controls-help = コントローラータグを作成し、タグ付きまたは共有のタグなし操作割り当てを編集します。
main-help-help = コミュニティや外部ガイドへのリンクを開きます。
main-exit-help = Antistatic を終了します。
settings-audio-help = マスター、効果音、UI、ボイス、音楽の音量を調整します。
settings-video-help = グラフィックプリセット、フルスクリーン、同期、エフェクト、フレーム制限の設定を変更します。
settings-native-adapter-help = GameCube アダプターの状態とセットアップメモを確認します。
settings-language-help = メニュー言語を切り替えます。
settings-start-mode-help = 起動時に最初に開くモードを選びます。
settings-live-reload = ライブリロード
settings-live-reload-help = ローカルで編集中にAnimatorからキャラクターファイルを再読み込みします。デフォルトでは無効です。
shared-settings-help = 設定に戻ります。
native-adapter-copy-udev-install-help = 057e:0337 用の標準 udev ルールのインストールと再読み込みコマンドをコピーします。
native-adapter-copy-udev-line-help = 057e:0337 用の標準 udev ルール行のみをコピーします。
native-adapter-help-button-help = Dolphin/Slippi と互換性のあるアダプターのインストール手順（Windows/Linux）を開きます。
audio-master-help = メイン出力音量を設定します。
audio-sfx-toggle-help = 効果音と UI 音を切り替えます。
audio-sfx-help = ゲーム内効果音の音量を設定します。
audio-ui-help = メニューとインターフェースの音量を設定します。
audio-voice-help = キャラクターボイスの音量を設定します。
audio-music-toggle-help = 音楽再生を切り替えます。
audio-music-help = 音楽の音量を設定します。
video-preset-help = グループ化されたグラフィックプリセットを適用するか、個別設定が異なる場合は カスタム を表示します。
video-fullscreen-toggle-help = ウィンドウ表示とフルスクリーン表示を切り替えます。
video-display-help = ゲームウィンドウまたはフルスクリーンモードで使用するディスプレイを選びます。
video-fullscreen-resolution-help = 排他的フルスクリーンの解像度を選びます。Auto はデスクトップフルスクリーンを使います。
video-windowed-resolution-help = ウィンドウモードとフルスクリーン復帰で使うウィンドウサイズを選びます。
video-render-scale-help = UI をネイティブのままにしつつ、3D グラフィックをウィンドウ解像度より下または上で描画します。
video-vsync-help = 交換タイミングを選びます。Adaptive はドライバーが対応していれば、低遅延の tear-if-late 同期を使います。
video-shadow-quality-help = 影の品質を選ぶか、影を無効にします。
video-ssao-help = 環境遮蔽の品質を選びます。
video-antialias-help = FXAA アンチエイリアスを切り替えます。
video-bloom-help = 最も明るい部分の周囲に柔らかな光彩を加えます。高性能な GPU に最適です。
video-reflections-help = スクリーンスペース反射で光沢のある表面にシーンを映し込みます。負荷が高く、高性能な GPU に最適です。
video-godrays-help = 太陽からの体積光のシャフトをシーンに投射します。負荷が高く、高性能な GPU に最適です。
video-perf-overlay-help = パフォーマンスオーバーレイを表示または非表示にします。
video-point-lights-help = 追加のポイントライト品質を選びます。
video-particle-quality-help = パーティクル効果の密度を選びます。
video-max-fps-help = 任意のフレームレート上限を設定します。
video-apply-help = 変更したビデオ設定を適用します。
replays-enabled-help = 対象の Versus と Quick Play のバトルをメモリに記録します。メモリが限られているシステムでは無効にしてください。
replays-auto-save-help = 手動で保存ボタンを押すのを待たずに、リザルト画面で Replay を自動保存します。
replays-compression-help = 保存時に Replay ファイルを圧縮します。圧縮で保存が遅くなる場合のみ無効にしてください。
netplay-copy-lobby-help = 利用可能な場合は現在のロビーコードをコピーします。
netplay-virtual-couch-help = ロビーのホスト、ロビーコードでの参加、詳細な招待オプションを開きます。
netplay-settings-menu-help = ロールバック、入力バッファ、LAN アドレスの動作を設定します。
netplay-back-help = 確立済みのセッションを切断せずにメインメニューへ戻ります。
arcade-cpu-level-help = 対戦相手の CPU 難易度レベル（0 が最も簡単、6 が最も難しい）
arcade-stocks-help = 1 試合ごとのストック数。
arcade-retries-help = 敗北でランを終了するまでのリトライ回数。
arcade-battles-help = ラン内の総バトル数。
arcade-start-help = 参加中の全プレイヤーが準備できたらランを開始します。
controls-remap-page-help = メニュー操作、コンソール、フルスクリーン、トレーニングモードのキー割り当てを変更します。
controls-remap-reset-binding-help = {$action} をデフォルトの割り当てに戻します。
controls-remap-reset-all-help = すべてのキーボードショートカットを内蔵のデフォルトに戻します。
replay-browser-help = Replay ブラウザー。
replay-offline-only-help = Replay はローカルファイルシステムから読み込むため、オフラインでのみ利用できます。
replay-refresh-help = {$dir} から保存済みの Replay ファイルを再スキャンします。
replay-entry-help = {$players} が {$stage} で；{$duration} ({$truncated})；{$result}；{$version}；{$compression}。
replay-unreadable-help = Replay を読み取れませんでした: {$error}
replay-actions-watch-help = 保存した Replay を最初から再生します。Replay 再生中は Jump In を利用できます。
replay-actions-back-help = Replay 一覧に戻ります。
replay-load-help = Replay ディレクトリから保存済みの Replay ファイルを読み込みます。
replay-prev-help = 新しい Replay を表示します。
replay-next-help = 古い Replay を表示します。
replay-settings-help = Replay の記録、自動保存、圧縮オプション。
audio-help = 音声設定を調整します。
video-help = 映像設定を調整します。
replays-help = Replay はデフォルトで有効で、1 試合あたり 16 分に制限されています。
native-adapter-help-text = Native Adapter は 4 ポートの直接ポーリングを提供します。PC モードはより簡単ですが、SDL のコントローラー割り当てを使用します。
shortcut-menu-up-help = メニューで選択を上に移動します。
shortcut-menu-down-help = メニューで選択を下に移動します。
shortcut-menu-left-help = 選択を左に移動するか、値を減らします。
shortcut-menu-right-help = 選択を右に移動するか、値を増やします。
shortcut-menu-confirm-help = フォーカス中の項目を実行します。
shortcut-menu-next-help = 次にフォーカス可能な項目へ移動します。Shift を押し続けると戻れます。
shortcut-menu-page-up-help = 複数項目ぶん上へジャンプします。
shortcut-menu-page-down-help = 複数項目ぶん下へジャンプします。
shortcut-menu-home-help = 一覧の最初の項目にフォーカスします。
shortcut-menu-end-help = 一覧の最後の項目にフォーカスします。
shortcut-console-help = ゲーム内デバッグコンソールを開きます。
shortcut-chat-help = チャット入力欄（say コマンド）を開きます。
shortcut-fullscreen-help = フルスクリーンを切り替えます。Alt+Enter でも動作します。
shortcut-frame-step-help = フリーズ中に 1 フレーム進めます。デバッグモードが必要です。
shortcut-freeze-help = TAS を一時停止または再開します。デバッグモードが必要です。
shortcut-save-state-help = トレーニングモードで現在の状態のスナップショットを保存します。
shortcut-restore-state-help = トレーニングモードの最後のスナップショットを復元します。

Start = スタート
Color = カラー
Leave = 退出
Not-Joined = 未参加
Hold-Start = スタート長押し
arcade-join-help = このアーケードランに参加します。
arcade-color-help = このプレイヤーのカラーをランダムにします。
arcade-palette-help = このプレイヤーのパレットを選択します。
arcade-leave-help = このアーケードランから退出します。
arcade-setting-cpu-level = CPUレベル
arcade-setting-stocks = ストック
arcade-setting-starting-stocks = 初期ストック
arcade-setting-retries = リトライ
arcade-setting-battles = バトル数
arcade-setting-value = {$label}: {$value}
arcade-palette = パレット {$number}
arcade-select-title = アーケード
arcade-select-infinite-title = 無限バトル
arcade-select-instructions = 決定で参加 · プレイヤーごとにキャラとパレットを選択 · 戻るで退出
arcade-between-cleared-battle = バトル {$current} / {$total} クリア
arcade-between-next = 決定: 次へ
arcade-between-retries-remaining =
    敗北 — { $count ->
       *[other] 残りリトライ {$count} 回
    }
arcade-between-retry-actions = 決定: リトライ · 戻る: 中断
arcade-between-results = 決定: リザルト
arcade-between-complete = アーケードクリア！
arcade-results-infinite-title = 無限バトル
arcade-results-infinite-subtitle = {$time} でスコア {$score}
arcade-results-cleared-title = アーケードクリア
arcade-results-cleared-subtitle = {$battles} 戦すべてをクリアしました。
arcade-results-abandoned-title = ラン中断
arcade-results-abandoned-subtitle = {$total} 戦中 {$current} 戦目で中断しました。
arcade-results-gameover-title = ゲームオーバー
arcade-results-gameover-subtitle = {$total} 戦中 {$current} 戦目まで到達しました。
replay-battle-controls = リプレイ: 保存でマーカー追加 · スタートで一時停止 · 十字キーで移動 · つかみで速度変更 · 決定/攻撃長押しで早送り · 戻るで終了
replay-battle-status = {$current} / {$total} · {$speed}x
replay-marker-default = マーカー {$number}
replay-marker-added = {$label}を{$time}に追加
replay-marker-selected = {$label} · {$time}
replay-marker-none = リプレイマーカーなし
replay-marker-save-unavailable = リプレイマーカーを保存できません
replay-speed-changed = 再生速度: {$speed}x
replay-export-button = リプレイパッケージを書き出す
replay-export-help = このリプレイとマーカーをローカルパッケージにします。アップロードは行いません。
replay-exporting = リプレイパッケージを書き出しています...
replay-exported = {$name}を書き出しました
replay-export-failed = 書き出し失敗: {$error}
results-controller-port = コントローラー P{$port}
results-controller-id = コントローラー {$id}
results-disconnected-slot = 切断されたスロット
results-remote-player = リモートプレイヤー
results-replay-capture = リプレイ保存
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = スロット {$index}: {$name}
results-row-kos = KOs
results-row-falls = 落下
results-row-sds = 自滅
results-row-damage-given = 与えたダメージ
results-row-damage-taken = 受けたダメージ
results-row-blocked = ガード
results-row-parries = パリィ
results-row-power-shields = ジャストシールド
results-row-lag-cancels = ラグキャンセル
results-row-kb-given = 与えた吹っ飛び
results-row-kb-taken = 受けた吹っ飛び
results-row-kb-absorbed = 吸収した吹っ飛び
results-row-ledge-grabs = 崖つかまり
results-row-ledge-time = 崖時間
results-row-crouch-cancels = しゃがみキャンセル
results-row-velocity-cancels = ベロシティキャンセル
controls-action-ui-save-replay = リプレイ保存
controls-device-unknown = 不明
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = キーボードショートカット
shortcut-unbound = （未設定）
shortcut-category-menu = メニュー操作
shortcut-category-general = 一般
shortcut-category-debug = デバッグ (TAS)
shortcut-category-training = トレーニングモード
shortcut-label-menu-up = 上へ移動
shortcut-label-menu-down = 下へ移動
shortcut-label-menu-left = 左へ移動
shortcut-label-menu-right = 右へ移動
shortcut-label-menu-confirm = 決定
shortcut-label-menu-next = 次の項目
shortcut-label-menu-page-up = 前のページ
shortcut-label-menu-page-down = 次のページ
shortcut-label-menu-home = 先頭項目
shortcut-label-menu-end = 最後の項目
shortcut-label-console = コンソールを開く
shortcut-label-chat = チャット
shortcut-label-fullscreen = フルスクリーン切替
shortcut-label-frame-step = 1フレーム進める (TAS)
shortcut-label-freeze = フリーズ (TAS)
shortcut-label-save-state = ステート保存
shortcut-label-restore-state = ステート復元
shortcut-bind = 割り当て
shortcut-add = 追加
shortcut-replace = 置き換え
shortcut-remove-key = {$key} を削除
shortcut-capture-bind-title = キーを割り当て: {$action}
shortcut-capture-replace-title = キーを置き換え: {$action}
shortcut-capture-hint = 割り当てるキーを押すか、Esc でキャンセルします。
shortcut-conflict-detail = {$key} はすでに {$action} に割り当てられています。再割り当てしますか？
shortcut-conflict-hint = Enter で再割り当て、Esc でキャンセルします。
shortcut-min-binding = {$action} には少なくとも 1 つの割り当てが必要です。
shortcut-overlap-menu = メニュー操作と重複: {$keys} はメニュー操作にも使われます。メニューではコントローラー割り当てが優先されます。
shortcut-overlap-actions = ショートカット重複: {$overlaps}。ゲームプレイ中はコントローラー割り当てが優先されます。
shortcut-reset-all = すべてのショートカットを初期設定に戻す
character-select-help = キャラクターを選択します。

matchmaking-service-fallback-stun = 代替 STUN
matchmaking-status-preparing-binding = Quick Play を準備中... ネットプレイソケットを開いています。
matchmaking-status-preparing-primary-stun = Quick Play を準備中... {$service} 経由で公開 UDP 経路を確認しています。
matchmaking-status-preparing-fallback-stun = Quick Play を準備中... プライマリ STUN に失敗したため、{$service} 経由で再試行しています。
matchmaking-status-preparing-queueing = Quick Play を準備中... キューに参加しています。
matchmaking-status-connecting-tunneling = 対戦相手が見つかりました。P2P ルートを開いています...
matchmaking-status-connecting-peer = P2P ルートが開きました。接続ハンドシェイクを完了しています...
matchmaking-status-waiting-peer = ルートが開きました。相手プレイヤーを待っています...
matchmaking-status-starting-battle = 接続準備完了。対戦を開始しています...
netplay-experimental-note = 実験的 — 不安定な場合があります
netplay-detail-connecting-peer = P2P ルートが開きました。接続ハンドシェイクを完了しています...
netplay-detail-waiting-for-peer = ルートが開きました。相手プレイヤーの接続完了を待っています...
netplay-detail-starting-battle = 接続準備完了。対戦を開始しています...
netplay-detail-matchmaking-binding = Quick Play を準備中。ネットプレイソケットを開いています...
netplay-detail-matchmaking-primary-stun = {$service} 経由で公開 UDP 経路を確認しています...
netplay-detail-matchmaking-fallback-stun = プライマリ STUN から応答がありません。{$service} を試しています...
netplay-detail-matchmaking-queueing = マッチメイキングのキューに参加しています...
netplay-detail-matchmaking-wait = {$wait}秒キュー待機中。待機プレイヤー: {$players}。
replay-stage-fallback = ステージ {$number}
replay-unknown-error = 不明なエラー
replay-title = リプレイ
replays-title = リプレイ
replay-watch-button = リプレイを見る
replay-settings-button = リプレイ設定
replay-refresh-button = 一覧を更新
replay-refreshing = 更新中...
replay-prev-button = 前のページ
replay-prev-disabled = 前のページ -
replay-next-button = 次のページ
replay-next-disabled = 次のページ -
replay-browser-scanning = リプレイフォルダーをスキャン中...
replay-browser-scan-failed = リプレイスキャンに失敗しました。
replay-browser-empty = リプレイが 0 件見つかりました。
replay-browser-page = {$first}-{$last} / {$count} 件 · ページ {$page}/{$pages}
replay-browser-loading = リプレイを読み込み中...
replay-browser-scanning-files = 保存されたリプレイファイルをスキャンしています。
replay-browser-scan-failed-detail = リプレイスキャンに失敗しました: {$error}
replay-browser-empty-slot = このスロットにリプレイはありません。
replay-browser-empty-list = 保存されたリプレイが見つかりません。
replay-browser-root-help = リプレイファイルはローカルのリプレイディレクトリから再帰的に読み込まれます。
replay-title-unreadable = 読み込み不可: {$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = 結果なし
replay-result-none-winner = 勝者: なし
replay-result-quit = 途中終了
replay-result-tie = 引き分け
replay-result-winner = 勝者: {$winner}
replay-action-participants = 参加者: {$players}
replay-action-duration = 再生時間: {$duration}
replay-action-duration-truncated = 再生時間: {$duration} (切り詰め)
replay-action-result = 結果: {$result}
replay-action-stage = ステージ: {$stage}
replay-action-mode = モード: {$mode}
replay-action-version = バージョン: {$version}
replay-action-file = ファイル: {$compression}; 切り詰め: {$truncated}
replay-compression-compressed = 圧縮
replay-compression-uncompressed = 非圧縮
replay-truncated-yes = はい
replay-truncated-no = いいえ

# ソーシャル機能と対戦CPUリスト
press-any-button-or-key = いずれかのボタンまたはキーを押してください
social-title = フレンドと招待
social-steam = Steam
social-steam-help = Steam にロビーを表示し、フレンドリストからフレンドが参加できるようにします。
social-discord = Discord
social-discord-help = Discord にロビーを表示し、フレンドが参加をリクエストできるようにします。
social-info = 初期設定ではオフです。有効にすると、連携機能がプラットフォームの SDK を読み込み、ロビー参加コードを共有してフレンドが参加できるようにします。接続には引き続き Antistatic 独自のネットプレイを使用します。
social-summary = Steam と Discord のリッチプレゼンスおよび招待。
social-settings-help = Steam と Discord のリッチプレゼンスおよび招待。初期設定では無効です。
versus-add-cpu = CPUを追加
versus-cpu-page-prev = 前へ
versus-cpu-page-next = 次へ
versus-cpu-page-help = 表示するCPUページを変更します。
versus-no-cpus-added = CPUが追加されていません
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# コントローラー調整
controller-calibration-title = コントローラー調整
controller-calibration-open = コントローラーを調整
controller-calibration-open-help = 選択中のローカルコントローラーを確認・調整します。
controller-calibration-online-blocked = オンラインプレイ中は調整できません。
controller-calibration-no-local-controller = ローカルコントローラーを接続して選択してください。
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = タグなし
controller-calibration-capability-no-axes = 調整可能な軸が報告されていません。
controller-calibration-capability-native-origin = ネイティブ原点データで自動調整できます。
controller-calibration-capability-absolute-no-automatic = 絶対値データあり。自動調整は利用できません。
controller-calibration-capability-sdl-normalized = SDL 正規化入力。手動調整のみです。
controller-calibration-suspicious-origin-warning = 自動原点を使う軸が 1 つ以上無視されました。下の代替詳細を確認してください。
controller-calibration-invalid-saved-warning = 保存済み調整を無視しました: {$reason}
controller-calibration-invalid-shaping-warning = 保存済みスティック設定を無視しました: {$reason}
controller-calibration-status-policy-preview = ポリシープレビュー
controller-calibration-status-manual-preview = 手動プレビュー
controller-calibration-status-modified = 変更済み
controller-calibration-status-current = 現在
controller-calibration-status-policy = ポリシー
controller-calibration-status-manual = 手動
controller-calibration-status-not-saved = 未保存
controller-calibration-status-saved = 保存済み
controller-calibration-status-active-differs = 使用中の設定は保存済みと異なります
controller-calibration-draft-status = {$intent} · 下書き {$draft} · 適用中 {$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = 自動調整: {$state}
controller-calibration-automatic-unavailable = 利用不可
controller-calibration-automatic-on = オン
controller-calibration-automatic-off = オフ
controller-calibration-automatic-policy-native-help = GameCube 原点の自動調整を切り替えます。
controller-calibration-automatic-policy-unavailable-help = この入力元では自動調整を利用できません。
controller-calibration-axis-left-x = 左スティック X
controller-calibration-axis-left-y = 左スティック Y
controller-calibration-axis-right-x = 右スティック X
controller-calibration-axis-right-y = 右スティック Y
controller-calibration-axis-left-trigger = 左トリガー
controller-calibration-axis-right-trigger = 右トリガー
controller-calibration-field-minimum = 最小
controller-calibration-field-center = 中央
controller-calibration-field-maximum = 最大
controller-calibration-field-released = 解放
controller-calibration-field-pressed = 押下
controller-calibration-value-na = N/A
controller-calibration-unit-gamecube-directed = GameCube 方向付きバイト
controller-calibration-unit-sdl-normalized = SDL 正規化
controller-calibration-unit-canonical-normalized = 正規化
controller-calibration-unit-gamecube-protocol-byte = GameCube プロトコルバイト
controller-calibration-axis-values-normalized = {$axis} · {$unit} · 入力 {$source} · 補正 {$corrected} · プレビュー {$preview} · ゲーム {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} 絶対 {$absolute}, 原点 {$origin} · {$sourceUnit} 入力 {$source} · {$normalizedUnit} 補正 {$corrected}, プレビュー {$preview}, ゲーム {$gameplay}
controller-calibration-axis-statistics = {$samples} サンプル · 最小 {$minimum} · 最大 {$maximum} · ピーク {$peak} · ジッター {$jitter} · {$unit}
controller-calibration-reported-buttons = 押下中: {$buttons}
controller-calibration-reported-buttons-none = なし
controller-calibration-capture-status-ready = 準備完了
controller-calibration-capture-status-waiting-release = すべて離してください
controller-calibration-capture-status-capturing = 取得中
controller-calibration-capture-status-captured = 取得済み
controller-calibration-capture-status-invalid = 取得失敗
controller-calibration-capture-neutral = ニュートラルを取得
controller-calibration-capture-range = 全範囲を取得
controller-calibration-capture-help = 指示時にすべて離し、取得操作を行ってください。
controller-calibration-stick-movement = 移動スティック
controller-calibration-stick-right = 右 / Cスティック
controller-calibration-shaping-deadzone = デッドゾーン
controller-calibration-shaping-cardinal-snap = 4方向スナップ
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting}: {$value}{$unit} · {$step}
controller-calibration-shaping-help = 左右または行の両側で調整 · 決定または行中央で微調整/粗調整を切替。
controller-calibration-adjust-value = {$axis} {$field}: {$value} {$unit} · {$step}
controller-calibration-step-fine = 微調整
controller-calibration-step-coarse = 粗調整
controller-calibration-adjust-help = 左右または行の両側で調整 · 決定または行中央で微調整/粗調整を切替。物理単位は入力元ごとに異なります。
controller-calibration-apply-current-connection = 現在の接続に適用
controller-calibration-save-to-tag = コントローラータグに保存
controller-calibration-save-to-tag-target = {$tag} ({$layout}) に保存
controller-calibration-save-to-tag-no-tag = タグに保存（タグ必須）
controller-calibration-reset-draft-active = 下書きを適用中の値に戻す
controller-calibration-reset-draft-saved = 下書きを保存値に戻す
controller-calibration-reset-draft-layout-defaults = 下書きをレイアウト初期値に戻す
controller-calibration-reset-session = 接続セッションをリセット
controller-calibration-delete-saved = 保存済み調整を削除
controller-calibration-delete-saved-confirm = 決定: 保存済み調整を削除
controller-calibration-copy-diagnostic = 診断情報をコピー
controller-calibration-action-help = 決定で実行します。
controller-calibration-applied = 現在の接続に調整を適用しました。
controller-calibration-save-tag-required = 保存には有効なコントローラータグが必要です。
controller-calibration-saved = {$tag} ({$layout}) に調整を保存しました。
controller-calibration-no-saved-calibration = このコントローラーに保存済み調整はありません。
controller-calibration-delete-saved-complete = 保存済み調整を削除しました。
controller-calibration-copy-diagnostic-complete = 調整診断をコピーしました。
controller-calibration-local-controllers = 他のローカルコントローラー
controller-calibration-switch-controller = コントローラーを切替
controller-calibration-switch-controller-name = {$controller} に切替
controller-calibration-switch-decision = {$controller} · 左 適用 · 右 {$save} · 決定 破棄
controller-calibration-switch-save-available = 保存
controller-calibration-switch-save-unavailable = 保存不可
controller-calibration-switch-decision-help = 未保存: 左で適用、右で保存、決定で破棄して切り替えます。
controller-calibration-back = 戻る
controller-calibration-back-help = コントロールへ戻ります。取得中の場合は先にキャンセルします。
controller-calibration-back-discard-confirm = 決定: 下書きを破棄して戻る
controller-calibration-disconnected-draft-discarded = コントローラー切断。調整の下書きを破棄しました。

# PhobGCC
controller-calibration-phob-board-unconfirmed = ボード未確認
controller-calibration-phob-board-v1 = PhobGCC v1 を選択します
controller-calibration-phob-board-v1-value = PhobGCC v1
controller-calibration-phob-board-v2 = PhobGCC v2 を選択します
controller-calibration-phob-board-v2-value = PhobGCC v2
controller-calibration-phob-calibrate-c-stick = C-stickを校正する: A+X+Y+R
controller-calibration-phob-calibrate-left = メインスティックの校正: A+X+Y+L
controller-calibration-phob-calibration-complete = 完了（キーボード/マウスのみ）
controller-calibration-phob-calibration-confirm = 確認: ファームウェアのキャリブレーションを開始します
controller-calibration-phob-calibration-help = コントローラー上で完了する必要があるファームウェア ワークフローを開始します。
controller-calibration-phob-calibration-no-cancel = コントローラー入力では中止も完了もできません。本体側の手順を終え、キーボード/マウスで「完了」を選んでください。進めない場合は抜き差ししてください。
controller-calibration-phob-calibration-phases = もう一方のスティックの指示に従い、中心・外周・ノッチの全手順を進めます。両方の段階を終えてから「完了」を選んでください。
controller-calibration-phob-enter-configure = Configure Modeと入力してください
controller-calibration-phob-enter-configure-instruction = 物理コントローラーで、両方のスティックが右上になるまで A+X+Y+Start を押し続けてから放します。
controller-calibration-phob-exit-safe-instruction = 物理コントローラーで、A+X+Y+Start を押します。右上の反応が長くなったら放します。
controller-calibration-phob-host-correction-stale = ファームウェア調整後の Antistatic 補正：使用中 {$active}、保存済み {$saved}。初期値を確認するか再取得してください。
controller-calibration-phob-instruction-none = 保留中のコマンドはありません
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = モード不明
controller-calibration-phob-open = PhobGCC ガイドを開く
controller-calibration-phob-open-guide-031 = 公式ファームウェア 0.31 ガイドを開く
controller-calibration-phob-open-help = ユーザーが確認した PhobGCC v1 または v2 のガイド付き読み取り専用チェック。
controller-calibration-phob-open-phobvision-029-v2 = PhobVision 0.29 ガイドを開く (装備されている v2 のみ)
controller-calibration-phob-open-release-031 = ファームウェア 0.31 リリース ノートを開く
controller-calibration-phob-open-version-guide = 報告されたファームウェアのオープンガイド
controller-calibration-phob-origin-checks = ファームウェア調整前に、必要なら物理 B でスティックを有効化し、アダプターが報告する原点を確認してください。
controller-calibration-phob-query-c-settings = C-stick 設定の読み取り: R+Start
controller-calibration-phob-query-main-settings = メインスティック設定の読み取り: L+Start
controller-calibration-phob-query-trigger-settings = トリガー設定の読み取り: L+R+Z
controller-calibration-phob-query-version = ファームウェア バージョンの読み取り: A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = 生診断が有効です。値は通常のコントローラーレポートによるファームウェア処理後の表示座標で、センサーの直接値でもゲームプレイ出力でもありません。
controller-calibration-phob-raw-disable = 生の出力を無効にする: L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = 物理コントローラーで、L+R+D-pad Down を押し、右上の応答を待ってからすべてを放します。
controller-calibration-phob-raw-enable = 生の出力を有効にする: L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = 物理コントローラーで、L+R+D-pad Up を押し、右上の応答を待ってからすべてを放します。
controller-calibration-phob-raw-values = ファームウェア処理後 メイン X {$leftX}、Y {$leftY}; C-stick X {$cX}、Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = 生の値は利用できません
controller-calibration-phob-remap-warning = コマンドは再割り当てに関係なく、外装表記どおりの物理ボタンを使います。Antistatic が受け取る報告ボタンとは異なる場合があります。
controller-calibration-phob-result-matched = Phob スタイルの応答が一致しました
controller-calibration-phob-result-none = まだ応答がありません
controller-calibration-phob-result-unknown-custom = 不明な応答またはカスタム応答
controller-calibration-phob-result-version-known = ファームウェア {$version}
controller-calibration-phob-result-version-no-response = ファームウェアが応答しません。バージョン不明
controller-calibration-phob-return-safe = Safe Modeに戻る
controller-calibration-phob-safe-recovery = Safe Mode を確実にするには、コントローラーを抜き差ししてください。その後ガイドを開き直してください。検出状態は切断時にリセットされます。
controller-calibration-phob-setting-c-response-x-raw = C-stick X 応答バイト
controller-calibration-phob-setting-c-response-y-raw = C-stick Y 応答バイト
controller-calibration-phob-setting-c-snapback-x = C-stick スナップバック X
controller-calibration-phob-setting-c-snapback-y = C-stick スナップバック Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick 波形整形 X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick ウェーブシェイピング X 生
controller-calibration-phob-setting-c-waveshaping-y = C-stick 波形整形 Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick ウェーブシェイピング Y raw
controller-calibration-phob-setting-main-smoothing-x = メインスティックスムージングX
controller-calibration-phob-setting-main-smoothing-y = メインスティックスムージングY
controller-calibration-phob-setting-main-snapback-x = メインスティックスナップバックX
controller-calibration-phob-setting-main-snapback-y = メインスティックスナップバックY
controller-calibration-phob-setting-main-waveshaping-x = メインスティックウェーブシェイピングX
controller-calibration-phob-setting-main-waveshaping-x-raw = メインスティックウェーブシェイピング×生
controller-calibration-phob-setting-main-waveshaping-y = メインスティックウェーブシェイピングY
controller-calibration-phob-setting-main-waveshaping-y-raw = メインスティック波形整形 Y raw
controller-calibration-phob-setting-row = {$setting}: {$value} {$unit}
controller-calibration-phob-setting-rows-none = デコードされた設定はありません
controller-calibration-phob-settings-c-stick-instruction = 物理コントローラーで、R+Start を 2 秒間読み出し続けてから放します。
controller-calibration-phob-settings-main-instruction = 物理コントローラーで、L+Start を 2 秒間読み出し続けてから放します。
controller-calibration-phob-settings-read-only = これらの読み出しはファームウェア設定を変更しません。変更とリセットについては公式の手順を使用してください。
controller-calibration-phob-settings-triggers-instruction = 物理コントローラーで、L+R+Z を 2 秒間読み出し続けてから放します。
controller-calibration-phob-setting-trigger-left-mode = 左トリガーモード
controller-calibration-phob-setting-trigger-left-value = 左トリガー値
controller-calibration-phob-setting-trigger-right-mode = 右トリガーモード
controller-calibration-phob-setting-trigger-right-value = 右トリガー値
controller-calibration-phob-setup-active = Phob Setup Mode 有効：報告 Dパッドで移動し、報告 A で決定します。
controller-calibration-phob-setup-enter = Phob Setup Modeと入力してください
controller-calibration-phob-setup-exit = Phob Setup Modeを終了します
controller-calibration-phob-setup-exit-chord = 終了するには、報告 Dパッド 下+左 + メインスティック右上 + C-stick右下だけを1秒間保持して放します。ファームウェア調整中は無効です。
controller-calibration-phob-stale-state-current = 現在
controller-calibration-phob-stale-state-stale = 古い
controller-calibration-phob-status = ボード: {$board} · モード: {$mode} · 結果: {$result} · ステップ: {$instruction} · {$raw} · 設定: {$rows}
controller-calibration-phob-unit-protocol-byte = プロトコルバイト
controller-calibration-phob-unit-setting-value = 設定値
controller-calibration-phob-unit-trigger-byte = トリガーバイト
controller-calibration-phob-unofficial-warning = PhobGCC 非公式・非提携ヘルパーです。基板とファームウェアを確認してください。Antistatic は機器を特定せず、設定も書き込みません。
controller-calibration-phob-version-instruction = Configure Mode では、物理的な A+Z+D-pad Up を押し、読み出しを 2 秒間押し続けてから放します。
controller-calibration-mode-basic = 表示：基本
controller-calibration-mode-advanced = 表示：詳細
controller-calibration-mode-toggle-help = よく使う設定と詳細な調整情報を切り替えます。
controller-calibration-origin-diagnostic-unavailable = この入力元では自動原点診断を利用できません。
controller-calibration-origin-diagnostic = 安定原点：{$phase} · {$reports} レポート · {$stable}/6 適用 · {$fallback}/6 既定値 · {$dropped} オーバーラン
controller-calibration-origin-phase-collecting = 取得中
controller-calibration-origin-phase-complete = 完了
controller-calibration-use-suggested-deadzones = 推奨デッドゾーンを使用
controller-calibration-use-suggested-deadzones-help = 測定した内側・外側デッドゾーンを下書きに適用します。
controller-calibration-section-stick-shaping = スティック調整
controller-calibration-section-trigger-shaping = トリガー調整
controller-calibration-section-action-diagnostics = アクション診断
controller-calibration-section-physical-diagnostics = 物理軸診断
controller-calibration-section-hardware-correction = ハードウェア補正
controller-calibration-shaping-inner-deadzone = 内側デッドゾーン
controller-calibration-shaping-outer-deadzone = 外側デッドゾーン
controller-calibration-snap-override-help = プレイヤー設定を切り替えます。ルールの最小値は常に適用されます。
controller-calibration-snap-override-state = {$stick} スナップ：{$state} · 最小 {$floor}° · 有効 {$effective}°
controller-calibration-override-enabled = 有効
controller-calibration-override-disabled = 無効
controller-calibration-trigger-shaping-help = 左右または行の両側で調整 · 決定または行中央で微調整/粗調整を切替。
controller-calibration-trigger-inner-deadzone = 内側デッドゾーン
controller-calibration-trigger-outer-deadzone = 外側デッドゾーン
controller-calibration-trigger-response-curve = 応答カーブ
controller-calibration-trigger-hard-press-threshold = 強押ししきい値
controller-calibration-trigger-shaping-value = {$trigger} {$setting}: {$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = 測定：移動ノイズ {$movementNoise}、内側 {$movementInner}、外側 {$movementOuter}、範囲 {$movementCoverage}/16 · 右ノイズ {$rightNoise}、内側 {$rightInner}、外側 {$rightOuter}、範囲 {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = トリガー：L ノイズ {$leftNoise}、内側 {$leftInner}、外側 {$leftOuter} · R ノイズ {$rightNoise}、内側 {$rightInner}、外側 {$rightOuter}
controller-calibration-stick-diagnostic = {$stick}: 入力 {$mapped} · ゲーム {$gameplay} · {$zone} · スナップ {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger}: 入力 {$mapped} · ゲーム {$gameplay} · {$zone} · 強押し {$hard}
controller-calibration-zone-inner-dead = 内側デッドゾーン
controller-calibration-zone-linear = 有効範囲
controller-calibration-zone-outer-saturated = 外側飽和
controller-calibration-state-yes = はい
controller-calibration-state-no = いいえ
controller-calibration-hard-source-none = なし
controller-calibration-hard-source-digital-button = デジタルクリック
controller-calibration-hard-source-analog-threshold = アナログしきい値
controller-calibration-help = 上下で移動 · 左右または行の両側で調整 · 決定または行中央で精度変更 · 戻るで前画面へ。
controller-calibration-tag-required-prerequisite = 調整前に「操作方法」でプレイヤータグを追加すると保存できます。現在の接続への適用は引き続き利用できます。
controller-calibration-status-draft-or-active-differs = 下書きまたは適用中の設定が保存済みと異なります
controller-calibration-capture-mode-neutral = ニュートラル
controller-calibration-capture-mode-range = 全範囲
controller-calibration-capture-accept-pending = {$mode}取得を確定
controller-calibration-capture-accept-and-start = {$pending}を確定後、{$next}を取得
controller-calibration-capture-status-pending = {$mode}取得は確認待ち
controller-calibration-legend-source = レイアウト初期値
controller-calibration-legend-corrected = 補正
controller-calibration-legend-preview = プレビュー
controller-calibration-legend-gameplay = ゲーム
controller-calibration-origin-fallback-detail = 代替: {$axes}
controller-calibration-origin-fallback-axis = {$axis}: {$reason}
controller-calibration-origin-reason-insufficient-reports = 正常なレポート不足。操作を離して再接続してください
controller-calibration-origin-reason-unstable = 入力が動きました。操作を離して再接続してください
controller-calibration-origin-reason-implausible = 原点が想定範囲外です。操作を離して再接続してください
controller-calibration-origin-reason-unsafe-bounds = 原点による補正が安全ではありません。ニュートラルと全範囲を取得してください
controller-calibration-phob-setup-suspended-raw = 生診断中は Phob Setup Mode が一時停止します。生出力を無効にすると再開します。
controller-calibration-phob-result-version-custom = カスタムファームウェア応答: X {$x}、Y {$y}
controller-calibration-phob-result-unknown = 認識できない応答
controller-calibration-phob-raw-mode-off = 生モードオフ

# プライバシー、レポート、フィードバック
privacy-title = プライバシー
privacy-settings-help = ネットワーク、クラッシュレポート、匿名統計、フィードバックを管理します。
privacy-networking = ネットワーク接続
privacy-networking-help = オンラインプレイと全 Antistatic サービスの一括設定です。オフにするとオンライン接続が切断されます。
privacy-crash-reporting = クラッシュレポート：{$value}
privacy-crash-reporting-help = 匿名のクラッシュ診断を送る前に確認するかを選びます。
privacy-crash-ask = 毎回確認
privacy-crash-never = 送信しない
privacy-crash-always = 常に送信
privacy-gameplay-metrics = 匿名のプレイ統計
privacy-gameplay-metrics-help = モード、キャラクター、対戦時間、結果などの大まかなデータ送信に同意します。
privacy-performance-metrics = 匿名のパフォーマンス統計
privacy-performance-metrics-help = 性能改善のため、大まかな機器情報とフレーム時間の送信に同意します。
privacy-feedback-open = フィードバックを送信
privacy-feedback-open-help = 不具合報告やその他の意見を Antistatic チームへ送ります。
privacy-policy-open = プライバシーポリシーを表示
privacy-policy-open-help = Antistatic の公式プライバシーポリシーを読みます。
privacy-policy-title = プライバシーポリシー
privacy-policy-help = このポリシーでは、ネットワーク接続、クラッシュレポート、任意の統計、フィードバックの扱いを説明します。
privacy-crash-send-pending = 保留中のレポートを送信
privacy-crash-send-pending-help = 同意待ちのクラッシュレポートを送ります。
privacy-crash-discard-pending = 保留中のレポートを破棄
privacy-crash-discard-pending-help = クラッシュレポートを送信せず完全に削除します。
privacy-summary = ネットワークは初期状態でオンです。クラッシュレポートは選択制で、匿名統計は同意するまでオフです。
privacy-netplay-disabled = ネット対戦は無効です
privacy-netplay-disabled-help = ネット対戦を使うには、プライバシー設定でネットワーク接続をオンにしてください。
privacy-crash-prompt-title = クラッシュレポート
privacy-crash-prompt-body = 保留中のクラッシュレポートがあります。安定性向上のため匿名の診断情報を送信しますか？
privacy-crash-prompt-send = レポートを送信
privacy-crash-prompt-later = 後で確認
privacy-crash-prompt-never = クラッシュレポートを送信しない
privacy-crash-prompt-summary = このレポートを送るか、後で決めるか、レポートを無効にするか選んでください。
privacy-report-sending = 送信中...
privacy-report-failed = 送信できませんでした。ネットワークを確認して再試行してください。
privacy-crash-sent = クラッシュレポートを送信しました
privacy-crash-discarded = クラッシュレポートを破棄しました
privacy-feedback-title = フィードバック
privacy-feedback-category = 種類：{$value}
privacy-feedback-category-help = 送信する内容の種類を選びます。
privacy-feedback-category-bug = 不具合
privacy-feedback-category-feedback = ご意見
privacy-feedback-category-other = その他
privacy-feedback-subject = 件名
privacy-feedback-subject-help = 短い概要を入力してください。
privacy-feedback-subject-placeholder = 短い概要
privacy-feedback-body = メッセージ
privacy-feedback-body-help = 問題や提案を説明してください。個人情報は入力しないでください。
privacy-feedback-body-placeholder = お気づきの点をお書きください
privacy-feedback-submit = フィードバックを送信
privacy-feedback-submit-help = このメッセージを Antistatic チームへ送ります。
privacy-feedback-warning = 個人情報、パスワード、非公開のアカウント情報は入力しないでください。
privacy-feedback-help = 件名とメッセージを入力して、フィードバックを送信してください。
privacy-feedback-required = 件名とメッセージの両方を入力してください。
privacy-feedback-sent = フィードバックを送信しました。レポート ID：{$id}
