hello-world = 안녕, 세상! { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = 규소
Iron = 철
Xenon = 제논
Helium = 헬륨
Carbon = 탄소
Rhodium = 로듐

Sandbag = 샌드백

Ruins = 유적
Transistor = 트랜지스터
Eroded = 침식
Scales = 저울
Crossing = 교차점
Longboat = 대형 보트
Boombox = 붐 박스
Fountain = 분수
Great-White = 그레이트 화이트
Plane = 평면
Satellite = 위성
Divided = 각기 다른
Pillars = 기둥
Debug = 디버그

mode-Antistatic = {Antistatic}
mode-19XX = 19XX

# Navigation
Back = 뒤로
Exit = 나가기
Save = 저장
Cancel = 취소
Close-Symbol = X

Modify = 수정
Reset = 초기화

# Main Menu
Versus = 대전 모드
Training = 트레이닝
battle-results = 배틀 결과
Settings = 설정
Controls = 조작 방식
Discord = Discord {"\u29C9"}
Guide = 가이드 {"\u29C9"}

# Settings Menu
SETTINGS = 설정
Audio = 오디오
Video = 영상
Windowed = 창 모드
Fullscreen = 전체화면

main = 메뉴
versus = 대전 모드
training = 트레이닝
start-mode = 스타트: { TRANSLATE($value) }

# Audio Menu
AUDIO = 오디오

Play-Audio = 오디오 재생
Play-Music = 음악을 재생

Audio-volume = 음량: {$value}
SFX-volume = SFX : {$value}
Music-volume = 음악: {$value}
UI-volume = UI: {$value}
Voice-volume = 음성: {$value}

# Video Menu
VIDEO = 영상

vsync-off = Vsync: 끄기
vsync-on = Vsync: 켜기
vsync-adaptive = Vsync: 적응형

shadow-off = 그림자: 끄기
shadow-low = 그림자: 낮음
shadow-highest = 그림자: 높음

ssao-off = SSAO: 끄기
ssao-on = SSAO: 켜기
ssao-full = SSAO: 풀

aa-off = 안티앨리어싱: 끄기
aa-fxaa = 안티앨리어싱: FXAA

bloom-off = Bloom: 끄기
bloom-on = Bloom: 켜기
reflections-off = 반사: 끄기
reflections-on = 반사: 켜기

perf-overlay-off = 성능 표시: 끄기
perf-overlay-on = 성능 표시: 켜기


point-lights-off = 점광원: 끄기
point-lights-on = 점광원: 켜기

particles-low = 파티클: 낮음
particles-medium = 파티클: 중간
particles-full = 파티클: 높음


max-fps-off = 최대 FPS: 끄기
max-fps-30 = 최대 FPS: 30
max-fps-60 = 최대 FPS: 60
max-fps-120 = 최대 FPS: 120
max-fps-144 = 최대 FPS: 144

# Controls Menu
CONTROLS = 조작 방식

controls-title = 조작 방식
controls-section-controllers = 컨트롤러
controls-section-mappings = 매핑
controls-set-tag = 태그 설정
controls-edit-bindings = 버튼 설정 편집
controls-tag-untagged = (태그 없음)
controls-tag-title = 플레이어 태그
controls-tag-prompt = P{$port} ({$layout}). 태그는 1-24자의 영숫자, "-", "_"를 사용할 수 있습니다. 지우려면 비워두세요.
controls-tag-confirm = 확인
controls-tag-clear = 지우기
controls-tag-cancel = 취소
controls-tag-select-title = 태그 선택
controls-tag-filter-empty = 입력해서 저장된 태그 필터링
controls-tag-filter-value = 필터: {$filter}
controls-tag-summary-empty = 저장된 태그 {$total}개. 입력해서 필터링하거나 새 태그를 만드세요.
controls-tag-summary-filter = 저장된 태그 {$total}개 중 {$visible}개 표시. 정확히 일치하면 저장된 조작 설정을 사용합니다.
controls-tag-defaults-suffix = 이 컨트롤러의 기본값
controls-tag-create-new = 새 태그 만들기
controls-tag-use-existing = 기존 태그 "{$tag}" 사용
controls-tag-create = "{$tag}" 만들기
controls-tag-reserved = "{$tag}"은(는) 예약되어 있습니다
controls-tag-netplay-blocked = 넷플레이 중에는 태그를 변경할 수 없습니다
controls-tag-no-controller = 선택된 로컬 컨트롤러가 없습니다
controls-tag-no-layout = 선택한 컨트롤러에 레이아웃이 없습니다
controls-tag-filter-help = 입력해서 태그를 필터링하세요. ESC는 지우거나 나갑니다
controls-tag-no-saved = 저장된 태그가 아직 없습니다
controls-tag-no-matches = 일치하는 태그가 없습니다
controls-tag-invalid = 잘못된 태그입니다(1-24자, 영숫자/-/_; "default" 예약됨)
controls-profile-help-untagged = 조작 설정을 편집하거나 탭 점프 기본값을 저장하기 전에 태그를 설정하세요.
controls-profile-help-tagged = 조작 설정과 탭 점프 기본값은 이 태그와 이 컨트롤러 유형에 저장됩니다.
controls-choose-existing-tag = 기존 태그 선택
controls-create-tag = 태그 만들기
controls-rename-create-tag = 태그 이름 변경/만들기
controls-edit-set-tag-first = 조작 설정 편집(먼저 태그 설정)
controls-edit-controls = 조작 설정 편집
controls-tap-jump-default = 탭 점프 기본값: {$state}
controls-state-on = 켬
controls-state-off = 끔
controls-netplay-blocked = 넷플레이 중에는 조작 설정을 변경할 수 없습니다
controls-no-local-controllers = 연결된 로컬 컨트롤러가 없습니다
controls-no-layout = 컨트롤러에 레이아웃이 없습니다
controls-set-tag-before-editing = 조작 설정을 편집하기 전에 태그를 설정하세요
controls-no-mapping = 이 컨트롤러에 사용할 수 있는 매핑이 없습니다
controls-set-tag-before-tap-jump = 탭 점프 기본값을 저장하려면 태그를 설정하세요
controls-connected-controllers = 연결된 컨트롤러
controls-remap-add-key = + 바인딩 추가(키 누르기)
controls-remap-find-input = 바인딩 찾기(입력 누르기)
controls-remap-capture-key-title = 키를 누르세요
controls-remap-capture-input-title = 입력을 누르세요
controls-remap-capture-key-help = 다음에 누르는 키가 새 바인딩으로 추가됩니다.
controls-remap-capture-input-help = 다음에 누르는 버튼 또는 스틱이 편집 대상으로 선택됩니다.
controls-remap-capture-cancel = ESC로 취소
controls-default-save-blocked = 기본 조작 설정은 덮어쓸 수 없습니다. 먼저 태그를 설정하세요
controls-default-reset-blocked = 이 메뉴에서는 기본 조작 설정을 초기화할 수 없습니다
controls-tag-filter-entry-help = 저장된 컨트롤러 태그를 필터링하려면 입력하세요. 게임패드는 방향 패드를 사용할 수 있습니다.
controls-tag-filter-label = 필터
controls-tag-preconfigured = 사전 설정됨
controls-tag-rename-title = 태그 이름 바꾸기
controls-tag-create-title = 태그 만들기
controls-tag-apply-existing-help = 일치하는 저장된 태그를 이 컨트롤러에 적용합니다.
controls-tag-create-empty-help = 이 컨트롤러용 새 태그를 만듭니다.
controls-tag-create-filtered-help = 이름이 유효하면 이 태그를 컨트롤러용으로 만듭니다.
controls-tag-apply-saved-help = 이 태그와 저장된 매핑을 컨트롤러에 적용합니다.
controls-tag-apply-preconfigured-help = 이 컨트롤러 유형의 기본 매핑으로 이 사전 설정 태그를 적용합니다.
controls-tag-apply-default-help = 이 컨트롤러 유형의 기본 매핑으로 이 태그를 적용합니다.
controls-tag-delete-button = {$tag} 삭제
controls-tag-delete-help = 확인 후 {$tag}와 저장된 조작 설정을 삭제합니다.
controls-tag-delete-title = 태그를 삭제할까요?
controls-tag-delete-body = "{$tag}"와 저장된 조작 설정을 삭제할까요?
controls-tag-delete-warning = 이 작업은 되돌릴 수 없습니다.
controls-back-help = 컨트롤로 돌아갑니다.
controls-tag-select-help = 컨트롤러 태그를 선택하거나 만드세요.
controls-edit-set-tag-first-help = 먼저 컨트롤러 태그를 만든 뒤 게임플레이와 메뉴 바인딩을 수정하세요.
controls-edit-controls-help = 이 컨트롤러 태그의 게임플레이와 메뉴 바인딩을 수정합니다.
controls-tap-jump-set-tag-first-help = 먼저 컨트롤러 태그를 만든 뒤 기본 탭 점프 설정을 지정하세요.
controls-tap-jump-default-help = 위를 눌렀을 때 이 컨트롤러가 기본적으로 점프할지 전환합니다.
controls-create-new-tag-help = 새 태그를 만들고 이 컨트롤러를 그 태그로 전환합니다.
controls-choose-existing-tag-help = 저장된 태그를 선택하거나 삭제합니다.
controls-rename-current-tag-help = 현재 컨트롤러 태그의 이름을 바꿉니다.
controls-switch-controller-help = 컨트롤 메뉴를 이 연결된 컨트롤러로 전환합니다.
menu-binding-hint = 스틱 또는 D-pad로 이동 · 확인/Start로 선택 · 뒤로 돌아가기
menu-adjust-hint = 스틱 또는 D-pad로 이동 · 왼쪽/오른쪽으로 값 변경 · 확인으로 선택 · 뒤로 돌아가기
menu-bind-hint = 스틱 또는 D-pad로 이동 · 확인으로 바인딩 선택 · 뒤로 돌아가기
arcade-select-leave = Select로 나가기
main-help-about-help = 가이드, 크레딧, bluehexagons 링크.
main-replays-available-help = 저장된 리플레이 파일을 찾아보고 미리 보거나 재생합니다.
main-replays-unavailable-help = 리플레이는 로컬 파일 시스템에서 불러오므로 오프라인에서만 사용할 수 있습니다.
arcade-menu-battles-help = 현재 Arcade Battles 설정으로 시작합니다.
arcade-menu-infinite-help = 점점 강해지는 1스톡 CPU와 끝없는 Arcade 모드를 시작합니다.
arcade-menu-training-help = 연습 도구와 세이브스테이트가 있는 훈련 모드를 엽니다.
arcade-menu-back-help = 메인 메뉴로 돌아갑니다.
arcade-menu-help = 아케이드 모드를 선택하세요.
help-bluehex-homepage-help = bluehexagons 홈페이지를 엽니다.
help-bluehex-github-help = GitHub에서 bluehexagons 프로젝트를 둘러봅니다.
help-bluehex-steam-help = bluehexagons Steam 큐레이터 페이지를 엽니다.
help-bluehex-itch-help = bluehexagons itch.io 페이지를 엽니다.
help-bluehex-bluesky-help = Bluesky에서 bluehexagons를 팔로우합니다.
help-bluehex-patreon-help = Patreon에서 bluehexagons를 후원합니다.
controls-source-keyboard = 키보드
controls-source-keyboard-defaults = 키보드 기본값
controls-current-menu-controls-heading = 현재 메뉴 조작
controls-current-menu-controls-summary = {$source} · 이동: {$navigate} · 선택: {$confirm} · 뒤로: {$back}
controls-action-attack = 공격
controls-action-jump = 점프
controls-action-special = 특수기
controls-action-grab = 잡기
controls-action-shield-1 = 실드 1
controls-action-shield-2 = 실드 2
controls-action-hard-shield-1 = 강실드 1
controls-action-hard-shield-2 = 강실드 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-pad 위
controls-action-dpad-down = D-pad 아래
controls-action-dpad-left = D-pad 왼쪽
controls-action-dpad-right = D-pad 오른쪽
controls-action-move-horizontal = 수평 이동
controls-action-move-vertical = 수직 이동
controls-action-right-stick-horizontal = 오른쪽 스틱 가로
controls-action-right-stick-vertical = 오른쪽 스틱 세로
controls-action-ui-confirm = UI 확인
controls-action-ui-back = UI 뒤로
controls-action-ui-up = UI 위
controls-action-ui-down = UI 아래
controls-action-ui-left = UI 왼쪽
controls-action-ui-right = UI 오른쪽
controls-action-ui-horizontal-nav = UI 가로 이동
controls-action-ui-vertical-nav = UI 세로 이동
controls-action-move-left = 왼쪽으로 이동
controls-action-move-right = 오른쪽으로 이동
controls-action-move-up = 위로 이동
controls-action-move-down = 아래로 이동
controls-action-tilt-left = 약하게 왼쪽
controls-action-tilt-right = 약하게 오른쪽
controls-action-tilt-up = 약하게 위
controls-action-tilt-down = 약하게 아래
controls-action-right-stick-left = 오른쪽 스틱 왼쪽
controls-action-right-stick-right = 오른쪽 스틱 오른쪽
controls-action-right-stick-up = 오른쪽 스틱 위
controls-action-right-stick-down = 오른쪽 스틱 아래
controls-action-light-shield-l = 약실드 L
controls-action-light-shield-r = 약실드 R
controls-action-ui-nav-left = UI 왼쪽 이동
controls-action-ui-nav-right = UI 오른쪽 이동
controls-action-ui-nav-up = UI 위 이동
controls-action-ui-nav-down = UI 아래 이동
controls-remap-section-buttons = 버튼
controls-remap-section-dpad = D-pad
controls-remap-section-movement = 이동
controls-remap-section-tilts = 약한 이동
controls-remap-section-right-stick = 오른쪽 스틱
controls-remap-section-light-shields = 약실드
controls-remap-section-ui-navigation = UI 탐색
controls-remap-section-sticks-triggers = 스틱과 트리거
controls-remap-unbound = 미할당
controls-remap-free-keys-none = 남은 키: (공통 세트 없음)
controls-remap-more-suffix = , +{$count}개 더
controls-remap-free-keys = 남은 키: {$keys}{$suffix}
controls-remap-free-buttons = 남은 버튼: {$buttons}
controls-remap-free-axes = 남은 축: {$axes}
controls-remap-conflict-detail = {$input}은(는) 이미 {$actions}에 바인딩되어 있습니다.
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = 메뉴 사용을 위해 UI 확인과 UI 뒤로 바인딩을 최소 하나씩 남겨 두세요.
controls-remap-capture-key-hint = {$action}에 사용할 키보드 키를 누르세요. ESC는 취소입니다.
controls-remap-capture-button-hint = {$action}에 사용할 {$layout} 버튼을 누르세요. 뒤로는 취소입니다.
controls-remap-capture-axis-hint = {$action}에 사용할 {$layout} 스틱/트리거를 움직이세요. 뒤로는 취소입니다.
controls-remap-capture-add-title = {$action} 추가
controls-remap-capture-replace-title = {$action} 교체
controls-remap-capture-matching-input = 이 동작에 맞는 입력을 사용하세요.
controls-remap-confirm-reassign = {$action}에 다시 할당하려면 확인하세요.
controls-remap-confirm-cancel-help = 확인하면 교체되고, 뒤로는 취소합니다.
controls-remap-command-add = 추가
controls-remap-command-replace = 교체
controls-remap-command-remove = 제거
controls-remap-add-help = {$action}에 다른 물리 입력을 추가합니다.
controls-remap-replace-help = {$action}의 {$input}을 교체합니다.
controls-remap-remove-help = {$action}에서 {$input}을 제거합니다.
controls-remap-back-to-controls = 컨트롤로 돌아가기
controls-remap-back-to-controls-help = 재매핑 목록 맨 아래까지 스크롤하지 않고 컨트롤로 돌아갑니다.
controls-remap-help = 추가, 교체, 제거 중 하나를 고르세요. Page 키로 목록을 건너뜁니다.
controls-remap-help-extended = 추가, 교체, 제거 중 하나를 고르세요. Page 키로 목록을 건너뜁니다. 뒤로는 취소입니다.
controls-remap-jump-to-section = 섹션으로 이동
controls-remap-jump-to-binding = {$section}(으)로 이동
controls-remap-focus-section-help = {$section}의 첫 번째 바인딩으로 포커스를 이동합니다.
controls-remap-reset-help = 이 태그 프로필을 기본 레이아웃으로 재설정합니다. 두 번 확인이 필요합니다.
controls-remap-reset-confirm = 다시 눌러 재설정을 확인하세요

standard = 표준
keyboard = 키보드
gcn_native = GCN 네이티브

# Training Menu
Swap-Character = 캐릭터 교체
Overlays = 오버레이
press-start = ‘시작’을 누르세요

drawHitbubbleInfo = 공격 정보
drawECB = 충돌
drawHeatmap = 히트 맵
drawRawPosition = 원시 위치
drawStage = 스테이지 충돌
animations = 애니메이션
controllers = 컨트롤러

# Versus Menu
FFA = FFA
Teams = 팀

Host-Netplay = 호스트 넷 플레이
Join-Netplay-Clipboard = 클립 보드에서 Netplay에 참여
Disconnect = 연결 해제
Copy-Lobby-Code = 로비 코드 복사

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = 직접 연결
Connect = Connect

netplay-action-start-lobby = 로비 시작
netplay-action-join-clipboard = 클립보드에서 참여
netplay-action-quick-host-copy-code = 퀵 호스트 & 코드 복사
netplay-action-copy-lan-invite = LAN 초대 복사
netplay-action-copy-localhost-invite = Localhost 초대 복사
netplay-action-copy-stun-invite = STUN 초대 복사
netplay-action-find-random-match = 랜덤 매치 찾기
netplay-action-cancel-lobby = 로비 취소
netplay-action-cancel-connection = 연결 취소
netplay-action-please-wait = 잠시 기다려 주세요
netplay-action-open-versus = Versus 열기
netplay-action-cancel-matchmaking = 매치메이킹 취소

netplay-status-label = 넷플레이: {$status}
netplay-status-uninitialized = 초기화되지 않음
netplay-status-initialized = 초기화됨
netplay-status-waiting = 대기 중
netplay-status-hosting = 호스팅 중
netplay-status-connecting = 연결 중
netplay-status-establishing = 설정 중
netplay-status-connected = 연결됨
netplay-status-ready = Netplay 준비 완료
netplay-status-waiting-player = 플레이어 참여 대기 중
netplay-status-waiting-lobby = 로비 응답 대기 중
netplay-status-hosting-lobby = 로비 호스팅 중
netplay-status-hosting-lobby-code = 로비 호스팅 중 {$code}
netplay-status-starting-lobby = 로비 시작 중
netplay-status-connecting-host = 호스트에 연결 중
netplay-status-connected-host = 호스트로 연결됨
netplay-status-connected-client = 호스트에 연결됨
netplay-status-disconnecting = 연결 해제 중
netplay-status-canceling = 연결 취소 중
netplay-status-matchmaking = 랜덤 매치 검색 중
netplay-status-match-found = 랜덤 매치 찾음
netplay-status-matchmaking-canceling = 매치메이킹 취소 중
netplay-status-error = Netplay 오류
netplay-status-error-message = Netplay 오류: {$error}
netplay-status-unavailable = Netplay 상태 사용 불가

matchmaking-title = 매치메이킹
matchmaking-status-select-character = 대기열에 넣을 캐릭터를 선택하세요
matchmaking-status-no-controller = 연결된 컨트롤러가 없습니다
matchmaking-status-searching = 상대를 찾는 중...
matchmaking-status-searching-details = 검색 중... {$wait}초 경과. 대기 중인 플레이어: {$players}. 최장 대기 시간: {$longest}초.
matchmaking-status-searching-estimate = 검색 중... {$wait}초 경과. 대기 중인 플레이어: {$players}. 완료된 매치 평균 시간: {$average}초.
matchmaking-status-canceling = 취소 중...
matchmaking-status-found = 매치를 찾았습니다!
matchmaking-status-connecting = 연결 중...
matchmaking-status-disconnecting = 연결 해제 중...
matchmaking-status-error = {$error} 다시 시도하려면 캐릭터를 선택하세요.

netplay-detail-ready = 로비를 호스트하거나, 복사한 초대를 붙여넣거나, 주소를 수동으로 입력하세요.
netplay-detail-lobby-code-ready = 로비 코드 {$code}가 공유할 준비가 되었습니다.
netplay-detail-creating-lobby-code = 로비 코드 생성 중.
netplay-detail-waiting-for-host = 호스트가 참여 요청에 응답하기를 기다리는 중.
netplay-detail-share-lobby-code = 로비 코드 {$code}를 다른 플레이어와 공유하세요.
netplay-detail-starting-lobby = 로비 연결 시작 중.
netplay-detail-joining-host = 선택한 호스트에 참여 시도 중.
netplay-detail-establishing = 플레이어 찾음. 핸드셰이크를 마치고 Versus를 여세요.
netplay-detail-connected = 연결 준비 완료. Versus를 열어 규칙, 캐릭터, 스테이지를 선택하세요.
netplay-detail-disconnecting = 현재 세션을 닫고 오프라인 플레이로 돌아갑니다.
netplay-detail-canceling = 현재 참여 요청 중지 중.
netplay-detail-matchmaking = Versus를 사용하여 선호하는 규칙으로 랜덤 상대를 기다립니다.
netplay-detail-match-found = 상대를 찾았습니다. 두 플레이어가 준비되면 Versus에서 설정을 마치세요.
netplay-detail-matchmaking-canceling = 현재 랜덤 매치 검색 중지 중.
netplay-detail-error-message = 마지막 오류: {$error}
netplay-detail-error-generic = 문제가 발생했습니다. 다른 코드나 연결 방법을 시도하세요.
netplay-detail-unavailable = Netplay 세부정보 사용 불가.

netplay-help-host-copy-code = 다른 플레이어가 붙여넣을 수 있도록 로비 코드를 복사하세요.
netplay-help-host-cancel-join = 현재 참여 시도를 중지하고 준비 상태로 돌아갑니다.
netplay-help-host-disconnect = 현재 넷플레이 세션을 나갑니다.
netplay-help-host-start-lobby = 새 로비를 시작하고 다른 플레이어가 참여하기를 기다립니다.
netplay-help-busy = Netplay이 현재 사용 중입니다. 완료될 때까지 기다리세요.
netplay-help-join-cancel-lobby = 현재 로비를 닫고 다른 플레이어를 기다리는 것을 중지합니다.
netplay-help-join-in-progress = 참여가 이미 진행 중입니다. 기다리거나 연결 취소를 사용하세요.
netplay-help-join-open-versus = Versus로 계속해서 매치 설정을 마치세요.
netplay-help-stop-random-search = 랜덤 상대 검색 중지.
netplay-help-join-clipboard = 클립보드에서 로비, 다이렉트, STUN 초대 코드를 붙여넣으세요.
netplay-help-copy-server = 필요한 경우 로비를 시작한 다음 공유 가능한 로비 코드를 복사하세요.
netplay-help-copy-direct = 이 LAN의 다른 장치용 다이렉트 연결 초대를 복사합니다.
netplay-help-copy-localhost = 이 컴퓨터에서 실행 중인 다른 복사본용 다이렉트 연결 초대를 복사합니다.
netplay-help-copy-stun = 인터넷에서 사용하기 더 쉬운 STUN 지원 초대를 복사합니다.
netplay-help-direct-connect = 복사한 초대 코드를 사용하는 대신 주소를 수동으로 입력합니다.
netplay-help-find-random-match = Versus를 열고 랜덤 상대를 기다립니다.
netplay-help-open-versus = 이 화면을 떠나지 않고 Versus 메뉴를 엽니다.
netplay-help-back = 메인 메뉴로 돌아갑니다.
netplay-help-unavailable = Netplay 작업 도움말 사용 불가.
netplay-help-advanced = 롤백 및 버퍼 같은 고급 넷플레이 설정을 조정합니다.

ADVANCED-CONNECTIONS = 고급 연결
netplay-settings-rollback-help = 온라인 매치에서 롤백 시뮬레이션을 켜거나 끕니다.
netplay-settings-buffer-help = 입력 프레임을 몇 개 버퍼링할지 선택하거나 넷플레이가 자동으로 고르게 합니다.
netplay-settings-force-ipv4-help = 혼합 네트워크에서 LAN 초대 코드를 만들 때 IPv4를 우선합니다.
netplay-settings-back-help = 넷플레이 메뉴로 돌아갑니다.
netplay-advanced-info = Quick Play나 일반 로비 코드로 연결할 수 없을 때 사용할 대체 옵션입니다. STUN은 인터넷 플레이를 위해 라우터를 통과하도록 도와줍니다. 직접 연결은 LAN 플레이나 UDP 포트를 포워딩한 호스트에 가장 적합합니다.
netplay-advanced-direct-help = 수동 대체 옵션입니다. LAN 플레이 또는 호스트가 UDP 포트를 포워딩한 경우 host:port를 입력하세요.
netplay-advanced-stun-help = 인터넷 대체 옵션입니다. 일반 로비 참가가 실패하고 라우터 지원 hole punching이 아직 필요할 때 이것을 공유하세요.
netplay-advanced-lan-help = LAN 대체 옵션입니다. 두 플레이어가 같은 네트워크에 있을 때 도달 가능한 로컬 주소를 공유하세요.
netplay-advanced-localhost-help = 테스트용 대체 옵션입니다. 두 클라이언트가 같은 장치에서 실행 중일 때만 사용하세요.
netplay-advanced-back-help = 버추얼 카우치로 돌아갑니다.
netplay-rollback-off = 롤백: 끔
netplay-rollback-on = 롤백: 켬
netplay-buffer-auto = 네트워크 버퍼: 자동
netplay-buffer-2 = 네트워크 버퍼: 2
netplay-buffer-3 = 네트워크 버퍼: 3
netplay-buffer-4 = 네트워크 버퍼: 4
netplay-buffer-5 = 네트워크 버퍼: 5
netplay-buffer-6 = 네트워크 버퍼: 6
netplay-buffer-7 = 네트워크 버퍼: 7
netplay-buffer-8 = 네트워크 버퍼: 8
netplay-buffer-10 = 네트워크 버퍼: 10
netplay-buffer-12 = 네트워크 버퍼: 12
netplay-force-ipv4-dual = LAN 주소: IPv6/IPv4
netplay-force-ipv4-v4 = LAN 주소: IPv4 강제

netplay-rollback = 롤백
netplay-buffer = 네트워크 버퍼
netplay-force-ipv4 = LAN 주소

netplay-direct-connect-prompt = IP 주소:포트를 입력하세요. 포트 기본값은 {$port}입니다.
netplay-stun-connect-title = STUN 서비스를 사용할까요?
netplay-stun-connect-prompt = 이 코드는 {$service}를 사용하여 {$address}:{$port}를 찾았습니다.
netplay-waiting-host-battle = 호스트의 전투가 끝날 때까지 대기 중
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = 캐릭터
Stages = 스테이지
AI = AI

Starter = 스타터
Legal = 공식
Miscellaneous = 기타

Start-Battle = 전투 시작

# Start Menu
quit-info = 방패 + 공격 + 시작으로 종료
paused = 일시 중지됨
tag-info = D-패드 위/아래로 태그 인/아웃

# Pause Menu
pause-resume = 계속
pause-restart = 다시 시작
pause-quit = 종료
pause-players = 플레이어
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = 컨트롤러를 연결하고 아무 버튼이나 눌러 참가하세요.
arcade-return-prompt = 확인을 눌러 메인 메뉴로 돌아갑니다.

# Replay
replay-paused = 재생 일시 중지됨
replay-controls = 확인: 참가  ←/→: 프레임  뒤로: 메뉴  리플레이 저장: [키]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = 영어
spanish = 스페인어
french = 프랑스어
italian = 이탈리아어
german = 독일어
russian = 러시아어
japanese = 일본어
chinese-cn = 중국어 간체
chinese-hk = 중국어 번체
korean = {ko-korean}

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean}

# Placeholder UI strings
Advanced = 고급
Clear-Spawns = 스폰 지우기
Create-new-tag = 새 태그 만들기
Credits = 크레딧
CREDITS = 크레딧
Cycle-Palette = 팔레트 변경
Delete = 삭제
Help = 도움말
HELP = 도움말
Join = 참가
Join-Lobby-Code = 로비 코드로 참가
Main-Menu = 메인 메뉴
Mode = 모드
Native-Adapter = 네이티브 어댑터
NATIVE-ADAPTER = 네이티브 어댑터
NETPLAY-SETTINGS = 넷플레이 설정
Other-saved-tags = 다른 저장된 태그
Profiles-for-this-controller-type = 이 컨트롤러 유형용 프로필
Quick-Play = 빠른 대전
Random-Color = 랜덤 색상
Rename-current-tag = 현재 태그 이름 바꾸기
Reset-to-Defaults = 기본값으로 재설정
Set-Character = 캐릭터 설정
Spawn-CPU = CPU 생성
Team = 팀
Virtual-Couch = 버추얼 카우치
x = x
Find-Random-Match = 무작위 대전 찾기
training-label-stage = 스테이지
training-label-character = 캐릭터
training-label-player-cursor = 플레이어 커서
training-label-cpu-spawn = CPU 생성
training-label-savestate = 상태 저장
Save-State = 상태 저장
Load-State = 상태 불러오기
State-Saved = 상태 저장됨
State-Restored = 상태 복원됨
No-State-Saved = 저장된 상태 없음
DPad-Right-Save-Left-Load = D-pad 오른쪽 저장 · 왼쪽 불러오기
shared-main-menu-help = 메인 메뉴로 돌아갑니다.
shared-mode-selector-label-help = 규칙 선택기 라벨입니다.
training-mode-selector-help = Antistatic과 19XX 훈련 상수를 전환합니다.
training-overlays-help = 디버그 오버레이와 훈련 보조 표시를 전환합니다.
training-close-help = 훈련 메뉴를 닫습니다.
training-stage-help = 훈련 스테이지를 바꾸고 스테이지 관련 개체를 초기화합니다.
training-character-help = 캐릭터 설정과 CPU 생성에 사용할 캐릭터를 고릅니다.
training-set-character-help = 떠 있는 플레이어 커서를 선택한 캐릭터로 바꿉니다.
training-random-color-help = 커서 캐릭터에 새 무작위 기본 색을 지정합니다.
training-cycle-palette-help = 커서 캐릭터의 팔레트를 순환합니다.
training-cpu-level-down-help = 새 훈련 CPU에 사용할 CPU 레벨을 낮춥니다.
training-cpu-level-current-help = 새로 생성되는 훈련 CPU의 현재 CPU 레벨입니다. 확인으로 순환합니다.
training-cpu-level-up-help = 새 훈련 CPU에 사용할 CPU 레벨을 높입니다.
training-spawn-cpu-help = 선택한 캐릭터와 CPU 레벨로 CPU를 생성합니다.
training-clear-spawns-help = 훈련에서 생성한 모든 CPU와 더미를 제거합니다.
training-save-state-help = 현재 훈련 위치, 피해, 스톡, 생성된 CPU, 스테이지, 타이밍 상태를 저장합니다. D-pad 오른쪽도 같은 단축키입니다.
training-load-state-help = 저장된 훈련 상태를 복원합니다. D-pad 왼쪽도 같은 단축키입니다.
training-savestate-shortcuts-help = D-pad 오른쪽은 현재 훈련 상태를 저장하고, D-pad 왼쪽은 복원합니다.
versus-tag-selector-default = 태그: {$tag}
versus-tag-none = 태그 없음
versus-tag-manage = 태그 생성 / 관리
versus-tag-change-failed = 태그를 변경할 수 없습니다
versus-cpu-level-help = 이 CPU 레벨을 순환합니다.
versus-cpu-color-help = 이 CPU의 색상과 팔레트를 다시 섞습니다.
versus-cpu-team-help = 이 CPU의 팀을 전환합니다.
versus-cpu-remove-help = 이 CPU를 제거합니다.
versus-character-select-help = 떠 있는 플레이어 커서에 이 캐릭터를 선택합니다.
versus-add-cpu-help = 이 캐릭터로 CPU를 추가합니다.
versus-tap-jump-help = 이 플레이어의 탭 점프를 전환합니다.
versus-random-color-help = 이 플레이어에게 새 무작위 색상을 지정합니다. 팀이 활성화되면 비활성화됩니다.
versus-cycle-palette-help = 이 플레이어의 팔레트를 순환합니다.
versus-team-help = 이 플레이어의 팀을 전환합니다. 팀 모드일 때 표시됩니다.
versus-tag-selector-help = 이 플레이어의 태그를 고릅니다. 넷플레이 중에는 비활성화됩니다.
versus-start-select-character-first = 먼저 캐릭터를 선택하세요
versus-start-not-enough-players = 게임을 시작하기에 플레이어 수가 부족합니다: {$count}
versus-start-not-enough-teams = 게임을 시작하기에 팀 수가 부족합니다: {$count}
versus-start-waiting-for-host = 호스트를 기다리는 중
versus-ffa-help = 난투와 팀전 규칙을 전환합니다.
versus-start-help = 충분한 플레이어, CPU, 팀, 스테이지가 준비되면 경기를 시작합니다.
versus-starter-help = 스타터 스테이지를 무작위로 골라 경기를 시작합니다.
versus-legal-help = 합법적인 스타터 또는 카운터픽 스테이지를 무작위로 골라 경기를 시작합니다.
versus-misc-help = 기타 스테이지.
versus-stage-preview-help = 호버하여 이 스테이지를 미리 보고, 확인하여 선택 후 시작합니다.
versus-stage-preview-counterpick-help = 호버하여 이 카운터픽 스테이지를 미리 보고, 확인하여 선택 후 시작합니다.
versus-stage-preview-misc-help = 호버하여 이 기타 스테이지를 미리 보고, 확인하여 선택 후 시작합니다.
versus-mode-selector-help = Antistatic과 19XX의 versus 상수를 전환합니다.
versus-tab-stages-help = 대전에 사용할 스테이지를 둘러보고 선택합니다.
versus-tab-settings-help = 대전 규칙과 설정을 조정합니다. 여기서 Start를 누르면 스테이지 선택으로 전환됩니다.
versus-setting-stock = 스톡
versus-setting-time = 시간
versus-setting-on = 켜짐
versus-setting-off = 꺼짐
versus-setting-none = 없음
versus-setting-stock-mode-value = 모드: {$value}
versus-setting-stocks-value = 스톡: {$value}
versus-setting-time-limit-value = 시간: {$value}
versus-setting-friendly-fire-value = 팀 피해: {$value}
versus-setting-stamina-value = 스태미나: {$value}
versus-setting-knockback-value = 넉백: {$value}×
versus-setting-pause-value = 일시정지: {$value}
versus-setting-sd-value = 자멸: {$value}
versus-setting-stock-mode-help = 스톡 모드(마지막까지 남은 플레이어 승리)와 시간 모드(타이머 종료 시 스톡이 가장 많은 플레이어 승리)를 전환합니다.
versus-setting-stocks-help = 각 플레이어가 시작할 스톡(목숨) 수입니다.
versus-setting-time-limit-help = 대전 제한 시간입니다. 시간 모드에서는 승자를 결정합니다.
versus-setting-friendly-fire-help = 팀원이 서로에게 피해를 줄 수 있는지 전환합니다. 팀 모드에서만 표시됩니다.
versus-setting-stamina-help = 시작 스태미나(HP)입니다. 0으로 설정하면 대미지 퍼센트 모드가 됩니다.
versus-setting-knockback-help = 전체 넉백 배율입니다. 값이 높을수록 날아가는 거리가 늘어납니다.
versus-setting-pause-help = 대전 중 일시정지를 허용하거나 금지합니다.
versus-setting-sd-help = 자멸 페널티입니다. -1은 스톡을 하나 차감하고, 0은 페널티가 없습니다.
netplay-copy-lobby-missing = 복사할 로비 코드가 없습니다
netplay-copy-lobby-copied = 로비 코드를 클립보드에 복사했습니다
netplay-direct-connect-empty = IP 주소를 입력하세요
netplay-lobby-code-prompt = 로비, LAN 또는 STUN 초대 코드를 입력하세요.
netplay-lobby-code-empty = 로비 코드를 입력하세요
netplay-error-connecting = 연결 오류: {$error}
matchmaking-no-controller-connected = 연결된 컨트롤러가 없습니다
battle-winner-log = 승자: {$player}
battle-winner-message = 승자: 플레이어 {$player}
battle-winner-team-log = 승자: {$team} 팀
battle-winner-team-message = 승자: {$team} 팀
battle-tie-log = 무승부
battle-tie-message = 무승부
battle-time-out = 시간 종료
battle-countdown-go = 시작
battle-infinite-score-log = 무한 점수: {$score}
battle-infinite-score-message = 점수 {$score}
team-name-red = 레드
team-name-green = 그린
team-name-blue = 블루
team-name-grey = 그레이
versus-start-sync-failed = 전투 시작 동기화에 실패했습니다

main-menu-help = 옵션 위로 커서를 옮기면 어떤 기능인지 볼 수 있습니다.
netplay-main-help = 넷플레이 동작을 선택하세요.
netplay-settings-help = 넷플레이 동작을 조정하세요.
netplay-advanced-help = 연결 도구를 선택하세요.
settings-help = 설정 카테고리를 선택하세요.
help-discord-help = 브라우저에서 Antistatic Discord 커뮤니티를 엽니다.
help-guide-help = 브라우저에서 Antistatic 온라인 가이드를 엽니다.
help-adapter-guide-help = 공식 GameCube 컨트롤러 어댑터용 Dolphin 설정 안내를 엽니다.
Adapter-Guide = 어댑터 가이드
Open-Dolphin-Guide = Dolphin 가이드 열기
Native-Adapter-Help = 어댑터 도움말
NATIVE-ADAPTER-HELP = 어댑터 도움말
native-adapter-help-summary = Antistatic은 libusb를 직접 사용하므로 Dolphin 네이티브 어댑터 지원과 같은 드라이버 설정을 사용합니다.
native-adapter-help-windows = Windows: Zadig로 USB ID 057e:0337에 WinUSB를 설치하세요.
native-adapter-help-linux = Linux: 057e:0337에 대한 사용자 접근을 허용하는 udev 규칙을 추가하세요.
native-adapter-help-sdl = SDL/Dolphin이 어댑터를 먼저 잡는다면 SDL_JOYSTICK_HIDAPI_GAMECUBE=0으로 실행하세요.
native-adapter-help-dolphin = Dolphin/Slippi: Antistatic 네이티브 어댑터 진단을 열기 전에 종료하세요.
native-adapter-help-claim = 다른 앱이 어댑터를 점유하고 있었다면 그 앱을 닫고 이 진단 화면을 다시 여세요.
native-adapter-help-back = 네이티브 어댑터 상태로 돌아갑니다.
help-credits-help = 크레딧, 저작권, 서드파티 출처를 봅니다.
help-back-help = 메인 메뉴로 돌아갑니다.
help-help = 도움말 항목을 선택하세요.
controls-help = 컨트롤러 동작을 선택하세요.
netplay-quick-play-help = 선택한 컨트롤러로 무작위 상대를 찾습니다.
credits-help = 크레딧 및 출처 표기.

credits-heading = Antistatic - 크레딧 및 출처 표기
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. 모든 권리 보유.
credits-developer = 개발자: bluehexagons (Loren Crain).
credits-original = 오리지널 사운드, 모델, 애니메이션, 게임플레이, UI, 엔진 코드는 모두 자체 제작되었습니다.
credits-runtime = 오픈 소스 런타임/도구: Node.js, TypeScript, CMake, Fluent, gl-matrix, jsonc-parser, os-locale.
credits-libraries = 네이티브 라이브러리: SDL3, SDL3_image, GLEW, OpenAL Soft, FreeType, Vorbis/libvorbisfile, libusb.
credits-build = 빌드/검사 도구: npm, oxlint, oxfmt 및 각 플랫폼 컴파일러 툴체인.
credits-fonts = 포함된 글꼴: Noto Sans, IBM Plex Mono, GNU Unifont.
credits-tools = 제작 도구: 3D 모델용 Blender, 오디오와 음악용 Audacity 및 LMMS.
credits-packages = bluehexagons 패키지: capacitor, trace, antistatic-translations.
credits-thanks = 이 프로젝트들을 유지하고 기여해 주신 분들께 감사드립니다.
credits-license = 서드파티 프로젝트는 각자의 라이선스를 따릅니다.

# Old UI hover/help text
main-versus-help = 로컬 매치를 시작하기 전에 캐릭터, CPU, 팀, 규칙, 스테이지를 선택합니다.
main-arcade-help = 연결된 모두를 위한 협동 CPU 전투입니다. 스톡은 제한되어 있으며, 패배하면 재시도합니다.
main-netplay-help = 온라인 게임 호스팅 또는 참가, Quick Play, Netplay 연결 설정을 엽니다.
main-training-help = 스테이지, CPU, 색상, 팔레트, 디버그 컨트롤이 있는 연습 모드를 엽니다.
main-replays-help = 저장된 Replay 파일을 찾아보고, 미리 보고, 재생합니다.
main-settings-help = 오디오, 비디오, 언어, 컨트롤러 어댑터, 시작 모드 설정을 조정합니다.
main-controls-help = 컨트롤러 태그를 만들고 태그별 조작 매핑을 편집합니다.
main-help-help = 커뮤니티 및 외부 가이드 링크를 엽니다.
main-exit-help = Antistatic를 종료합니다.
settings-audio-help = 마스터, 효과음, UI, 보이스, 음악의 볼륨을 조정합니다.
settings-video-help = 그래픽 프리셋, 전체 화면, 동기화, 효과, 프레임 제한 설정을 변경합니다.
settings-native-adapter-help = GameCube 어댑터의 상태와 설정 메모를 확인합니다.
settings-language-help = 메뉴 언어를 바꿉니다.
settings-start-mode-help = 시작할 때 가장 먼저 열 모드를 선택합니다.
shared-settings-help = 설정으로 돌아갑니다.
native-adapter-copy-udev-install-help = 057e:0337용 표준 udev 규칙 설치 및 다시 로드 명령을 복사합니다.
native-adapter-copy-udev-line-help = 057e:0337용 표준 udev 규칙 줄만 복사합니다.
native-adapter-help-button-help = Dolphin/Slippi와 호환되는 어댑터 설치용 Windows 및 Linux 설정 메모를 엽니다.
audio-master-help = 마스터 출력 볼륨을 설정합니다.
audio-sfx-toggle-help = 효과음과 UI 사운드를 켜거나 끕니다.
audio-sfx-help = 게임 효과음 볼륨을 설정합니다.
audio-ui-help = 메뉴와 인터페이스 볼륨을 설정합니다.
audio-voice-help = 캐릭터 보이스 볼륨을 설정합니다.
audio-music-toggle-help = 음악 재생을 켜거나 끕니다.
audio-music-help = 음악 볼륨을 설정합니다.
video-preset-help = 그룹화된 그래픽 프리셋을 적용하거나, 개별 설정이 다를 때는 사용자 지정을 표시합니다.
video-fullscreen-toggle-help = 창 모드와 전체 화면 표시를 전환합니다.
video-display-help = 게임 창이나 전체 화면 모드에서 사용할 디스플레이를 선택합니다.
video-fullscreen-resolution-help = 독점 전체 화면 모드 해상도를 선택합니다. Auto는 데스크톱 전체 화면을 사용합니다.
video-windowed-resolution-help = 창 모드와 전체 화면 복원에 사용할 창 크기를 선택합니다.
video-render-scale-help = UI를 기본 그대로 유지하면서 3D 그래픽을 창 해상도보다 낮게 또는 높게 렌더링합니다.
video-vsync-help = 스왑 타이밍을 선택합니다. Adaptive는 드라이버가 지원하면 낮은 지연의 tear-if-late 동기화를 사용합니다.
video-shadow-quality-help = 그림자 품질을 선택하거나 그림자를 끕니다.
video-ssao-help = 주변 폐색 품질을 선택합니다.
video-antialias-help = FXAA 안티앨리어싱을 켜거나 끕니다.
video-bloom-help = 가장 밝은 하이라이트 주변에 부드러운 광채를 추가합니다. 고사양 GPU에서 가장 좋습니다.
video-reflections-help = 화면 공간 반사로 광택 있는 표면에 장면을 비춥니다. 부하가 크며 고사양 GPU에서 가장 좋습니다.
video-perf-overlay-help = 성능 오버레이를 표시하거나 숨깁니다.
video-point-lights-help = 추가 포인트 라이트 품질을 선택합니다.
video-particle-quality-help = 파티클 효과 밀도를 선택합니다.
video-max-fps-help = 선택적 프레임레이트 제한을 설정합니다.
video-apply-help = 변경된 비디오 설정을 적용합니다.
replays-enabled-help = 대상이 되는 Versus 및 Quick Play 전투를 메모리에 기록합니다. 메모리가 부족한 시스템에서는 끄세요.
replays-auto-save-help = 수동 저장 입력을 기다리지 않고 결과 화면에서 Replay를 자동 저장합니다.
replays-compression-help = 저장할 때 Replay 파일을 압축합니다. 압축 때문에 저장이 느려질 때만 끄세요.
netplay-copy-lobby-help = 이용 가능할 때 현재 로비 코드를 복사합니다.
netplay-virtual-couch-help = 로비 호스팅, 로비 코드 참가, 고급 초대 옵션을 엽니다.
netplay-settings-menu-help = 롤백, 입력 버퍼, LAN 주소 동작을 설정합니다.
netplay-back-help = 기존 세션을 끊지 않고 메인 메뉴로 돌아갑니다.
arcade-cpu-level-help = 상대 CPU 난이도 레벨 (0 가장 쉬움, 6 가장 어려움).
arcade-stocks-help = 전투당 스톡 수.
arcade-retries-help = 패배로 런이 끝나기 전까지의 재시도 횟수.
arcade-battles-help = 런의 총 전투 수.
arcade-start-help = 참가한 모든 플레이어가 준비되면 런을 시작합니다.
controls-remap-page-help = 메뉴 이동, 콘솔, 전체 화면, 연습 모드 키를 다시 지정합니다.
controls-remap-reset-binding-help = {$action}을 기본 할당으로 되돌립니다.
controls-remap-reset-all-help = 모든 키보드 단축키를 내장 기본값으로 복원합니다.
replay-browser-help = Replay 브라우저.
replay-offline-only-help = Replay는 로컬 파일 시스템에서 불러오므로 오프라인에서만 사용할 수 있습니다.
replay-refresh-help = {$dir}에서 저장된 Replay 파일을 다시 검색합니다.
replay-entry-help = {$players}가 {$stage}에서; {$duration} ({$truncated}); {$result}; {$version}; {$compression}.
replay-unreadable-help = Replay를 읽을 수 없습니다: {$error}
replay-actions-watch-help = 저장된 Replay를 처음부터 재생합니다. Replay 재생 중에는 Jump In을 사용할 수 있습니다.
replay-actions-back-help = Replay 목록으로 돌아갑니다.
replay-load-help = Replay 디렉터리에서 저장된 Replay 파일을 불러옵니다.
replay-prev-help = 새로운 Replay를 표시합니다.
replay-next-help = 오래된 Replay를 표시합니다.
replay-settings-help = Replay 기록, 자동 저장, 압축 옵션.
audio-help = 오디오 설정을 조정합니다.
video-help = 비디오 설정을 조정합니다.
replays-help = Replay는 기본적으로 활성화되어 있으며 전투당 16분으로 제한됩니다.
native-adapter-help-text = Native Adapter는 4포트 직접 폴링을 제공합니다. PC 모드는 더 간단하지만 SDL 컨트롤러 할당을 사용합니다.
shortcut-menu-up-help = 메뉴에서 선택을 위로 이동합니다.
shortcut-menu-down-help = 메뉴에서 선택을 아래로 이동합니다.
shortcut-menu-left-help = 선택을 왼쪽으로 이동하거나 값을 줄입니다.
shortcut-menu-right-help = 선택을 오른쪽으로 이동하거나 값을 늘립니다.
shortcut-menu-confirm-help = 포커스된 항목을 실행합니다.
shortcut-menu-next-help = 다음으로 포커스 가능한 항목으로 이동합니다. Shift를 누르면 돌아갑니다.
shortcut-menu-page-up-help = 여러 항목 위로 건너뜁니다.
shortcut-menu-page-down-help = 여러 항목 아래로 건너뜁니다.
shortcut-menu-home-help = 목록의 첫 번째 항목에 포커스를 맞춥니다.
shortcut-menu-end-help = 목록의 마지막 항목에 포커스를 맞춥니다.
shortcut-console-help = 게임 내 디버그 콘솔을 엽니다.
shortcut-chat-help = 채팅 입력창(say 명령)을 엽니다.
shortcut-fullscreen-help = 전체 화면을 전환합니다. Alt+Enter도 동작합니다.
shortcut-frame-step-help = 고정된 상태에서 한 프레임 진행합니다. 디버그 모드가 필요합니다.
shortcut-freeze-help = TAS를 일시 중지하거나 다시 시작합니다. 디버그 모드가 필요합니다.
shortcut-save-state-help = 연습 모드에서 현재 상태의 스냅샷을 저장합니다.
shortcut-restore-state-help = 연습 모드의 마지막 스냅샷을 복원합니다.

Start = 스타트
Color = 색상
Leave = 나가기
Not-Joined = 미참가
Hold-Start = 스타트 길게 누르기
arcade-join-help = 이 아케이드 런에 참가합니다.
arcade-color-help = 이 플레이어의 색상을 무작위로 바꿉니다.
arcade-palette-help = 이 플레이어의 팔레트를 선택합니다.
arcade-leave-help = 이 아케이드 런에서 나갑니다.
arcade-setting-cpu-level = CPU 레벨
arcade-setting-stocks = 스톡
arcade-setting-starting-stocks = 시작 스톡
arcade-setting-retries = 재시도
arcade-setting-battles = 배틀 수
arcade-setting-value = {$label}: {$value}
arcade-palette = 팔레트 {$number}
arcade-select-title = 아케이드
arcade-select-infinite-title = 무한 배틀
arcade-select-instructions = 확인으로 참가 · 플레이어별 캐릭터와 팔레트 선택 · 뒤로 나가기
arcade-between-cleared-battle = 배틀 {$current} / {$total} 클리어
arcade-between-next = 확인: 다음
arcade-between-retries-remaining =
    패배 — { $count ->
       *[other] 재시도 {$count}회 남음
    }
arcade-between-retry-actions = 확인: 재시도 · 뒤로: 포기
arcade-between-results = 확인: 결과
arcade-between-complete = 아케이드 완료!
arcade-results-infinite-title = 무한 배틀
arcade-results-infinite-subtitle = {$time} 동안 점수 {$score}
arcade-results-cleared-title = 아케이드 클리어
arcade-results-cleared-subtitle = {$battles}개 배틀을 모두 클리어했습니다.
arcade-results-abandoned-title = 런 포기
arcade-results-abandoned-subtitle = {$total}개 중 {$current}번째 배틀 후 포기했습니다.
arcade-results-gameover-title = 게임 오버
arcade-results-gameover-subtitle = {$total}개 중 {$current}번째 배틀까지 도달했습니다.
replay-battle-controls = 리플레이: 저장/난입 · 스타트 일시정지 · 확인/공격 길게 눌러 빨리감기 · 뒤로 종료
results-controller-port = 컨트롤러 P{$port}
results-controller-id = 컨트롤러 {$id}
results-disconnected-slot = 연결 끊긴 슬롯
results-remote-player = 원격 플레이어
results-replay-capture = 리플레이 저장
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = 슬롯 {$index}: {$name}
results-row-kos = KOs
results-row-falls = 추락
results-row-sds = 자멸
results-row-damage-given = 준 피해
results-row-damage-taken = 받은 피해
results-row-blocked = 방어
results-row-parries = 패리
results-row-power-shields = 퍼펙트 실드
results-row-lag-cancels = 랙 캔슬
results-row-kb-given = 준 넉백
results-row-kb-taken = 받은 넉백
results-row-kb-absorbed = 흡수한 넉백
results-row-ledge-grabs = 절벽 잡기
results-row-ledge-time = 절벽 시간
results-row-crouch-cancels = 웅크리기 캔슬
results-row-velocity-cancels = 속도 캔슬
controls-action-ui-save-replay = 리플레이 저장
controls-device-unknown = 알 수 없음
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = 키보드 단축키
shortcut-unbound = (미지정)
shortcut-category-menu = 메뉴 이동
shortcut-category-general = 일반
shortcut-category-debug = 디버그 (TAS)
shortcut-category-training = 트레이닝 모드
shortcut-label-menu-up = 위로 이동
shortcut-label-menu-down = 아래로 이동
shortcut-label-menu-left = 왼쪽으로 이동
shortcut-label-menu-right = 오른쪽으로 이동
shortcut-label-menu-confirm = 확인
shortcut-label-menu-next = 다음 항목
shortcut-label-menu-page-up = 페이지 위로
shortcut-label-menu-page-down = 페이지 아래로
shortcut-label-menu-home = 첫 항목
shortcut-label-menu-end = 마지막 항목
shortcut-label-console = 콘솔 열기
shortcut-label-chat = 채팅
shortcut-label-fullscreen = 전체 화면 전환
shortcut-label-frame-step = 한 프레임 진행 (TAS)
shortcut-label-freeze = 정지 (TAS)
shortcut-label-save-state = 상태 저장
shortcut-label-restore-state = 상태 불러오기
shortcut-bind = 지정
shortcut-add = 추가
shortcut-replace = 교체
shortcut-remove-key = {$key} 제거
shortcut-capture-bind-title = 키 지정: {$action}
shortcut-capture-replace-title = 키 교체: {$action}
shortcut-capture-hint = 지정할 키를 누르거나 Esc로 취소하세요.
shortcut-conflict-detail = {$key} 키는 이미 {$action}에 지정되어 있습니다. 다시 지정할까요?
shortcut-conflict-hint = Enter로 다시 지정하고 Esc로 취소하세요.
shortcut-min-binding = {$action}에는 최소 하나의 지정이 필요합니다.
shortcut-overlap-menu = 메뉴 이동 중복: {$keys} 키는 메뉴 이동에도 쓰입니다. 메뉴에서는 컨트롤러 바인딩이 우선됩니다.
shortcut-overlap-actions = 단축키 중복: {$overlaps}. 게임플레이 중에는 컨트롤러 바인딩이 우선됩니다.
shortcut-reset-all = 모든 단축키를 기본값으로 초기화
character-select-help = 캐릭터를 선택합니다.

matchmaking-service-fallback-stun = 대체 STUN
matchmaking-status-preparing-binding = Quick Play 준비 중... 넷플레이 소켓을 열고 있습니다.
matchmaking-status-preparing-primary-stun = Quick Play 준비 중... {$service}를 통해 공개 UDP 경로를 확인하고 있습니다.
matchmaking-status-preparing-fallback-stun = Quick Play 준비 중... 기본 STUN이 실패하여 {$service}로 다시 시도하고 있습니다.
matchmaking-status-preparing-queueing = Quick Play 준비 중... 대기열에 참가하고 있습니다.
matchmaking-status-connecting-tunneling = 상대를 찾았습니다. P2P 경로를 열고 있습니다...
matchmaking-status-connecting-peer = P2P 경로가 열렸습니다. 연결 핸드셰이크를 마무리하고 있습니다...
matchmaking-status-waiting-peer = 경로가 열렸습니다. 다른 플레이어를 기다리고 있습니다...
matchmaking-status-starting-battle = 연결 준비 완료. 대전을 시작합니다...
netplay-experimental-note = 실험적 — 불안정할 수 있습니다
netplay-detail-connecting-peer = P2P 경로가 열렸습니다. 연결 핸드셰이크를 마무리하고 있습니다...
netplay-detail-waiting-for-peer = 경로가 열렸습니다. 다른 플레이어의 연결 완료를 기다리고 있습니다...
netplay-detail-starting-battle = 연결 준비 완료. 대전을 시작합니다...
netplay-detail-matchmaking-binding = Quick Play 준비 중. 넷플레이 소켓을 열고 있습니다...
netplay-detail-matchmaking-primary-stun = {$service}를 통해 공개 UDP 경로를 확인하고 있습니다...
netplay-detail-matchmaking-fallback-stun = 기본 STUN이 응답하지 않았습니다. {$service}를 시도합니다...
netplay-detail-matchmaking-queueing = 매치메이킹 대기열에 참가하고 있습니다...
netplay-detail-matchmaking-wait = {$wait}초 동안 대기열에 있습니다. 대기 중인 플레이어: {$players}.
replay-stage-fallback = 스테이지 {$number}
replay-unknown-error = 알 수 없는 오류
replay-title = 리플레이
replays-title = 리플레이
replay-watch-button = 리플레이 보기
replay-settings-button = 리플레이 설정
replay-refresh-button = 목록 새로고침
replay-refreshing = 새로고침 중...
replay-prev-button = 이전 페이지
replay-prev-disabled = 이전 페이지 -
replay-next-button = 다음 페이지
replay-next-disabled = 다음 페이지 -
replay-browser-scanning = 리플레이 디렉터리 검사 중...
replay-browser-scan-failed = 리플레이 검사에 실패했습니다.
replay-browser-empty = 리플레이 0개를 찾았습니다.
replay-browser-page = {$first}-{$last} / {$count}개 · 페이지 {$page}/{$pages}
replay-browser-loading = 리플레이 불러오는 중...
replay-browser-scanning-files = 저장된 리플레이 파일을 검사하고 있습니다.
replay-browser-scan-failed-detail = 리플레이 검사 실패: {$error}
replay-browser-empty-slot = 이 슬롯에는 리플레이가 없습니다.
replay-browser-empty-list = 저장된 리플레이를 찾지 못했습니다.
replay-browser-root-help = 리플레이 파일은 로컬 리플레이 디렉터리에서 재귀적으로 불러옵니다.
replay-title-unreadable = 읽을 수 없음: {$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = 결과 없음
replay-result-none-winner = 승자: 없음
replay-result-quit = 조기 종료
replay-result-tie = 무승부
replay-result-winner = 승자: {$winner}
replay-action-participants = 참가자: {$players}
replay-action-duration = 길이: {$duration}
replay-action-duration-truncated = 길이: {$duration} (잘림)
replay-action-result = 결과: {$result}
replay-action-stage = 스테이지: {$stage}
replay-action-mode = 모드: {$mode}
replay-action-version = 버전: {$version}
replay-action-file = 파일: {$compression}; 잘림: {$truncated}
replay-compression-compressed = 압축됨
replay-compression-uncompressed = 압축 안 함
replay-truncated-yes = 예
replay-truncated-no = 아니오
