hello-world = Привет, мир! { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = Кремний
Iron = Железо
Xenon = Ксенон
Helium = Гелий
Carbon = Углерод
Rhodium = Родий

Sandbag = Мешок с песком

Ruins = Руины
Transistor = Транзистор
Eroded = Разъеденный
Scales = Весы
Crossing = Пересечение
Longboat = Баркас
Boombox = Бумбокс
Fountain = Фонтан
Great-White = Большой Белый
Plane = Плоскость
Satellite = Спутник
Divided = Разделённый
Pillars = Столпы
Debug = Отлаживать

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = Ванильная
Physics = Физика
color-preset-random = Случайный
color-preset-red = Красный
color-preset-orange = Оранжевый
color-preset-gold = Золотой
color-preset-green = Зелёный
color-preset-blue = Синий
color-preset-purple = Фиолетовый
color-preset-pink = Розовый
color-preset-white = Белый
versus-color-preset-help = Выберите семейство цветов; каждый выбор получает небольшую случайную вариацию. Отключено в командном режиме.

# Navigation
Back = Назад
Exit = Покинуть
Save = Сохранить
Cancel = Отмена
Close-Symbol = X

Modify = Изменить
Reset = Сброс

# Main Menu
Versus = Поединок
Training = Тренировка
Courses = Курсы
TRAINING = ТРЕНИРОВКА
COURSES = КУРСЫ
battle-results = Результаты боя
Settings = Настройки
Controls = Управление
Discord = Discord {"\u29C9"}
Guide = Руководство {"\u29C9"}

# Settings Menu
SETTINGS = Настройки
Audio = Звук
Video = Видео
accessibility-title = Доступность
settings-accessibility-help = Настройте движение, эффекты ударов, звуки меню и видимость фокуса.
accessibility-reduced-motion = Меньше движения
accessibility-reduced-motion-help = Отключает анимацию фона меню и визуальную тряску от ударов.
accessibility-hit-flash = Вспышка удара: {$value}
accessibility-hit-flash-help = Настройте яркость вспышек при ударах по персонажам.
accessibility-screen-shake = Тряска от удара: {$value}
accessibility-screen-shake-help = Настройте визуальную тряску персонажей и интерфейса при ударах.
accessibility-menu-sound = Усилить звуки меню
accessibility-menu-sound-help = Делает звуки навигации и подтверждения громче.
accessibility-high-contrast-focus = Контрастный фокус
accessibility-high-contrast-focus-help = Добавляет яркую двойную рамку к выбранному элементу меню.
accessibility-help = Настройте параметры доступности и отображения.
first-run-title = Добро пожаловать в Antistatic
first-run-intro = Выберите, с чего начать. Управление и доступность всегда доступны в главном меню.
first-run-versus = Локальный поединок
first-run-versus-help = Настройте матч для игроков за одним устройством.
first-run-controls = Управление
first-run-controls-help = Проверьте, переназначьте и откалибруйте управление.
first-run-training = Тренировка
first-run-training-help = Тренируйтесь свободно с инструментами и целями.
first-run-courses = Курсы
first-run-courses-help = Изучайте движение, атаки, защиту и восстановление в пошаговых уроках.
first-run-skip = В главное меню (Пропустить)
first-run-skip-help = Завершить это одноразовое знакомство, не открывая режим.
first-run-help = Выберите, с чего начать. Любой выбор завершит это одноразовое знакомство.
Windowed = Оконный режим
Fullscreen = Во весь экран

main = Главное меню
versus = Поединок
training = Тренировка
start-mode = Начать: { TRANSLATE($value) }

# Audio Menu
AUDIO = Звук

Play-Audio = Воспроизвести аудио
Play-Music = Воспроизвести музыку

Audio-volume = Громкость: {$value}
SFX-volume = SFX: {$value}
Music-volume = Музыка: {$value}
UI-volume = UI: {$value}
Voice-volume = Голос: {$value}

# Video Menu
VIDEO = Видео
Quick-Setup = Быстрая настройка
Display = Экран
Quality = Качество
Effects = Эффекты
Apply-Changes = Применить изменения

graphics-preset-low = Графика: Низко
graphics-preset-medium = Графика: Средне
graphics-preset-high = Графика: Высоко
graphics-preset-max = Графика: Максимум
graphics-preset-custom = Графика: Пользовательская

vsync-off = Vsync: Выкл
vsync-on = Vsync: Вкл
vsync-adaptive = Vsync: Адаптивный

shadow-off = Тени: Выкл
shadow-low = Тени: Низко
shadow-highest = Тени: Максимум

ssao-off = SSAO: Выкл
ssao-on = SSAO: Вкл
ssao-full = SSAO: Полный

aa-off = Антиалиасинг: Выкл
aa-fxaa = Антиалиасинг: FXAA
aa-fxaa-high = Антиалиасинг: FXAA высокий

bloom-off = Bloom: Выкл
bloom-on = Bloom: Вкл
reflections-off = Отражения: Выкл
reflections-on = Отражения: Вкл
reflections-low = Отражения: Низко
reflections-high = Отражения: Высоко
godrays-off = Лучи света: Выкл
godrays-on = Лучи света: Вкл

perf-overlay-off = Индикатор производительности: Выкл
perf-overlay-on = Индикатор производительности: Вкл


point-lights-off = Точечные источники света: Выкл
point-lights-on = Точечные источники света: Вкл

particles-low = Частицы: Низко
particles-medium = Частицы: Средне
particles-full = Частицы: Максимум


max-fps-off = Макс. FPS: Выкл
max-fps-30 = Макс. FPS: 30
max-fps-60 = Макс. FPS: 60
max-fps-120 = Макс. FPS: 120
max-fps-144 = Макс. FPS: 144

# Controls Menu
CONTROLS = Управление

controls-title = Управление
controls-section-controllers = Контроллеры
controls-section-mappings = Назначения
controls-set-tag = Установить тег
controls-edit-bindings = Редактировать настройки
controls-tag-untagged = (нет тега)
controls-tag-title = Тег игрока
controls-tag-prompt = P{$port} ({$layout}). Теги могут содержать 1-24 буквенно-цифровых символа, «-» или «_». Оставьте пустым для очистки.
controls-tag-confirm = Подтвердить
controls-tag-clear = Очистить
controls-tag-cancel = Отмена
controls-tag-select-title = Выбрать тег
controls-tag-filter-empty = Введите текст для фильтрации сохранённых тегов
controls-tag-filter-value = Фильтр: {$filter}
controls-tag-summary-empty = Сохранённых тегов: {$total}. Введите текст для фильтрации или создайте новый тег.
controls-tag-summary-filter = Показано {$visible} из {$total} сохранённых тегов. Точные совпадения используют сохранённые настройки.
controls-tag-defaults-suffix = по умолчанию для этого контроллера
controls-tag-create-new = Создать новый тег
controls-tag-use-existing = Использовать существующий тег «{$tag}»
controls-tag-create = Создать «{$tag}»
controls-tag-reserved = «{$tag}» зарезервирован
controls-tag-netplay-blocked = Теги нельзя менять во время сетевой игры
controls-tag-no-controller = Локальный контроллер не выбран
controls-tag-no-layout = У выбранного контроллера нет раскладки
controls-tag-filter-help = Введите текст для фильтрации тегов; ESC очищает или выходит
controls-tag-no-saved = Сохранённых тегов пока нет
controls-tag-no-matches = Подходящих тегов нет
controls-tag-invalid = Недопустимый тег (1-24 символа, буквы/цифры/-/_; «default» зарезервирован)
controls-profile-help-untagged = Управление сохраняется в общем профиле без тега; тег нужен только для стандартного tap jump.
controls-profile-help-tagged = Управление и стандартный tap jump сохраняются для этого тега и этого типа контроллера.
controls-choose-existing-tag = Выбрать существующий тег
controls-create-tag = Создать тег
controls-rename-create-tag = Переименовать/создать тег
controls-edit-set-tag-first = Редактировать управление (сначала установите тег)
controls-edit-controls = Редактировать управление
controls-tap-jump-default = Стандартный Tap Jump: {$state}
controls-state-on = ВКЛ
controls-state-off = ВЫКЛ
controls-netplay-blocked = Управление нельзя менять во время сетевой игры
controls-no-local-controllers = Нет активного контроллера. Нажмите игровую клавишу или кнопку контроллера, чтобы подключить его.
controls-no-layout = У контроллера нет раскладки
controls-set-tag-before-editing = Установите тег перед редактированием управления
controls-no-mapping = Для этого контроллера нет доступного назначения
controls-set-tag-before-tap-jump = Установите тег, чтобы сохранить стандартный tap jump
controls-connected-controllers = Подключённые контроллеры
controls-remap-add-key = + Добавить привязку (нажмите клавишу)
controls-remap-find-input = Найти привязку (нажмите ввод)
controls-remap-capture-key-title = Нажмите клавишу
controls-remap-capture-input-title = Нажмите ввод
controls-remap-capture-key-help = Следующая нажатая клавиша будет добавлена как новая привязка.
controls-remap-capture-input-help = Следующая нажатая кнопка или стик будут выбраны для редактирования.
controls-remap-capture-cancel = ESC для отмены
controls-default-save-blocked = Управление по умолчанию нельзя перезаписать; сначала установите тег
controls-default-reset-blocked = Управление по умолчанию нельзя сбросить из этого меню
controls-tag-filter-entry-help = Введите текст для фильтрации сохранённых тегов контроллера; геймпады могут использовать крестовину.
controls-tag-filter-label = Фильтр
controls-tag-preconfigured = преднастроен
controls-tag-rename-title = Переименовать тег
controls-tag-create-title = Создать тег
controls-tag-apply-existing-help = Применить к этому контроллеру совпадающий сохранённый тег.
controls-tag-create-empty-help = Создать новый тег для этого контроллера.
controls-tag-create-filtered-help = Создать этот тег для контроллера, если имя допустимо.
controls-tag-apply-saved-help = Применить этот тег и его сохранённую раскладку к контроллеру.
controls-tag-apply-preconfigured-help = Применить этот преднастроенный тег с раскладкой по умолчанию для этого типа контроллера.
controls-tag-apply-default-help = Применить этот тег с раскладкой по умолчанию для этого типа контроллера.
controls-tag-delete-button = Удалить {$tag}
controls-tag-delete-help = После подтверждения удалить {$tag}, сохранённое управление и калибровку для всех типов контроллеров.
controls-tag-delete-title = Удалить тег?
controls-tag-delete-body = Удалить «{$tag}», управление и калибровку для всех типов контроллеров и снять тег с подключённых контроллеров?
controls-tag-delete-warning = Это действие нельзя отменить.
controls-back-help = Вернуться к управлению.
controls-tag-select-help = Выберите или создайте тег контроллера.
controls-edit-set-tag-first-help = Сначала создайте тег контроллера, затем редактируйте игровые и меню-привязки.
controls-edit-controls-help = Редактировать игровые и меню-привязки для этого профиля контроллера.
controls-tap-jump-set-tag-first-help = Сначала создайте тег контроллера, затем задайте стандартное значение прыжка вверх.
controls-tap-jump-default-help = Переключает, будет ли нажатие вверх по умолчанию заставлять этот контроллер прыгать.
controls-create-new-tag-help = Создать новый тег и переключить на него этот контроллер.
controls-choose-existing-tag-help = Выбрать или удалить сохранённый тег.
controls-rename-current-tag-help = Переименовать текущий тег контроллера.
controls-switch-controller-help = Переключить меню управления на этот подключённый контроллер.
menu-binding-hint = Перемещение стиком или крестовиной · Подтвердить/Start выбирает · Назад возвращает
menu-adjust-hint = Перемещение стиком или крестовиной · Влево/Вправо меняет значения · Подтвердить выбирает · Назад возвращает
menu-bind-hint = Перемещение стиком или крестовиной · Подтвердить выбирает привязку · Назад возвращает
arcade-select-leave = Select — выйти
main-help-about-help = Руководства, титры и ссылки bluehexagons.
main-replays-available-help = Просматривать, предварительно смотреть и запускать сохранённые повторы.
main-replays-unavailable-help = Повторы доступны только офлайн, потому что загружаются из локальной файловой системы.
arcade-menu-battles-help = Начать текущий забег Arcade Battles.
arcade-menu-infinite-help = Начать бесконечный Arcade-режим с усиливающимися CPU на 1 сток.
arcade-menu-training-help = Открыть тренировку с инструментами практики и сохранениями состояния.
arcade-menu-back-help = Вернуться в главное меню.
arcade-menu-help = Выберите аркадный режим.
training-menu-courses-help = Выберите короткий курс о механиках игры.
training-menu-help = Выберите тренировочное занятие.
courses-menu-course-help = Перейдите в эту зону курса.
courses-menu-back-help = Вернуться к тренировке.
courses-menu-help = Зоны курсов расположены слева направо. По ним всегда можно свободно перемещаться.
course-instruction-movement-walk = Наклоните стик движения влево или вправо, чтобы идти.
course-instruction-movement-dash = Резко отклоните стик движения влево или вправо, чтобы совершить рывок.
course-instruction-movement-crouch = Нажмите вниз, чтобы присесть.
course-name-movement = Движение
course-name-jumping = Прыжки
course-name-attacks = Атаки
course-name-defense = Защита
course-name-advanced = Продвинутый
course-name-directional-influence = Направленное влияние
course-name-teching = Тех
course-summary-movement = Идите, совершите рывок, присядьте и доберитесь до метки.
course-summary-jumping = Прыгайте в воздухе, цепляйтесь за края и тренируйте доступные прыжки от стен.
course-summary-attacks = Атакуйте на земле и в воздухе, затем потратьте энергию на спецприём.
course-summary-defense = Блокируйте, ставьте идеальный щит, уклоняйтесь, перекатывайтесь, парируйте и захватывайте.
course-summary-advanced = Используйте атаки стиком, воздушные уклонения, быстрое падение и восстановление верхним спецприёмом.
course-summary-directional-influence = Меняйте траекторию запуска ловушки стиком движения.
course-summary-teching = Выполните тех при приземлении после запуска ловушкой.
course-instruction-movement-travel = Доберитесь до метки со стрелкой.
course-instruction-jumping-jump = Нажмите прыжок, чтобы оторваться от земли.
course-instruction-jumping-air-jump = Ещё раз нажмите прыжок в воздухе, чтобы выполнить воздушный прыжок.
course-instruction-jumping-steer = После прыжка удерживайте влево или вправо, чтобы двигаться в воздухе.
course-instruction-jumping-ledge-grab = Подлетите к краю платформы снизу, чтобы зацепиться за него.
course-instruction-jumping-wall-jump = Коснитесь верхней стены, затем резко отклоните стик от неё, чтобы выполнить прыжок от стены.
course-instruction-attacks-normal = Попадите по тренировочной цели обычной атакой.
course-instruction-attacks-aerial = Прыгните и попадите по тренировочной цели воздушной атакой.
course-instruction-attacks-energy = Используйте спецприём и проследите, как общая шкала энергии уменьшается, а затем восстанавливается с задержкой.
course-instruction-attacks-special = Попадите по тренировочной цели спецприёмом.
course-instruction-defense-shield = Заблокируйте атаку тренировочной цели щитом.
course-instruction-defense-power-shield = Сильно нажмите щит перед самым ударом, чтобы поставить идеальный щит без потери энергии.
course-instruction-defense-roll = Удерживая щит, нажмите влево или вправо, чтобы перекатиться.
course-instruction-defense-spot-dodge = Удерживая щит, нажмите вниз, чтобы уклониться на месте.
course-instruction-defense-parry = Отпустите щит перед самым ударом, чтобы парировать его.
course-instruction-defense-grab = Выполните захват тренировочной цели.
course-instruction-advanced-stick = Резко отклоните правый стик в любом направлении, чтобы выполнить атаку стиком.
course-instruction-advanced-air-dodge = Прыгните, затем сильно нажмите кнопку щита, чтобы уклониться в воздухе.
course-instruction-advanced-fast-fall = В воздухе нажмите вниз, чтобы быстро упасть.
course-instruction-advanced-recovery = В воздухе нажмите вверх и спецприём, чтобы восстановиться верхним спецприёмом.
course-instruction-directional-influence = Удерживайте влево или вправо в момент удара пусковой площадки, чтобы изменить угол полёта.
course-instruction-teching-neutral = Сильно нажмите кнопку щита перед приземлением после запуска, чтобы выполнить тех.
course-instruction-complete = Зона пройдена. Переходите в другую зону, когда будете готовы.
course-action-restart = Начать зону заново
course-action-next = Следующая зона
course-session-progress = Пройдено зон: {$completed}/{$total}
course-target-label = Тренировочная цель
course-target-reset = Сбросить цель
course-target-disable = Отключить цель
course-target-enable = Включить цель
course-target-unavailable = В этой зоне нет цели
course-target-reset-help = Возвращает тренировочную цель этой зоны в исходную позицию и включает её.
course-target-toggle-help = Скрывает или возвращает тренировочную цель этой зоны в текущем сеансе курса.
course-defense-feedback-early = Ставьте щит ближе к моменту атаки.
course-defense-feedback-late = Слишком поздно. Поставьте щит до попадания атаки.
course-defense-feedback-success = Отличный момент. Атака заблокирована.
course-demonstration-label = Демонстрация
course-demonstration-show = Показать статичный пример
course-demonstration-hide = Скрыть статичный пример
course-demonstration-help = Показать или скрыть пример без анимации для текущего шага урока.
course-demonstration-still = Статичная поза · без анимации
help-bluehex-homepage-help = Открыть домашнюю страницу bluehexagons.
help-bluehex-github-help = Просмотреть проекты bluehexagons на GitHub.
help-bluehex-steam-help = Открыть страницу куратора bluehexagons в Steam.
help-bluehex-itch-help = Открыть страницу bluehexagons на itch.io.
help-bluehex-bluesky-help = Читать bluehexagons в Bluesky.
help-bluehex-patreon-help = Поддержать bluehexagons на Patreon.
controls-source-keyboard = Клавиатура
controls-source-keyboard-defaults = Стандартная клавиатура
controls-current-menu-controls-heading = Текущие элементы управления меню
controls-current-menu-controls-summary = {$source} · Перемещение: {$navigate} · Подтвердить: {$confirm} · Назад: {$back}
controls-action-attack = Атака
controls-action-jump = Прыжок
controls-action-special = Спецприём
controls-action-grab = Захват
controls-action-shield-1 = Щит 1
controls-action-shield-2 = Щит 2
controls-action-hard-shield-1 = Сильный щит 1
controls-action-hard-shield-2 = Сильный щит 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-pad вверх
controls-action-dpad-down = D-pad вниз
controls-action-dpad-left = D-pad влево
controls-action-dpad-right = D-pad вправо
controls-action-move-horizontal = Горизонтальное движение
controls-action-move-vertical = Вертикальное движение
controls-action-right-stick-horizontal = Правый стик по горизонтали
controls-action-right-stick-vertical = Правый стик по вертикали
controls-action-ui-confirm = Подтвердить UI
controls-action-ui-back = Назад UI
controls-action-ui-up = UI вверх
controls-action-ui-down = UI вниз
controls-action-ui-left = UI влево
controls-action-ui-right = UI вправо
controls-action-ui-horizontal-nav = Горизонтальная навигация UI
controls-action-ui-vertical-nav = Вертикальная навигация UI
controls-action-move-left = Движение влево
controls-action-move-right = Движение вправо
controls-action-move-up = Движение вверх
controls-action-move-down = Движение вниз
controls-action-tilt-left = Лёгкий наклон влево
controls-action-tilt-right = Лёгкий наклон вправо
controls-action-tilt-up = Лёгкий наклон вверх
controls-action-tilt-down = Лёгкий наклон вниз
controls-action-right-stick-left = Правый стик влево
controls-action-right-stick-right = Правый стик вправо
controls-action-right-stick-up = Правый стик вверх
controls-action-right-stick-down = Правый стик вниз
controls-action-light-shield-l = Лёгкий щит L
controls-action-light-shield-r = Лёгкий щит R
controls-action-ui-nav-left = Навигация UI влево
controls-action-ui-nav-right = Навигация UI вправо
controls-action-ui-nav-up = Навигация UI вверх
controls-action-ui-nav-down = Навигация UI вниз
controls-remap-section-buttons = Кнопки
controls-remap-section-dpad = D-pad
controls-remap-section-movement = Движение
controls-remap-section-tilts = Наклоны (мягкое движение)
controls-remap-section-right-stick = Правый стик
controls-remap-section-light-shields = Лёгкие щиты
controls-remap-section-ui-navigation = Навигация UI
controls-remap-section-sticks-triggers = Стики и триггеры
controls-remap-unbound = Не назначено
controls-remap-free-keys-none = Свободные клавиши: (нет в общем наборе)
controls-remap-more-suffix = , ещё +{$count}
controls-remap-free-keys = Свободные клавиши: {$keys}{$suffix}
controls-remap-free-buttons = Свободные кнопки: {$buttons}
controls-remap-free-axes = Свободные оси: {$axes}
controls-remap-conflict-detail = {$input} уже назначен на {$actions}.
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = Сохраните Подтвердить UI, Назад UI, горизонтальную и вертикальную навигацию, чтобы меню оставались управляемыми.
controls-remap-capture-key-hint = Нажмите клавишу клавиатуры для {$action}. ESC отменяет.
controls-remap-capture-button-hint = Нажмите кнопку {$layout} для {$action}. Назад отменяет.
controls-remap-capture-axis-hint = Двиньте стик/триггер {$layout} для {$action}. Назад отменяет.
controls-remap-capture-add-title = Добавить {$action}
controls-remap-capture-replace-title = Заменить {$action}
controls-remap-capture-matching-input = Используйте подходящий ввод для этого действия.
controls-remap-confirm-reassign = Подтвердите переназначение на {$action}.
controls-remap-confirm-cancel-help = Подтверждение заменяет. Назад отменяет.
controls-remap-command-add = Добавить
controls-remap-command-replace = Заменить
controls-remap-command-remove = Удалить
controls-remap-add-help = Добавить ещё один физический ввод для {$action}.
controls-remap-replace-help = Заменить {$input} для {$action}.
controls-remap-remove-help = Удалить {$input} из {$action}.
controls-remap-back-to-controls = Назад к управлению
controls-remap-back-to-controls-help = Вернуться к управлению, не прокручивая список переназначения до конца.
controls-remap-help = Выберите Добавить, Заменить или Удалить. Клавиши Page прыгают по списку.
controls-remap-help-extended = Выберите Добавить, Заменить или Удалить. Клавиши Page прыгают по списку; Назад отменяет.
controls-remap-jump-to-section = Перейти к разделу
controls-remap-jump-to-binding = Перейти к {$section}
controls-remap-focus-section-help = Переместить фокус к первой привязке {$section}.
controls-remap-reset-help = Сбрасывает этот профиль управления к раскладке по умолчанию. Требуются два подтверждения.
controls-remap-reset-confirm = Нажмите ещё раз для подтверждения сброса
controls-quick-map-action-unbound = Не назначено
controls-quick-map-action-hard-shield-1-short = Щит 1
controls-quick-map-action-hard-shield-2-short = Щит 2
controls-quick-map-action-dpad-up-short = D-вверх
controls-quick-map-action-dpad-down-short = D-вниз
controls-quick-map-action-dpad-left-short = D-влево
controls-quick-map-action-dpad-right-short = D-вправо
controls-quick-map-title = Быстрая раскладка: {$layout}
controls-quick-map-mode-editing = Подтвердить или нажать действие, чтобы применить · Назад или нажать заголовок, чтобы выйти
controls-quick-map-mode-ready = Подтвердить открывает быстрое редактирование
controls-quick-map-mode-unavailable = Управление недоступно
controls-quick-map-assign = Назначить
controls-quick-map-assign-input = Назначить {$input}
controls-quick-map-unavailable-status = Быстрая раскладка недоступна для этого контроллера. Изменения не сохранены.
controls-remap-autosave-status = Изменения сохраняются автоматически.
controls-remap-saved-status = Сохранено автоматически.
controls-remap-blocked-menu-controls-status = Заблокировано: сохраните Подтвердить UI, Назад UI, горизонтальную и вертикальную навигацию меню. Изменения не сохранены.
controls-remap-default-reset-blocked-status = Встроенное управление по умолчанию нельзя сбросить. Изменения не сохранены.
controls-layout-standard = Xbox / Стандартная
controls-layout-arcade-stick = Аркадный стик
controls-layout-retro-dpad = Ретро-крестовина
controls-layout-switch-pro = Switch Pro
controls-layout-playstation = PlayStation
controls-layout-8bitdo-nintendo = 8BitDo (раскладка Nintendo)
controls-layout-steam-deck = Steam Deck
controls-layout-gamecube = GameCube
controls-layout-n64 = Nintendo 64
controls-layout-keyboard = Клавиатура

standard = стандарт
keyboard = клавиатура
gcn_native = GCN родные

# Training Menu
Swap-Character = Поменять персонажа
Overlays = Накладки
press-start = Нажмите Start

drawHitbubbleInfo = Информация об атаке
drawECB = Коллизия
drawHeatmap = Тепловая карта
drawRawPosition = Сырая позиция
drawStage = Стадия столкновения
animations = Анимации
controllers = Контроллеры

# Versus Menu
FFA = FFA
Teams = Команды

Host-Netplay = Хост нетплей
Join-Netplay-Clipboard = Присоединяйтесь к нетплее из буфера обмена
Disconnect = Отключить
Copy-Lobby-Code = Скопируйте код лобби

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = Прямое подключение
Connect = Подключиться

netplay-action-start-lobby = Начать лобби
netplay-action-join-clipboard = Присоединиться из буфера обмена
netplay-action-quick-host-copy-code = Быстрый хост и копирование кода
netplay-action-copy-lan-invite = Копировать LAN-приглашение
netplay-action-copy-localhost-invite = Копировать localhost-приглашение
netplay-action-copy-stun-invite = Копировать STUN-приглашение
netplay-action-find-random-match = Найти случайный матч
netplay-action-cancel-lobby = Отменить лобби
netplay-action-cancel-connection = Отменить подключение
netplay-action-please-wait = Пожалуйста, подождите
netplay-action-open-versus = Открыть Versus
netplay-action-cancel-matchmaking = Отменить подбор

netplay-status-label = Сетевая игра: {$status}
netplay-status-uninitialized = не инициализировано
netplay-status-initialized = инициализировано
netplay-status-waiting = ожидание
netplay-status-hosting = хостинг
netplay-status-connecting = подключение
netplay-status-establishing = установка соединения
netplay-status-connected = подключено
netplay-status-ready = Готово для netplay
netplay-status-waiting-player = Ожидание игрока
netplay-status-waiting-lobby = Ожидание ответа лобби
netplay-status-hosting-lobby = Хостинг лобби
netplay-status-hosting-lobby-code = Хостинг лобби {$code}
netplay-status-starting-lobby = Запуск лобби
netplay-status-connecting-host = Подключение к хосту
netplay-status-connected-host = Подключен как хост
netplay-status-connected-client = Подключен к хосту
netplay-status-disconnecting = Отключение
netplay-status-canceling = Отмена подключения
netplay-status-matchmaking = Поиск случайного матча
netplay-status-match-found = Случайный матч найден
netplay-status-matchmaking-canceling = Отмена подбора
netplay-status-error = Ошибка netplay
netplay-status-error-message = Ошибка netplay: {$error}
netplay-status-unavailable = Статус netplay недоступен

matchmaking-title = ПОДБОР ИГРЫ
matchmaking-status-select-character = Выберите персонажа, чтобы встать в очередь
matchmaking-status-no-controller = Контроллер не подключён
matchmaking-status-searching = Поиск матча...
matchmaking-status-searching-details = Поиск... ожидание {$wait} с. Игроков в очереди: {$players}. Самое долгое ожидание: {$longest} с.
matchmaking-status-searching-estimate = Поиск... ожидание {$wait} с. Игроков в очереди: {$players}. Средняя длительность завершённых матчей: {$average} с.
matchmaking-status-canceling = Отмена...
matchmaking-status-found = Матч найден!
matchmaking-status-connecting = Подключение...
matchmaking-status-disconnecting = Отключение...
matchmaking-status-error = {$error} Выберите персонажа, чтобы попробовать снова.

# Match by Code
match-code-title = МАТЧ ПО КОДУ
match-code-hint = Поделитесь своим кодом и введите код друга. Оба нажмите «Поиск». Регистр не важен.
match-code-own-label = Ваш код: {$code}
match-code-peer-label = Код друга: {$code}
match-code-peer-unset = Код друга: (не задан)
match-code-search = Поиск
match-code-entry-limit = Не более {$length} букв или цифр
match-code-own-prompt = Ваш код
match-code-peer-prompt = Код друга
match-code-status-enter-peer = Введите код друга, чтобы создать закрытый матч
match-code-status-ready = Готово — оба игрока должны нажать «Поиск»
match-code-error-enter-peer = Сначала введите код друга
match-code-error-own = Введите код друга, а не свой
match-code-error-invalid = Этот код недействителен
match-code-error-length = Код должен содержать от {$min} до {$max} букв или цифр
match-code-error-blocked = Этот код запрещён; выберите другой

netplay-detail-ready = Хостите лобби, вставьте скопированное приглашение или введите адрес вручную.
netplay-detail-lobby-code-ready = Код лобби {$code} готов к обмену.
netplay-detail-creating-lobby-code = Создание кода вашего лобби.
netplay-detail-waiting-for-host = Ожидание ответа хоста на ваш запрос на присоединение.
netplay-detail-share-lobby-code = Поделитесь кодом лобби {$code} с другим игроком.
netplay-detail-starting-lobby = Запуск подключения вашего лобби.
netplay-detail-joining-host = Попытка присоединиться к выбранному хосту.
netplay-detail-establishing = Игроки найдены. Завершите рукопожатие, затем откройте Versus.
netplay-detail-connected = Соединение готово. Откройте Versus, чтобы выбрать правила, персонажей и стадию.
netplay-detail-disconnecting = Закрытие текущей сессии и возврат к офлайн-игре.
netplay-detail-canceling = Остановка текущего запроса на присоединение.
netplay-detail-matchmaking = Используйте Versus, чтобы встать в очередь на случайного противника с вашими предпочтительными правилами.
netplay-detail-match-found = Противник найден. Завершите настройку в Versus, когда оба игрока будут готовы.
netplay-detail-matchmaking-canceling = Остановка текущего поиска случайного матча.
netplay-detail-error-message = Последняя ошибка: {$error}
netplay-detail-error-generic = Что-то пошло не так. Попробуйте другой код или способ подключения.
netplay-detail-unavailable = Подробности netplay недоступны.

netplay-help-host-copy-code = Скопируйте код вашего лобби, чтобы другой игрок мог его вставить.
netplay-help-host-cancel-join = Остановите текущую попытку присоединения и вернитесь в состояние готовности.
netplay-help-host-disconnect = Покиньте текущую сессию netplay.
netplay-help-host-start-lobby = Начните новое лобби и ждите, когда присоединится другой игрок.
netplay-help-busy = Netplay сейчас занят. Подождите, пока он закончит.
netplay-help-join-cancel-lobby = Закройте текущее лобби и перестаньте ждать другого игрока.
netplay-help-join-in-progress = Присоединение уже выполняется. Подождите или используйте «Отменить подключение».
netplay-help-join-open-versus = Продолжите в Versus и завершите настройку матча.
netplay-help-stop-random-search = Остановить поиск случайного противника.
netplay-help-join-clipboard = Вставьте код приглашения лобби, прямого или STUN из буфера обмена.
netplay-help-copy-server = При необходимости запустите лобби, затем скопируйте его общий код лобби.
netplay-help-copy-direct = Скопируйте приглашение прямого подключения для другого устройства в этой LAN.
netplay-help-copy-localhost = Скопируйте приглашение прямого подключения для другой копии, запущенной на этом компьютере.
netplay-help-copy-stun = Скопируйте приглашение с поддержкой STUN, которое проще использовать через интернет.
netplay-help-direct-connect = Введите адрес вручную вместо использования скопированного кода приглашения.
netplay-help-find-random-match = Откройте Versus и встаньте в очередь на случайного противника.
netplay-help-open-versus = Откройте меню Versus, не покидая этот экран.
netplay-help-back = Вернуться в главное меню.
netplay-help-unavailable = Помощь по действию netplay недоступна.
netplay-help-advanced = Настройка расширенных параметров netplay, таких как откат и буфер.

ADVANCED-CONNECTIONS = ДОПОЛНИТЕЛЬНЫЕ ПОДКЛЮЧЕНИЯ
netplay-settings-rollback-help = Включить или выключить rollback-симуляцию для сетевых матчей.
netplay-settings-buffer-help = Выберите, сколько кадров ввода буферизовать, или позвольте сетевой игре выбрать автоматически.
netplay-settings-force-ipv4-help = Предпочитать IPv4 при создании LAN-кодов приглашения в смешанных сетях.
netplay-settings-back-help = Вернуться в меню сетевой игры.
netplay-advanced-info = Используйте эти варианты как запасные, когда Quick Play или обычные коды лобби не могут подключиться. STUN помогает пробиться через роутеры для игры через интернет. Прямое подключение лучше всего подходит для LAN или хоста с проброшенным UDP-портом.
netplay-advanced-direct-help = Ручной запасной вариант. Введите host:port для игры по LAN или когда у хоста проброшен UDP-порт.
netplay-advanced-stun-help = Запасной вариант для интернета. Поделитесь им, когда обычное подключение к лобби не срабатывает, а вам всё ещё нужен hole punching через роутер.
netplay-advanced-lan-help = Запасной вариант для LAN. Поделитесь своим доступным локальным адресом, когда оба игрока находятся в одной сети.
netplay-advanced-localhost-help = Тестовый запасной вариант. Используйте его только когда оба клиента запущены на одной машине.
netplay-advanced-back-help = Вернуться к Виртуальному дивану.
netplay-rollback-off = Rollback: Выкл
netplay-rollback-on = Rollback: Вкл
netplay-buffer-auto = Сетевой буфер: Авто
netplay-buffer-2 = Сетевой буфер: 2
netplay-buffer-3 = Сетевой буфер: 3
netplay-buffer-4 = Сетевой буфер: 4
netplay-buffer-5 = Сетевой буфер: 5
netplay-buffer-6 = Сетевой буфер: 6
netplay-buffer-7 = Сетевой буфер: 7
netplay-buffer-8 = Сетевой буфер: 8
netplay-buffer-10 = Сетевой буфер: 10
netplay-buffer-12 = Сетевой буфер: 12
netplay-force-ipv4-dual = LAN-адрес: IPv6/IPv4
netplay-force-ipv4-v4 = LAN-адрес: Принудительно IPv4

netplay-rollback = Откат
netplay-buffer = Сетевой буфер
netplay-force-ipv4 = LAN-адрес

netplay-direct-connect-prompt = Введите IP-адрес:порт. Порт по умолчанию: {$port}.
netplay-stun-connect-title = Использовать службу STUN?
netplay-stun-connect-prompt = Этот код использовал {$service} для обнаружения {$address}:{$port}.
netplay-waiting-host-battle = Ожидание завершения битвы хоста
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = Персонажи
Stages = Арены
CPU = CPU

Starter = Стартер
Legal = Турнирные
Miscellaneous = Разное

Start-Battle = Начать бой

# Start Menu
quit-info = Щит + Атака + Старт, чтобы выйти
paused = Приостановлено
tag-info = D-Pad вверх/вниз для тега вход/выход

# Pause Menu
pause-resume = Продолжить
pause-restart = Перезагрузка
pause-quit = Выход
pause-players = Игроки
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = Подключите контроллер и нажмите любую кнопку для присоединения.
arcade-return-prompt = Нажмите подтверждение для возврата в главное меню.

# Replay
replay-paused = Воспроизведение приостановлено
replay-controls = Подтвердить: присоединиться  ←/→: кадр  Назад: меню  Сохранить: [клавиша]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = английский
spanish = испанский
french = французский
italian = итальянский
german = немецкий
russian = {ru-russian}
japanese = японский
chinese-cn = Упрощенный китайский
chinese-hk = Традиционный китайский
korean = корейский

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian}
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean} ({korean})

# Shared UI labels
Advanced = Дополнительно
Clear-Spawns = Очистить точки спавна
Create-new-tag = Создать новый тег
Credits = Титры
CREDITS = ТИТРЫ
Cycle-Palette = Сменить палитру
Delete = Удалить
Help = Справка
HELP = СПРАВКА
Join = Присоединиться
Join-Lobby-Code = Войти по коду лобби
Main-Menu = Главное меню
Mode = Режим
Native-Adapter = Нативный адаптер
NATIVE-ADAPTER = НАТИВНЫЙ АДАПТЕР
NETPLAY-SETTINGS = НАСТРОЙКИ СЕТЕВОЙ ИГРЫ
Other-saved-tags = Другие сохранённые теги
Profiles-for-this-controller-type = Профили для этого типа контроллера
Quick-Play = Быстрый матч
Random-Color = Случайный цвет
Rename-current-tag = Переименовать текущий тег
Reset-to-Defaults = Сбросить по умолчанию
Set-Character = Выбрать персонажа
Spawn-CPU = Создать CPU
Team = Команда
Virtual-Couch = Виртуальный диван
x = x
Find-Random-Match = Найти случайный матч
training-label-stage = Сцена
training-label-character = Персонаж
training-label-player-cursor = Курсор игрока
training-label-cpu-spawn = Создание CPU
training-label-savestate = Состояние
Save-State = Сохранить состояние
Load-State = Загрузить состояние
State-Saved = Состояние сохранено
State-Restored = Состояние восстановлено
No-State-Saved = Нет сохранённого состояния
DPad-Right-Save-Left-Load = Крестовина вправо сохраняет · влево загружает
shared-main-menu-help = Вернуться в главное меню.
shared-mode-selector-label-help = Подпись выбора правил.
training-mode-selector-help = Переключение между тренировочными правилами Antistatic и 19XX.
training-overlays-help = Переключает отладочные оверлеи и тренировочные подсказки.
training-close-help = Закрыть меню тренировки.
training-stage-help = Сменить тренировочную сцену и сбросить объекты, связанные со сценой.
training-character-help = Выберите персонажа, используемого для команд выбора персонажа и создания CPU.
training-set-character-help = Переключить плавающий курсор игрока на выбранного персонажа.
training-random-color-help = Назначить персонажу курсора новый случайный базовый цвет.
training-cycle-palette-help = Переключить палитру персонажа курсора.
training-cpu-level-down-help = Понизить уровень CPU для новых тренировочных CPU.
training-cpu-level-current-help = Текущий уровень CPU для новых тренировочных CPU. Нажмите подтверждение, чтобы переключить.
training-cpu-level-up-help = Повысить уровень CPU для новых тренировочных CPU.
training-spawn-cpu-help = Создать CPU с выбранным персонажем и уровнем CPU.
training-clear-spawns-help = Удалить всех созданных в тренировке CPU и манекены.
training-save-state-help = Сохранить текущие позицию, урон, стоки, созданных CPU, сцену и тайминг тренировки. Крестовина вправо использует тот же ярлык.
training-load-state-help = Восстановить сохранённое состояние тренировки. Крестовина влево использует тот же ярлык.
training-savestate-shortcuts-help = Крестовина вправо сохраняет текущее состояние тренировки; крестовина влево восстанавливает его.
versus-tag-selector-default = Тег: {$tag}
versus-tag-none = Без тега
versus-tag-manage = Создать / управлять тегами
versus-tag-change-failed = Не удалось изменить тег
versus-cpu-level-help = Переключить уровень этой CPU.
versus-cpu-color-help = Перемешать цвет и палитру этой CPU.
versus-cpu-team-help = Переключить команду этой CPU.
versus-cpu-remove-help = Удалить эту CPU.
versus-character-select-help = Выбрать этого персонажа для плавающего курсора игрока.
versus-add-cpu-help = Добавить CPU с этим персонажем.
versus-tap-jump-help = Переключить tap jump для этого игрока.
versus-random-color-help = Назначить этому игроку новый случайный цвет. Отключено, когда включены команды.
versus-cycle-palette-help = Переключить палитру этого игрока.
versus-team-help = Переключить команду этого игрока. Показывается, когда включён командный режим.
versus-tag-selector-help = Выбрать тег этого игрока. Отключено в netplay.
versus-start-select-character-first = Сначала выберите персонажа
versus-start-not-enough-players = Недостаточно игроков для начала матча: {$count}
versus-start-not-enough-teams = Недостаточно команд для начала матча: {$count}
versus-start-waiting-for-host = Ожидание хоста
versus-ffa-help = Переключить правила между свободной схваткой и командами.
versus-start-help = Начать матч, когда готовы достаточно игроков, CPU, команд и сцена.
versus-starter-help = Случайно выбрать стартовую сцену и начать матч.
versus-legal-help = Случайно выбрать разрешённую стартовую или counterpick-сцену и начать матч.
versus-misc-help = Прочие сцены.
versus-stage-preview-help = Наведите, чтобы просмотреть сцену; подтвердите, чтобы выбрать её и начать.
versus-stage-preview-counterpick-help = Наведите, чтобы просмотреть counterpick-сцену; подтвердите, чтобы выбрать её и начать.
versus-stage-preview-misc-help = Наведите, чтобы просмотреть прочую сцену; подтвердите, чтобы выбрать её и начать.
versus-mode-selector-help = Переключение между правилами versus Antistatic и 19XX.
versus-tab-stages-help = Просмотреть и выбрать арену для матча.
versus-tab-settings-help = Настроить правила и параметры матча. Нажатие Start здесь переключает к выбору арены.
versus-setting-stock = Стоки
versus-setting-time = Время
versus-setting-on = Вкл
versus-setting-off = Выкл
versus-setting-none = Нет
versus-setting-stock-mode-value = Режим: {$value}
versus-setting-stocks-value = Стоки: {$value}
versus-setting-time-limit-value = Время: {$value}
versus-setting-friendly-fire-value = Урон союзникам: {$value}
versus-setting-stamina-value = Выносливость: {$value}
versus-setting-knockback-value = Отбрасывание: {$value}×
versus-setting-pause-value = Пауза: {$value}
versus-setting-sd-value = Самоубийство: {$value}
versus-setting-stock-mode-help = Переключить режим Stock (побеждает последний выживший игрок) и Time (побеждает игрок с наибольшим числом стоков по окончании таймера).
versus-setting-stocks-help = Количество стоков (жизней), с которым начинает каждый игрок.
versus-setting-time-limit-help = Лимит времени матча. В режиме Time он определяет победителя.
versus-setting-friendly-fire-help = Включить или выключить урон между союзниками. Отображается только в командном режиме.
versus-setting-stamina-help = Начальная выносливость (HP). Значение 0 включает режим процентов урона.
versus-setting-knockback-help = Общий множитель отбрасывания. Чем выше значение, тем дальше запуск.
versus-setting-pause-help = Разрешить или запретить паузу во время матча.
versus-setting-sd-help = Штраф за самоубийство. -1 отнимает сток; 0 означает отсутствие штрафа.
netplay-copy-lobby-missing = Нет кода лобби для копирования
netplay-copy-lobby-copied = Код лобби скопирован в буфер обмена
netplay-direct-connect-empty = Введите IP-адрес
netplay-lobby-code-prompt = Введите код приглашения лобби, LAN или STUN.
netplay-lobby-code-empty = Введите код лобби
netplay-error-connecting = Ошибка подключения: {$error}
matchmaking-no-controller-connected = Контроллер не подключён
battle-winner-log = Победитель: {$player}
battle-winner-message = Победитель: Игрок {$player}
battle-winner-team-log = Победитель: команда {$team}
battle-winner-team-message = Победитель: команда {$team}
battle-tie-log = Ничья
battle-tie-message = НИЧЬЯ
battle-time-out = ВРЕМЯ
battle-countdown-go = СТАРТ
battle-infinite-score-log = Бесконечный счёт: {$score}
battle-infinite-score-message = Счёт {$score}
team-name-red = Красная
team-name-green = Зелёная
team-name-blue = Синяя
team-name-grey = Серая
versus-start-sync-failed = Не удалось синхронизировать начало боя

main-menu-help = Наведите курсор на пункт, чтобы узнать, что он делает.
netplay-main-help = Выберите действие сетевой игры.
netplay-settings-help = Настройте поведение сетевой игры.
netplay-advanced-help = Выберите способ подключения.
settings-help = Выберите категорию настроек.
help-discord-help = Откройте сообщество Antistatic в Discord в браузере.
help-guide-help = Откройте онлайн-руководство Antistatic в браузере.
help-adapter-guide-help = Откройте заметки по настройке Dolphin для официального адаптера контроллера GameCube.
Adapter-Guide = Руководство по адаптеру
Open-Dolphin-Guide = Открыть руководство Dolphin
Native-Adapter-Help = Справка по адаптеру
NATIVE-ADAPTER-HELP = СПРАВКА ПО АДАПТЕРУ
native-adapter-help-summary = Antistatic использует libusb напрямую, поэтому ему подходит та же настройка драйверов, что и для нативного адаптера Dolphin.
native-adapter-help-windows = Windows: установите WinUSB для USB ID 057e:0337 с помощью Zadig.
native-adapter-help-linux = Linux: добавьте правило udev, которое даст пользователю доступ к 057e:0337.
native-adapter-help-sdl = Если SDL/Dolphin первым захватывает адаптер, запускайте с SDL_JOYSTICK_HIDAPI_GAMECUBE=0.
native-adapter-help-dolphin = Dolphin/Slippi: закройте их перед открытием диагностики нативного адаптера Antistatic.
native-adapter-help-claim = Если адаптер был занят другим приложением, закройте его и снова откройте этот экран диагностики.
native-adapter-help-back = Вернуться к состоянию нативного адаптера.
help-credits-help = Просмотреть титры, авторские права и информацию о сторонних проектах.
help-back-help = Вернуться в главное меню.
help-help = Выберите раздел справки.
controls-help = Выберите действие контроллера.
netplay-quick-play-help = Найти случайного соперника с выбранным контроллером.
credits-help = Титры и атрибуция.

credits-heading = Antistatic - титры и атрибуция
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. Все права защищены.
credits-developer = Разработчик: bluehexagons (Loren Crain).
credits-original = Оригинальные звуки, модели, анимации, игровой процесс, интерфейс и код движка созданы внутри команды.
credits-runtime = Открытые runtime/инструменты: Node.js, TypeScript, CMake, Fluent, gl-matrix, jsonc-parser, os-locale.
credits-libraries = Нативные библиотеки: SDL3, SDL3_image, GLEW, OpenAL Soft, FreeType, Vorbis/libvorbisfile, libusb.
credits-build = Инструменты сборки и проверки: npm, oxlint, oxfmt и платформенные цепочки компиляторов.
credits-fonts = В комплект входят шрифты: Noto Sans, IBM Plex Mono и GNU Unifont.
credits-tools = Инструменты производства: Blender для 3D-моделей; Audacity и LMMS для аудио и музыки.
credits-packages = Пакеты bluehexagons: capacitor, trace и antistatic-translations.
credits-thanks = Спасибо сопровождающим и участникам этих проектов.
credits-license = Сторонние проекты остаются под своими лицензиями.

# Old UI hover/help text
main-versus-help = Выберите персонажей, CPU, команды, правила и стадию перед началом локального матча.
main-arcade-help = Кооперативные бои с CPU для всех подключённых игроков. Ограниченные запасы, повтор при поражении.
main-netplay-help = Создавайте или присоединяйтесь к онлайн-играм, Quick Play и настройкам подключения Netplay.
main-training-help = Откройте режим тренировки со стадией, CPU, цветом, палитрой и отладочными управлениями.
main-replays-help = Просматривайте, предварительно просматривайте и запускайте сохранённые файлы Replay.
main-settings-help = Настройте аудио, видео, язык, адаптер контроллера и режим запуска.
main-controls-help = Создавайте теги контроллеров и редактируйте привязки для тегированных или общих контроллеров без тега.
main-help-help = Откройте ссылки на сообщество и внешние руководства.
main-exit-help = Выйти из Antistatic.
settings-audio-help = Настройте громкость мастер-выхода, эффектов, интерфейса, голосов и музыки.
settings-video-help = Измените графический пресет, полноэкранный режим, синхронизацию, эффекты и параметры лимита FPS.
settings-native-adapter-help = Проверьте состояние адаптера GameCube и заметки по настройке.
settings-language-help = Смените язык меню.
settings-start-mode-help = Выберите, какой режим открывается первым при запуске.
settings-live-reload = Горячая перезагрузка
settings-live-reload-help = Перезагружает файлы персонажей из Animator во время локального редактирования. По умолчанию отключено.
shared-settings-help = Вернуться к настройкам.
native-adapter-copy-udev-install-help = Скопируйте стандартные команды установки и перезагрузки правила udev для 057e:0337.
native-adapter-copy-udev-line-help = Скопируйте только стандартную строку правила udev для 057e:0337.
native-adapter-help-button-help = Откройте заметки по установке для Windows и Linux для адаптеров, совместимых с Dolphin/Slippi.
audio-master-help = Установите громкость мастер-выхода.
audio-sfx-toggle-help = Включите или выключите звуковые эффекты и звуки интерфейса.
audio-sfx-help = Установите громкость игровых звуковых эффектов.
audio-ui-help = Установите громкость меню и интерфейса.
audio-voice-help = Установите громкость голосов персонажей.
audio-music-toggle-help = Включите или выключите воспроизведение музыки.
audio-music-help = Установите громкость музыки.
video-preset-help = Примените сгруппированный графический пресет или покажите Пользовательский, когда отдельные настройки различаются.
video-fullscreen-toggle-help = Переключайтесь между оконным и полноэкранным режимом.
video-display-help = Выберите, какой дисплей должен использовать оконный или полноэкранный режим игры.
video-fullscreen-resolution-help = Выберите разрешение эксклюзивного полноэкранного режима. Auto использует полноэкранный рабочий стол.
video-windowed-resolution-help = Выберите размер окна, используемый в оконном режиме и при возврате из полноэкранного.
video-render-scale-help = Рендерьте 3D-графику ниже или выше разрешения окна, сохраняя интерфейс нативным.
video-vsync-help = Выберите синхронизацию обмена. Adaptive использует низколатентную синхронизацию tear-if-late, если драйвер её поддерживает.
video-shadow-quality-help = Выберите качество теней или отключите тени.
video-ssao-help = Выберите качество окружающего затенения.
video-antialias-help = Включите или выключите сглаживание FXAA.
video-bloom-help = Добавляет мягкое свечение вокруг самых ярких бликов. Лучше на мощных видеокартах.
video-reflections-help = Отражает сцену на блестящих поверхностях с помощью экранно-пространственных отражений. Требовательно; лучше на мощных видеокартах.
video-godrays-help = Объёмные солнечные лучи, пронизывающие сцену. Требовательно; лучше на мощных видеокартах.
video-perf-overlay-help = Показывайте или скрывайте оверлей производительности.
video-point-lights-help = Выберите качество дополнительных точечных источников света.
video-particle-quality-help = Выберите плотность эффектов частиц.
video-max-fps-help = Установите необязательный лимит FPS.
video-apply-help = Примените изменённые параметры видео.
replays-enabled-help = Записывайте в память подходящие бои Versus и Quick Play. Отключите это на системах с малым объёмом памяти.
replays-auto-save-help = Автоматически сохраняйте Replay на экране результатов вместо ожидания ручного нажатия сохранения.
replays-compression-help = Сжимайте файлы Replay при сохранении. Отключайте только если сжатие замедляет сохранение.
netplay-copy-lobby-help = Скопируйте текущий код лобби, когда он доступен.
netplay-virtual-couch-help = Откройте хостинг лобби, присоединение по коду лобби и расширенные параметры приглашения.
netplay-settings-menu-help = Настройте поведение rollback, буфера ввода и адреса LAN.
netplay-back-help = Вернитесь в главное меню, не отключая существующую сессию.
arcade-cpu-level-help = Уровень сложности CPU для противников (0 самый лёгкий, 6 самый сложный).
arcade-stocks-help = Запасы за бой.
arcade-retries-help = Количество повторов перед тем, как поражение завершит прохождение.
arcade-battles-help = Общее количество боёв в прохождении.
arcade-start-help = Начните прохождение, когда каждый присоединившийся игрок будет готов.
controls-remap-page-help = Переназначьте навигацию меню, консоль, полноэкранный режим и клавиши режима тренировки.
controls-remap-reset-binding-help = Сбросьте {$action} к привязке по умолчанию.
controls-remap-reset-all-help = Восстановите все сочетания клавиш к встроенным значениям по умолчанию.
replay-browser-help = Браузер Replay.
replay-offline-only-help = Replay доступны только офлайн, потому что они загружаются из локальной файловой системы.
replay-refresh-help = Повторно просканируйте сохранённые файлы Replay из {$dir}.
replay-entry-help = {$players} на {$stage}; {$duration} ({$truncated}); {$result}; {$version}; {$compression}.
replay-unreadable-help = Не удалось прочитать Replay: {$error}
replay-actions-watch-help = Воспроизведите сохранённый Replay с начала. Jump In доступен во время воспроизведения Replay.
replay-actions-back-help = Вернуться к списку Replay.
replay-load-help = Загрузите сохранённые файлы Replay из каталога Replay.
replay-prev-help = Показать более новые Replay.
replay-next-help = Показать более старые Replay.
replay-settings-help = Параметры записи Replay, авто-сохранения и сжатия.
audio-help = Настройте параметры аудио.
video-help = Настройте параметры видео.
replays-help = Replay включены по умолчанию и ограничены 16 минутами на бой.
native-adapter-help-text = Native Adapter обеспечивает прямой опрос 4 портов. Режим PC проще, но использует раскладки контроллера SDL.
shortcut-menu-up-help = Переместить выделение вверх в меню.
shortcut-menu-down-help = Переместить выделение вниз в меню.
shortcut-menu-left-help = Переместить выделение влево или уменьшить значение.
shortcut-menu-right-help = Переместить выделение вправо или увеличить значение.
shortcut-menu-confirm-help = Активировать выделенный элемент.
shortcut-menu-next-help = Перейти к следующему доступному для фокуса элементу. Удерживайте Shift, чтобы вернуться назад.
shortcut-menu-page-up-help = Прыгнуть вверх на несколько элементов.
shortcut-menu-page-down-help = Прыгнуть вниз на несколько элементов.
shortcut-menu-home-help = Сфокусировать первый элемент списка.
shortcut-menu-end-help = Сфокусировать последний элемент списка.
shortcut-console-help = Открыть отладочную консоль в игре.
shortcut-chat-help = Открыть поле чата (команда say).
shortcut-fullscreen-help = Переключить полноэкранный режим. Alt+Enter тоже работает.
shortcut-frame-step-help = Продвинуться на один кадр, пока игра заморожена. Требуется режим отладки.
shortcut-freeze-help = Приостановить или возобновить TAS. Требуется режим отладки.
shortcut-save-state-help = Создать снимок текущего состояния в режиме тренировки.
shortcut-restore-state-help = Восстановить последний снимок режима тренировки.

Start = Старт
Color = Цвет
Leave = Выйти
Not-Joined = Не присоединился
Hold-Start = Удерживайте Start
arcade-join-help = Присоединиться к этому аркадному забегу.
arcade-color-help = Случайно выбрать цвет этого игрока.
arcade-palette-help = Выбрать палитру этого игрока.
arcade-leave-help = Покинуть этот аркадный забег.
arcade-setting-cpu-level = Уровень CPU
arcade-setting-stocks = Стоки
arcade-setting-starting-stocks = Стартовые стоки
arcade-setting-retries = Попытки
arcade-setting-battles = Бои
arcade-setting-value = {$label}: {$value}
arcade-palette = Палитра {$number}
arcade-select-title = АРКАДА
arcade-select-infinite-title = БЕСКОНЕЧНЫЕ БОИ
arcade-select-instructions = Подтвердить — присоединиться · выбрать персонажа и палитру для каждого игрока · Назад — выйти
arcade-between-cleared-battle = Бой {$current} / {$total} пройден
arcade-between-next = Подтвердить: далее
arcade-between-retries-remaining =
    Поражение — { $count ->
        [one] осталась {$count} попытка
        [few] осталось {$count} попытки
        [many] осталось {$count} попыток
       *[other] осталось {$count} попытки
    }
arcade-between-retry-actions = Подтвердить: повторить · Назад: сдаться
arcade-between-results = Подтвердить: результаты
arcade-between-complete = Аркада пройдена!
arcade-results-infinite-title = Бесконечные бои
arcade-results-infinite-subtitle = Счёт {$score} за {$time}
arcade-results-cleared-title = Аркада пройдена
arcade-results-cleared-subtitle = Пройдены все бои ({$battles}).
arcade-results-abandoned-title = Забег прерван
arcade-results-abandoned-subtitle = Забег прерван после боя {$current} из {$total}.
arcade-results-gameover-title = Игра окончена
arcade-results-gameover-subtitle = Достигнут бой {$current} из {$total}.
replay-battle-controls = Повтор: Сохранить ставит метку · Start — пауза · крестовина — навигация · Захват — скорость · удерживайте Подтвердить/Атака для ускорения · Назад — выход
replay-battle-status = {$current} / {$total} · {$speed}x
replay-marker-default = Метка {$number}
replay-marker-added = {$label} добавлена на {$time}
replay-marker-selected = {$label} · {$time}
replay-marker-none = Нет меток повтора
replay-marker-save-unavailable = Сохранение меток повтора недоступно
replay-speed-changed = Скорость воспроизведения: {$speed}x
replay-export-button = Экспортировать пакет повтора
replay-export-help = Создать локальный пакет с повтором и метками. Ничего не загружается в сеть.
replay-exporting = Экспорт пакета повтора...
replay-exported = Экспортирован {$name}
replay-export-failed = Ошибка экспорта: {$error}
results-controller-port = Контроллер P{$port}
results-controller-id = Контроллер {$id}
results-disconnected-slot = Отключённый слот
results-remote-player = Удалённый игрок
results-replay-capture = Запись повтора
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = Слот {$index}: {$name}
results-row-kos = KOs
results-row-falls = Падения
results-row-sds = Самоустранения
results-row-damage-given = Нанесённый урон
results-row-damage-taken = Полученный урон
results-row-blocked = Блоки
results-row-parries = Парирования
results-row-power-shields = Идеальные щиты
results-row-lag-cancels = Лаг-канселы
results-row-kb-given = Нанесённый нокбэк
results-row-kb-taken = Полученный нокбэк
results-row-kb-absorbed = Поглощённый нокбэк
results-row-ledge-grabs = Захваты края
results-row-ledge-time = Время на краю
results-row-crouch-cancels = Присед-канселы
results-row-velocity-cancels = Канселы скорости
controls-action-ui-save-replay = Сохранить повтор
controls-device-unknown = Неизвестно
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = Горячие клавиши
shortcut-unbound = (не назначено)
shortcut-category-menu = Навигация по меню
shortcut-category-general = Общее
shortcut-category-debug = Отладка (TAS)
shortcut-category-training = Режим тренировки
shortcut-label-menu-up = Вверх
shortcut-label-menu-down = Вниз
shortcut-label-menu-left = Влево
shortcut-label-menu-right = Вправо
shortcut-label-menu-confirm = Подтвердить
shortcut-label-menu-next = Следующее поле
shortcut-label-menu-page-up = Страница вверх
shortcut-label-menu-page-down = Страница вниз
shortcut-label-menu-home = Первый элемент
shortcut-label-menu-end = Последний элемент
shortcut-label-console = Открыть консоль
shortcut-label-chat = Чат
shortcut-label-fullscreen = Переключить полный экран
shortcut-label-frame-step = Шаг кадра (TAS)
shortcut-label-freeze = Заморозка (TAS)
shortcut-label-save-state = Сохранить состояние
shortcut-label-restore-state = Восстановить состояние
shortcut-bind = Назначить
shortcut-add = Добавить
shortcut-replace = Заменить
shortcut-remove-key = Удалить {$key}
shortcut-capture-bind-title = Назначить клавишу: {$action}
shortcut-capture-replace-title = Заменить клавишу: {$action}
shortcut-capture-hint = Нажмите клавишу для назначения или Esc для отмены.
shortcut-conflict-detail = {$key} уже назначена на {$action}. Переназначить?
shortcut-conflict-hint = Нажмите Enter для переназначения, Esc для отмены.
shortcut-min-binding = Для {$action} должна остаться как минимум одна привязка.
shortcut-overlap-menu = Конфликт навигации меню: {$keys} также управляет меню. В меню приоритет у привязки контроллера.
shortcut-overlap-actions = Конфликт горячих клавиш: {$overlaps}. Во время игры приоритет у привязки контроллера.
shortcut-reset-all = Сбросить все горячие клавиши по умолчанию
character-select-help = Выберите персонажа.

matchmaking-service-fallback-stun = резервный STUN
matchmaking-status-preparing-binding = Подготовка Quick Play... Открытие netplay-сокета.
matchmaking-status-preparing-primary-stun = Подготовка Quick Play... Проверка вашего публичного UDP-маршрута через {$service}.
matchmaking-status-preparing-fallback-stun = Подготовка Quick Play... Основной STUN не сработал, повтор через {$service}.
matchmaking-status-preparing-queueing = Подготовка Quick Play... Вход в очередь.
matchmaking-status-connecting-tunneling = Матч найден. Открываем peer-to-peer маршрут...
matchmaking-status-connecting-peer = P2P-маршрут открыт. Завершаем рукопожатие соединения...
matchmaking-status-waiting-peer = Маршрут открыт. Ждём другого игрока...
matchmaking-status-starting-battle = Соединение готово. Запускаем матч...
netplay-experimental-note = Экспериментально — возможна нестабильная работа
netplay-detail-connecting-peer = P2P-маршрут открыт. Завершаем рукопожатие соединения...
netplay-detail-waiting-for-peer = Маршрут открыт. Ждём, пока другой игрок завершит подключение...
netplay-detail-starting-battle = Соединение готово. Запускаем матч...
netplay-detail-matchmaking-binding = Подготовка Quick Play. Открытие netplay-сокета...
netplay-detail-matchmaking-primary-stun = Проверка вашего публичного UDP-маршрута через {$service}...
netplay-detail-matchmaking-fallback-stun = Основной STUN не ответил. Пробуем {$service}...
netplay-detail-matchmaking-queueing = Входим в очередь матчмейкинга...
netplay-detail-matchmaking-wait = В очереди {$wait}с. Ожидающих игроков: {$players}.
replay-stage-fallback = Сцена {$number}
replay-unknown-error = неизвестная ошибка
replay-title = ПОВТОР
replays-title = ПОВТОРЫ
replay-watch-button = Смотреть повтор
replay-settings-button = Настройки повторов
replay-refresh-button = Обновить список
replay-refreshing = Обновление...
replay-prev-button = Предыдущая страница
replay-prev-disabled = Предыдущая страница -
replay-next-button = Следующая страница
replay-next-disabled = Следующая страница -
replay-browser-scanning = Сканирование каталога повторов...
replay-browser-scan-failed = Сканирование повторов не удалось.
replay-browser-empty = Найдено 0 повторов.
replay-browser-page =
    {$first}-{$last} из {$count} { $count ->
        [one] повтор
        [few] повтора
        [many] повторов
       *[other] повтора
    } · Страница {$page}/{$pages}
replay-browser-loading = Загрузка повторов...
replay-browser-scanning-files = Сканирование сохранённых файлов повторов.
replay-browser-scan-failed-detail = Сканирование повторов не удалось: {$error}
replay-browser-empty-slot = В этом слоте нет повтора.
replay-browser-empty-list = Сохранённые повторы не найдены.
replay-browser-root-help = Файлы повторов загружаются рекурсивно из локального каталога повторов.
replay-title-unreadable = Нечитаемо: {$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = Нет результата
replay-result-none-winner = Победитель: нет
replay-result-quit = Выход раньше времени
replay-result-tie = Ничья
replay-result-winner = Победитель: {$winner}
replay-action-participants = Участники: {$players}
replay-action-duration = Длительность: {$duration}
replay-action-duration-truncated = Длительность: {$duration} (обрезано)
replay-action-result = Результат: {$result}
replay-action-stage = Сцена: {$stage}
replay-action-mode = Режим: {$mode}
replay-action-version = Версия: {$version}
replay-action-file = Файл: {$compression}; Обрезано: {$truncated}
replay-compression-compressed = Сжатый
replay-compression-uncompressed = Несжатый
replay-truncated-yes = Да
replay-truncated-no = Нет

# Социальные функции и список CPU в режиме Versus
press-any-button-or-key = Нажмите любую кнопку или клавишу
social-title = ДРУЗЬЯ И ПРИГЛАШЕНИЯ
social-steam = Steam
social-steam-help = Показывать вашу комнату в Steam, чтобы друзья могли присоединиться через список друзей.
social-discord = Discord
social-discord-help = Показывать вашу комнату в Discord, чтобы друзья могли запросить подключение.
social-info = По умолчанию выключено. После включения интеграция загружает SDK платформы и делится кодом комнаты, чтобы друзья могли присоединиться. Для подключений по-прежнему используется собственный нетплей Antistatic.
social-summary = Статус в Steam и Discord, а также приглашения.
social-settings-help = Статус в Steam и Discord, а также приглашения. По умолчанию выключено.
versus-add-cpu = Добавить CPU
versus-cpu-page-prev = Назад
versus-cpu-page-next = Далее
versus-cpu-page-help = Сменить отображаемую страницу CPU.
versus-no-cpus-added = CPU не добавлены
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# Калибровка контроллера
controller-calibration-title = КАЛИБРОВКА КОНТРОЛЛЕРА
controller-calibration-open = Калибровать контроллер
controller-calibration-open-help = Проверить и откалибровать выбранный локальный контроллер.
controller-calibration-online-blocked = Калибровка недоступна во время сетевой игры.
controller-calibration-no-local-controller = Подключите и выберите локальный контроллер для калибровки.
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = без тега
controller-calibration-capability-no-axes = Контроллер не сообщает калибруемых осей.
controller-calibration-capability-native-origin = Нативные данные начала отсчёта поддерживают автокалибровку.
controller-calibration-capability-absolute-no-automatic = Абсолютные данные доступны; автокалибровка недоступна.
controller-calibration-capability-sdl-normalized = Нормализованный ввод SDL; только ручная калибровка.
controller-calibration-suspicious-origin-warning = Одна или несколько осей с автоматическим началом отсчёта проигнорированы. Проверьте сведения о резервных значениях ниже.
controller-calibration-invalid-saved-warning = Сохранённая калибровка пропущена: {$reason}
controller-calibration-invalid-shaping-warning = Сохранённые настройки стиков пропущены: {$reason}
controller-calibration-status-policy-preview = предпросмотр политики
controller-calibration-status-manual-preview = ручной предпросмотр
controller-calibration-status-modified = изменён
controller-calibration-status-current = текущий
controller-calibration-status-policy = политика
controller-calibration-status-manual = вручную
controller-calibration-status-not-saved = не сохранено
controller-calibration-status-saved = сохранено
controller-calibration-status-active-differs = Активная настройка отличается от сохранённой
controller-calibration-draft-status = {$intent} · черновик {$draft} · активно {$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = Автокалибровка: {$state}
controller-calibration-automatic-unavailable = недоступна
controller-calibration-automatic-on = включена
controller-calibration-automatic-off = выключена
controller-calibration-automatic-policy-native-help = Переключить автокалибровку начала отсчёта GameCube.
controller-calibration-automatic-policy-unavailable-help = Для этого источника ввода автокалибровка недоступна.
controller-calibration-axis-left-x = Левый стик X
controller-calibration-axis-left-y = Левый стик Y
controller-calibration-axis-right-x = Правый стик X
controller-calibration-axis-right-y = Правый стик Y
controller-calibration-axis-left-trigger = Левый триггер
controller-calibration-axis-right-trigger = Правый триггер
controller-calibration-field-minimum = минимум
controller-calibration-field-center = центр
controller-calibration-field-maximum = максимум
controller-calibration-field-released = отпущен
controller-calibration-field-pressed = нажат
controller-calibration-value-na = Н/Д
controller-calibration-unit-gamecube-directed = направленный байт GameCube
controller-calibration-unit-sdl-normalized = нормализовано SDL
controller-calibration-unit-canonical-normalized = нормализовано
controller-calibration-unit-gamecube-protocol-byte = байт протокола GameCube
controller-calibration-axis-values-normalized = {$axis} · {$unit} · источник {$source} · корр. {$corrected} · предпр. {$preview} · игра {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} абс. {$absolute}, начало {$origin} · {$sourceUnit} источник {$source} · {$normalizedUnit} корр. {$corrected}, предпр. {$preview}, игра {$gameplay}
controller-calibration-axis-statistics = Отсчётов: {$samples} · мин. {$minimum} · макс. {$maximum} · пик {$peak} · дрожание {$jitter} · {$unit}
controller-calibration-reported-buttons = Нажаты: {$buttons}
controller-calibration-reported-buttons-none = нет
controller-calibration-capture-status-ready = готово
controller-calibration-capture-status-waiting-release = отпустите всё
controller-calibration-capture-status-capturing = захват
controller-calibration-capture-status-captured = захвачено
controller-calibration-capture-status-invalid = неверный захват
controller-calibration-capture-neutral = Захватить нейтраль
controller-calibration-capture-range = Захватить полный диапазон
controller-calibration-capture-help = По запросу отпустите всё, затем выполните действие захвата.
controller-calibration-stick-movement = Стик движения
controller-calibration-stick-right = Правый / C-стик
controller-calibration-shaping-deadzone = мёртвая зона
controller-calibration-shaping-cardinal-snap = привязка к осям
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting}: {$value}{$unit} · {$step}
controller-calibration-shaping-help = Влево/вправо или края строки — настройка · Подтверждение или центр строки — переключение точного/грубого шага.
controller-calibration-adjust-value = {$axis} {$field}: {$value} {$unit} · {$step}
controller-calibration-step-fine = точно
controller-calibration-step-coarse = грубо
controller-calibration-adjust-help = Влево/вправо или края строки — настройка · Подтверждение или центр строки — переключение точного/грубого шага. Физические единицы зависят от источника.
controller-calibration-apply-current-connection = Применить к текущему подключению
controller-calibration-save-to-tag = Сохранить для тега контроллера
controller-calibration-save-to-tag-target = Сохранить для {$tag} ({$layout})
controller-calibration-save-to-tag-no-tag = Сохранить для тега (нужен тег)
controller-calibration-reset-draft-active = Сбросить черновик к активной
controller-calibration-reset-draft-saved = Сбросить черновик к сохранённой
controller-calibration-reset-draft-layout-defaults = Сбросить к стандарту раскладки
controller-calibration-reset-session = Сбросить сеанс подключения
controller-calibration-delete-saved = Удалить сохранённую калибровку
controller-calibration-delete-saved-confirm = Подтвердить: удалить калибровку
controller-calibration-copy-diagnostic = Копировать диагностику
controller-calibration-action-help = Подтвердите выполнение действия.
controller-calibration-applied = Калибровка применена к текущему подключению.
controller-calibration-save-tag-required = Для сохранения нужен действительный тег контроллера.
controller-calibration-saved = Калибровка сохранена для {$tag} ({$layout}).
controller-calibration-no-saved-calibration = Для этого контроллера нет сохранённой калибровки.
controller-calibration-delete-saved-complete = Сохранённая калибровка удалена.
controller-calibration-copy-diagnostic-complete = Диагностика калибровки скопирована.
controller-calibration-local-controllers = Другие локальные контроллеры
controller-calibration-switch-controller = Сменить контроллер
controller-calibration-switch-controller-name = Переключиться на {$controller}
controller-calibration-switch-decision = {$controller} · Влево применить · Вправо {$save} · Подтвердить отбросить
controller-calibration-switch-save-available = сохранить
controller-calibration-switch-save-unavailable = сохранение недоступно
controller-calibration-switch-decision-help = Не сохранено: влево — применить, вправо — сохранить, подтвердить — отбросить и сменить.
controller-calibration-back = Назад
controller-calibration-back-help = Вернуться к управлению. Активный захват сначала отменяется.
controller-calibration-back-discard-confirm = Подтвердить: отбросить черновик и выйти
controller-calibration-disconnected-draft-discarded = Контроллер отключён; черновик калибровки отброшен.

# PhobGCC
controller-calibration-phob-board-unconfirmed = доска не подтверждена
controller-calibration-phob-board-v1 = Выберите PhobGCC v1.
controller-calibration-phob-board-v1-value = PhobGCC v1
controller-calibration-phob-board-v2 = Выберите PhobGCC v2.
controller-calibration-phob-board-v2-value = PhobGCC v2
controller-calibration-phob-calibrate-c-stick = Калибровка C-stick: A+X+Y+R
controller-calibration-phob-calibrate-left = Калибровка основного джойстика: A+X+Y+L
controller-calibration-phob-calibration-complete = Завершить (только клавиатура/мышь)
controller-calibration-phob-calibration-confirm = Подтвердить: начать калибровку прошивки
controller-calibration-phob-calibration-help = Запускает рабочий процесс прошивки, который необходимо завершить на контроллере.
controller-calibration-phob-calibration-no-cancel = С контроллера нельзя отменить или завершить эту процедуру. Закончите её и выберите «Завершить» клавиатурой/мышью. Если процесс завис, переподключите контроллер.
controller-calibration-phob-calibration-phases = Следуйте указаниям другого стика для каждого шага центра, края и выемки. Завершите обе фазы прошивки перед кнопкой «Завершить».
controller-calibration-phob-enter-configure = Введите Configure Mode
controller-calibration-phob-enter-configure-instruction = На физическом контроллере удерживайте A+X+Y+Start, пока оба джойстика не сообщат о верхнем правом углу, затем отпустите.
controller-calibration-phob-exit-safe-instruction = На физическом контроллере нажмите A+X+Y+Start. Отпустите после более длинного ответа в правом верхнем углу.
controller-calibration-phob-host-correction-stale = Коррекция Antistatic после калибровки прошивки: активная {$active}; сохранённая {$saved}. Проверьте значения по умолчанию или выполните захват заново.
controller-calibration-phob-instruction-none = ни одна команда не ожидает выполнения
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = режим неизвестен
controller-calibration-phob-open = Открыть руководство по PhobGCC
controller-calibration-phob-open-guide-031 = Открыть официальную инструкцию по прошивке 0.31
controller-calibration-phob-open-help = Управляемые проверки только для чтения для подтвержденного пользователем PhobGCC v1 или v2.
controller-calibration-phob-open-phobvision-029-v2 = Открыть руководство PhobVision 0.29 (только с версией v2)
controller-calibration-phob-open-release-031 = Открыть примечания к выпуску прошивки 0.31
controller-calibration-phob-open-version-guide = Открыть руководство по заявленной прошивке
controller-calibration-phob-origin-checks = Перед калибровкой прошивки при необходимости активируйте стики физической B и проверьте исходные значения адаптера.
controller-calibration-phob-query-c-settings = Прочитайте настройки C-stick: R+Start
controller-calibration-phob-query-main-settings = Чтение настроек основного джойстика: L+Start
controller-calibration-phob-query-trigger-settings = Чтение настроек триггера: L+R+Z
controller-calibration-phob-query-version = Чтение версии прошивки: A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = Диагностика необработанных значений активна. Это экранные координаты после обработки прошивкой из обычных отчётов контроллера, а не прямые данные датчиков или игровой вывод.
controller-calibration-phob-raw-disable = Отключить необработанный вывод: L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = На физическом контроллере нажмите L+R+D-pad Down, дождитесь ответа в правом верхнем углу, а затем отпустите все.
controller-calibration-phob-raw-enable = Включить необработанный вывод: L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = На физическом контроллере нажмите L+R+D-pad Up, дождитесь ответа в правом верхнем углу, а затем отпустите все.
controller-calibration-phob-raw-values = после прошивки: основной X {$leftX}, Y {$leftY}; C-stick X {$cX}, Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = необработанные значения недоступны
controller-calibration-phob-remap-warning = Команды используют физические кнопки по надписям на корпусе, несмотря на переназначение. Antistatic видит сообщаемые кнопки, которые могут отличаться.
controller-calibration-phob-result-matched = Ответ в стиле фоба совпал
controller-calibration-phob-result-none = пока нет ответа
controller-calibration-phob-result-unknown-custom = неизвестный или индивидуальный ответ
controller-calibration-phob-result-version-known = прошивка {$version}
controller-calibration-phob-result-version-no-response = нет ответа прошивки; версия неизвестна
controller-calibration-phob-return-safe = Вернуться в Safe Mode
controller-calibration-phob-safe-recovery = Чтобы гарантировать Safe Mode, отключите и снова подключите контроллер. Затем откройте руководство заново; обнаруженное состояние сбрасывается при отключении.
controller-calibration-phob-setting-c-response-x-raw = C-stick X байт ответа
controller-calibration-phob-setting-c-response-y-raw = C-stick Y байт ответа
controller-calibration-phob-setting-c-snapback-x = C-stick Snapback X
controller-calibration-phob-setting-c-snapback-y = C-stick Snapback Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick формирование волны X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick формирование волны X raw
controller-calibration-phob-setting-c-waveshaping-y = C-stick формирование волны Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick формирование волны Y необработанный
controller-calibration-phob-setting-main-smoothing-x = сглаживание основного джойстика X
controller-calibration-phob-setting-main-smoothing-y = сглаживание основного джойстика Y
controller-calibration-phob-setting-main-snapback-x = Snapback X с основным джойстиком
controller-calibration-phob-setting-main-snapback-y = Snapback с основным джойстиком Y
controller-calibration-phob-setting-main-waveshaping-x = формирование волны основного джойстика X
controller-calibration-phob-setting-main-waveshaping-x-raw = основной джойстик вейвшейпинг X raw
controller-calibration-phob-setting-main-waveshaping-y = формирование волны основного джойстика Y
controller-calibration-phob-setting-main-waveshaping-y-raw = формирование волны основного джойстика Y raw
controller-calibration-phob-setting-row = {$setting}: {$value} {$unit}
controller-calibration-phob-setting-rows-none = нет декодированных настроек
controller-calibration-phob-settings-c-stick-instruction = На физическом контроллере удерживайте R+Start в течение двух секунд, а затем отпустите.
controller-calibration-phob-settings-main-instruction = На физическом контроллере удерживайте L+Start в течение двух секунд, а затем отпустите.
controller-calibration-phob-settings-read-only = Эти показания не меняют настройки прошивки. Используйте официальные инструкции для внесения изменений и сброса настроек.
controller-calibration-phob-settings-triggers-instruction = На физическом контроллере удерживайте L+R+Z в течение двух секунд, а затем отпустите.
controller-calibration-phob-setting-trigger-left-mode = режим левого триггера
controller-calibration-phob-setting-trigger-left-value = значение левого триггера
controller-calibration-phob-setting-trigger-right-mode = правый режим триггера
controller-calibration-phob-setting-trigger-right-value = правильное значение триггера
controller-calibration-phob-setup-active = Phob Setup Mode активен: сообщаемый D-pad перемещает, сообщаемая A подтверждает.
controller-calibration-phob-setup-enter = Введите Phob Setup Mode
controller-calibration-phob-setup-exit = Выход Phob Setup Mode
controller-calibration-phob-setup-exit-chord = Для выхода ровно одну секунду удерживайте только сообщаемые D-pad Вниз+Влево + основной стик вправо-вверх + C-stick вправо-вниз, затем отпустите. Недоступно при калибровке прошивки.
controller-calibration-phob-stale-state-current = текущий
controller-calibration-phob-stale-state-stale = несвежий
controller-calibration-phob-status = Доска: {$board} · Режим: {$mode} · Результат: {$result} · Шаг: {$instruction} · {$raw} · Настройки: {$rows}
controller-calibration-phob-unit-protocol-byte = байт протокола
controller-calibration-phob-unit-setting-value = значение настройки
controller-calibration-phob-unit-trigger-byte = триггерный байт
controller-calibration-phob-unofficial-warning = Неофициальный помощник PhobGCC, не связанный с проектом. Подтвердите плату и прошивку; Antistatic не определяет оборудование и не записывает настройки.
controller-calibration-phob-version-instruction = В Configure Mode нажмите физический A+Z+D-pad Up, удерживайте показание в течение двух секунд, затем отпустите.
controller-calibration-mode-basic = Вид: ОСНОВНОЙ
controller-calibration-mode-advanced = Вид: РАСШИРЕННЫЙ
controller-calibration-mode-toggle-help = Переключает обычные настройки и подробную диагностику.
controller-calibration-origin-diagnostic-unavailable = Автоматическая диагностика начала отсчёта недоступна для этого источника.
controller-calibration-origin-diagnostic = Стабильное начало: {$phase} · {$reports} отчётов · {$stable}/6 применено · {$fallback}/6 резерв · {$dropped} переполнений
controller-calibration-origin-phase-collecting = сбор
controller-calibration-origin-phase-complete = завершено
controller-calibration-use-suggested-deadzones = Применить рекомендуемые мёртвые зоны
controller-calibration-use-suggested-deadzones-help = Применяет измеренные внутренние и внешние мёртвые зоны.
controller-calibration-section-stick-shaping = НАСТРОЙКА СТИКОВ
controller-calibration-section-trigger-shaping = НАСТРОЙКА ТРИГГЕРОВ
controller-calibration-section-action-diagnostics = ДИАГНОСТИКА ДЕЙСТВИЙ
controller-calibration-section-physical-diagnostics = ДИАГНОСТИКА ОСЕЙ
controller-calibration-section-hardware-correction = АППАРАТНАЯ КОРРЕКЦИЯ
controller-calibration-shaping-inner-deadzone = внутренняя мёртвая зона
controller-calibration-shaping-outer-deadzone = внешняя мёртвая зона
controller-calibration-snap-override-help = Переключает настройку игрока. Минимум режима продолжает действовать.
controller-calibration-snap-override-state = Привязка {$stick}: {$state} · минимум {$floor}° · итог {$effective}°
controller-calibration-override-enabled = включена
controller-calibration-override-disabled = выключена
controller-calibration-trigger-shaping-help = Влево/вправо или края строки — настройка · Подтверждение или центр строки — переключение точного/грубого шага.
controller-calibration-trigger-inner-deadzone = внутренняя мёртвая зона
controller-calibration-trigger-outer-deadzone = внешняя мёртвая зона
controller-calibration-trigger-response-curve = кривая отклика
controller-calibration-trigger-hard-press-threshold = порог сильного нажатия
controller-calibration-trigger-shaping-value = {$trigger} {$setting}: {$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = Измерено: шум движения {$movementNoise}, внутр. {$movementInner}, внеш. {$movementOuter}, охват {$movementCoverage}/16 · правый шум {$rightNoise}, внутр. {$rightInner}, внеш. {$rightOuter}, охват {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = Триггеры: L шум {$leftNoise}, внутр. {$leftInner}, внеш. {$leftOuter} · R шум {$rightNoise}, внутр. {$rightInner}, внеш. {$rightOuter}
controller-calibration-stick-diagnostic = {$stick}: вход {$mapped} · игра {$gameplay} · {$zone} · привязка {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger}: вход {$mapped} · игра {$gameplay} · {$zone} · сильное {$hard}
controller-calibration-zone-inner-dead = внутренняя мёртвая зона
controller-calibration-zone-linear = активный диапазон
controller-calibration-zone-outer-saturated = внешнее насыщение
controller-calibration-state-yes = да
controller-calibration-state-no = нет
controller-calibration-hard-source-none = нет
controller-calibration-hard-source-digital-button = цифровой щелчок
controller-calibration-hard-source-analog-threshold = аналоговый порог
controller-calibration-help = Вверх/вниз — перемещение · Влево/вправо или края строки — настройка · Подтверждение или центр строки — смена точности · Назад — вернуться.
controller-calibration-tag-required-prerequisite = Перед калибровкой добавьте тег игрока в меню управления, чтобы включить сохранение. Применение к этому подключению останется доступно.
controller-calibration-status-draft-or-active-differs = Черновик или активная настройка отличается от сохранённой
controller-calibration-capture-mode-neutral = Нейтраль
controller-calibration-capture-mode-range = Полный диапазон
controller-calibration-capture-accept-pending = Принять захват «{$mode}»
controller-calibration-capture-accept-and-start = Принять {$pending}, затем захватить {$next}
controller-calibration-capture-status-pending = захват «{$mode}» ожидает проверки
controller-calibration-legend-source = Стандарт раскладки
controller-calibration-legend-corrected = Коррекция
controller-calibration-legend-preview = Предпросмотр
controller-calibration-legend-gameplay = Игра
controller-calibration-origin-fallback-detail = Резерв: {$axes}
controller-calibration-origin-fallback-axis = {$axis}: {$reason}
controller-calibration-origin-reason-insufficient-reports = недостаточно корректных отчётов; отпустите управление и переподключите контроллер
controller-calibration-origin-reason-unstable = ввод двигался; отпустите управление и переподключите контроллер
controller-calibration-origin-reason-implausible = начало вне ожидаемого диапазона; отпустите управление и переподключите контроллер
controller-calibration-origin-reason-unsafe-bounds = начало сделает коррекцию небезопасной; захватите нейтраль и полный диапазон
controller-calibration-phob-setup-suspended-raw = Phob Setup Mode приостановлен, пока активна диагностика необработанных значений. Отключите необработанный вывод для продолжения.
controller-calibration-phob-result-version-custom = ответ нестандартной прошивки: X {$x}, Y {$y}
controller-calibration-phob-result-unknown = нераспознанный ответ
controller-calibration-phob-raw-mode-off = режим необработанных значений выключен

# Конфиденциальность, отчёты и обратная связь
privacy-title = Конфиденциальность
privacy-settings-help = Настройка сети, отчётов о сбоях, анонимной статистики и обратной связи.
privacy-networking = Доступ к сети
privacy-networking-help = Главный переключатель сетевой игры и всех служб Antistatic. При отключении текущие сетевые сеансы завершатся.
privacy-crash-reporting = Отчёты о сбоях: {$value}
privacy-crash-reporting-help = Выберите, должен ли Antistatic спрашивать перед отправкой анонимной диагностики сбоев.
privacy-crash-ask = Всегда спрашивать
privacy-crash-never = Никогда не отправлять
privacy-crash-always = Всегда отправлять
privacy-gameplay-metrics = Анонимная статистика матчей
privacy-gameplay-metrics-help = Разрешить отправку общих данных: режим, персонажи, длительность и результат матча.
privacy-performance-metrics = Анонимная статистика производительности
privacy-performance-metrics-help = Разрешить отправку общих данных об оборудовании и времени кадра для улучшения производительности.
privacy-feedback-open = Отправить отзыв
privacy-feedback-open-help = Отправить сообщение об ошибке или другой отзыв команде Antistatic.
privacy-policy-open = Открыть политику конфиденциальности
privacy-policy-open-help = Прочитать официальную политику конфиденциальности Antistatic.
privacy-policy-title = Политика конфиденциальности
privacy-policy-help = В этой политике объясняется, как Antistatic обрабатывает сетевой доступ, отчёты о сбоях, необязательную статистику и обратную связь.
privacy-crash-send-pending = Отправить ожидающий отчёт
privacy-crash-send-pending-help = Отправить отчёт о сбое, ожидающий вашего согласия.
privacy-crash-discard-pending = Удалить ожидающий отчёт
privacy-crash-discard-pending-help = Навсегда удалить отчёт о сбое, не отправляя его.
privacy-summary = Сеть включена по умолчанию. Для отчётов о сбоях требуется ваш выбор; анонимная статистика выключена до вашего согласия.
privacy-netplay-disabled = Сетевая игра отключена
privacy-netplay-disabled-help = Включите Доступ к сети в настройках конфиденциальности, чтобы играть по сети.
privacy-crash-prompt-title = Отчёт о сбое
privacy-crash-prompt-body = Antistatic обнаружил ожидающий отчёт о сбое. Отправить анонимную диагностику для повышения стабильности?
privacy-crash-prompt-send = Отправить отчёт
privacy-crash-prompt-later = Спросить позже
privacy-crash-prompt-never = Не отправлять отчёты о сбоях
privacy-crash-prompt-summary = Отправьте этот отчёт, решите позже или отключите отчёты о сбоях.
privacy-report-sending = Отправка...
privacy-report-failed = Не удалось отправить. Проверьте сеть и повторите попытку.
privacy-crash-sent = Отчёт о сбое отправлен
privacy-crash-discarded = Отчёт о сбое удалён
privacy-feedback-title = Обратная связь
privacy-feedback-category = Категория: {$value}
privacy-feedback-category-help = Выберите тип сообщения.
privacy-feedback-category-bug = Ошибка
privacy-feedback-category-feedback = Отзыв
privacy-feedback-category-other = Другое
privacy-feedback-subject = Тема
privacy-feedback-subject-help = Введите краткое описание.
privacy-feedback-subject-placeholder = Краткое описание
privacy-feedback-body = Сообщение
privacy-feedback-body-help = Опишите проблему или предложение. Не указывайте личные данные.
privacy-feedback-body-placeholder = Что вы хотите нам сообщить?
privacy-feedback-submit = Отправить отзыв
privacy-feedback-submit-help = Отправить это сообщение команде Antistatic.
privacy-feedback-warning = Не указывайте личные данные, пароли и закрытые данные учётных записей.
privacy-feedback-help = Заполните тему и сообщение, затем отправьте отзыв.
privacy-feedback-required = Введите тему и сообщение.
privacy-feedback-sent = Отзыв отправлен. ID отчёта: {$id}
