hello-world = 你好，世界！ { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = 矽
Iron = 鐵
Xenon = 氙
Helium = 氦
Carbon = 碳
Rhodium = 銠

Sandbag = 沙袋

Ruins = 廢墟
Transistor = 晶體管
Eroded = 腐蝕的
Scales = 秤
Crossing = 路口
Longboat = 長艇
Boombox = 手提音響
Fountain = 噴泉
Great-White = 大白鯊
Plane = 平面
Satellite = 衛星
Divided = 分為
Pillars = 支柱
Debug = 除錯

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = 原版
Physics = 物理
color-preset-random = 隨機
color-preset-red = 紅色
color-preset-orange = 橙色
color-preset-gold = 金色
color-preset-green = 綠色
color-preset-blue = 藍色
color-preset-purple = 紫色
color-preset-pink = 粉紅色
color-preset-white = 白色
versus-color-preset-help = 選擇一個顏色系列；每次選擇都會獲得輕微的隨機變化。隊伍模式下不可用。

# Navigation
Back = 返回
Exit = 退出
Save = 保存
Cancel = 取消
Close-Symbol = X

Modify = 修改
Reset = 重啟

# Main Menu
Versus = 對抗模式
Training = 訓練
Courses = 課程
TRAINING = 訓練
COURSES = 課程
battle-results = 對戰結果
Settings = 設置
Controls = 操作
Discord = Discord {"\u29C9"}
Guide = 指南 {"\u29C9"}

# Settings Menu
SETTINGS = 設置
Audio = 音訊
Video = 視頻設置
accessibility-title = 輔助功能
settings-accessibility-help = 調整動態、打擊效果、選單音效和焦點可見度。
accessibility-reduced-motion = 減少動態
accessibility-reduced-motion-help = 停止選單背景動畫和打擊時的視覺抖動。
accessibility-hit-flash = 打擊閃光：{$value}
accessibility-hit-flash-help = 調整角色受擊閃光的亮度。
accessibility-screen-shake = 打擊抖動：{$value}
accessibility-screen-shake-help = 調整打擊時角色和介面的視覺抖動。
accessibility-menu-sound = 增強選單音效
accessibility-menu-sound-help = 提高導覽和確認音效的音量。
accessibility-high-contrast-focus = 高對比度焦點
accessibility-high-contrast-focus-help = 為目前的選單控制項加上明亮的雙層輪廓。
accessibility-help = 調整輔助功能和顯示偏好。
first-run-title = 歡迎來到 Antistatic
first-run-intro = 選擇一個起點。你可以隨時從主選單調整控制和輔助功能。
first-run-versus = 本機對戰
first-run-versus-help = 為共用此裝置的玩家設定對戰。
first-run-controls = 控制
first-run-controls-help = 檢視、重新配置和校準輸入。
first-run-training = 訓練
first-run-training-help = 使用訓練工具和目標自由練習。
first-run-courses = 課程
first-run-courses-help = 透過引導課程學習移動、攻擊、防禦和返回場地。
first-run-skip = 前往主選單（略過）
first-run-skip-help = 不開啟任何模式，完成這次首次引導。
first-run-help = 選擇從哪裡開始。選擇任何項目都會完成這次首次引導。
Windowed = 窗口模式
Fullscreen = 全屏

main = 主界面
versus = 對抗模式
training = 訓練
start-mode = 開始： { TRANSLATE($value) }

# Audio Menu
AUDIO = 音訊

Play-Audio = 播放音訊
Play-Music = 播放音樂

Audio-volume = 音量： {$value}
SFX-volume = 特效： {$value}
Music-volume = 音樂： {$value}
UI-volume = 介面： {$value}
Voice-volume = 語音： {$value}

# Video Menu
VIDEO = 視頻設置
Quick-Setup = 快速設定
Display = 顯示
Quality = 品質
Effects = 特效
Apply-Changes = 套用變更

graphics-preset-low = 圖形：低
graphics-preset-medium = 圖形：中
graphics-preset-high = 圖形：高
graphics-preset-max = 圖形：最高
graphics-preset-custom = 圖形：自訂

vsync-off = 垂直同步：關閉
vsync-on = 垂直同步：開啟
vsync-adaptive = 垂直同步：自適應

shadow-off = 陰影：關閉
shadow-low = 陰影：低
shadow-highest = 陰影：最高

ssao-off = SSAO：關閉
ssao-on = SSAO：開啟
ssao-full = SSAO：完整

aa-off = 抗鋸齒：關閉
aa-fxaa = 抗鋸齒：FXAA
aa-fxaa-high = 抗鋸齒：高品質 FXAA

bloom-off = Bloom：關閉
bloom-on = Bloom：開啟
reflections-off = 反射：關閉
reflections-on = 反射：開啟
reflections-low = 反射：低
reflections-high = 反射：高
godrays-off = 體積光：關閉
godrays-on = 體積光：開啟

perf-overlay-off = 效能指示器：關閉
perf-overlay-on = 效能指示器：開啟


point-lights-off = 點光源：關閉
point-lights-on = 點光源：開啟

particles-low = 粒子：低
particles-medium = 粒子：中
particles-full = 粒子：高


max-fps-off = 最大幀率：關閉
max-fps-30 = 最大幀率：30
max-fps-60 = 最大幀率：60
max-fps-120 = 最大幀率：120
max-fps-144 = 最大幀率：144

# Controls Menu
CONTROLS = 操作

controls-title = 操作
controls-section-controllers = 控制器
controls-section-mappings = 映射
controls-set-tag = 設置標籤
controls-edit-bindings = 編輯按鍵綁定
controls-tag-untagged = (無標籤)
controls-tag-title = 玩家標籤
controls-tag-prompt = P{$port} ({$layout})。標籤可以是1-24個字母數字、「-」或「_」字符。留空以清除。
controls-tag-confirm = 確認
controls-tag-clear = 清除
controls-tag-cancel = 取消
controls-tag-select-title = 選擇標籤
controls-tag-filter-empty = 輸入以篩選已儲存標籤
controls-tag-filter-value = 篩選：{$filter}
controls-tag-summary-empty = 已儲存 {$total} 個標籤。輸入以篩選，或建立新標籤。
controls-tag-summary-filter = 顯示 {$visible}/{$total} 個已儲存標籤。完全相符會使用已儲存的控制設定。
controls-tag-defaults-suffix = 此控制器的預設設定
controls-tag-create-new = 建立新標籤
controls-tag-use-existing = 使用現有標籤「{$tag}」
controls-tag-create = 建立「{$tag}」
controls-tag-reserved = 「{$tag}」已保留
controls-tag-netplay-blocked = 連線對戰期間不能更改標籤
controls-tag-no-controller = 未選擇本地控制器
controls-tag-no-layout = 所選控制器沒有佈局
controls-tag-filter-help = 輸入以篩選標籤；ESC 清除或離開
controls-tag-no-saved = 尚未有已儲存標籤
controls-tag-no-matches = 沒有相符標籤
controls-tag-invalid = 標籤無效（1-24個字符，字母數字/-/_；「default」已保留）
controls-profile-help-untagged = 控制設定會儲存到共用的無標籤設定檔；只有儲存上跳預設值時需要標籤。
controls-profile-help-tagged = 控制和上跳預設值會儲存到此標籤和此控制器類型。
controls-choose-existing-tag = 選擇現有標籤
controls-create-tag = 建立標籤
controls-rename-create-tag = 重新命名/建立標籤
controls-edit-set-tag-first = 編輯控制（請先設定標籤）
controls-edit-controls = 編輯控制
controls-tap-jump-default = 上跳預設值：{$state}
controls-state-on = 開
controls-state-off = 關
controls-netplay-blocked = 連線對戰期間不能更改控制
controls-no-local-controllers = 沒有使用中的控制器。按遊戲操作鍵或控制器按鈕進行連接。
controls-no-layout = 控制器沒有佈局
controls-set-tag-before-editing = 請先設定標籤，再編輯控制
controls-no-mapping = 此控制器沒有可用映射
controls-set-tag-before-tap-jump = 請設定標籤以儲存上跳預設值
controls-connected-controllers = 已連接控制器
controls-remap-add-key = + 新增綁定（按一個鍵）
controls-remap-find-input = 尋找綁定（按一個輸入）
controls-remap-capture-key-title = 按一個鍵
controls-remap-capture-input-title = 按一個輸入
controls-remap-capture-key-help = 下一個按下的鍵會新增為新綁定。
controls-remap-capture-input-help = 下一個使用的按鈕或搖桿會被選中以便編輯。
controls-remap-capture-cancel = 按 ESC 取消
controls-default-save-blocked = 不能覆蓋預設控制；請先設定標籤
controls-default-reset-blocked = 不能從此選單重置預設控制
controls-tag-filter-entry-help = 輸入以篩選已儲存的控制器標籤；手掣可使用方向鍵。
controls-tag-filter-label = 篩選
controls-tag-preconfigured = 預先設定
controls-tag-rename-title = 重新命名標籤
controls-tag-create-title = 建立標籤
controls-tag-apply-existing-help = 將相符的已儲存標籤套用到此控制器。
controls-tag-create-empty-help = 為此控制器建立新標籤。
controls-tag-create-filtered-help = 如果名稱有效，就為控制器建立此標籤。
controls-tag-apply-saved-help = 將此標籤及其已儲存映射套用到控制器。
controls-tag-apply-preconfigured-help = 使用此控制器類型的預設映射套用這個預先設定標籤。
controls-tag-apply-default-help = 使用此控制器類型的預設映射套用此標籤。
controls-tag-delete-button = 刪除 {$tag}
controls-tag-delete-help = 確認後刪除 {$tag} 及每種控制器類型已儲存的控制設定和校準。
controls-tag-delete-title = 刪除標籤？
controls-tag-delete-body = 刪除「{$tag}」、每種控制器類型的控制設定和校準，並取消其與已連接控制器的分配？
controls-tag-delete-warning = 此操作無法復原。
controls-back-help = 返回控制。
controls-tag-select-help = 選擇或建立控制器標籤。
controls-edit-set-tag-first-help = 先建立控制器標籤，再編輯遊戲與選單綁定。
controls-edit-controls-help = 編輯此控制器設定檔的遊戲與選單綁定。
controls-tap-jump-set-tag-first-help = 先建立控制器標籤，再設定預設輕點跳躍偏好。
controls-tap-jump-default-help = 切換此控制器預設是否按上就跳。
controls-create-new-tag-help = 建立新標籤並將此控制器切換到它。
controls-choose-existing-tag-help = 選擇或刪除已儲存標籤。
controls-rename-current-tag-help = 重新命名目前控制器標籤。
controls-switch-controller-help = 將控制選單切換到這個已連接的控制器。
menu-binding-hint = 用搖桿或方向鍵移動 · 確認/Start 選擇 · 返回鍵返回
menu-adjust-hint = 用搖桿或方向鍵移動 · 左/右更改數值 · 確認選擇 · 返回鍵返回
menu-bind-hint = 用搖桿或方向鍵移動 · 確認選擇綁定 · 返回鍵返回
arcade-select-leave = Select 離開
main-help-about-help = 指南、製作人員和 bluehexagons 連結。
main-replays-available-help = 瀏覽、預覽並播放已儲存的回放檔案。
main-replays-unavailable-help = 回放只能離線使用，因為它們會從本機檔案系統載入。
arcade-menu-battles-help = 使用目前 Arcade Battles 設定開始。
arcade-menu-infinite-help = 開始無盡 Arcade 模式，對抗會逐步增強的 1-stock CPU。
arcade-menu-training-help = 打開帶練習工具和狀態儲存的訓練模式。
arcade-menu-back-help = 返回主選單。
arcade-menu-help = 選擇一個街機模式。
training-menu-courses-help = 選擇一個簡短的遊戲機制課程。
training-menu-help = 選擇一項訓練活動。
courses-menu-course-help = 前往這個課程區域。
courses-menu-back-help = 返回訓練。
courses-menu-help = 課程區域從左到右排列。你可以隨時自由移動。
course-instruction-movement-walk = 向左或右推動移動搖桿來行走。
course-instruction-movement-dash = 向左或右快速推動移動搖桿來衝刺。
course-name-movement = 移動
course-name-jumping = 跳躍
course-name-attacks = 攻擊
course-name-defense = 防禦
course-name-advanced = 進階
course-name-directional-influence = 方向影響
course-name-teching = 受身
course-summary-movement = 行走、衝刺並到達標記。
course-summary-jumping = 跳躍並在空中移動。
course-summary-attacks = 用普通攻擊和必殺技擊中目標。
course-summary-defense = 擋下攻擊，然後抓取目標。
course-summary-advanced = 使用搖桿攻擊、空中迴避和快速下落。
course-summary-directional-influence = 用移動搖桿改變危險裝置的擊飛方向。
course-summary-teching = 被危險裝置擊飛後，在落地時受身。
course-instruction-movement-travel = 移動到箭頭標記。
course-instruction-jumping-jump = 按下跳躍離開地面。
course-instruction-jumping-steer = 跳躍後持續按住左或右，在空中移動。
course-instruction-attacks-normal = 用普通攻擊擊中練習目標。
course-instruction-attacks-special = 用必殺技擊中練習目標。
course-instruction-defense-shield = 用盾擋下練習目標的攻擊。
course-instruction-defense-grab = 抓取練習目標。
course-instruction-advanced-stick = 向任意方向快速推動右搖桿來使出搖桿攻擊。
course-instruction-advanced-air-dodge = 跳躍後用力按下盾按鈕來空中迴避。
course-instruction-advanced-fast-fall = 在空中按下下方向來快速下落。
course-instruction-directional-influence = 被發射台擊中的瞬間持續按住左或右，改變擊飛角度。
course-instruction-teching-neutral = 從發射台落地前，用力按下盾按鈕來受身。
course-instruction-complete = 區域完成。準備好後可前往其他區域。
course-action-restart = 重新開始區域
course-action-next = 下一個區域
course-session-progress = 已完成區域：{$completed}/{$total}
course-target-label = 練習目標
course-target-reset = 重設目標
course-target-disable = 停用目標
course-target-enable = 啟用目標
course-target-unavailable = 此區域沒有目標
course-target-reset-help = 將此區域的練習目標恢復到起始位置並啟用。
course-target-toggle-help = 在目前課程工作階段中隱藏或恢復此區域的練習目標。
course-defense-feedback-early = 等攻擊接近時再防禦。
course-defense-feedback-late = 太遲了。請在攻擊命中前防禦。
course-defense-feedback-success = 時機很好。已擋住攻擊。
course-demonstration-label = 示範
course-demonstration-show = 顯示靜態示範
course-demonstration-hide = 隱藏靜態示範
course-demonstration-help = 顯示或隱藏目前課程步驟的無動畫示例。
course-demonstration-still = 靜態姿勢 · 無動畫
help-bluehex-homepage-help = 造訪 bluehexagons 主頁。
help-bluehex-github-help = 在 GitHub 瀏覽 bluehexagons 專案。
help-bluehex-steam-help = 打開 bluehexagons 的 Steam 鑑賞家頁面。
help-bluehex-itch-help = 打開 bluehexagons 的 itch.io 頁面。
help-bluehex-bluesky-help = 在 Bluesky 關注 bluehexagons。
help-bluehex-patreon-help = 在 Patreon 支持 bluehexagons。
controls-source-keyboard = 鍵盤
controls-source-keyboard-defaults = 鍵盤預設值
controls-current-menu-controls-heading = 目前選單控制
controls-current-menu-controls-summary = {$source} · 移動：{$navigate} · 確認：{$confirm} · 返回：{$back}
controls-action-attack = 攻擊
controls-action-jump = 跳躍
controls-action-special = 必殺
controls-action-grab = 抓取
controls-action-shield-1 = 盾 1
controls-action-shield-2 = 盾 2
controls-action-hard-shield-1 = 強盾 1
controls-action-hard-shield-2 = 強盾 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-pad 上
controls-action-dpad-down = D-pad 下
controls-action-dpad-left = D-pad 左
controls-action-dpad-right = D-pad 右
controls-action-move-horizontal = 水平移動
controls-action-move-vertical = 垂直移動
controls-action-right-stick-horizontal = 右搖桿水平
controls-action-right-stick-vertical = 右搖桿垂直
controls-action-ui-confirm = UI 確認
controls-action-ui-back = UI 返回
controls-action-ui-up = UI 上
controls-action-ui-down = UI 下
controls-action-ui-left = UI 左
controls-action-ui-right = UI 右
controls-action-ui-horizontal-nav = UI 水平導航
controls-action-ui-vertical-nav = UI 垂直導航
controls-action-move-left = 向左移動
controls-action-move-right = 向右移動
controls-action-move-up = 向上移動
controls-action-move-down = 向下移動
controls-action-tilt-left = 輕推左
controls-action-tilt-right = 輕推右
controls-action-tilt-up = 輕推上
controls-action-tilt-down = 輕推下
controls-action-right-stick-left = 右搖桿左
controls-action-right-stick-right = 右搖桿右
controls-action-right-stick-up = 右搖桿上
controls-action-right-stick-down = 右搖桿下
controls-action-light-shield-l = 輕盾 L
controls-action-light-shield-r = 輕盾 R
controls-action-ui-nav-left = UI 左導航
controls-action-ui-nav-right = UI 右導航
controls-action-ui-nav-up = UI 上導航
controls-action-ui-nav-down = UI 下導航
controls-remap-section-buttons = 按鈕
controls-remap-section-dpad = D-pad
controls-remap-section-movement = 移動
controls-remap-section-tilts = 輕推（柔和輸入）
controls-remap-section-right-stick = 右搖桿
controls-remap-section-light-shields = 輕盾
controls-remap-section-ui-navigation = UI 導航
controls-remap-section-sticks-triggers = 搖桿與扳機
controls-remap-unbound = 未綁定
controls-remap-free-keys-none = 空閒按鍵：（常用集合中沒有）
controls-remap-more-suffix = ，另有 +{$count}
controls-remap-free-keys = 空閒按鍵：{$keys}{$suffix}
controls-remap-free-buttons = 空閒按鈕：{$buttons}
controls-remap-free-axes = 空閒軸：{$axes}
controls-remap-conflict-detail = {$input} 已綁定到 {$actions}。
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = 請保留 UI 確認、UI 返回及水平和垂直導覽，讓選單仍可使用。
controls-remap-capture-key-hint = 按下要用於 {$action} 的鍵盤按鍵。ESC 取消。
controls-remap-capture-button-hint = 按下要用於 {$action} 的 {$layout} 按鈕。返回取消。
controls-remap-capture-axis-hint = 移動要用於 {$action} 的 {$layout} 搖桿/扳機。返回取消。
controls-remap-capture-add-title = 加入 {$action}
controls-remap-capture-replace-title = 取代 {$action}
controls-remap-capture-matching-input = 請使用適合此動作的輸入。
controls-remap-confirm-reassign = 確認將它重新分配給 {$action}。
controls-remap-confirm-cancel-help = 確認會取代它。返回會取消。
controls-remap-command-add = 加入
controls-remap-command-replace = 取代
controls-remap-command-remove = 移除
controls-remap-add-help = 為 {$action} 加入另一個實體輸入。
controls-remap-replace-help = 取代 {$action} 的 {$input}。
controls-remap-remove-help = 從 {$action} 移除 {$input}。
controls-remap-back-to-controls = 返回控制
controls-remap-back-to-controls-help = 不用滾到重映射清單底部也可返回控制。
controls-remap-help = 選擇加入、取代或移除。Page 鍵可在清單中跳轉。
controls-remap-help-extended = 選擇加入、取代或移除。Page 鍵可在清單中跳轉；返回取消。
controls-remap-jump-to-section = 跳到分區
controls-remap-jump-to-binding = 跳到 {$section}
controls-remap-focus-section-help = 將焦點移到 {$section} 的第一個綁定。
controls-remap-reset-help = 將此控制設定重設為預設版面。需要兩次確認。
controls-remap-reset-confirm = 再按一次以確認重設
controls-quick-map-action-unbound = 未綁定
controls-quick-map-action-hard-shield-1-short = 盾 1
controls-quick-map-action-hard-shield-2-short = 盾 2
controls-quick-map-action-dpad-up-short = D-上
controls-quick-map-action-dpad-down-short = D-下
controls-quick-map-action-dpad-left-short = D-左
controls-quick-map-action-dpad-right-short = D-右
controls-quick-map-title = {$layout} 快速版面
controls-quick-map-mode-editing = 確認或點擊操作以套用 · 返回或點擊標題以離開
controls-quick-map-mode-ready = 確認進入快速編輯
controls-quick-map-mode-unavailable = 控制無法使用
controls-quick-map-assign = 分配
controls-quick-map-assign-input = 分配 {$input}
controls-quick-map-unavailable-status = 此控制器不支援快速映射。未儲存任何變更。
controls-remap-autosave-status = 變更會自動儲存。
controls-remap-saved-status = 已自動儲存。
controls-remap-blocked-menu-controls-status = 已阻止：請保留 UI 確認、UI 返回及選單的水平和垂直導覽。未儲存任何變更。
controls-remap-default-reset-blocked-status = 無法重設內置預設控制。未儲存任何變更。
controls-layout-standard = Xbox / 標準
controls-layout-arcade-stick = 街機搖桿
controls-layout-retro-dpad = 復古方向鍵
controls-layout-switch-pro = Switch Pro
controls-layout-playstation = PlayStation
controls-layout-8bitdo-nintendo = 8BitDo（Nintendo 版面）
controls-layout-steam-deck = Steam Deck
controls-layout-gamecube = GameCube
controls-layout-n64 = Nintendo 64
controls-layout-keyboard = 鍵盤

standard = 標準
keyboard = 鍵盤
gcn_native = GCN原生

# Training Menu
Swap-Character = 交換角色
Overlays = 疊加層
press-start = 按下開始

drawHitbubbleInfo = 攻擊信息
drawECB = 碰撞
drawHeatmap = 熱圖
drawRawPosition = 原始位置
drawStage = 舞台碰撞
animations = 動畫製作
controllers = 控制器

# Versus Menu
FFA = FFA
Teams = 隊伍

Host-Netplay = 主機網絡遊戲
Join-Netplay-Clipboard = 從剪貼板加入Netplay
Disconnect = 斷開
Copy-Lobby-Code = 複製大廳代碼

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = 直接連線
Connect = Connect

netplay-action-start-lobby = 開始大廳
netplay-action-join-clipboard = 從剪貼簿加入
netplay-action-quick-host-copy-code = 快速主機並複製代碼
netplay-action-copy-lan-invite = 複製LAN邀請
netplay-action-copy-localhost-invite = 複製Localhost邀請
netplay-action-copy-stun-invite = 複製STUN邀請
netplay-action-find-random-match = 查找隨機比賽
netplay-action-cancel-lobby = 取消大廳
netplay-action-cancel-connection = 取消連接
netplay-action-please-wait = 請稍候
netplay-action-open-versus = 打開Versus
netplay-action-cancel-matchmaking = 取消配對

netplay-status-label = 連線：{$status}
netplay-status-uninitialized = 未初始化
netplay-status-initialized = 已初始化
netplay-status-waiting = 等待中
netplay-status-hosting = 正在主持
netplay-status-connecting = 正在連接
netplay-status-establishing = 正在建立
netplay-status-connected = 已連接
netplay-status-ready = 準備Netplay
netplay-status-waiting-player = 等待玩家加入
netplay-status-waiting-lobby = 等待大廳響應
netplay-status-hosting-lobby = 正在主持大廳
netplay-status-hosting-lobby-code = 正在主持大廳 {$code}
netplay-status-starting-lobby = 正在開始大廳
netplay-status-connecting-host = 正在連接主機
netplay-status-connected-host = 已作為主機連接
netplay-status-connected-client = 已連接到主機
netplay-status-disconnecting = 正在斷開連接
netplay-status-canceling = 正在取消連接
netplay-status-matchmaking = 正在搜索隨機比賽
netplay-status-match-found = 找到隨機比賽
netplay-status-matchmaking-canceling = 正在取消配對
netplay-status-error = Netplay錯誤
netplay-status-error-message = Netplay錯誤: {$error}
netplay-status-unavailable = Netplay狀態不可用

matchmaking-title = 配對
matchmaking-status-select-character = 選擇角色以加入配對佇列
matchmaking-status-no-controller = 未連接控制器
matchmaking-status-searching = 正在尋找對手...
matchmaking-status-searching-details = 搜尋中... 已等待 {$wait} 秒。排隊玩家：{$players}。最長等待：{$longest} 秒。
matchmaking-status-searching-estimate = 搜尋中... 已等待 {$wait} 秒。排隊玩家：{$players}。已完成對戰平均耗時 {$average} 秒。
matchmaking-status-canceling = 正在取消...
matchmaking-status-found = 已找到對手！
matchmaking-status-connecting = 正在連線...
matchmaking-status-disconnecting = 正在中斷連線...
matchmaking-status-error = {$error} 請選擇角色後再試一次。

# Match by Code
match-code-title = 透過代碼對戰
match-code-hint = 分享你的代碼並輸入朋友的代碼。雙方都按「搜尋」。不分大小寫。
match-code-own-label = 你的代碼：{$code}
match-code-peer-label = 朋友的代碼：{$code}
match-code-peer-unset = 朋友的代碼：（未設定）
match-code-search = 搜尋
match-code-entry-limit = 最多 {$length} 個字母或數字
match-code-own-prompt = 你的代碼
match-code-peer-prompt = 朋友的代碼
match-code-status-enter-peer = 輸入朋友的代碼以建立私人對戰
match-code-status-ready = 準備就緒 — 雙方都應按「搜尋」
match-code-error-enter-peer = 請先輸入朋友的代碼
match-code-error-own = 請輸入朋友的代碼，而不是你自己的代碼
match-code-error-invalid = 該代碼無效
match-code-error-length = 代碼必須由 {$min}–{$max} 個字母或數字組成
match-code-error-blocked = 不允許使用該代碼；請選擇其他代碼

netplay-detail-ready = 主持大廳、貼上複製的邀請或手動輸入地址。
netplay-detail-lobby-code-ready = 大廳代碼 {$code} 已準備好分享。
netplay-detail-creating-lobby-code = 正在創建您的大廳代碼。
netplay-detail-waiting-for-host = 等待主機回答您的加入請求。
netplay-detail-share-lobby-code = 與其他玩家分享大廳代碼 {$code}。
netplay-detail-starting-lobby = 正在開始您的大廳連接。
netplay-detail-joining-host = 正在嘗試加入選定的主機。
netplay-detail-establishing = 找到玩家。完成握手，然後打開Versus。
netplay-detail-connected = 連接就緒。打開Versus選擇規則、角色和場地。
netplay-detail-disconnecting = 正在關閉當前會話並返回離線遊戲。
netplay-detail-canceling = 正在停止當前的加入請求。
netplay-detail-matchmaking = 使用Versus排隊尋找符合您首選規則的隨機對手。
netplay-detail-match-found = 找到對手。當兩名玩家都準備好時，在Versus中完成設置。
netplay-detail-matchmaking-canceling = 正在停止當前的隨機比賽搜索。
netplay-detail-error-message = 最後的錯誤: {$error}
netplay-detail-error-generic = 出現問題。請嘗試不同的代碼或連接方式。
netplay-detail-unavailable = Netplay詳情不可用。

netplay-help-host-copy-code = 複製您的大廳代碼，以便其他玩家可以貼上。
netplay-help-host-cancel-join = 停止當前的加入嘗試並返回就緒狀態。
netplay-help-host-disconnect = 離開當前的netplay會話。
netplay-help-host-start-lobby = 開始新大廳並等待其他玩家加入。
netplay-help-busy = Netplay現在正忙。請等待它完成。
netplay-help-join-cancel-lobby = 關閉當前大廳並停止等待其他玩家。
netplay-help-join-in-progress = 加入已在進行中。請等待或使用「取消連接」。
netplay-help-join-open-versus = 繼續到Versus並完成比賽設置。
netplay-help-stop-random-search = 停止搜索隨機對手。
netplay-help-join-clipboard = 從剪貼簿貼上大廳、直連或STUN邀請代碼。
netplay-help-copy-server = 如需要，先開始大廳，然後複製其可分享的大廳代碼。
netplay-help-copy-direct = 為此LAN上的另一個設備複製直連邀請。
netplay-help-copy-localhost = 為此計算機上運行的另一個副本複製直連邀請。
netplay-help-copy-stun = 複製STUN輔助邀請，在互聯網上更容易使用。
netplay-help-direct-connect = 手動輸入地址，而不是使用複製的邀請代碼。
netplay-help-find-random-match = 打開Versus並排隊等待隨機對手。
netplay-help-open-versus = 不離開此屏幕打開Versus菜單。
netplay-help-back = 返回主菜單。
netplay-help-unavailable = Netplay操作幫助不可用。
netplay-help-advanced = 調整netplay的高級設置，如回滾和緩衝區。

ADVANCED-CONNECTIONS = 進階連線
netplay-settings-rollback-help = 切換線上對戰的回滾模擬。
netplay-settings-buffer-help = 選擇要緩衝多少輸入影格，或讓連線自動選擇。
netplay-settings-force-ipv4-help = 在混合網路中產生區域網路邀請碼時優先使用 IPv4。
netplay-settings-back-help = 返回連線選單。
netplay-advanced-info = 當 Quick Play 或一般大廳代碼無法連線時，請使用這些備用選項。STUN 可協助在網際網路對戰中穿透路由器。直接連線最適合區域網路對戰，或適用於已轉送 UDP 連接埠的主機。
netplay-advanced-direct-help = 手動備用。用於區域網路對戰，或當主機已轉送 UDP 連接埠時輸入 host:port。
netplay-advanced-stun-help = 網際網路備用。當一般大廳加入失敗且仍需要路由器輔助打洞時，請分享這個選項。
netplay-advanced-lan-help = 區域網路備用。當兩位玩家位於同一網路時，請分享你可連到的本地位址。
netplay-advanced-localhost-help = 測試備用。僅在兩個用戶端都在同一台機器上執行時使用。
netplay-advanced-back-help = 返回虛擬沙發。
netplay-rollback-off = 回滾：關
netplay-rollback-on = 回滾：開
netplay-buffer-auto = 網路緩衝：自動
netplay-buffer-2 = 網路緩衝：2
netplay-buffer-3 = 網路緩衝：3
netplay-buffer-4 = 網路緩衝：4
netplay-buffer-5 = 網路緩衝：5
netplay-buffer-6 = 網路緩衝：6
netplay-buffer-7 = 網路緩衝：7
netplay-buffer-8 = 網路緩衝：8
netplay-buffer-10 = 網路緩衝：10
netplay-buffer-12 = 網路緩衝：12
netplay-force-ipv4-dual = 區域網路位址：IPv6/IPv4
netplay-force-ipv4-v4 = 區域網路位址：強制 IPv4

netplay-rollback = 回滾
netplay-buffer = 網絡緩衝區
netplay-force-ipv4 = LAN地址

netplay-direct-connect-prompt = 輸入IP地址:端口。端口默認為 {$port}。
netplay-stun-connect-title = 使用STUN服務？
netplay-stun-connect-prompt = 此代碼使用 {$service} 發現了 {$address}:{$port}。
netplay-waiting-host-battle = 等待主機戰鬥結束
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = 角色
Stages = 場地
CPU = CPU

Starter = 起始
Legal = 賽事
Miscellaneous = 其他

Start-Battle = 開始戰鬥

# Start Menu
quit-info = 盾牌 + 攻擊 + 開始 以退出
paused = 已暫停
tag-info = D-pad 上/下切換標籤進出

# Pause Menu
pause-resume = 繼續
pause-restart = 重新開始
pause-quit = 退出
pause-players = 玩家
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = 連接控制器並按任意按鈕加入。
arcade-return-prompt = 按確認返回主菜單。

# Replay
replay-paused = 重放已暫停
replay-controls = 確認：加入  ←/→：幀  返回：菜單  保存重放：[鍵]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = 英語
spanish = 西班牙文
french = 法文
italian = 意大利文
german = 德語
russian = 俄語
japanese = 日語
chinese-cn = 簡體中文
chinese-hk = {zh-chinese-hk}
korean = 韓語

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn} ({chinese-cn})
zh-hk = {zh-chinese-hk}
ko = {ko-korean} ({korean})

# Placeholder UI strings
Advanced = 進階
Clear-Spawns = 清除出生點
Create-new-tag = 建立新標籤
Credits = 製作人員
CREDITS = 製作人員
Cycle-Palette = 切換配色
Delete = 刪除
Help = 說明
HELP = 說明
Join = 加入
Join-Lobby-Code = 以大廳代碼加入
Main-Menu = 主選單
Mode = 模式
Native-Adapter = 原生轉接器
NATIVE-ADAPTER = 原生轉接器
NETPLAY-SETTINGS = 連線設定
Other-saved-tags = 其他已儲存標籤
Profiles-for-this-controller-type = 此控制器類型的設定檔
Quick-Play = 快速對戰
Random-Color = 隨機顏色
Rename-current-tag = 重新命名目前標籤
Reset-to-Defaults = 重設為預設值
Set-Character = 設定角色
Spawn-CPU = 生成 CPU
Team = 隊伍
Virtual-Couch = 虛擬沙發
x = x
Find-Random-Match = 尋找隨機對戰
training-label-stage = 場地
training-label-character = 角色
training-label-player-cursor = 玩家游標
training-label-cpu-spawn = 生成 CPU
training-label-savestate = 狀態儲存
Save-State = 儲存狀態
Load-State = 讀取狀態
State-Saved = 狀態已儲存
State-Restored = 狀態已恢復
No-State-Saved = 沒有已儲存狀態
DPad-Right-Save-Left-Load = 方向鍵右儲存 · 左讀取
shared-main-menu-help = 返回主選單。
shared-mode-selector-label-help = 規則選擇器標籤。
training-mode-selector-help = 在 Antistatic 和 19XX 的訓練規則之間切換。
training-overlays-help = 切換除錯覆蓋層和訓練輔助顯示。
training-close-help = 關閉訓練選單。
training-stage-help = 更換訓練場地並重設依附於場地的實體。
training-character-help = 選擇「設定角色」和「生成 CPU」會使用的角色。
training-set-character-help = 將懸停中的玩家游標切換到所選角色。
training-random-color-help = 為游標角色指派新的隨機基礎顏色。
training-cycle-palette-help = 循環切換游標角色的配色。
training-cpu-level-down-help = 降低新訓練 CPU 使用的 CPU 等級。
training-cpu-level-current-help = 新生成訓練 CPU 的目前 CPU 等級。確認可循環切換。
training-cpu-level-up-help = 提高新訓練 CPU 使用的 CPU 等級。
training-spawn-cpu-help = 使用所選角色和 CPU 等級生成一個 CPU。
training-clear-spawns-help = 移除訓練中生成的所有 CPU 和木樁角色。
training-save-state-help = 儲存目前訓練的位置、傷害、stock、生成的 CPU、場地和時序狀態。方向鍵右也可執行同一快捷操作。
training-load-state-help = 恢復已儲存的訓練狀態。方向鍵左也可執行同一快捷操作。
training-savestate-shortcuts-help = 方向鍵右儲存目前訓練狀態；方向鍵左恢復它。
versus-tag-selector-default = 標籤：{$tag}
versus-tag-none = 無標籤
versus-tag-manage = 建立 / 管理標籤
versus-tag-change-failed = 無法更改標籤
versus-cpu-level-help = 循環切換這個 CPU 等級。
versus-cpu-color-help = 重新隨機這個 CPU 的顏色和配色。
versus-cpu-team-help = 循環切換這個 CPU 的隊伍。
versus-cpu-remove-help = 移除此 CPU。
versus-character-select-help = 為懸停中的玩家游標選擇這個角色。
versus-add-cpu-help = 加入一個使用此角色的 CPU。
versus-tap-jump-help = 切換此玩家的輕點跳躍。
versus-random-color-help = 為此玩家指派新的隨機顏色。啟用隊伍時會停用。
versus-cycle-palette-help = 循環切換此玩家的配色。
versus-team-help = 循環切換此玩家的隊伍。只會在隊伍模式顯示。
versus-tag-selector-help = 選擇此玩家的標籤。連線對戰時停用。
versus-start-select-character-first = 請先選擇一個角色
versus-start-not-enough-players = 玩家數量不足，無法開始遊戲：{$count}
versus-start-not-enough-teams = 隊伍數量不足，無法開始遊戲：{$count}
versus-start-waiting-for-host = 正在等待主機開始
versus-ffa-help = 切換自由混戰與隊伍戰規則。
versus-start-help = 當足夠的玩家、CPU、隊伍和場地準備好後開始比賽。
versus-starter-help = 隨機選擇一個起始場地並開始比賽。
versus-legal-help = 隨機選擇一個合法的起始或反選場地並開始比賽。
versus-misc-help = 雜項場地。
versus-stage-preview-help = 懸停以預覽這個場地；確認即可選擇並開始。
versus-stage-preview-counterpick-help = 懸停以預覽這個反選場地；確認即可選擇並開始。
versus-stage-preview-misc-help = 懸停以預覽這個雜項場地；確認即可選擇並開始。
versus-mode-selector-help = 在 Antistatic 和 19XX 的對戰規則之間切換。
versus-tab-stages-help = 瀏覽並選擇本局對戰的場地。
versus-tab-settings-help = 設定對戰規則和選項。在這裏按 Start 會切換到場地選擇。
versus-setting-stock = Stock 模式
versus-setting-time = 時間模式
versus-setting-on = 開
versus-setting-off = 關
versus-setting-none = 無
versus-setting-stock-mode-value = 模式：{$value}
versus-setting-stocks-value = Stocks：{$value}
versus-setting-time-limit-value = 時間：{$value}
versus-setting-friendly-fire-value = FF：{$value}
versus-setting-stamina-value = 體力：{$value}
versus-setting-knockback-value = KB：{$value}×
versus-setting-pause-value = 暫停：{$value}
versus-setting-sd-value = SD：{$value}
versus-setting-stock-mode-help = 在 Stock 模式（最後存活的玩家勝出）和 Time 模式（計時結束時剩餘 stock 最多者勝出）之間切換。
versus-setting-stocks-help = 每名玩家開局擁有的 stock（生命）數量。
versus-setting-time-limit-help = 對戰時間限制。在 Time 模式中它決定勝者。
versus-setting-friendly-fire-help = 切換隊友之間是否可以互相造成傷害。只在組隊模式顯示。
versus-setting-stamina-help = 開始體力（HP）。設為 0 可使用傷害百分比模式。
versus-setting-knockback-help = 全局擊飛倍率。數值越高，擊飛距離越遠。
versus-setting-pause-help = 允許或禁止在對戰中暫停。
versus-setting-sd-help = 自毀懲罰。-1 扣除一個 stock；0 無懲罰。
netplay-copy-lobby-missing = 沒有可複製的大廳代碼
netplay-copy-lobby-copied = 已將大廳代碼複製到剪貼簿
netplay-direct-connect-empty = 請輸入 IP 位址
netplay-lobby-code-prompt = 輸入大廳、區域網或 STUN 邀請代碼。
netplay-lobby-code-empty = 請輸入大廳代碼
netplay-error-connecting = 連線錯誤：{$error}
matchmaking-no-controller-connected = 沒有連接控制器
battle-winner-log = 勝者：{$player}
battle-winner-message = 勝者：玩家 {$player}
battle-winner-team-log = 勝者：{$team}隊
battle-winner-team-message = 勝者：{$team}隊
battle-tie-log = 平局
battle-tie-message = 平局
battle-time-out = 時間到
battle-countdown-go = 開始
battle-infinite-score-log = 無限分數：{$score}
battle-infinite-score-message = 分數 {$score}
team-name-red = 紅
team-name-green = 綠
team-name-blue = 藍
team-name-grey = 灰
versus-start-sync-failed = 無法同步戰鬥開始

main-menu-help = 將游標移到選項上即可查看其作用。
netplay-main-help = 選擇一個連線操作。
netplay-settings-help = 調整連線行為。
netplay-advanced-help = 選擇一種連線方式。
settings-help = 選擇一個設定類別。
help-discord-help = 在瀏覽器中開啟 Antistatic Discord 社群。
help-guide-help = 在瀏覽器中開啟 Antistatic 線上指南。
help-adapter-guide-help = 開啟官方 GameCube 控制器轉接器的 Dolphin 設定說明。
Adapter-Guide = 轉接器指南
Open-Dolphin-Guide = 開啟 Dolphin 指南
Native-Adapter-Help = 轉接器說明
NATIVE-ADAPTER-HELP = 轉接器說明
native-adapter-help-summary = Antistatic 直接使用 libusb，因此與 Dolphin 的原生轉接器支援共用相同的驅動設定。
native-adapter-help-windows = Windows：使用 Zadig 為 USB ID 057e:0337 安裝 WinUSB。
native-adapter-help-linux = Linux：加入一條 udev 規則，授予使用者對 057e:0337 的存取權。
native-adapter-help-sdl = 如果 SDL/Dolphin 先取得轉接器，請用 SDL_JOYSTICK_HIDAPI_GAMECUBE=0 啟動。
native-adapter-help-dolphin = Dolphin/Slippi：在開啟 Antistatic 原生轉接器診斷前請先關閉它們。
native-adapter-help-claim = 如果另一個應用程式占用了轉接器，請先關閉它，再重新開啟此診斷畫面。
native-adapter-help-back = 返回原生轉接器狀態。
help-credits-help = 查看製作人員、版權和第三方署名。
help-back-help = 返回主選單。
help-help = 選擇一個說明項目。
controls-help = 選擇一個控制器操作。
netplay-quick-play-help = 使用所選控制器搜尋隨機對手。
credits-help = 製作人員與署名。

credits-heading = Antistatic - 製作人員與署名
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. 保留所有權利。
credits-developer = 開發者：bluehexagons (Loren Crain)。
credits-original = 原創音效、模型、動畫、玩法、介面與引擎程式碼皆為內部製作。
credits-runtime = 開源執行階段/工具：Node.js、TypeScript、CMake、Fluent、gl-matrix、jsonc-parser、os-locale。
credits-libraries = 原生函式庫：SDL3、SDL3_image、GLEW、OpenAL Soft、FreeType、Vorbis/libvorbisfile、libusb。
credits-build = 建置/檢查工具：npm、oxlint、oxfmt，以及各平台編譯器工具鏈。
credits-fonts = 隨附字型：Noto Sans、IBM Plex Mono 和 GNU Unifont。
credits-tools = 製作工具：3D 模型使用 Blender；音訊與音樂使用 Audacity 和 LMMS。
credits-packages = bluehexagons 套件：capacitor、trace 和 antistatic-translations。
credits-thanks = 感謝這些專案的維護者與貢獻者。
credits-license = 第三方專案仍遵循各自的授權條款。

# Old UI hover/help text
main-versus-help = 在開始本地對戰前，選擇角色、CPU、隊伍、規則和舞台。
main-arcade-help = 為所有已連接玩家提供合作 CPU 戰鬥。生命有限，失敗後可重試。
main-netplay-help = 主持或加入線上遊戲、Quick Play 和 Netplay 連線設定。
main-training-help = 開啟訓練模式，包含舞台、CPU、顏色、調色板和除錯控制。
main-replays-help = 瀏覽、預覽並播放已儲存的 Replay 檔案。
main-settings-help = 調整音訊、視訊、語言、控制器轉接器和啟動模式設定。
main-controls-help = 建立控制器標籤，並編輯有標籤或共用無標籤的按鍵對應。
main-help-help = 開啟社群和外部指南連結。
main-exit-help = 結束 Antistatic。
settings-audio-help = 調整主音量、音效、介面、語音和音樂音量。
settings-video-help = 更改圖形預設、全螢幕、同步、特效和畫面幀率限制選項。
settings-native-adapter-help = 查看 GameCube 轉接器狀態和安裝說明。
settings-language-help = 切換選單語言。
settings-start-mode-help = 選擇啟動時最先開啟的模式。
settings-live-reload = 即時重新載入
settings-live-reload-help = 在本機編輯時從 Animator 重新載入角色檔案。預設為關閉。
shared-settings-help = 返回設定。
native-adapter-copy-udev-install-help = 複製 057e:0337 的標準 udev 規則安裝和重新載入命令。
native-adapter-copy-udev-line-help = 只複製 057e:0337 的標準 udev 規則行。
native-adapter-help-button-help = 開啟適用於 Dolphin/Slippi 相容轉接器安裝的 Windows 和 Linux 設定說明。
audio-master-help = 設定主輸出音量。
audio-sfx-toggle-help = 切換音效和介面聲音。
audio-sfx-help = 設定遊戲音效音量。
audio-ui-help = 設定選單和介面音量。
audio-voice-help = 設定角色語音音量。
audio-music-toggle-help = 切換音樂播放。
audio-music-help = 設定音樂音量。
video-preset-help = 套用分組的圖形預設，或在各項設定不同時顯示自訂。
video-fullscreen-toggle-help = 在視窗模式和全螢幕之間切換。
video-display-help = 選擇遊戲視窗或全螢幕模式要使用的顯示器。
video-fullscreen-resolution-help = 選擇獨佔全螢幕模式的解析度。Auto 使用桌面全螢幕。
video-windowed-resolution-help = 選擇視窗模式和從全螢幕還原時使用的視窗大小。
video-render-scale-help = 在保持 UI 原生大小的同時，以低於或高於視窗解析度渲染 3D 圖形。
video-vsync-help = 選擇交換時序。Adaptive 在驅動支援時使用低延遲的 tear-if-late 同步。
video-shadow-quality-help = 選擇陰影品質或停用陰影。
video-ssao-help = 選擇環境光遮蔽品質。
video-antialias-help = 切換 FXAA 抗鋸齒。
video-bloom-help = 在最亮的高光周圍加入柔和的光暈。在高階 GPU 上效果最佳。
video-reflections-help = 使用螢幕空間反射在光滑表面上映出場景。效能開銷較大，在高階 GPU 上效果最佳。
video-godrays-help = 讓陽光在場景中投射出體積光束。效能開銷較大，在高階 GPU 上效果最佳。
video-perf-overlay-help = 顯示或隱藏效能疊加層。
video-point-lights-help = 選擇額外點光源品質。
video-particle-quality-help = 選擇粒子效果密度。
video-max-fps-help = 設定可選的幀率上限。
video-apply-help = 套用已變更的視訊設定。
replays-enabled-help = 在記憶體中記錄符合條件的 Versus 和 Quick Play 對戰。記憶體受限的系統請關閉此項。
replays-auto-save-help = 在結果畫面自動儲存 Replay，而不是等待手動儲存按鍵。
replays-compression-help = 儲存時壓縮 Replay 檔案。僅在壓縮會拖慢儲存時關閉。
netplay-copy-lobby-help = 如果可用，複製目前的大廳代碼。
netplay-virtual-couch-help = 開啟大廳託管、大廳代碼加入和進階邀請選項。
netplay-settings-menu-help = 配置 rollback、輸入緩衝和 LAN 位址行為。
netplay-back-help = 在不中斷現有會話的情況下返回主選單。
arcade-cpu-level-help = 對手 CPU 難度等級（0 最簡單，6 最難）。
arcade-stocks-help = 每場對戰的生命數。
arcade-retries-help = 失敗前的重試次數。
arcade-battles-help = 本次流程的總對戰數。
arcade-start-help = 當所有已加入玩家都準備好後開始流程。
controls-remap-page-help = 重新綁定選單導覽、主控台、全螢幕和訓練模式按鍵。
controls-remap-reset-binding-help = 將 {$action} 重設為預設綁定。
controls-remap-reset-all-help = 將所有鍵盤快速鍵還原為內建預設值。
replay-browser-help = Replay 瀏覽器。
replay-offline-only-help = Replay 只可離線使用，因為它們從本機檔案系統載入。
replay-refresh-help = 重新掃描 {$dir} 中儲存的 Replay 檔案。
replay-entry-help = {$players} 在 {$stage}；{$duration}（{$truncated}）；{$result}；{$version}；{$compression}。
replay-unreadable-help = 無法讀取 Replay：{$error}
replay-actions-watch-help = 從頭播放已儲存的 Replay。Replay 播放期間可使用 Jump In。
replay-actions-back-help = 返回 Replay 清單。
replay-load-help = 從 Replay 目錄載入已儲存的 Replay 檔案。
replay-prev-help = 顯示較新的 Replay。
replay-next-help = 顯示較舊的 Replay。
replay-settings-help = Replay 錄製、自動儲存和壓縮選項。
audio-help = 調整音訊設定。
video-help = 調整視訊設定。
replays-help = Replay 預設為啟用，並限制為每場對戰 16 分鐘。
native-adapter-help-text = Native Adapter 提供 4 埠直接輪詢。PC 模式更簡單，但使用 SDL 控制器對應。
shortcut-menu-up-help = 在選單中向上移動選取。
shortcut-menu-down-help = 在選單中向下移動選取。
shortcut-menu-left-help = 向左移動選取或減少數值。
shortcut-menu-right-help = 向右移動選取或增加數值。
shortcut-menu-confirm-help = 啟動目前焦點項目。
shortcut-menu-next-help = 移到下一個可聚焦項目。按住 Shift 可返回。
shortcut-menu-page-up-help = 向上跳過多個項目。
shortcut-menu-page-down-help = 向下跳過多個項目。
shortcut-menu-home-help = 聚焦清單中的第一項。
shortcut-menu-end-help = 聚焦清單中的最後一項。
shortcut-console-help = 開啟遊戲內除錯主控台。
shortcut-chat-help = 開啟聊天輸入框（say 指令）。
shortcut-fullscreen-help = 切換全螢幕。Alt+Enter 也可用。
shortcut-frame-step-help = 凍結時前進一幀。需要除錯模式。
shortcut-freeze-help = 暫停或恢復 TAS。需要除錯模式。
shortcut-save-state-help = 在訓練模式中儲存目前狀態快照。
shortcut-restore-state-help = 還原上一個訓練模式快照。

Start = 開始
Color = 顏色
Leave = 離開
Not-Joined = 未加入
Hold-Start = 按住開始
arcade-join-help = 加入這次街機流程。
arcade-color-help = 隨機更換這位玩家的顏色。
arcade-palette-help = 選擇這位玩家的配色。
arcade-leave-help = 離開這次街機流程。
arcade-setting-cpu-level = CPU 等級
arcade-setting-stocks = 命數
arcade-setting-starting-stocks = 初始命數
arcade-setting-retries = 重試次數
arcade-setting-battles = 戰鬥數
arcade-setting-value = {$label}: {$value}
arcade-palette = 配色 {$number}
arcade-select-title = 街機
arcade-select-infinite-title = 無限戰鬥
arcade-select-instructions = 確認加入 · 為每位玩家選擇角色與配色 · 返回離開
arcade-between-cleared-battle = 已完成戰鬥 {$current} / {$total}
arcade-between-next = 確認：下一場
arcade-between-retries-remaining =
    落敗 — { $count ->
       *[other] 剩餘 {$count} 次重試
    }
arcade-between-retry-actions = 確認：重試 · 返回：放棄
arcade-between-results = 確認：結果
arcade-between-complete = 街機完成！
arcade-results-infinite-title = 無限戰鬥
arcade-results-infinite-subtitle = {$time} 內得分 {$score}
arcade-results-cleared-title = 街機通關
arcade-results-cleared-subtitle = 完成全部 {$battles} 場戰鬥。
arcade-results-abandoned-title = 已放棄流程
arcade-results-abandoned-subtitle = 在第 {$current} / {$total} 場戰鬥後放棄。
arcade-results-gameover-title = 遊戲結束
arcade-results-gameover-subtitle = 達到第 {$current} / {$total} 場戰鬥。
replay-battle-controls = 回放：儲存鍵加入標記 · Start 暫停 · 十字鍵導覽 · 抓取鍵變速 · 按住確認/攻擊快進 · 返回退出
replay-battle-status = {$current} / {$total} · {$speed}x
replay-marker-default = 標記 {$number}
replay-marker-added = 已於 {$time} 加入 {$label}
replay-marker-selected = {$label} · {$time}
replay-marker-none = 沒有回放標記
replay-marker-save-unavailable = 無法儲存回放標記
replay-speed-changed = 播放速度：{$speed}x
replay-export-button = 匯出回放套件
replay-export-help = 建立包含此回放及其標記的本機套件。不會上載任何內容。
replay-exporting = 正在匯出回放套件...
replay-exported = 已匯出 {$name}
replay-export-failed = 匯出失敗：{$error}
results-controller-port = 控制器 P{$port}
results-controller-id = 控制器 {$id}
results-disconnected-slot = 已斷線槽位
results-remote-player = 遠端玩家
results-replay-capture = 回放記錄
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = 槽位 {$index}: {$name}
results-row-kos = KOs
results-row-falls = 墜落
results-row-sds = 自滅
results-row-damage-given = 造成傷害
results-row-damage-taken = 承受傷害
results-row-blocked = 格擋
results-row-parries = 招架
results-row-power-shields = 完美護盾
results-row-lag-cancels = 硬直取消
results-row-kb-given = 造成擊退
results-row-kb-taken = 承受擊退
results-row-kb-absorbed = 吸收擊退
results-row-ledge-grabs = 抓邊次數
results-row-ledge-time = 掛邊時間
results-row-crouch-cancels = 蹲下取消
results-row-velocity-cancels = 速度取消
controls-action-ui-save-replay = 儲存回放
controls-device-unknown = 未知
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = 鍵盤快捷鍵
shortcut-unbound = （未綁定）
shortcut-category-menu = 選單導航
shortcut-category-general = 一般
shortcut-category-debug = 除錯 (TAS)
shortcut-category-training = 訓練模式
shortcut-label-menu-up = 上移
shortcut-label-menu-down = 下移
shortcut-label-menu-left = 左移
shortcut-label-menu-right = 右移
shortcut-label-menu-confirm = 確認
shortcut-label-menu-next = 下一個欄位
shortcut-label-menu-page-up = 上一頁
shortcut-label-menu-page-down = 下一頁
shortcut-label-menu-home = 第一個項目
shortcut-label-menu-end = 最後一個項目
shortcut-label-console = 開啟主控台
shortcut-label-chat = 聊天
shortcut-label-fullscreen = 切換全螢幕
shortcut-label-frame-step = 逐幀前進 (TAS)
shortcut-label-freeze = 凍結 (TAS)
shortcut-label-save-state = 儲存狀態
shortcut-label-restore-state = 還原狀態
shortcut-bind = 綁定
shortcut-add = 新增
shortcut-replace = 取代
shortcut-remove-key = 移除 {$key}
shortcut-capture-bind-title = 綁定按鍵：{$action}
shortcut-capture-replace-title = 取代按鍵：{$action}
shortcut-capture-hint = 按下要綁定的按鍵，或按 Esc 取消。
shortcut-conflict-detail = {$key} 已綁定到 {$action}。要重新指派嗎？
shortcut-conflict-hint = 按 Enter 重新指派，按 Esc 取消。
shortcut-min-binding = {$action} 至少要保留一個綁定。
shortcut-overlap-menu = 選單導航衝突：{$keys} 也會用於選單導航。選單中控制器綁定優先。
shortcut-overlap-actions = 快捷鍵衝突：{$overlaps}。遊戲進行時控制器綁定優先。
shortcut-reset-all = 將所有快捷鍵重設為預設值
character-select-help = 選擇一個角色。

matchmaking-service-fallback-stun = 備用 STUN
matchmaking-status-preparing-binding = 正在準備 Quick Play... 正在開啟 netplay socket。
matchmaking-status-preparing-primary-stun = 正在準備 Quick Play... 正在透過 {$service} 檢查你的公開 UDP 路徑。
matchmaking-status-preparing-fallback-stun = 正在準備 Quick Play... 主要 STUN 失敗，正在透過 {$service} 重試。
matchmaking-status-preparing-queueing = 正在準備 Quick Play... 正在加入佇列。
matchmaking-status-connecting-tunneling = 已找到對手。正在開啟點對點路徑...
matchmaking-status-connecting-peer = 點對點路徑已開啟。正在完成連線握手...
matchmaking-status-waiting-peer = 路徑已開啟。正在等待另一位玩家...
matchmaking-status-starting-battle = 連線已就緒。正在開始對戰...
netplay-experimental-note = 實驗性功能 — 可能不穩定
netplay-detail-connecting-peer = 點對點路徑已開啟。正在完成連線握手...
netplay-detail-waiting-for-peer = 路徑已開啟。正在等待另一位玩家完成連線...
netplay-detail-starting-battle = 連線已就緒。正在開始對戰...
netplay-detail-matchmaking-binding = 正在準備 Quick Play。正在開啟 netplay socket...
netplay-detail-matchmaking-primary-stun = 正在透過 {$service} 檢查你的公開 UDP 路徑...
netplay-detail-matchmaking-fallback-stun = 主要 STUN 沒有回應。正在嘗試 {$service}...
netplay-detail-matchmaking-queueing = 正在加入配對佇列...
netplay-detail-matchmaking-wait = 已排隊 {$wait} 秒。等待中的玩家：{$players}。
replay-stage-fallback = 場地 {$number}
replay-unknown-error = 未知錯誤
replay-title = 回放
replays-title = 回放
replay-watch-button = 觀看回放
replay-settings-button = 回放設定
replay-refresh-button = 重新整理清單
replay-refreshing = 正在重新整理...
replay-prev-button = 上一頁
replay-prev-disabled = 上一頁 -
replay-next-button = 下一頁
replay-next-disabled = 下一頁 -
replay-browser-scanning = 正在掃描回放目錄...
replay-browser-scan-failed = 回放掃描失敗。
replay-browser-empty = 找到 0 個回放。
replay-browser-page = {$first}-{$last} / {$count} 個回放 · 第 {$page}/{$pages} 頁
replay-browser-loading = 正在載入回放...
replay-browser-scanning-files = 正在掃描已儲存的回放檔案。
replay-browser-scan-failed-detail = 回放掃描失敗：{$error}
replay-browser-empty-slot = 此槽位沒有回放。
replay-browser-empty-list = 找不到已儲存的回放。
replay-browser-root-help = 回放檔案會從本機回放目錄中遞迴載入。
replay-title-unreadable = 無法讀取：{$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = 無結果
replay-result-none-winner = 勝者：無
replay-result-quit = 提前退出
replay-result-tie = 平手
replay-result-winner = 勝者：{$winner}
replay-action-participants = 參與者：{$players}
replay-action-duration = 時長：{$duration}
replay-action-duration-truncated = 時長：{$duration}（已截斷）
replay-action-result = 結果：{$result}
replay-action-stage = 場地：{$stage}
replay-action-mode = 模式：{$mode}
replay-action-version = 版本：{$version}
replay-action-file = 檔案：{$compression}；已截斷：{$truncated}
replay-compression-compressed = 已壓縮
replay-compression-uncompressed = 未壓縮
replay-truncated-yes = 是
replay-truncated-no = 否

# 社交功能和對戰 CPU 清單
press-any-button-or-key = 按任意按鈕或按鍵
social-title = 好友和邀請
social-steam = Steam
social-steam-help = 在 Steam 顯示你的房間，讓好友能從好友清單加入。
social-discord = Discord
social-discord-help = 在 Discord 顯示你的房間，讓好友可以要求加入。
social-info = 預設為關閉。啟用後，整合功能會載入平台 SDK 並分享你的房間加入碼，讓好友可以加入。連線仍使用 Antistatic 自家的網路對戰。
social-summary = Steam 和 Discord 的豐富狀態及邀請。
social-settings-help = Steam 和 Discord 的豐富狀態及邀請。預設為關閉。
versus-add-cpu = 新增 CPU
versus-cpu-page-prev = 上一頁
versus-cpu-page-next = 下一頁
versus-cpu-page-help = 變更顯示的 CPU 頁面。
versus-no-cpus-added = 尚未新增 CPU
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# 控制器校準
controller-calibration-title = 控制器校準
controller-calibration-open = 校準控制器
controller-calibration-open-help = 檢查並校準所選本機控制器。
controller-calibration-online-blocked = 線上遊戲期間無法校準控制器。
controller-calibration-no-local-controller = 請連接並選擇要校準的本機控制器。
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = 無標籤
controller-calibration-capability-no-axes = 此控制器未回報可校準軸。
controller-calibration-capability-native-origin = 原生原點資料支援自動校準。
controller-calibration-capability-absolute-no-automatic = 有絕對值資料；無法自動校準。
controller-calibration-capability-sdl-normalized = SDL 正規化輸入；僅支援手動校準。
controller-calibration-suspicious-origin-warning = 已忽略一個或多個自動原點軸。請查看下方的後備詳情。
controller-calibration-invalid-saved-warning = 已忽略儲存的校準：{$reason}
controller-calibration-invalid-shaping-warning = 已忽略儲存的搖桿設定：{$reason}
controller-calibration-status-policy-preview = 策略預覽
controller-calibration-status-manual-preview = 手動預覽
controller-calibration-status-modified = 已修改
controller-calibration-status-current = 目前
controller-calibration-status-policy = 策略
controller-calibration-status-manual = 手動
controller-calibration-status-not-saved = 未儲存
controller-calibration-status-saved = 已儲存
controller-calibration-status-active-differs = 目前設定與已儲存設定不同
controller-calibration-draft-status = {$intent} · 草稿{$draft} · 目前{$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = 自動校準：{$state}
controller-calibration-automatic-unavailable = 無法使用
controller-calibration-automatic-on = 開
controller-calibration-automatic-off = 關
controller-calibration-automatic-policy-native-help = 切換 GameCube 原點自動校準。
controller-calibration-automatic-policy-unavailable-help = 此輸入來源不支援自動校準。
controller-calibration-axis-left-x = 左搖桿 X
controller-calibration-axis-left-y = 左搖桿 Y
controller-calibration-axis-right-x = 右搖桿 X
controller-calibration-axis-right-y = 右搖桿 Y
controller-calibration-axis-left-trigger = 左扳機
controller-calibration-axis-right-trigger = 右扳機
controller-calibration-field-minimum = 最小值
controller-calibration-field-center = 中心
controller-calibration-field-maximum = 最大值
controller-calibration-field-released = 放開
controller-calibration-field-pressed = 按下
controller-calibration-value-na = 不適用
controller-calibration-unit-gamecube-directed = GameCube 有向位元組
controller-calibration-unit-sdl-normalized = SDL 正規化
controller-calibration-unit-canonical-normalized = 正規化
controller-calibration-unit-gamecube-protocol-byte = GameCube 協定位元組
controller-calibration-axis-values-normalized = {$axis} · {$unit} · 輸入 {$source} · 修正 {$corrected} · 預覽 {$preview} · 遊戲 {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} 絕對值 {$absolute}，原點 {$origin} · {$sourceUnit} 輸入 {$source} · {$normalizedUnit} 修正 {$corrected}，預覽 {$preview}，遊戲 {$gameplay}
controller-calibration-axis-statistics = {$samples} 個樣本 · 最小 {$minimum} · 最大 {$maximum} · 峰值 {$peak} · 抖動 {$jitter} · {$unit}
controller-calibration-reported-buttons = 已按下：{$buttons}
controller-calibration-reported-buttons-none = 無
controller-calibration-capture-status-ready = 就緒
controller-calibration-capture-status-waiting-release = 請放開所有控制
controller-calibration-capture-status-capturing = 正在擷取
controller-calibration-capture-status-captured = 已擷取
controller-calibration-capture-status-invalid = 擷取無效
controller-calibration-capture-neutral = 擷取中立位置
controller-calibration-capture-range = 擷取完整範圍
controller-calibration-capture-help = 提示時放開所有控制，然後執行擷取動作。
controller-calibration-stick-movement = 移動搖桿
controller-calibration-stick-right = 右搖桿 / C 搖桿
controller-calibration-shaping-deadzone = 死區
controller-calibration-shaping-cardinal-snap = 四向吸附
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting}：{$value}{$unit} · {$step}
controller-calibration-shaping-help = 左右或列兩側調整 · 確認或列中央切換微調/粗調。
controller-calibration-adjust-value = {$axis} {$field}：{$value} {$unit} · {$step}
controller-calibration-step-fine = 微調
controller-calibration-step-coarse = 粗調
controller-calibration-adjust-help = 左右或列兩側調整 · 確認或列中央切換微調/粗調。實體單位依輸入來源而異。
controller-calibration-apply-current-connection = 套用到目前連線
controller-calibration-save-to-tag = 儲存到控制器標籤
controller-calibration-save-to-tag-target = 儲存到 {$tag}（{$layout}）
controller-calibration-save-to-tag-no-tag = 儲存到標籤（需要標籤）
controller-calibration-reset-draft-active = 將草稿重設為目前值
controller-calibration-reset-draft-saved = 將草稿重設為儲存值
controller-calibration-reset-draft-layout-defaults = 將草稿重設為配置預設值
controller-calibration-reset-session = 重設連線工作階段
controller-calibration-delete-saved = 刪除儲存的校準
controller-calibration-delete-saved-confirm = 確認：刪除儲存的校準
controller-calibration-copy-diagnostic = 複製診斷資料
controller-calibration-action-help = 確認以執行此操作。
controller-calibration-applied = 校準已套用到目前連線。
controller-calibration-save-tag-required = 儲存校準需要有效的控制器標籤。
controller-calibration-saved = 校準已儲存到 {$tag}（{$layout}）。
controller-calibration-no-saved-calibration = 此控制器沒有儲存的校準。
controller-calibration-delete-saved-complete = 已刪除儲存的校準。
controller-calibration-copy-diagnostic-complete = 已複製校準診斷資料。
controller-calibration-local-controllers = 其他本機控制器
controller-calibration-switch-controller = 切換控制器
controller-calibration-switch-controller-name = 切換到 {$controller}
controller-calibration-switch-decision = {$controller} · 左：套用 · 右：{$save} · 確認：捨棄
controller-calibration-switch-save-available = 儲存
controller-calibration-switch-save-unavailable = 無法儲存
controller-calibration-switch-decision-help = 未儲存：左套用，右儲存，確認則捨棄並切換。
controller-calibration-back = 返回
controller-calibration-back-help = 返回控制選單。進行中的擷取會先取消。
controller-calibration-back-discard-confirm = 確認：捨棄草稿並返回
controller-calibration-disconnected-draft-discarded = 控制器已斷線；校準草稿已捨棄。

# PhobGCC
controller-calibration-phob-board-unconfirmed = 董事會未經確認
controller-calibration-phob-board-v1 = 選擇PhobGCC v1
controller-calibration-phob-board-v1-value = PhobGCC v1
controller-calibration-phob-board-v2 = 選擇PhobGCC v2
controller-calibration-phob-board-v2-value = PhobGCC v2
controller-calibration-phob-calibrate-c-stick = 校準 C-stick：A+X+Y+R
controller-calibration-phob-calibrate-left = 校準主桿：A+X+Y+L
controller-calibration-phob-calibration-complete = 完成（僅限鍵盤/滑鼠）
controller-calibration-phob-calibration-confirm = 確認：開始韌體校準
controller-calibration-phob-calibration-help = 啟動必須在控制器上完成的韌體工作流程。
controller-calibration-phob-calibration-no-cancel = 控制器輸入無法取消或完成此流程。完成韌體步驟後，用鍵盤/滑鼠選擇「完成」。若卡住，請拔下並重新插入控制器。
controller-calibration-phob-calibration-phases = 按另一搖桿的提示完成所有中心、邊緣及槽口步驟。兩個韌體階段都結束後再選擇「完成」。
controller-calibration-phob-enter-configure = 輸入Configure Mode
controller-calibration-phob-enter-configure-instruction = 在實體控制器上，按住 A+X+Y+Start 直到兩個搖桿都報告位於右上角，然後放開。
controller-calibration-phob-exit-safe-instruction = 在實體控制器上按“A+X+Y+Start”。在右上角較長的響應後釋放。
controller-calibration-phob-host-correction-stale = 韌體校準後的 Antistatic 校正：目前使用 {$active}；已儲存 {$saved}。請檢查預設值或重新擷取。
controller-calibration-phob-instruction-none = 沒有待處理的命令
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = 模式未知
controller-calibration-phob-open = 開啟PhobGCC指南
controller-calibration-phob-open-guide-031 = 開啟官方韌體0.31指南
controller-calibration-phob-open-help = 針對使用者確認的 PhobGCC v1 或 v2 進行引導式唯讀檢查。
controller-calibration-phob-open-phobvision-029-v2 = 開啟PhobVision 0.29指南（僅配備v2）
controller-calibration-phob-open-release-031 = 開放韌體 0.31 發行說明
controller-calibration-phob-open-version-guide = 開啟報告韌體指南
controller-calibration-phob-origin-checks = 韌體校準前，如有需要請用實體 B 啟動搖桿，並檢查適配器回報的原點。
controller-calibration-phob-query-c-settings = 讀取C-stick設定：R+Start
controller-calibration-phob-query-main-settings = 讀取主搖桿設定：L+Start
controller-calibration-phob-query-trigger-settings = 讀取觸發設定：L+R+Z
controller-calibration-phob-query-version = 讀取韌體版本：A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = 原始診斷已啟用。這些值是一般控制器報告經韌體處理後的顯示座標，不是直接感測器資料或遊戲輸出。
controller-calibration-phob-raw-disable = 停用原始輸出：L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = 在實體控制器上，按 L+R+D-pad Down，等待右上角回應，然後釋放所有內容。
controller-calibration-phob-raw-enable = 啟用原始輸出：L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = 在實體控制器上，按 L+R+D-pad Up，等待右上角回應，然後釋放所有內容。
controller-calibration-phob-raw-values = 韌體處理後主搖桿 X {$leftX}，Y {$leftY}；C-stick X {$cX}，Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = 原始值不可用
controller-calibration-phob-remap-warning = 指令一律使用外殼標示的實體按鈕，不受韌體重新映射影響。Antistatic 看到的是回報按鈕，兩者可能不同。
controller-calibration-phob-result-matched = 匹配的 Phob 式響應
controller-calibration-phob-result-none = 尚未回覆
controller-calibration-phob-result-unknown-custom = 未知或自訂回應
controller-calibration-phob-result-version-known = 韌體 {$version}
controller-calibration-phob-result-version-no-response = 韌體無響應；版本未知
controller-calibration-phob-return-safe = 返回Safe Mode
controller-calibration-phob-safe-recovery = 要確保進入 Safe Mode，請拔下再插回控制器。之後重新開啟本指南；斷線會重設偵測狀態。
controller-calibration-phob-setting-c-response-x-raw = C-stick X 回應位元組
controller-calibration-phob-setting-c-response-y-raw = C-stick Y 回應字節
controller-calibration-phob-setting-c-snapback-x = C-stick 彈回 X
controller-calibration-phob-setting-c-snapback-y = C-stick 回彈 Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick 波形整形 X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick 波形 X 原始
controller-calibration-phob-setting-c-waveshaping-y = C-stick 波形 Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick 波形 Y 原始
controller-calibration-phob-setting-main-smoothing-x = 主桿平滑 X
controller-calibration-phob-setting-main-smoothing-y = 主桿平滑Y
controller-calibration-phob-setting-main-snapback-x = 主桿彈回 X
controller-calibration-phob-setting-main-snapback-y = 主桿回彈 Y
controller-calibration-phob-setting-main-waveshaping-x = 主棒波形整形 X
controller-calibration-phob-setting-main-waveshaping-x-raw = 主棒波形整形 X raw
controller-calibration-phob-setting-main-waveshaping-y = 主桿波形整形Y
controller-calibration-phob-setting-main-waveshaping-y-raw = 主棒波形整形 Y raw
controller-calibration-phob-setting-row = {$setting}：{$value} {$unit}
controller-calibration-phob-setting-rows-none = 沒有解碼設定
controller-calibration-phob-settings-c-stick-instruction = 在實體控制器上，按住 R+Start 兩秒鐘讀出，然後放開。
controller-calibration-phob-settings-main-instruction = 在實體控制器上，按住 L+Start 兩秒鐘讀出，然後放開。
controller-calibration-phob-settings-read-only = 這些讀數不會更改韌體設定。使用官方說明進行更改和重置。
controller-calibration-phob-settings-triggers-instruction = 在實體控制器上，按住 L+R+Z 兩秒鐘讀出，然後放開。
controller-calibration-phob-setting-trigger-left-mode = 左觸發模式
controller-calibration-phob-setting-trigger-left-value = 左觸發值
controller-calibration-phob-setting-trigger-right-mode = 右邊觸發模式
controller-calibration-phob-setting-trigger-right-value = 右觸發值
controller-calibration-phob-setup-active = Phob Setup Mode 已啟用：用回報的十字鍵移動，用回報的 A 確認。
controller-calibration-phob-setup-enter = 輸入Phob Setup Mode
controller-calibration-phob-setup-exit = 退出 Phob Setup Mode
controller-calibration-phob-setup-exit-chord = 離開時，只按住回報的十字鍵 下+左 + 主搖桿右上 + C-stick右下一秒，然後放開。韌體校準期間停用。
controller-calibration-phob-stale-state-current = 目前的
controller-calibration-phob-stale-state-stale = 陳舊
controller-calibration-phob-status = 開發板：{$board} · 模式：{$mode} · 結果：{$result} · 步驟：{$instruction} · {$raw} · 設定：{$rows}
controller-calibration-phob-unit-protocol-byte = 協定位元組
controller-calibration-phob-unit-setting-value = 設定值
controller-calibration-phob-unit-trigger-byte = 觸發位元組
controller-calibration-phob-unofficial-warning = 此 PhobGCC 助手並非官方且無隸屬關係。請確認主機板及韌體；Antistatic 不會辨識硬體或寫入設定。
controller-calibration-phob-version-instruction = 在 Configure Mode 中，按下實體 A+Z+D-pad Up，按住讀數兩秒鐘，然後放開。
controller-calibration-mode-basic = 檢視：基本
controller-calibration-mode-advanced = 檢視：進階
controller-calibration-mode-toggle-help = 在常用設定和詳細校準診斷之間切換。
controller-calibration-origin-diagnostic-unavailable = 此輸入來源不支援自動原點診斷。
controller-calibration-origin-diagnostic = 穩定原點：{$phase} · {$reports} 份報告 · {$stable}/6 已套用 · {$fallback}/6 後備 · {$dropped} 次溢出
controller-calibration-origin-phase-collecting = 擷取中
controller-calibration-origin-phase-complete = 已完成
controller-calibration-use-suggested-deadzones = 使用建議死區
controller-calibration-use-suggested-deadzones-help = 將量度的內外死區建議套用到草稿。
controller-calibration-section-stick-shaping = 搖桿調整
controller-calibration-section-trigger-shaping = 扳機調整
controller-calibration-section-action-diagnostics = 動作診斷
controller-calibration-section-physical-diagnostics = 實體軸診斷
controller-calibration-section-hardware-correction = 硬件校正
controller-calibration-shaping-inner-deadzone = 內死區
controller-calibration-shaping-outer-deadzone = 外死區
controller-calibration-snap-override-help = 切換玩家覆寫。規則模式的最小值仍會生效。
controller-calibration-snap-override-state = {$stick} 吸附：{$state} · 最小 {$floor}° · 實際 {$effective}°
controller-calibration-override-enabled = 已啟用
controller-calibration-override-disabled = 已停用
controller-calibration-trigger-shaping-help = 左右或列兩側調整 · 確認或列中央切換微調/粗調。
controller-calibration-trigger-inner-deadzone = 內死區
controller-calibration-trigger-outer-deadzone = 外死區
controller-calibration-trigger-response-curve = 響應曲線
controller-calibration-trigger-hard-press-threshold = 強按門檻
controller-calibration-trigger-shaping-value = {$trigger} {$setting}：{$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = 量度：移動雜訊 {$movementNoise}、內 {$movementInner}、外 {$movementOuter}、覆蓋 {$movementCoverage}/16 · 右搖桿雜訊 {$rightNoise}、內 {$rightInner}、外 {$rightOuter}、覆蓋 {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = 扳機：L 雜訊 {$leftNoise}、內 {$leftInner}、外 {$leftOuter} · R 雜訊 {$rightNoise}、內 {$rightInner}、外 {$rightOuter}
controller-calibration-stick-diagnostic = {$stick}：映射 {$mapped} · 遊戲 {$gameplay} · {$zone} · 吸附 {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger}：映射 {$mapped} · 遊戲 {$gameplay} · {$zone} · 強按 {$hard}
controller-calibration-zone-inner-dead = 內死區
controller-calibration-zone-linear = 有效範圍
controller-calibration-zone-outer-saturated = 外部飽和
controller-calibration-state-yes = 是
controller-calibration-state-no = 否
controller-calibration-hard-source-none = 無
controller-calibration-hard-source-digital-button = 數碼點擊
controller-calibration-hard-source-analog-threshold = 模擬門檻
controller-calibration-help = 上下移動 · 左右或列兩側調整 · 確認或列中央更改精度 · 返回上一層。
controller-calibration-tag-required-prerequisite = 校準前請在控制選單中新增玩家標籤以啟用儲存。仍可套用到目前連線。
controller-calibration-status-draft-or-active-differs = 草稿或目前設定與已儲存設定不同
controller-calibration-capture-mode-neutral = 中立位置
controller-calibration-capture-mode-range = 完整範圍
controller-calibration-capture-accept-pending = 接受{$mode}擷取
controller-calibration-capture-accept-and-start = 接受{$pending}，然後擷取{$next}
controller-calibration-capture-status-pending = {$mode}擷取等待審核
controller-calibration-legend-source = 配置預設值
controller-calibration-legend-corrected = 修正
controller-calibration-legend-preview = 預覽
controller-calibration-legend-gameplay = 遊戲
controller-calibration-origin-fallback-detail = 後備：{$axes}
controller-calibration-origin-fallback-axis = {$axis}：{$reason}
controller-calibration-origin-reason-insufficient-reports = 有效報告不足；請放開控制並重新連線
controller-calibration-origin-reason-unstable = 輸入曾移動；請放開控制並重新連線
controller-calibration-origin-reason-implausible = 原點超出預期範圍；請放開控制並重新連線
controller-calibration-origin-reason-unsafe-bounds = 原點會令修正不安全；請擷取中立位置和完整範圍
controller-calibration-phob-setup-suspended-raw = 原始診斷啟用時，Phob Setup Mode 會暫停。請停用原始輸出以繼續。
controller-calibration-phob-result-version-custom = 自訂韌體回應：X {$x}，Y {$y}
controller-calibration-phob-result-unknown = 無法辨識的回應
controller-calibration-phob-raw-mode-off = 原始模式關閉

# 私隱、報告及意見
privacy-title = 私隱
privacy-settings-help = 管理網絡、當機報告、匿名數據及意見。
privacy-networking = 網絡功能
privacy-networking-help = 網上遊戲及所有 Antistatic 服務的總開關。關閉後會中斷目前的網上連線。
privacy-crash-reporting = 當機報告：{$value}
privacy-crash-reporting-help = 選擇 Antistatic 是否在傳送匿名當機診斷前詢問。
privacy-crash-ask = 每次詢問
privacy-crash-never = 永不傳送
privacy-crash-always = 總是傳送
privacy-gameplay-metrics = 匿名對戰數據
privacy-gameplay-metrics-help = 自願傳送模式、角色、對戰時間及結果等概略數據。
privacy-performance-metrics = 匿名效能數據
privacy-performance-metrics-help = 自願傳送概略硬件及幀時間數據，以協助改善效能。
privacy-feedback-open = 傳送意見
privacy-feedback-open-help = 向 Antistatic 團隊傳送錯誤報告或其他意見。
privacy-policy-open = 查看私隱政策
privacy-policy-open-help = 閱讀 Antistatic 的官方私隱政策。
privacy-policy-title = 私隱政策
privacy-policy-help = 本政策說明 Antistatic 如何處理網絡功能、當機報告、可選數據及意見。
privacy-crash-send-pending = 傳送待處理當機報告
privacy-crash-send-pending-help = 傳送正在等候你同意的當機報告。
privacy-crash-discard-pending = 刪除待處理當機報告
privacy-crash-discard-pending-help = 永久刪除當機報告，不作傳送。
privacy-summary = 網絡功能預設開啟。當機報告由你選擇是否傳送；匿名數據在你同意前保持關閉。
privacy-netplay-disabled = 網上對戰已關閉
privacy-netplay-disabled-help = 請在私隱設定中開啟網絡功能，以使用網上對戰。
privacy-crash-prompt-title = 當機報告
privacy-crash-prompt-body = Antistatic 發現一份待處理當機報告。是否傳送匿名診斷資料，以協助改善穩定性？
privacy-crash-prompt-send = 傳送報告
privacy-crash-prompt-later = 稍後詢問
privacy-crash-prompt-never = 不傳送當機報告
privacy-crash-prompt-summary = 選擇傳送此報告、稍後決定或關閉當機報告。
privacy-report-sending = 正在傳送...
privacy-report-failed = 無法傳送。請檢查網絡後再試。
privacy-crash-sent = 當機報告已傳送
privacy-crash-discarded = 當機報告已刪除
privacy-feedback-title = 意見
privacy-feedback-category = 類別：{$value}
privacy-feedback-category-help = 選擇要傳送的訊息類別。
privacy-feedback-category-bug = 錯誤
privacy-feedback-category-feedback = 意見
privacy-feedback-category-other = 其他
privacy-feedback-subject = 主旨
privacy-feedback-subject-help = 輸入簡短摘要。
privacy-feedback-subject-placeholder = 簡短摘要
privacy-feedback-body = 訊息
privacy-feedback-body-help = 描述問題或建議。請勿填寫個人資料。
privacy-feedback-body-placeholder = 你想告訴我們甚麼？
privacy-feedback-submit = 傳送意見
privacy-feedback-submit-help = 將此訊息傳送給 Antistatic 團隊。
privacy-feedback-warning = 請勿填寫個人資料、密碼或私人帳戶資料。
privacy-feedback-help = 填寫主旨及訊息，然後傳送意見。
privacy-feedback-required = 請填寫主旨及訊息。
privacy-feedback-sent = 意見已傳送。報告 ID：{$id}
