hello-world = 你好，世界！ { TRANSLATE("ANTISTATIC") }

# Nouns
ANTISTATIC = ANTISTATIC
Antistatic = Antistatic

Silicon = 硅
Iron = 铁
Xenon = 氙
Helium = 氦
Carbon = 碳
Rhodium = 铑

Sandbag = 沙袋

Ruins = 废墟
Transistor = 晶体管
Eroded = 腐蚀的
Scales = 秤
Crossing = 路口
Longboat = 长艇
Boombox = 手提音响
Fountain = 喷泉
Great-White = 大白鲨
Plane = 平面
Satellite = 卫星
Divided = 分为
Pillars = 支柱
Debug = 除错

mode-Antistatic = {Antistatic}
mode-19XX = 19XX
mode-Vanilla = 原版
Physics = 物理
color-preset-random = 随机
color-preset-red = 红色
color-preset-orange = 橙色
color-preset-gold = 金色
color-preset-green = 绿色
color-preset-blue = 蓝色
color-preset-purple = 紫色
color-preset-pink = 粉色
color-preset-white = 白色
versus-color-preset-help = 选择一个颜色系列；每次选择都会获得轻微的随机变化。队伍模式下不可用。

# Navigation
Back = 返回
Exit = 退出
Save = 保存
Cancel = 取消
Close-Symbol = X

Modify = 修改
Reset = 重启

# Main Menu
Versus = 对抗模式
Training = 训练
Courses = 课程
TRAINING = 训练
COURSES = 课程
battle-results = 对战结果
Settings = 设置
Controls = 操作
Discord = Discord {"\u29C9"}
Guide = 指南 {"\u29C9"}

# Settings Menu
SETTINGS = 设置
Audio = 音讯
Video = 视频设置
accessibility-title = 辅助功能
settings-accessibility-help = 调整动态、打击效果、菜单音效和焦点可见度。
accessibility-reduced-motion = 减少动态
accessibility-reduced-motion-help = 停止菜单背景动画和打击时的视觉抖动。
accessibility-hit-flash = 打击闪光：{$value}
accessibility-hit-flash-help = 调整角色受击闪光的亮度。
accessibility-screen-shake = 打击抖动：{$value}
accessibility-screen-shake-help = 调整打击时角色和界面的视觉抖动。
accessibility-menu-sound = 增强菜单音效
accessibility-menu-sound-help = 提高导航和确认音效的音量。
accessibility-high-contrast-focus = 高对比度焦点
accessibility-high-contrast-focus-help = 为当前菜单控件添加明亮的双层轮廓。
accessibility-help = 调整辅助功能和显示偏好。
first-run-title = 欢迎来到 Antistatic
first-run-intro = 选择一个起点。你可以随时从主菜单调整控制和辅助功能。
first-run-versus = 本地对战
first-run-versus-help = 为共用此设备的玩家设置对战。
first-run-controls = 控制
first-run-controls-help = 查看、重新映射和校准输入。
first-run-training = 训练
first-run-training-help = 使用训练工具和目标自由练习。
first-run-courses = 课程
first-run-courses-help = 通过引导课程学习移动、攻击、防御和返回场地。
first-run-skip = 前往主菜单（跳过）
first-run-skip-help = 不打开任何模式，完成这次初次引导。
first-run-help = 选择从哪里开始。选择任意项目都会完成这次初次引导。
Windowed = 窗口模式
Fullscreen = 全屏

main = 主界面
versus = 对抗模式
training = 训练
start-mode = 开始： { TRANSLATE($value) }

# Audio Menu
AUDIO = 音讯

Play-Audio = 播放音讯
Play-Music = 播放音乐

Audio-volume = 音量： {$value}
SFX-volume = 特效： {$value}
Music-volume = 音乐： {$value}
UI-volume = 界面： {$value}
Voice-volume = 语音： {$value}

# Video Menu
VIDEO = 视频设置
Quick-Setup = 快速设置
Display = 显示
Quality = 质量
Effects = 特效
Apply-Changes = 应用更改

graphics-preset-low = 图形：低
graphics-preset-medium = 图形：中
graphics-preset-high = 图形：高
graphics-preset-max = 图形：最高
graphics-preset-custom = 图形：自定义

vsync-off = 垂直同步：关闭
vsync-on = 垂直同步：开启
vsync-adaptive = 垂直同步：自适应

shadow-off = 阴影：关闭
shadow-low = 阴影：低
shadow-highest = 阴影：最高

ssao-off = SSAO：关闭
ssao-on = SSAO：开启
ssao-full = SSAO：完整

aa-off = 抗锯齿：关闭
aa-fxaa = 抗锯齿：FXAA
aa-fxaa-high = 抗锯齿：高质量 FXAA

bloom-off = Bloom：关闭
bloom-on = Bloom：开启
reflections-off = 反射：关闭
reflections-on = 反射：开启
reflections-low = 反射：低
reflections-high = 反射：高
godrays-off = 体积光：关闭
godrays-on = 体积光：开启

perf-overlay-off = 性能指示器：关闭
perf-overlay-on = 性能指示器：开启


point-lights-off = 点光源：关闭
point-lights-on = 点光源：开启

particles-low = 粒子：低
particles-medium = 粒子：中
particles-full = 粒子：高


max-fps-off = 最大帧率：关闭
max-fps-30 = 最大帧率：30
max-fps-60 = 最大帧率：60
max-fps-120 = 最大帧率：120
max-fps-144 = 最大帧率：144

# Controls Menu
CONTROLS = 操作

controls-title = 操作
controls-section-controllers = 控制器
controls-section-mappings = 映射
controls-set-tag = 设置标签
controls-edit-bindings = 编辑按键绑定
controls-tag-untagged = (无标签)
controls-tag-title = 玩家标签
controls-tag-prompt = P{$port} ({$layout})。标签可以是1-24个字母数字、"-"或"_"字符。留空以清除。
controls-tag-confirm = 确认
controls-tag-clear = 清除
controls-tag-cancel = 取消
controls-tag-select-title = 选择标签
controls-tag-filter-empty = 输入以筛选已保存标签
controls-tag-filter-value = 筛选：{$filter}
controls-tag-summary-empty = 已保存 {$total} 个标签。输入以筛选，或创建新标签。
controls-tag-summary-filter = 显示 {$visible}/{$total} 个已保存标签。完全匹配会使用已保存的控制设置。
controls-tag-defaults-suffix = 此控制器的默认设置
controls-tag-create-new = 创建新标签
controls-tag-use-existing = 使用现有标签“{$tag}”
controls-tag-create = 创建“{$tag}”
controls-tag-reserved = “{$tag}”已保留
controls-tag-netplay-blocked = 联机对战期间不能更改标签
controls-tag-no-controller = 未选择本地控制器
controls-tag-no-layout = 所选控制器没有布局
controls-tag-filter-help = 输入以筛选标签；ESC 清除或退出
controls-tag-no-saved = 还没有已保存标签
controls-tag-no-matches = 没有匹配的标签
controls-tag-invalid = 标签无效（1-24个字符，字母数字/-/_；“default”已保留）
controls-profile-help-untagged = 控制设置会保存到共享的无标签配置；只有保存上跳默认值时需要标签。
controls-profile-help-tagged = 控制和上跳默认值会保存到此标签和此控制器类型。
controls-choose-existing-tag = 选择现有标签
controls-create-tag = 创建标签
controls-rename-create-tag = 重命名/创建标签
controls-edit-set-tag-first = 编辑控制（请先设置标签）
controls-edit-controls = 编辑控制
controls-tap-jump-default = 上跳默认值：{$state}
controls-state-on = 开
controls-state-off = 关
controls-netplay-blocked = 联机对战期间不能更改控制
controls-no-local-controllers = 没有活动控制器。按游戏操作键或控制器按钮进行连接。
controls-no-layout = 控制器没有布局
controls-set-tag-before-editing = 请先设置标签，再编辑控制
controls-no-mapping = 此控制器没有可用映射
controls-set-tag-before-tap-jump = 请设置标签以保存上跳默认值
controls-connected-controllers = 已连接控制器
controls-remap-add-key = + 添加绑定（按一个键）
controls-remap-find-input = 查找绑定（按一个输入）
controls-remap-capture-key-title = 按一个键
controls-remap-capture-input-title = 按一个输入
controls-remap-capture-key-help = 下一个按下的键会添加为新绑定。
controls-remap-capture-input-help = 下一个使用的按钮或摇杆会被选中以便编辑。
controls-remap-capture-cancel = 按 ESC 取消
controls-default-save-blocked = 不能覆盖默认控制；请先设置标签
controls-default-reset-blocked = 不能从此菜单重置默认控制
controls-tag-filter-entry-help = 输入以筛选已保存的控制器标签；手柄可以使用方向键。
controls-tag-filter-label = 过滤
controls-tag-preconfigured = 预设
controls-tag-rename-title = 重命名标签
controls-tag-create-title = 创建标签
controls-tag-apply-existing-help = 将匹配的已保存标签应用到此控制器。
controls-tag-create-empty-help = 为此控制器创建一个新标签。
controls-tag-create-filtered-help = 如果名称有效，就为控制器创建此标签。
controls-tag-apply-saved-help = 将此标签及其保存的映射应用到控制器。
controls-tag-apply-preconfigured-help = 使用此控制器类型的默认映射应用这个预设标签。
controls-tag-apply-default-help = 使用此控制器类型的默认映射应用此标签。
controls-tag-delete-button = 删除 {$tag}
controls-tag-delete-help = 确认后删除 {$tag} 及每种控制器类型保存的控制设置和校准。
controls-tag-delete-title = 删除标签？
controls-tag-delete-body = 删除“{$tag}”、每种控制器类型的控制设置和校准，并取消其与已连接控制器的分配？
controls-tag-delete-warning = 此操作无法撤销。
controls-back-help = 返回控制。
controls-tag-select-help = 选择或创建一个控制器标签。
controls-edit-set-tag-first-help = 先创建控制器标签，再编辑游戏和菜单绑定。
controls-edit-controls-help = 编辑此控制器配置的游戏和菜单绑定。
controls-tap-jump-set-tag-first-help = 先创建控制器标签，再设置默认轻点跳跃偏好。
controls-tap-jump-default-help = 切换该控制器默认是否按上就跳。
controls-create-new-tag-help = 创建新标签并将此控制器切换到它。
controls-choose-existing-tag-help = 选择或删除已保存的标签。
controls-rename-current-tag-help = 重命名当前控制器标签。
controls-switch-controller-help = 将控制菜单切换到这个已连接的控制器。
menu-binding-hint = 用摇杆或方向键移动 · 确认/Start 选择 · 返回键返回
menu-adjust-hint = 用摇杆或方向键移动 · 左/右更改数值 · 确认选择 · 返回键返回
menu-bind-hint = 用摇杆或方向键移动 · 确认选择绑定 · 返回键返回
arcade-select-leave = Select 离开
main-help-about-help = 指南、制作人员和 bluehexagons 链接。
main-replays-available-help = 浏览、预览并播放保存的回放文件。
main-replays-unavailable-help = 回放只能离线使用，因为它们会从本地文件系统加载。
arcade-menu-battles-help = 使用当前 Arcade Battles 设置开始。
arcade-menu-infinite-help = 开始无尽 Arcade 模式，对抗会逐步增强的 1-stock CPU。
arcade-menu-training-help = 打开带练习工具和状态保存的训练模式。
arcade-menu-back-help = 返回主菜单。
arcade-menu-help = 选择一个街机模式。
training-menu-courses-help = 选择一个简短的游戏机制课程。
training-menu-help = 选择一项训练活动。
courses-menu-course-help = 前往这个课程区域。
courses-menu-back-help = 返回训练。
courses-menu-help = 课程区域从左到右排列。你可以随时自由移动。
course-instruction-movement-walk = 向左或右推动移动摇杆来行走。
course-instruction-movement-dash = 向左或右快速推动移动摇杆来冲刺。
course-instruction-movement-crouch = 按下方向蹲下。
course-name-movement = 移动
course-name-jumping = 跳跃
course-name-attacks = 攻击
course-name-defense = 防御
course-name-advanced = 高级
course-name-directional-influence = 方向影响
course-name-teching = 受身
course-summary-movement = 行走、冲刺、蹲下并到达标记。
course-summary-jumping = 练习跳跃、空中跳跃、穿过平台、抓边以及角色可用的蹬墙跳。
course-summary-attacks = 练习地面攻击、空中攻击和追击，然后用必杀技消耗能量。
course-summary-defense = 练习防御、完美盾、闪避、翻滚、弹反、蹲姿取消、抓取和投掷。
course-summary-advanced = 练习摇杆攻击、空中闪避、V取消、波浪冲刺、快速下落、落地取消和上必杀技回场。
course-summary-directional-influence = 用移动摇杆改变危险装置的击飞方向。
course-summary-teching = 被危险装置击飞后，在落地和撞墙时受身。
course-instruction-movement-travel = 移动到箭头标记。
course-instruction-jumping-jump = 按下跳跃离开地面。
course-instruction-jumping-air-jump = 在空中再次按下跳跃来空中跳跃。
course-instruction-jumping-steer = 跳跃后持续按住左或右，在空中移动。
course-instruction-jumping-platform-drop = 落到上方平台后，按下下方向穿过平台。
course-instruction-jumping-ledge-grab = 从下方靠近平台边缘来抓住边缘。
course-instruction-jumping-ledge-option = 抓住边缘后，选择一种行动：爬上、翻滚、攻击、跳跃或松手。
course-instruction-jumping-wall-jump = 碰到上方墙壁后，快速向远离墙壁的方向推动摇杆来蹬墙跳。
course-instruction-attacks-normal = 用普通攻击击中练习目标。
course-instruction-attacks-aerial = 跳跃并用空中攻击击中练习目标。
course-instruction-attacks-combo = 在练习目标恢复前，再接一次攻击。
course-instruction-attacks-energy = 使用必杀技，观察共用能量条减少并在延迟后恢复。
course-instruction-attacks-special = 用必杀技击中练习目标。
course-instruction-defense-shield = 用盾挡下练习目标的攻击。
course-instruction-defense-power-shield = 在攻击命中前用力按下盾，打出不损失能量的完美盾。
course-instruction-defense-roll = 举盾时按左或右来翻滚。
course-instruction-defense-spot-dodge = 举盾时按下来原地闪避。
course-instruction-defense-parry = 在攻击命中前松开盾来弹反。
course-instruction-defense-crouch-cancel = 持续按下，在蹲姿中承受练习目标的攻击来蹲姿取消。
course-instruction-defense-grab = 抓取练习目标。
course-instruction-defense-throw = 抓住练习目标后，选择一个方向将其投掷出去。
course-instruction-advanced-stick = 向任意方向快速推动右摇杆来使出摇杆攻击。
course-instruction-advanced-air-dodge = 跳跃后用力按下盾按钮来空中闪避。
course-instruction-advanced-v-cancel = 在目标附近跳跃，并在起跳时用力按下盾按钮，以V取消减轻它在空中对你的攻击。
course-instruction-advanced-wave-dash = 跳跃后，斜向地面进行空中闪避来使出波浪冲刺。
course-instruction-advanced-fast-fall = 在空中按下下方向来快速下落。
course-instruction-advanced-lag-cancel = 空中攻击后，在落地前按下盾来取消落地硬直。
course-instruction-advanced-recovery = 在空中按上方向和必杀技，用上必杀技回场。
course-instruction-directional-influence = 被发射台击中的瞬间持续按住左或右，改变击飞角度。
course-instruction-teching-neutral = 从发射台落地前，用力按下盾按钮来受身。
course-instruction-teching-wall = 撞上墙壁前，用力按下盾按钮来墙受身。
course-instruction-complete = 区域完成。准备好后可前往其他区域。
course-action-restart = 重新开始区域
course-action-next = 下一个区域
course-session-progress = 已完成区域：{$completed}/{$total}
course-target-label = 练习目标
course-target-reset = 重置目标
course-target-disable = 禁用目标
course-target-enable = 启用目标
course-target-unavailable = 此区域没有目标
course-target-reset-help = 将此区域的练习目标恢复到起始位置并启用。
course-target-toggle-help = 在当前课程会话中隐藏或恢复此区域的练习目标。
course-defense-feedback-early = 等攻击临近时再防御。
course-defense-feedback-late = 太晚了。请在攻击命中前防御。
course-defense-feedback-success = 时机很好。已挡住攻击。
course-demonstration-label = 演示
course-demonstration-show = 显示静态演示
course-demonstration-hide = 隐藏静态演示
course-demonstration-help = 显示或隐藏当前课程步骤的无动画示例。
course-demonstration-still = 静态姿势 · 无动画
help-bluehex-homepage-help = 访问 bluehexagons 主页。
help-bluehex-github-help = 在 GitHub 浏览 bluehexagons 项目。
help-bluehex-steam-help = 打开 bluehexagons 的 Steam 鉴赏家页面。
help-bluehex-itch-help = 打开 bluehexagons 的 itch.io 页面。
help-bluehex-bluesky-help = 在 Bluesky 关注 bluehexagons。
help-bluehex-patreon-help = 在 Patreon 支持 bluehexagons。
controls-source-keyboard = 键盘
controls-source-keyboard-defaults = 键盘默认值
controls-current-menu-controls-heading = 当前菜单控制
controls-current-menu-controls-summary = {$source} · 移动：{$navigate} · 确认：{$confirm} · 返回：{$back}
controls-action-attack = 攻击
controls-action-jump = 跳跃
controls-action-special = 必杀
controls-action-grab = 抓取
controls-action-shield-1 = 盾 1
controls-action-shield-2 = 盾 2
controls-action-hard-shield-1 = 强盾 1
controls-action-hard-shield-2 = 强盾 2
controls-action-select = Select
controls-action-start = Start
controls-action-dpad-up = D-pad 上
controls-action-dpad-down = D-pad 下
controls-action-dpad-left = D-pad 左
controls-action-dpad-right = D-pad 右
controls-action-move-horizontal = 水平移动
controls-action-move-vertical = 垂直移动
controls-action-right-stick-horizontal = 右摇杆水平
controls-action-right-stick-vertical = 右摇杆垂直
controls-action-ui-confirm = UI 确认
controls-action-ui-back = UI 返回
controls-action-ui-up = UI 上
controls-action-ui-down = UI 下
controls-action-ui-left = UI 左
controls-action-ui-right = UI 右
controls-action-ui-horizontal-nav = UI 水平导航
controls-action-ui-vertical-nav = UI 垂直导航
controls-action-move-left = 向左移动
controls-action-move-right = 向右移动
controls-action-move-up = 向上移动
controls-action-move-down = 向下移动
controls-action-tilt-left = 轻推左
controls-action-tilt-right = 轻推右
controls-action-tilt-up = 轻推上
controls-action-tilt-down = 轻推下
controls-action-right-stick-left = 右摇杆左
controls-action-right-stick-right = 右摇杆右
controls-action-right-stick-up = 右摇杆上
controls-action-right-stick-down = 右摇杆下
controls-action-light-shield-l = 轻盾 L
controls-action-light-shield-r = 轻盾 R
controls-action-ui-nav-left = UI 左导航
controls-action-ui-nav-right = UI 右导航
controls-action-ui-nav-up = UI 上导航
controls-action-ui-nav-down = UI 下导航
controls-remap-section-buttons = 按钮
controls-remap-section-dpad = D-pad
controls-remap-section-movement = 移动
controls-remap-section-tilts = 轻推（软输入）
controls-remap-section-right-stick = 右摇杆
controls-remap-section-light-shields = 轻盾
controls-remap-section-ui-navigation = UI 导航
controls-remap-section-sticks-triggers = 摇杆与扳机
controls-remap-unbound = 未绑定
controls-remap-free-keys-none = 空闲按键：（常用集合中没有）
controls-remap-more-suffix = ，另有 +{$count}
controls-remap-free-keys = 空闲按键：{$keys}{$suffix}
controls-remap-free-buttons = 空闲按钮：{$buttons}
controls-remap-free-axes = 空闲轴：{$axes}
controls-remap-conflict-detail = {$input} 已绑定到 {$actions}。
controls-remap-row-label = {$label}: {$input}
controls-remap-protected-ui-bindings = 请保留 UI 确认、UI 返回以及水平和垂直导航，以便菜单仍可使用。
controls-remap-capture-key-hint = 按下要用于 {$action} 的键盘按键。ESC 取消。
controls-remap-capture-button-hint = 按下要用于 {$action} 的 {$layout} 按钮。返回取消。
controls-remap-capture-axis-hint = 移动要用于 {$action} 的 {$layout} 摇杆/扳机。返回取消。
controls-remap-capture-add-title = 添加 {$action}
controls-remap-capture-replace-title = 替换 {$action}
controls-remap-capture-matching-input = 请使用适合此动作的输入。
controls-remap-confirm-reassign = 确认将其重新分配给 {$action}。
controls-remap-confirm-cancel-help = 确认会替换它。返回会取消。
controls-remap-command-add = 添加
controls-remap-command-replace = 替换
controls-remap-command-remove = 移除
controls-remap-add-help = 为 {$action} 添加另一个物理输入。
controls-remap-replace-help = 将 {$action} 的 {$input} 替换掉。
controls-remap-remove-help = 从 {$action} 中移除 {$input}。
controls-remap-back-to-controls = 返回控制
controls-remap-back-to-controls-help = 无需滚动到重映射列表底部即可返回控制。
controls-remap-help = 选择添加、替换或移除。Page 键可在列表中跳转。
controls-remap-help-extended = 选择添加、替换或移除。Page 键可在列表中跳转；返回取消。
controls-remap-jump-to-section = 跳到分区
controls-remap-jump-to-binding = 跳到 {$section}
controls-remap-focus-section-help = 将焦点移到 {$section} 的第一个绑定。
controls-remap-reset-help = 将此控制配置重置为默认布局。需要两次确认。
controls-remap-reset-confirm = 再按一次以确认重置
controls-quick-map-action-unbound = 未绑定
controls-quick-map-action-hard-shield-1-short = 盾 1
controls-quick-map-action-hard-shield-2-short = 盾 2
controls-quick-map-action-dpad-up-short = D-上
controls-quick-map-action-dpad-down-short = D-下
controls-quick-map-action-dpad-left-short = D-左
controls-quick-map-action-dpad-right-short = D-右
controls-quick-map-title = {$layout} 快速布局
controls-quick-map-mode-editing = 确认或点击操作以应用 · 返回或点击标题以退出
controls-quick-map-mode-ready = 确认进入快速编辑
controls-quick-map-mode-unavailable = 控制不可用
controls-quick-map-assign = 分配
controls-quick-map-assign-input = 分配 {$input}
controls-quick-map-unavailable-status = 此控制器不支持快速映射。未保存任何更改。
controls-remap-autosave-status = 更改会自动保存。
controls-remap-saved-status = 已自动保存。
controls-remap-blocked-menu-controls-status = 已阻止：请保留 UI 确认、UI 返回以及菜单的水平和垂直导航。未保存任何更改。
controls-remap-default-reset-blocked-status = 无法重置内置默认控制。未保存任何更改。
controls-layout-standard = Xbox / 标准
controls-layout-arcade-stick = 街机摇杆
controls-layout-retro-dpad = 复古方向键
controls-layout-switch-pro = Switch Pro
controls-layout-playstation = PlayStation
controls-layout-8bitdo-nintendo = 8BitDo（Nintendo 布局）
controls-layout-steam-deck = Steam Deck
controls-layout-gamecube = GameCube
controls-layout-n64 = Nintendo 64
controls-layout-keyboard = 键盘

standard = 标准
keyboard = 键盘
gcn_native = GCN原生

# Training Menu
Swap-Character = 交换角色
Overlays = 叠加层
press-start = 按下开始

drawHitbubbleInfo = 攻击信息
drawECB = 碰撞
drawHeatmap = 热图
drawRawPosition = 原始位置
drawStage = 舞台碰撞
animations = 动画制作
controllers = 控制器

# Versus Menu
FFA = FFA
Teams = 队伍

Host-Netplay = 主机网络游戏
Join-Netplay-Clipboard = 从剪贴板加入Netplay
Disconnect = 断开
Copy-Lobby-Code = 复制大厅代码

# Netplay Menu
NETPLAY = NETPLAY
Netplay = Netplay
Direct-Connect = 直接连接
Connect = 连接

netplay-action-start-lobby = 开始大厅
netplay-action-join-clipboard = 从剪贴板加入
netplay-action-quick-host-copy-code = 快速主机并复制代码
netplay-action-copy-lan-invite = 复制LAN邀请
netplay-action-copy-localhost-invite = 复制Localhost邀请
netplay-action-copy-stun-invite = 复制STUN邀请
netplay-action-find-random-match = 查找随机比赛
netplay-action-cancel-lobby = 取消大厅
netplay-action-cancel-connection = 取消连接
netplay-action-please-wait = 请稍候
netplay-action-open-versus = 打开Versus
netplay-action-cancel-matchmaking = 取消匹配

netplay-status-label = 联机：{$status}
netplay-status-uninitialized = 未初始化
netplay-status-initialized = 已初始化
netplay-status-waiting = 等待中
netplay-status-hosting = 正在主持
netplay-status-connecting = 正在连接
netplay-status-establishing = 正在建立
netplay-status-connected = 已连接
netplay-status-ready = 准备Netplay
netplay-status-waiting-player = 等待玩家加入
netplay-status-waiting-lobby = 等待大厅响应
netplay-status-hosting-lobby = 正在主持大厅
netplay-status-hosting-lobby-code = 正在主持大厅 {$code}
netplay-status-starting-lobby = 正在开始大厅
netplay-status-connecting-host = 正在连接主机
netplay-status-connected-host = 已作为主机连接
netplay-status-connected-client = 已连接到主机
netplay-status-disconnecting = 正在断开连接
netplay-status-canceling = 正在取消连接
netplay-status-matchmaking = 正在搜索随机比赛
netplay-status-match-found = 找到随机比赛
netplay-status-matchmaking-canceling = 正在取消匹配
netplay-status-error = Netplay错误
netplay-status-error-message = Netplay错误: {$error}
netplay-status-unavailable = Netplay状态不可用

matchmaking-title = 匹配
matchmaking-status-select-character = 选择一个角色以加入匹配队列
matchmaking-status-no-controller = 未连接控制器
matchmaking-status-searching = 正在寻找对手...
matchmaking-status-searching-details = 正在搜索... 已等待 {$wait} 秒。排队玩家：{$players}。最长等待：{$longest} 秒。
matchmaking-status-searching-estimate = 正在搜索... 已等待 {$wait} 秒。排队玩家：{$players}。已完成对局平均耗时 {$average} 秒。
matchmaking-status-canceling = 正在取消...
matchmaking-status-found = 已找到对手！
matchmaking-status-connecting = 正在连接...
matchmaking-status-disconnecting = 正在断开连接...
matchmaking-status-error = {$error} 请选择一个角色后重试。

# Match by Code
match-code-title = 通过代码对战
match-code-hint = 分享你的代码并输入好友的代码。双方都按“搜索”。不区分大小写。
match-code-own-label = 你的代码：{$code}
match-code-peer-label = 好友的代码：{$code}
match-code-peer-unset = 好友的代码：（未设置）
match-code-search = 搜索
match-code-entry-limit = 最多 {$length} 个字母或数字
match-code-own-prompt = 你的代码
match-code-peer-prompt = 好友的代码
match-code-status-enter-peer = 输入好友的代码以创建私人对战
match-code-status-ready = 准备就绪 — 双方都应按“搜索”
match-code-error-enter-peer = 请先输入好友的代码
match-code-error-own = 请输入好友的代码，而不是你自己的代码
match-code-error-invalid = 该代码无效
match-code-error-length = 代码必须由 {$min}–{$max} 个字母或数字组成
match-code-error-blocked = 不允许使用该代码；请选择其他代码

netplay-detail-ready = 主持大厅、粘贴复制的邀请或手动输入地址。
netplay-detail-lobby-code-ready = 大厅代码 {$code} 已准备好分享。
netplay-detail-creating-lobby-code = 正在创建您的大厅代码。
netplay-detail-waiting-for-host = 等待主机回答您的加入请求。
netplay-detail-share-lobby-code = 与其他玩家分享大厅代码 {$code}。
netplay-detail-starting-lobby = 正在开始您的大厅连接。
netplay-detail-joining-host = 正在尝试加入选定的主机。
netplay-detail-establishing = 找到玩家。完成握手，然后打开Versus。
netplay-detail-connected = 连接就绪。打开Versus选择规则、角色和场地。
netplay-detail-disconnecting = 正在关闭当前会话并返回离线游戏。
netplay-detail-canceling = 正在停止当前的加入请求。
netplay-detail-matchmaking = 使用Versus排队寻找符合您首选规则的随机对手。
netplay-detail-match-found = 找到对手。当两名玩家都准备好时，在Versus中完成设置。
netplay-detail-matchmaking-canceling = 正在停止当前的随机比赛搜索。
netplay-detail-error-message = 最后的错误: {$error}
netplay-detail-error-generic = 出现问题。请尝试不同的代码或连接方式。
netplay-detail-unavailable = Netplay详情不可用。

netplay-help-host-copy-code = 复制您的大厅代码，以便其他玩家可以粘贴。
netplay-help-host-cancel-join = 停止当前的加入尝试并返回就绪状态。
netplay-help-host-disconnect = 离开当前的netplay会话。
netplay-help-host-start-lobby = 开始新大厅并等待其他玩家加入。
netplay-help-busy = Netplay现在正忙。请等待它完成。
netplay-help-join-cancel-lobby = 关闭当前大厅并停止等待其他玩家。
netplay-help-join-in-progress = 加入已在进行中。请等待或使用"取消连接"。
netplay-help-join-open-versus = 继续到Versus并完成比赛设置。
netplay-help-stop-random-search = 停止搜索随机对手。
netplay-help-join-clipboard = 从剪贴板粘贴大厅、直连或STUN邀请代码。
netplay-help-copy-server = 如需要，先开始大厅，然后复制其可分享的大厅代码。
netplay-help-copy-direct = 为此LAN上的另一个设备复制直连邀请。
netplay-help-copy-localhost = 为此计算机上运行的另一个副本复制直连邀请。
netplay-help-copy-stun = 复制STUN辅助邀请，在互联网上更容易使用。
netplay-help-direct-connect = 手动输入地址，而不是使用复制的邀请代码。
netplay-help-find-random-match = 打开Versus并排队等待随机对手。
netplay-help-open-versus = 不离开此屏幕打开Versus菜单。
netplay-help-back = 返回主菜单。
netplay-help-unavailable = Netplay操作帮助不可用。
netplay-help-advanced = 调整netplay的高级设置，如回滚和缓冲区。

ADVANCED-CONNECTIONS = 高级连接
netplay-settings-rollback-help = 切换联机对战的回滚模拟。
netplay-settings-buffer-help = 选择要缓冲多少输入帧，或让联机自动选择。
netplay-settings-force-ipv4-help = 在混合网络中生成局域网邀请代码时优先使用 IPv4。
netplay-settings-back-help = 返回联机菜单。
netplay-advanced-info = 当 Quick Play 或普通大厅代码无法连接时，请使用这些备用选项。STUN 可帮助在互联网对战中穿透路由器。直接连接最适合局域网对战，或适用于已转发 UDP 端口的主机。
netplay-advanced-direct-help = 手动备用。用于局域网对战，或当主机已转发 UDP 端口时输入 host:port。
netplay-advanced-stun-help = 互联网备用。当普通大厅加入失败且仍需要路由器辅助打洞时，请分享这个选项。
netplay-advanced-lan-help = 局域网备用。当两位玩家位于同一网络时，请分享你可访问的本地地址。
netplay-advanced-localhost-help = 测试备用。仅当两个客户端都运行在同一台机器上时使用。
netplay-advanced-back-help = 返回虚拟沙发。
netplay-rollback-off = 回滚：关
netplay-rollback-on = 回滚：开
netplay-buffer-auto = 网络缓冲：自动
netplay-buffer-2 = 网络缓冲：2
netplay-buffer-3 = 网络缓冲：3
netplay-buffer-4 = 网络缓冲：4
netplay-buffer-5 = 网络缓冲：5
netplay-buffer-6 = 网络缓冲：6
netplay-buffer-7 = 网络缓冲：7
netplay-buffer-8 = 网络缓冲：8
netplay-buffer-10 = 网络缓冲：10
netplay-buffer-12 = 网络缓冲：12
netplay-force-ipv4-dual = 局域网地址：IPv6/IPv4
netplay-force-ipv4-v4 = 局域网地址：强制 IPv4

netplay-rollback = 回滚
netplay-buffer = 网络缓冲区
netplay-force-ipv4 = LAN地址

netplay-direct-connect-prompt = 输入IP地址:端口。端口默认为 {$port}。
netplay-stun-connect-title = 使用STUN服务？
netplay-stun-connect-prompt = 此代码使用 {$service} 发现了 {$address}:{$port}。
netplay-waiting-host-battle = 等待主机战斗结束
Random-Q = ?
Sub-Symbol = -
Add-Symbol = +
Tapjump-Symbol = TJ

Characters = 角色
Stages = 场地
CPU = CPU

Starter = 起始
Legal = 赛事
Miscellaneous = 其他

Start-Battle = 开始战斗

# Start Menu
quit-info = 盾牌 + 攻击 + 开始 以退出
paused = 已暂停
tag-info = D-pad 上/下切换标签进出

# Pause Menu
pause-resume = 继续
pause-restart = 重新开始
pause-quit = 退出
pause-players = 玩家
pause-tap-jump = Tap Jump

# Arcade Mode
arcade-connect = 连接控制器并按任意按钮加入。
arcade-return-prompt = 按确认返回主菜单。

# Replay
replay-paused = 重放已暂停
replay-controls = 确认：加入  ←/→：帧  返回：菜单  保存重放：[键]

# Languages
en-english = English
es-spanish = Español
fr-french = Français
it-italian = Italiano
de-german = Deutsch
ru-russian = Русский
ja-japanese = 日本語
zh-chinese-cn = 简体中文
zh-chinese-hk = 繁體中文
ko-korean = 한국어

english = 英语
spanish = 西班牙文
french = 法文
italian = 意大利文
german = 德语
russian = 俄语
japanese = 日语
chinese-cn = {zh-chinese-cn}
chinese-hk = 繁体中文
korean = 韩语

en = {en-english} ({english})
es = {es-spanish} ({spanish})
fr = {fr-french} ({french})
it = {it-italian} ({italian})
de = {de-german} ({german})
ru = {ru-russian} ({russian})
ja = {ja-japanese} ({japanese})
zh = {zh-chinese-cn}
zh-hk = {zh-chinese-hk} ({chinese-hk})
ko = {ko-korean} ({korean})

# Shared UI labels
Advanced = 高级
Clear-Spawns = 清除生成点
Create-new-tag = 创建新标签
Credits = 制作人员
CREDITS = 制作人员
Cycle-Palette = 切换配色
Delete = 删除
Help = 帮助
HELP = 帮助
Join = 加入
Join-Lobby-Code = 通过大厅代码加入
Main-Menu = 主菜单
Mode = 模式
Native-Adapter = 原生适配器
NATIVE-ADAPTER = 原生适配器
NETPLAY-SETTINGS = 联机设置
Other-saved-tags = 其他已保存标签
Profiles-for-this-controller-type = 此控制器类型的配置
Quick-Play = 快速对战
Random-Color = 随机颜色
Rename-current-tag = 重命名当前标签
Reset-to-Defaults = 重置为默认值
Set-Character = 设置角色
Spawn-CPU = 生成 CPU
Team = 队伍
Virtual-Couch = 虚拟沙发
x = x
Find-Random-Match = 寻找随机对战
training-label-stage = 场地
training-label-character = 角色
training-label-player-cursor = 玩家光标
training-label-cpu-spawn = 生成 CPU
training-label-savestate = 状态保存
Save-State = 保存状态
Load-State = 读取状态
State-Saved = 状态已保存
State-Restored = 状态已恢复
No-State-Saved = 没有已保存状态
DPad-Right-Save-Left-Load = 方向键右保存 · 左读取
shared-main-menu-help = 返回主菜单。
shared-mode-selector-label-help = 规则选择器标签。
training-mode-selector-help = 在 Antistatic 和 19XX 的训练规则之间切换。
training-overlays-help = 切换调试叠加层和训练辅助显示。
training-close-help = 关闭训练菜单。
training-stage-help = 更换训练场地并重置依附于场地的实体。
training-character-help = 选择“设置角色”和“生成 CPU”使用的角色。
training-set-character-help = 将悬停的玩家光标切换到所选角色。
training-random-color-help = 为光标角色分配新的随机基础颜色。
training-cycle-palette-help = 循环切换光标角色的配色方案。
training-cpu-level-down-help = 降低新训练 CPU 使用的 CPU 等级。
training-cpu-level-current-help = 新生成训练 CPU 的当前 CPU 等级。确认可循环切换。
training-cpu-level-up-help = 提高新训练 CPU 使用的 CPU 等级。
training-spawn-cpu-help = 使用所选角色和 CPU 等级生成一个 CPU。
training-clear-spawns-help = 移除训练中生成的所有 CPU 和木桩角色。
training-save-state-help = 保存当前训练的位置、伤害、stock、生成的 CPU、场地和时序状态。方向键右也可执行同一快捷操作。
training-load-state-help = 恢复已保存的训练状态。方向键左也可执行同一快捷操作。
training-savestate-shortcuts-help = 方向键右保存当前训练状态；方向键左恢复它。
versus-tag-selector-default = 标签：{$tag}
versus-tag-none = 无标签
versus-tag-manage = 创建 / 管理标签
versus-tag-change-failed = 无法更改标签
versus-cpu-level-help = 循环切换这个 CPU 等级。
versus-cpu-color-help = 重新随机这个 CPU 的颜色和配色。
versus-cpu-team-help = 循环切换这个 CPU 的队伍。
versus-cpu-remove-help = 移除此 CPU。
versus-character-select-help = 为悬停的玩家光标选择这个角色。
versus-add-cpu-help = 添加一个使用此角色的 CPU。
versus-tap-jump-help = 切换该玩家的轻点跳跃。
versus-random-color-help = 为该玩家分配新的随机颜色。启用队伍时会禁用。
versus-cycle-palette-help = 循环切换该玩家的配色方案。
versus-team-help = 循环切换该玩家的队伍。仅在队伍模式下显示。
versus-tag-selector-help = 选择该玩家的标签。联机对战时禁用。
versus-start-select-character-first = 请先选择一个角色
versus-start-not-enough-players = 玩家数量不足，无法开始游戏：{$count}
versus-start-not-enough-teams = 队伍数量不足，无法开始游戏：{$count}
versus-start-waiting-for-host = 正在等待主机开始
versus-ffa-help = 切换自由混战和队伍战规则。
versus-start-help = 当足够的玩家、CPU、队伍和场地准备好后开始比赛。
versus-starter-help = 随机选择一个起始场地并开始比赛。
versus-legal-help = 随机选择一个合法的起始或反选场地并开始比赛。
versus-misc-help = 杂项场地。
versus-stage-preview-help = 悬停以预览这个场地；确认即可选择并开始。
versus-stage-preview-counterpick-help = 悬停以预览这个反选场地；确认即可选择并开始。
versus-stage-preview-misc-help = 悬停以预览这个杂项场地；确认即可选择并开始。
versus-mode-selector-help = 在 Antistatic 和 19XX 的对战规则之间切换。
versus-tab-stages-help = 浏览并选择本局对战的场地。
versus-tab-settings-help = 配置对战规则和设置。在这里按 Start 会切换到场地选择。
versus-setting-stock = Stock 模式
versus-setting-time = 时间模式
versus-setting-on = 开
versus-setting-off = 关
versus-setting-none = 无
versus-setting-stock-mode-value = 模式：{$value}
versus-setting-stocks-value = Stocks：{$value}
versus-setting-time-limit-value = 时间：{$value}
versus-setting-friendly-fire-value = FF：{$value}
versus-setting-stamina-value = 体力：{$value}
versus-setting-knockback-value = KB：{$value}×
versus-setting-pause-value = 暂停：{$value}
versus-setting-sd-value = SD：{$value}
versus-setting-stock-mode-help = 在 Stock 模式（最后存活的玩家获胜）和 Time 模式（计时结束时剩余 stock 最多者获胜）之间切换。
versus-setting-stocks-help = 每名玩家开局拥有的 stock（生命）数量。
versus-setting-time-limit-help = 对战时间限制。在 Time 模式中它决定胜者。
versus-setting-friendly-fire-help = 切换队友之间是否可以互相造成伤害。仅在组队模式显示。
versus-setting-stamina-help = 开始体力（HP）。设为 0 可使用伤害百分比模式。
versus-setting-knockback-help = 全局击飞倍率。数值越高，击飞距离越远。
versus-setting-pause-help = 允许或禁止在对战中暂停。
versus-setting-sd-help = 自毁惩罚。-1 扣除一个 stock；0 无惩罚。
netplay-copy-lobby-missing = 没有可复制的大厅代码
netplay-copy-lobby-copied = 已将大厅代码复制到剪贴板
netplay-direct-connect-empty = 请输入 IP 地址
netplay-lobby-code-prompt = 输入大厅、局域网或 STUN 邀请代码。
netplay-lobby-code-empty = 请输入大厅代码
netplay-error-connecting = 连接错误：{$error}
matchmaking-no-controller-connected = 没有连接控制器
battle-winner-log = 胜者：{$player}
battle-winner-message = 胜者：玩家 {$player}
battle-winner-team-log = 胜者：{$team}队
battle-winner-team-message = 胜者：{$team}队
battle-tie-log = 平局
battle-tie-message = 平局
battle-time-out = 时间到
battle-countdown-go = 开始
battle-infinite-score-log = 无限分数：{$score}
battle-infinite-score-message = 分数 {$score}
team-name-red = 红
team-name-green = 绿
team-name-blue = 蓝
team-name-grey = 灰
versus-start-sync-failed = 无法同步战斗开始

main-menu-help = 将光标移到选项上即可查看其作用。
netplay-main-help = 选择一个联机操作。
netplay-settings-help = 调整联机行为。
netplay-advanced-help = 选择一种连接方式。
settings-help = 选择一个设置类别。
help-discord-help = 在浏览器中打开 Antistatic Discord 社区。
help-guide-help = 在浏览器中打开 Antistatic 在线指南。
help-adapter-guide-help = 打开官方 GameCube 控制器适配器的 Dolphin 设置说明。
Adapter-Guide = 适配器指南
Open-Dolphin-Guide = 打开 Dolphin 指南
Native-Adapter-Help = 适配器帮助
NATIVE-ADAPTER-HELP = 适配器帮助
native-adapter-help-summary = Antistatic 直接使用 libusb，因此它与 Dolphin 的原生适配器支持共用同一套驱动设置。
native-adapter-help-windows = Windows：使用 Zadig 为 USB ID 057e:0337 安装 WinUSB。
native-adapter-help-linux = Linux：添加一条 udev 规则，向用户授予 057e:0337 的访问权限。
native-adapter-help-sdl = 如果 SDL/Dolphin 先占用了适配器，请使用 SDL_JOYSTICK_HIDAPI_GAMECUBE=0 启动。
native-adapter-help-dolphin = Dolphin/Slippi：在打开 Antistatic 原生适配器诊断前请先关闭它们。
native-adapter-help-claim = 如果其他应用占用了适配器，请关闭它并重新打开此诊断界面。
native-adapter-help-back = 返回原生适配器状态。
help-credits-help = 查看制作人员、版权和第三方署名。
help-back-help = 返回主菜单。
help-help = 选择一个帮助项目。
controls-help = 选择一个控制器操作。
netplay-quick-play-help = 使用所选控制器搜索随机对手。
credits-help = 制作人员和署名。

credits-heading = Antistatic - 制作人员与署名
credits-copyright = Copyright (c) 2026 bluehexagons / Loren Crain. 保留所有权利。
credits-developer = 开发者：bluehexagons (Loren Crain)。
credits-original = 原创音效、模型、动画、玩法、界面和引擎代码均为内部制作。
credits-runtime = 开源运行时/工具：Node.js、TypeScript、CMake、Fluent、gl-matrix、jsonc-parser、os-locale。
credits-libraries = 原生库：SDL3、SDL3_image、GLEW、OpenAL Soft、FreeType、Vorbis/libvorbisfile、libusb。
credits-build = 构建/检查工具：npm、oxlint、oxfmt，以及各平台编译器工具链。
credits-fonts = 随附字体：Noto Sans、IBM Plex Mono 和 GNU Unifont。
credits-tools = 制作工具：3D 模型使用 Blender；音频和音乐使用 Audacity 和 LMMS。
credits-packages = bluehexagons 软件包：capacitor、trace 和 antistatic-translations。
credits-thanks = 感谢这些项目的维护者和贡献者。
credits-license = 第三方项目仍遵循各自的许可证。

# Old UI hover/help text
main-versus-help = 在开始本地对战前，选择角色、CPU、队伍、规则和舞台。
main-arcade-help = 为所有已连接玩家提供合作 CPU 战斗。生命有限，失败后可重试。
main-netplay-help = 主持或加入在线游戏、Quick Play 和 Netplay 连接设置。
main-training-help = 打开训练模式，包含舞台、CPU、颜色、调色板和调试控制。
main-replays-help = 浏览、预览并播放已保存的 Replay 文件。
main-settings-help = 调整音频、视频、语言、控制器适配器和启动模式设置。
main-controls-help = 创建控制器标签，并编辑带标签或共享的无标签按键映射。
main-help-help = 打开社区和外部指南链接。
main-exit-help = 退出 Antistatic。
settings-audio-help = 调整主音量、音效、界面、语音和音乐音量。
settings-video-help = 更改图形预设、全屏、同步、特效和帧率限制选项。
settings-native-adapter-help = 查看 GameCube 适配器状态和安装说明。
settings-language-help = 切换菜单语言。
settings-start-mode-help = 选择启动时最先打开的模式。
settings-live-reload = 实时重新加载
settings-live-reload-help = 在本地编辑时从 Animator 重新加载角色文件。默认关闭。
shared-settings-help = 返回设置。
native-adapter-copy-udev-install-help = 复制 057e:0337 的标准 udev 规则安装和重新加载命令。
native-adapter-copy-udev-line-help = 仅复制 057e:0337 的标准 udev 规则行。
native-adapter-help-button-help = 打开适用于 Dolphin/Slippi 兼容适配器安装的 Windows 和 Linux 设置说明。
audio-master-help = 设置主输出音量。
audio-sfx-toggle-help = 切换音效和界面声音。
audio-sfx-help = 设置游戏音效音量。
audio-ui-help = 设置菜单和界面音量。
audio-voice-help = 设置角色语音音量。
audio-music-toggle-help = 切换音乐播放。
audio-music-help = 设置音乐音量。
video-preset-help = 应用分组的图形预设，或在各项设置不同时时显示自定义。
video-fullscreen-toggle-help = 在窗口模式和全屏之间切换。
video-display-help = 选择游戏窗口或全屏模式要使用的显示器。
video-fullscreen-resolution-help = 选择独占全屏模式的分辨率。Auto 使用桌面全屏。
video-windowed-resolution-help = 选择窗口模式和从全屏恢复时使用的窗口大小。
video-render-scale-help = 在保持 UI 原生大小的同时，以低于或高于窗口分辨率渲染 3D 图形。
video-vsync-help = 选择交换时序。Adaptive 在驱动支持时使用低延迟的 tear-if-late 同步。
video-shadow-quality-help = 选择阴影质量或禁用阴影。
video-ssao-help = 选择环境光遮蔽质量。
video-antialias-help = 切换 FXAA 抗锯齿。
video-bloom-help = 在最亮的高光周围添加柔和的光晕。在高端 GPU 上效果最佳。
video-reflections-help = 使用屏幕空间反射在光滑表面上映出场景。性能开销较大，在高端 GPU 上效果最佳。
video-godrays-help = 让阳光在场景中投射出体积光束。性能开销较大，在高端 GPU 上效果最佳。
video-perf-overlay-help = 显示或隐藏性能叠加层。
video-point-lights-help = 选择额外点光源质量。
video-particle-quality-help = 选择粒子效果密度。
video-max-fps-help = 设置可选的帧率上限。
video-apply-help = 应用已更改的视频设置。
replays-enabled-help = 在内存中记录符合条件的 Versus 和 Quick Play 对战。内存受限的系统请关闭此项。
replays-auto-save-help = 在结果界面自动保存 Replay，而不是等待手动保存按键。
replays-compression-help = 保存时压缩 Replay 文件。仅在压缩会拖慢保存时关闭。
netplay-copy-lobby-help = 如果可用，复制当前大厅代码。
netplay-virtual-couch-help = 打开大厅托管、大厅代码加入和高级邀请选项。
netplay-settings-menu-help = 配置 rollback、输入缓冲和 LAN 地址行为。
netplay-back-help = 在不断开现有会话的情况下返回主菜单。
arcade-cpu-level-help = 对手 CPU 难度等级（0 最简单，6 最难）。
arcade-stocks-help = 每场对战的生命数。
arcade-retries-help = 失败前的重试次数。
arcade-battles-help = 本次流程的总对战数。
arcade-start-help = 当所有已加入玩家都准备好后开始流程。
controls-remap-page-help = 重新绑定菜单导航、控制台、全屏和训练模式按键。
controls-remap-reset-binding-help = 将 {$action} 重置为默认绑定。
controls-remap-reset-all-help = 将所有键盘快捷键恢复为内置默认值。
replay-browser-help = Replay 浏览器。
replay-offline-only-help = Replay 仅可离线使用，因为它们从本地文件系统加载。
replay-refresh-help = 重新扫描 {$dir} 中保存的 Replay 文件。
replay-entry-help = {$players} 在 {$stage}；{$duration}（{$truncated}）；{$result}；{$version}；{$compression}。
replay-unreadable-help = 无法读取 Replay：{$error}
replay-actions-watch-help = 从头播放已保存的 Replay。Replay 播放期间可使用 Jump In。
replay-actions-back-help = 返回 Replay 列表。
replay-load-help = 从 Replay 目录加载已保存的 Replay 文件。
replay-prev-help = 显示较新的 Replay。
replay-next-help = 显示较旧的 Replay。
replay-settings-help = Replay 录制、自动保存和压缩选项。
audio-help = 调整音频设置。
video-help = 调整视频设置。
replays-help = Replay 默认启用，并限制为每场对战 16 分钟。
native-adapter-help-text = Native Adapter 提供 4 端口直接轮询。PC 模式更简单，但使用 SDL 控制器映射。
shortcut-menu-up-help = 在菜单中向上移动选择。
shortcut-menu-down-help = 在菜单中向下移动选择。
shortcut-menu-left-help = 向左移动选择或减少数值。
shortcut-menu-right-help = 向右移动选择或增加数值。
shortcut-menu-confirm-help = 激活当前焦点项。
shortcut-menu-next-help = 移动到下一个可聚焦项。按住 Shift 可返回。
shortcut-menu-page-up-help = 向上跳过多个项目。
shortcut-menu-page-down-help = 向下跳过多个项目。
shortcut-menu-home-help = 聚焦列表中的第一项。
shortcut-menu-end-help = 聚焦列表中的最后一项。
shortcut-console-help = 打开游戏内调试控制台。
shortcut-chat-help = 打开聊天输入框（say 命令）。
shortcut-fullscreen-help = 切换全屏。Alt+Enter 也可用。
shortcut-frame-step-help = 冻结时前进一帧。需要调试模式。
shortcut-freeze-help = 暂停或恢复 TAS。需要调试模式。
shortcut-save-state-help = 在训练模式中保存当前状态快照。
shortcut-restore-state-help = 恢复上一个训练模式快照。

Start = 开始
Color = 颜色
Leave = 离开
Not-Joined = 未加入
Hold-Start = 按住开始
arcade-join-help = 加入这次街机流程。
arcade-color-help = 随机更换该玩家的颜色。
arcade-palette-help = 选择该玩家的配色。
arcade-leave-help = 离开这次街机流程。
arcade-setting-cpu-level = CPU 等级
arcade-setting-stocks = 命数
arcade-setting-starting-stocks = 初始命数
arcade-setting-retries = 重试次数
arcade-setting-battles = 战斗数
arcade-setting-value = {$label}: {$value}
arcade-palette = 配色 {$number}
arcade-select-title = 街机
arcade-select-infinite-title = 无限战斗
arcade-select-instructions = 确认加入 · 为每位玩家选择角色和配色 · 返回离开
arcade-between-cleared-battle = 已通过战斗 {$current} / {$total}
arcade-between-next = 确认：下一场
arcade-between-retries-remaining =
    失败 — { $count ->
       *[other] 剩余 {$count} 次重试
    }
arcade-between-retry-actions = 确认：重试 · 返回：放弃
arcade-between-results = 确认：结果
arcade-between-complete = 街机完成！
arcade-results-infinite-title = 无限战斗
arcade-results-infinite-subtitle = {$time} 内得分 {$score}
arcade-results-cleared-title = 街机通关
arcade-results-cleared-subtitle = 完成了全部 {$battles} 场战斗。
arcade-results-abandoned-title = 已放弃流程
arcade-results-abandoned-subtitle = 在第 {$current} / {$total} 场战斗后放弃。
arcade-results-gameover-title = 游戏结束
arcade-results-gameover-subtitle = 达到第 {$current} / {$total} 场战斗。
replay-battle-controls = 回放：保存键添加标记 · Start 暂停 · 十字键导航 · 抓取键变速 · 按住确认/攻击快进 · 返回退出
replay-battle-status = {$current} / {$total} · {$speed}x
replay-marker-default = 标记 {$number}
replay-marker-added = 已在 {$time} 添加 {$label}
replay-marker-selected = {$label} · {$time}
replay-marker-none = 没有回放标记
replay-marker-save-unavailable = 无法保存回放标记
replay-speed-changed = 播放速度：{$speed}x
replay-export-button = 导出回放包
replay-export-help = 创建包含此回放及其标记的本地包。不会上传任何内容。
replay-exporting = 正在导出回放包...
replay-exported = 已导出 {$name}
replay-export-failed = 导出失败：{$error}
results-controller-port = 控制器 P{$port}
results-controller-id = 控制器 {$id}
results-disconnected-slot = 已断开槽位
results-remote-player = 远程玩家
results-replay-capture = 回放记录
results-cpu = CPU
results-title-player = P{$index}: {$name}
results-title-slot = 槽位 {$index}: {$name}
results-row-kos = KOs
results-row-falls = 坠落
results-row-sds = 自灭
results-row-damage-given = 造成伤害
results-row-damage-taken = 承受伤害
results-row-blocked = 格挡
results-row-parries = 招架
results-row-power-shields = 完美护盾
results-row-lag-cancels = 后摇取消
results-row-kb-given = 造成击退
results-row-kb-taken = 承受击退
results-row-kb-absorbed = 吸收击退
results-row-ledge-grabs = 抓边次数
results-row-ledge-time = 挂边时间
results-row-crouch-cancels = 下蹲取消
results-row-velocity-cancels = 速度取消
controls-action-ui-save-replay = 保存回放
controls-device-unknown = 未知
controls-controller-label = P{$port} ({$device})
controls-keyboard-shortcuts = 键盘快捷键
shortcut-unbound = （未绑定）
shortcut-category-menu = 菜单导航
shortcut-category-general = 常规
shortcut-category-debug = 调试 (TAS)
shortcut-category-training = 训练模式
shortcut-label-menu-up = 上移
shortcut-label-menu-down = 下移
shortcut-label-menu-left = 左移
shortcut-label-menu-right = 右移
shortcut-label-menu-confirm = 确认
shortcut-label-menu-next = 下一个字段
shortcut-label-menu-page-up = 上一页
shortcut-label-menu-page-down = 下一页
shortcut-label-menu-home = 第一个项目
shortcut-label-menu-end = 最后一个项目
shortcut-label-console = 打开控制台
shortcut-label-chat = 聊天
shortcut-label-fullscreen = 切换全屏
shortcut-label-frame-step = 逐帧前进 (TAS)
shortcut-label-freeze = 冻结 (TAS)
shortcut-label-save-state = 保存状态
shortcut-label-restore-state = 恢复状态
shortcut-bind = 绑定
shortcut-add = 添加
shortcut-replace = 替换
shortcut-remove-key = 移除 {$key}
shortcut-capture-bind-title = 绑定按键：{$action}
shortcut-capture-replace-title = 替换按键：{$action}
shortcut-capture-hint = 按下要绑定的按键，或按 Esc 取消。
shortcut-conflict-detail = {$key} 已绑定到 {$action}。要重新分配吗？
shortcut-conflict-hint = 按 Enter 重新分配，按 Esc 取消。
shortcut-min-binding = {$action} 至少要保留一个绑定。
shortcut-overlap-menu = 菜单导航冲突：{$keys} 也会用于菜单导航。在菜单中控制器绑定优先。
shortcut-overlap-actions = 快捷键冲突：{$overlaps}。游戏过程中控制器绑定优先。
shortcut-reset-all = 将所有快捷键重置为默认值
character-select-help = 选择一个角色。

matchmaking-service-fallback-stun = 备用 STUN
matchmaking-status-preparing-binding = 正在准备 Quick Play... 正在打开 netplay 套接字。
matchmaking-status-preparing-primary-stun = 正在准备 Quick Play... 正在通过 {$service} 检查你的公网 UDP 路径。
matchmaking-status-preparing-fallback-stun = 正在准备 Quick Play... 主 STUN 失败，正在通过 {$service} 重试。
matchmaking-status-preparing-queueing = 正在准备 Quick Play... 正在加入队列。
matchmaking-status-connecting-tunneling = 已找到对手。正在打开点对点路径...
matchmaking-status-connecting-peer = 点对点路径已打开。正在完成连接握手...
matchmaking-status-waiting-peer = 路径已打开。正在等待另一位玩家...
matchmaking-status-starting-battle = 连接已就绪。正在开始对战...
netplay-experimental-note = 实验性功能 — 可能不稳定
netplay-detail-connecting-peer = 点对点路径已打开。正在完成连接握手...
netplay-detail-waiting-for-peer = 路径已打开。正在等待另一位玩家完成连接...
netplay-detail-starting-battle = 连接已就绪。正在开始对战...
netplay-detail-matchmaking-binding = 正在准备 Quick Play。正在打开 netplay 套接字...
netplay-detail-matchmaking-primary-stun = 正在通过 {$service} 检查你的公网 UDP 路径...
netplay-detail-matchmaking-fallback-stun = 主 STUN 没有响应。正在尝试 {$service}...
netplay-detail-matchmaking-queueing = 正在加入匹配队列...
netplay-detail-matchmaking-wait = 已排队 {$wait} 秒。等待中的玩家：{$players}。
replay-stage-fallback = 场地 {$number}
replay-unknown-error = 未知错误
replay-title = 回放
replays-title = 回放
replay-watch-button = 观看回放
replay-settings-button = 回放设置
replay-refresh-button = 刷新列表
replay-refreshing = 正在刷新...
replay-prev-button = 上一页
replay-prev-disabled = 上一页 -
replay-next-button = 下一页
replay-next-disabled = 下一页 -
replay-browser-scanning = 正在扫描回放目录...
replay-browser-scan-failed = 回放扫描失败。
replay-browser-empty = 找到 0 个回放。
replay-browser-page = {$first}-{$last} / {$count} 个回放 · 第 {$page}/{$pages} 页
replay-browser-loading = 正在加载回放...
replay-browser-scanning-files = 正在扫描已保存的回放文件。
replay-browser-scan-failed-detail = 回放扫描失败：{$error}
replay-browser-empty-slot = 此槽位没有回放。
replay-browser-empty-list = 未找到已保存的回放。
replay-browser-root-help = 回放文件会从本地回放目录中递归加载。
replay-title-unreadable = 无法读取：{$name}
replay-title-summary = {$date} - {$mode} - {$stage}
replay-list-summary = {$date} - {$duration} - {$players} - {$result}
replay-result-none = 无结果
replay-result-none-winner = 胜者：无
replay-result-quit = 提前退出
replay-result-tie = 平局
replay-result-winner = 胜者：{$winner}
replay-action-participants = 参与者：{$players}
replay-action-duration = 时长：{$duration}
replay-action-duration-truncated = 时长：{$duration}（已截断）
replay-action-result = 结果：{$result}
replay-action-stage = 场地：{$stage}
replay-action-mode = 模式：{$mode}
replay-action-version = 版本：{$version}
replay-action-file = 文件：{$compression}；已截断：{$truncated}
replay-compression-compressed = 已压缩
replay-compression-uncompressed = 未压缩
replay-truncated-yes = 是
replay-truncated-no = 否

# 社交功能和对战 CPU 列表
press-any-button-or-key = 按任意按钮或按键
social-title = 好友和邀请
social-steam = Steam
social-steam-help = 在 Steam 上显示你的房间，让好友能从好友列表加入。
social-discord = Discord
social-discord-help = 在 Discord 上显示你的房间，让好友可以请求加入。
social-info = 默认关闭。启用后，集成功能会加载平台 SDK 并分享你的房间加入码，让好友可以加入。连接仍使用 Antistatic 自己的网络对战。
social-summary = Steam 和 Discord 富状态及邀请。
social-settings-help = Steam 和 Discord 富状态及邀请。默认关闭。
versus-add-cpu = 添加 CPU
versus-cpu-page-prev = 上一页
versus-cpu-page-next = 下一页
versus-cpu-page-help = 更改显示的 CPU 页面。
versus-no-cpus-added = 尚未添加 CPU
versus-cpu-page-range = CPU {$first}-{$last} / {$count}
versus-cpu-page-total = CPU {$count} / {$max}
# 控制器校准
controller-calibration-title = 控制器校准
controller-calibration-open = 校准控制器
controller-calibration-open-help = 检查并校准所选本地控制器。
controller-calibration-online-blocked = 在线游戏期间无法校准控制器。
controller-calibration-no-local-controller = 请连接并选择要校准的本地控制器。
controller-calibration-device-status = {$source} · {$layout} · P{$port} · {$tag}
controller-calibration-tag-untagged = 无标签
controller-calibration-capability-no-axes = 此控制器未报告可校准轴。
controller-calibration-capability-native-origin = 原生原点数据支持自动校准。
controller-calibration-capability-absolute-no-automatic = 有绝对值数据；无法自动校准。
controller-calibration-capability-sdl-normalized = SDL 归一化输入；仅支持手动校准。
controller-calibration-suspicious-origin-warning = 已忽略一个或多个自动原点轴。请查看下方的回退详情。
controller-calibration-invalid-saved-warning = 已忽略保存的校准：{$reason}
controller-calibration-invalid-shaping-warning = 已忽略保存的摇杆设置：{$reason}
controller-calibration-status-policy-preview = 策略预览
controller-calibration-status-manual-preview = 手动预览
controller-calibration-status-modified = 已修改
controller-calibration-status-current = 当前
controller-calibration-status-policy = 策略
controller-calibration-status-manual = 手动
controller-calibration-status-not-saved = 未保存
controller-calibration-status-saved = 已保存
controller-calibration-status-active-differs = 当前设置与已保存设置不同
controller-calibration-draft-status = {$intent} · 草稿{$draft} · 当前{$active} · {$saved} · {$capture}
controller-calibration-automatic-policy-state = 自动校准：{$state}
controller-calibration-automatic-unavailable = 不可用
controller-calibration-automatic-on = 开
controller-calibration-automatic-off = 关
controller-calibration-automatic-policy-native-help = 切换 GameCube 原点自动校准。
controller-calibration-automatic-policy-unavailable-help = 此输入源不支持自动校准。
controller-calibration-axis-left-x = 左摇杆 X
controller-calibration-axis-left-y = 左摇杆 Y
controller-calibration-axis-right-x = 右摇杆 X
controller-calibration-axis-right-y = 右摇杆 Y
controller-calibration-axis-left-trigger = 左扳机
controller-calibration-axis-right-trigger = 右扳机
controller-calibration-field-minimum = 最小值
controller-calibration-field-center = 中心
controller-calibration-field-maximum = 最大值
controller-calibration-field-released = 松开
controller-calibration-field-pressed = 按下
controller-calibration-value-na = 不适用
controller-calibration-unit-gamecube-directed = GameCube 有向字节
controller-calibration-unit-sdl-normalized = SDL 归一化
controller-calibration-unit-canonical-normalized = 归一化
controller-calibration-unit-gamecube-protocol-byte = GameCube 协议字节
controller-calibration-axis-values-normalized = {$axis} · {$unit} · 输入 {$source} · 修正 {$corrected} · 预览 {$preview} · 游戏 {$gameplay}
controller-calibration-axis-values-native = {$axis} · {$protocolUnit} 绝对值 {$absolute}，原点 {$origin} · {$sourceUnit} 输入 {$source} · {$normalizedUnit} 修正 {$corrected}，预览 {$preview}，游戏 {$gameplay}
controller-calibration-axis-statistics = {$samples} 个样本 · 最小 {$minimum} · 最大 {$maximum} · 峰值 {$peak} · 抖动 {$jitter} · {$unit}
controller-calibration-reported-buttons = 已按下：{$buttons}
controller-calibration-reported-buttons-none = 无
controller-calibration-capture-status-ready = 就绪
controller-calibration-capture-status-waiting-release = 请松开所有控件
controller-calibration-capture-status-capturing = 正在采集
controller-calibration-capture-status-captured = 已采集
controller-calibration-capture-status-invalid = 采集无效
controller-calibration-capture-neutral = 采集中立位置
controller-calibration-capture-range = 采集完整范围
controller-calibration-capture-help = 提示时松开所有控件，然后执行采集动作。
controller-calibration-stick-movement = 移动摇杆
controller-calibration-stick-right = 右摇杆 / C 摇杆
controller-calibration-shaping-deadzone = 死区
controller-calibration-shaping-cardinal-snap = 四向吸附
controller-calibration-unit-percent = %
controller-calibration-unit-degrees = °
controller-calibration-shaping-value = {$stick} {$setting}：{$value}{$unit} · {$step}
controller-calibration-shaping-help = 左右或行两侧调整 · 确认或行中央切换微调/粗调。
controller-calibration-adjust-value = {$axis} {$field}：{$value} {$unit} · {$step}
controller-calibration-step-fine = 微调
controller-calibration-step-coarse = 粗调
controller-calibration-adjust-help = 左右或行两侧调整 · 确认或行中央切换微调/粗调。物理单位因输入源而异。
controller-calibration-apply-current-connection = 应用到当前连接
controller-calibration-save-to-tag = 保存到控制器标签
controller-calibration-save-to-tag-target = 保存到 {$tag}（{$layout}）
controller-calibration-save-to-tag-no-tag = 保存到标签（需要标签）
controller-calibration-reset-draft-active = 将草稿重置为当前值
controller-calibration-reset-draft-saved = 将草稿重置为保存值
controller-calibration-reset-draft-layout-defaults = 将草稿重置为布局默认值
controller-calibration-reset-session = 重置连接会话
controller-calibration-delete-saved = 删除保存的校准
controller-calibration-delete-saved-confirm = 确认：删除保存的校准
controller-calibration-copy-diagnostic = 复制诊断信息
controller-calibration-action-help = 确认以执行此操作。
controller-calibration-applied = 校准已应用到当前连接。
controller-calibration-save-tag-required = 保存校准需要有效的控制器标签。
controller-calibration-saved = 校准已保存到 {$tag}（{$layout}）。
controller-calibration-no-saved-calibration = 此控制器没有保存的校准。
controller-calibration-delete-saved-complete = 已删除保存的校准。
controller-calibration-copy-diagnostic-complete = 已复制校准诊断信息。
controller-calibration-local-controllers = 其他本地控制器
controller-calibration-switch-controller = 切换控制器
controller-calibration-switch-controller-name = 切换到 {$controller}
controller-calibration-switch-decision = {$controller} · 左：应用 · 右：{$save} · 确认：放弃
controller-calibration-switch-save-available = 保存
controller-calibration-switch-save-unavailable = 无法保存
controller-calibration-switch-decision-help = 未保存：左应用，右保存，确认则放弃并切换。
controller-calibration-back = 返回
controller-calibration-back-help = 返回控制菜单。进行中的采集会先取消。
controller-calibration-back-discard-confirm = 确认：放弃草稿并返回
controller-calibration-disconnected-draft-discarded = 控制器已断开；校准草稿已放弃。

# PhobGCC
controller-calibration-phob-board-unconfirmed = 董事会未经确认
controller-calibration-phob-board-v1 = 选择PhobGCC v1
controller-calibration-phob-board-v1-value = PhobGCC v1
controller-calibration-phob-board-v2 = 选择PhobGCC v2
controller-calibration-phob-board-v2-value = PhobGCC v2
controller-calibration-phob-calibrate-c-stick = 校准 C-stick：A+X+Y+R
controller-calibration-phob-calibrate-left = 校准主杆：A+X+Y+L
controller-calibration-phob-calibration-complete = 完成（仅限键盘/鼠标）
controller-calibration-phob-calibration-confirm = 确认：开始固件校准
controller-calibration-phob-calibration-help = 启动必须在控制器上完成的固件工作流程。
controller-calibration-phob-calibration-no-cancel = 控制器输入无法取消或完成此流程。完成固件步骤后，用键盘/鼠标选择“完成”。若卡住，请拔下并重新插入控制器。
controller-calibration-phob-calibration-phases = 按另一摇杆的提示完成所有中心、边缘和槽口步骤。两个固件阶段都结束后再选择“完成”。
controller-calibration-phob-enter-configure = 输入Configure Mode
controller-calibration-phob-enter-configure-instruction = 在物理控制器上，按住 A+X+Y+Start 直到两个摇杆都报告位于右上角，然后松开。
controller-calibration-phob-exit-safe-instruction = 在物理控制器上按“A+X+Y+Start”。在右上角较长的响应后释放。
controller-calibration-phob-host-correction-stale = 固件校准后的 Antistatic 校正：当前使用 {$active}；已保存 {$saved}。请检查默认值或重新采集。
controller-calibration-phob-instruction-none = 没有待处理的命令
controller-calibration-phob-mode-configure = Configure Mode
controller-calibration-phob-mode-safe = Safe Mode
controller-calibration-phob-mode-unknown = 模式未知
controller-calibration-phob-open = 打开PhobGCC指南
controller-calibration-phob-open-guide-031 = 打开官方固件0.31指南
controller-calibration-phob-open-help = 针对用户确认的 PhobGCC v1 或 v2 进行引导式只读检查。
controller-calibration-phob-open-phobvision-029-v2 = 打开PhobVision 0.29指南（仅配备v2）
controller-calibration-phob-open-release-031 = 开放固件 0.31 发行说明
controller-calibration-phob-open-version-guide = 打开报告固件指南
controller-calibration-phob-origin-checks = 固件校准前，如有需要请用物理 B 激活摇杆，并检查适配器报告的原点。
controller-calibration-phob-query-c-settings = 读取C-stick设置：R+Start
controller-calibration-phob-query-main-settings = 读取主摇杆设置：L+Start
controller-calibration-phob-query-trigger-settings = 读取触发设置：L+R+Z
controller-calibration-phob-query-version = 读取固件版本：A+Z+D-pad Up
controller-calibration-phob-raw-diagnostics-active = 原始诊断已启用。这些值是常规控制器报告经固件处理后的显示坐标，不是直接传感器数据或游戏输出。
controller-calibration-phob-raw-disable = 禁用原始输出：L+R+D-pad Down
controller-calibration-phob-raw-disable-instruction = 在物理控制器上，按 L+R+D-pad Down，等待右上角响应，然后释放所有内容。
controller-calibration-phob-raw-enable = 启用原始输出：L+R+D-pad Up
controller-calibration-phob-raw-enable-instruction = 在物理控制器上，按 L+R+D-pad Up，等待右上角响应，然后释放所有内容。
controller-calibration-phob-raw-values = 固件处理后主摇杆 X {$leftX}，Y {$leftY}；C-stick X {$cX}，Y {$cY} (0..100)
controller-calibration-phob-raw-values-unavailable = 原始值不可用
controller-calibration-phob-remap-warning = 命令始终使用外壳标注的物理按钮，不受固件重映射影响。Antistatic 看到的是报告按钮，两者可能不同。
controller-calibration-phob-result-matched = 匹配的 Phob 式响应
controller-calibration-phob-result-none = 尚未回复
controller-calibration-phob-result-unknown-custom = 未知或自定义响应
controller-calibration-phob-result-version-known = 固件 {$version}
controller-calibration-phob-result-version-no-response = 固件无响应；版本未知
controller-calibration-phob-return-safe = 返回Safe Mode
controller-calibration-phob-safe-recovery = 要确保进入 Safe Mode，请拔下再插回控制器。之后重新打开本指南；断开连接会重置检测状态。
controller-calibration-phob-setting-c-response-x-raw = C-stick X 响应字节
controller-calibration-phob-setting-c-response-y-raw = C-stick Y 响应字节
controller-calibration-phob-setting-c-snapback-x = C-stick 弹回 X
controller-calibration-phob-setting-c-snapback-y = C-stick 回弹 Y
controller-calibration-phob-setting-c-waveshaping-x = C-stick 波形整形 X
controller-calibration-phob-setting-c-waveshaping-x-raw = C-stick 波形 X 原始
controller-calibration-phob-setting-c-waveshaping-y = C-stick 波形 Y
controller-calibration-phob-setting-c-waveshaping-y-raw = C-stick 波形 Y 原始
controller-calibration-phob-setting-main-smoothing-x = 主杆平滑 X
controller-calibration-phob-setting-main-smoothing-y = 主杆平滑Y
controller-calibration-phob-setting-main-snapback-x = 主杆弹回 X
controller-calibration-phob-setting-main-snapback-y = 主杆回弹 Y
controller-calibration-phob-setting-main-waveshaping-x = 主棒波形整形 X
controller-calibration-phob-setting-main-waveshaping-x-raw = 主棒波形整形 X raw
controller-calibration-phob-setting-main-waveshaping-y = 主杆波形整形Y
controller-calibration-phob-setting-main-waveshaping-y-raw = 主棒波形整形 Y raw
controller-calibration-phob-setting-row = {$setting}：{$value} {$unit}
controller-calibration-phob-setting-rows-none = 没有解码设置
controller-calibration-phob-settings-c-stick-instruction = 在物理控制器上，按住 R+Start 两秒读出，然后松开。
controller-calibration-phob-settings-main-instruction = 在物理控制器上，按住 L+Start 两秒读出，然后松开。
controller-calibration-phob-settings-read-only = 这些读数不会更改固件设置。使用官方说明进行更改和重置。
controller-calibration-phob-settings-triggers-instruction = 在物理控制器上，按住 L+R+Z 两秒读出，然后松开。
controller-calibration-phob-setting-trigger-left-mode = 左触发模式
controller-calibration-phob-setting-trigger-left-value = 左触发值
controller-calibration-phob-setting-trigger-right-mode = 右触发模式
controller-calibration-phob-setting-trigger-right-value = 右触发值
controller-calibration-phob-setup-active = Phob Setup Mode 已启用：用报告的十字键移动，用报告的 A 确认。
controller-calibration-phob-setup-enter = 输入Phob Setup Mode
controller-calibration-phob-setup-exit = 退出 Phob Setup Mode
controller-calibration-phob-setup-exit-chord = 退出时，只按住报告的十字键 下+左 + 主摇杆右上 + C-stick右下一秒，然后松开。固件校准期间禁用。
controller-calibration-phob-stale-state-current = 当前的
controller-calibration-phob-stale-state-stale = 陈旧
controller-calibration-phob-status = 开发板：{$board} · 模式：{$mode} · 结果：{$result} · 步骤：{$instruction} · {$raw} · 设置：{$rows}
controller-calibration-phob-unit-protocol-byte = 协议字节
controller-calibration-phob-unit-setting-value = 设定值
controller-calibration-phob-unit-trigger-byte = 触发字节
controller-calibration-phob-unofficial-warning = 此 PhobGCC 助手非官方且无隶属关系。请确认主板和固件；Antistatic 不会识别硬件或写入设置。
controller-calibration-phob-version-instruction = 在 Configure Mode 中，按下物理 A+Z+D-pad Up，按住读数两秒钟，然后松开。
controller-calibration-mode-basic = 视图：基础
controller-calibration-mode-advanced = 视图：高级
controller-calibration-mode-toggle-help = 在常用设置和详细校准诊断之间切换。
controller-calibration-origin-diagnostic-unavailable = 此输入源不支持自动原点诊断。
controller-calibration-origin-diagnostic = 稳定原点：{$phase} · {$reports} 份报告 · {$stable}/6 已应用 · {$fallback}/6 回退 · {$dropped} 次溢出
controller-calibration-origin-phase-collecting = 采集中
controller-calibration-origin-phase-complete = 已完成
controller-calibration-use-suggested-deadzones = 使用建议死区
controller-calibration-use-suggested-deadzones-help = 将测得的内外死区建议应用到草稿。
controller-calibration-section-stick-shaping = 摇杆调整
controller-calibration-section-trigger-shaping = 扳机调整
controller-calibration-section-action-diagnostics = 动作诊断
controller-calibration-section-physical-diagnostics = 物理轴诊断
controller-calibration-section-hardware-correction = 硬件校正
controller-calibration-shaping-inner-deadzone = 内死区
controller-calibration-shaping-outer-deadzone = 外死区
controller-calibration-snap-override-help = 切换玩家覆盖。规则模式的最小值仍会生效。
controller-calibration-snap-override-state = {$stick} 吸附：{$state} · 最小 {$floor}° · 实际 {$effective}°
controller-calibration-override-enabled = 已启用
controller-calibration-override-disabled = 已禁用
controller-calibration-trigger-shaping-help = 左右或行两侧调整 · 确认或行中央切换微调/粗调。
controller-calibration-trigger-inner-deadzone = 内死区
controller-calibration-trigger-outer-deadzone = 外死区
controller-calibration-trigger-response-curve = 响应曲线
controller-calibration-trigger-hard-press-threshold = 强按阈值
controller-calibration-trigger-shaping-value = {$trigger} {$setting}：{$value}{$unit} · {$step}
controller-calibration-deadzone-analysis = 测量：移动噪声 {$movementNoise}、内 {$movementInner}、外 {$movementOuter}、覆盖 {$movementCoverage}/16 · 右摇杆噪声 {$rightNoise}、内 {$rightInner}、外 {$rightOuter}、覆盖 {$rightCoverage}/16
controller-calibration-trigger-deadzone-analysis = 扳机：L 噪声 {$leftNoise}、内 {$leftInner}、外 {$leftOuter} · R 噪声 {$rightNoise}、内 {$rightInner}、外 {$rightOuter}
controller-calibration-stick-diagnostic = {$stick}：映射 {$mapped} · 游戏 {$gameplay} · {$zone} · 吸附 {$snapped} · {$snap}°
controller-calibration-trigger-diagnostic = {$trigger}：映射 {$mapped} · 游戏 {$gameplay} · {$zone} · 强按 {$hard}
controller-calibration-zone-inner-dead = 内死区
controller-calibration-zone-linear = 有效范围
controller-calibration-zone-outer-saturated = 外部饱和
controller-calibration-state-yes = 是
controller-calibration-state-no = 否
controller-calibration-hard-source-none = 无
controller-calibration-hard-source-digital-button = 数字点击
controller-calibration-hard-source-analog-threshold = 模拟阈值
controller-calibration-help = 上下移动 · 左右或行两侧调整 · 确认或行中央更改精度 · 返回上一级。
controller-calibration-tag-required-prerequisite = 校准前请在控制菜单中添加玩家标签以启用保存。仍可应用到当前连接。
controller-calibration-status-draft-or-active-differs = 草稿或当前设置与已保存设置不同
controller-calibration-capture-mode-neutral = 中立位置
controller-calibration-capture-mode-range = 完整范围
controller-calibration-capture-accept-pending = 接受{$mode}采集
controller-calibration-capture-accept-and-start = 接受{$pending}，然后采集{$next}
controller-calibration-capture-status-pending = {$mode}采集等待审核
controller-calibration-legend-source = 布局默认值
controller-calibration-legend-corrected = 修正
controller-calibration-legend-preview = 预览
controller-calibration-legend-gameplay = 游戏
controller-calibration-origin-fallback-detail = 回退：{$axes}
controller-calibration-origin-fallback-axis = {$axis}：{$reason}
controller-calibration-origin-reason-insufficient-reports = 有效报告不足；请松开控制并重新连接
controller-calibration-origin-reason-unstable = 输入发生移动；请松开控制并重新连接
controller-calibration-origin-reason-implausible = 原点超出预期范围；请松开控制并重新连接
controller-calibration-origin-reason-unsafe-bounds = 原点会导致修正不安全；请采集中立位置和完整范围
controller-calibration-phob-setup-suspended-raw = 原始诊断启用时，Phob Setup Mode 会暂停。请禁用原始输出以继续。
controller-calibration-phob-result-version-custom = 自定义固件响应：X {$x}，Y {$y}
controller-calibration-phob-result-unknown = 无法识别的响应
controller-calibration-phob-raw-mode-off = 原始模式关闭

# 隐私、报告与反馈
privacy-title = 隐私
privacy-settings-help = 管理联网、崩溃报告、匿名数据和反馈。
privacy-networking = 联网功能
privacy-networking-help = 在线游戏和所有 Antistatic 服务的总开关。关闭后会断开当前在线连接。
privacy-crash-reporting = 崩溃报告：{$value}
privacy-crash-reporting-help = 选择 Antistatic 是否在发送匿名崩溃诊断前询问。
privacy-crash-ask = 每次询问
privacy-crash-never = 从不发送
privacy-crash-always = 始终发送
privacy-gameplay-metrics = 匿名对战数据
privacy-gameplay-metrics-help = 自愿发送模式、角色、对战时长和结果等概略数据。
privacy-performance-metrics = 匿名性能数据
privacy-performance-metrics-help = 自愿发送概略硬件和帧时间数据，以帮助改善性能。
privacy-feedback-open = 发送反馈
privacy-feedback-open-help = 向 Antistatic 团队发送错误报告或其他反馈。
privacy-policy-open = 查看隐私政策
privacy-policy-open-help = 阅读 Antistatic 的官方隐私政策。
privacy-policy-title = 隐私政策
privacy-policy-help = 本政策说明 Antistatic 如何处理联网、崩溃报告、可选统计和反馈。
privacy-crash-send-pending = 发送待处理崩溃报告
privacy-crash-send-pending-help = 发送正在等待你同意的崩溃报告。
privacy-crash-discard-pending = 删除待处理崩溃报告
privacy-crash-discard-pending-help = 永久删除崩溃报告，不进行发送。
privacy-summary = 联网功能默认开启。崩溃报告由你选择是否发送；匿名数据在你同意前保持关闭。
privacy-netplay-disabled = 联机对战已关闭
privacy-netplay-disabled-help = 请在隐私设置中开启联网功能以使用联机对战。
privacy-crash-prompt-title = 崩溃报告
privacy-crash-prompt-body = Antistatic 发现一份待处理崩溃报告。是否发送匿名诊断信息以帮助改善稳定性？
privacy-crash-prompt-send = 发送报告
privacy-crash-prompt-later = 稍后询问
privacy-crash-prompt-never = 不发送崩溃报告
privacy-crash-prompt-summary = 选择发送本报告、稍后决定或关闭崩溃报告。
privacy-report-sending = 正在发送...
privacy-report-failed = 发送失败。请检查网络后重试。
privacy-crash-sent = 崩溃报告已发送
privacy-crash-discarded = 崩溃报告已删除
privacy-feedback-title = 反馈
privacy-feedback-category = 类别：{$value}
privacy-feedback-category-help = 选择要发送的消息类别。
privacy-feedback-category-bug = 错误
privacy-feedback-category-feedback = 意见
privacy-feedback-category-other = 其他
privacy-feedback-subject = 主题
privacy-feedback-subject-help = 输入简短摘要。
privacy-feedback-subject-placeholder = 简短摘要
privacy-feedback-body = 消息
privacy-feedback-body-help = 描述问题或建议。请勿填写个人信息。
privacy-feedback-body-placeholder = 你想告诉我们什么？
privacy-feedback-submit = 发送反馈
privacy-feedback-submit-help = 将此消息发送给 Antistatic 团队。
privacy-feedback-warning = 请勿填写个人信息、密码或私人账户资料。
privacy-feedback-help = 填写主题和消息，然后发送反馈。
privacy-feedback-required = 请填写主题和消息。
privacy-feedback-sent = 反馈已发送。报告 ID：{$id}
